### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by nicoavila** [scullyio/scully#1]
Hi there!
Thanks for building this :heart:. I can't wait to try the alpha version 😃 
I'd like to propose a logo for this project and explain the main idea. **I'm not a designer**, but I really like illustration and drawing.

**Logo**
The logo is based on the background topic of the name [Scully](https://en.wikipedia.org/wiki/Dana_Scully). An UFO seems fine for it. The font used is [Montserrat Black Italic](https://fonts.google.com/specimen/Montserrat) with a little modification of the final letter to give the impression of quickness.
![Logo Proposal](https://nicoavila.s3.us-west-2.amazonaws.com/scully_logos_contrast.png)

**Cover Image**
The cover image uses the Angular shield and the UFO with a strong bottom light coming from the ship.
![Image Proposal](https://nicoavila.s3.us-west-2.amazonaws.com/scully_image.png)

If you like this I can give the logos for this project. If you want another colors or modifications, just let me know 😉 
Great work guys!

**Comment by webmaxru** [comment]
My proposal: Scully, scull and sculling :)

![scully](https://user-images.githubusercontent.com/1560278/70930916-98142000-2036-11ea-96ef-2242b1fdbe78.png)

**Comment by LayZeeDK** [comment]
A 3rd option by [AJonP](https://ajonp.com/blog/scully-io/)
![image](https://user-images.githubusercontent.com/6364586/71286059-f60e7380-2366-11ea-814d-ac0c30d91504.png)

**Comment by LayZeeDK** [comment]
Proposal from [live launch](https://youtu.be/Sh37rIUL-d4) cover image
![image](https://user-images.githubusercontent.com/6364586/71315123-4f090500-2456-11ea-8926-81cb35ea3d80.png)

**Comment by nicoavila** [comment]
More logo proposals:
**Scully 01**
![Logo 01](https://nicoavila.s3.us-west-2.amazonaws.com/SCULLY01.jpg)

**Comment by nicoavila** [comment]
More logo proposals:
**Scully 02**
![Logo 02](https://nicoavila.s3.us-west-2.amazonaws.com/SCULLY02.jpg)

**Comment by nicoavila** [comment]
More logo proposals:
**Scully 03**
![Logo 03](https://nicoavila.s3.us-west-2.amazonaws.com/SCULLY03.jpg)

**Comment by willi84** [comment]
honestly just a way of thought ...

![scully](https://user-images.githubusercontent.com/6207308/71410751-d1f0b200-2646-11ea-833d-e0d351de99ad.png)

**Comment by jordanpowell88** [comment]
![scully-logo](https://user-images.githubusercontent.com/3605268/71626150-b98a1580-2bb9-11ea-8436-424fe9bca591.png)

**Comment by d-koppenhagen** [comment]
I really like the initial one from @nicoavila

**Comment by d-koppenhagen** [comment]
Waiting for a decision and stickes for my macbook 😄

**Comment by jorgeucano** [comment]
Hey thanks to all: D We love all this proposals ... now we have the official logo 
![scullyio-icon](https://user-images.githubusercontent.com/5982204/73778945-bf4fb980-476a-11ea-8fa4-24599589d88e.png)

**Comment by LayZeeDK** [comment]
What's the story behind that logo, @jorgeucano?
