### ISSUE TITLE
scully-plugin-critical-css has jsdom as peer dependency

### ISSUE THREAD

**Issue by chrisguttandin** [scullyio/scully#1016]
### Description

The `scully-plugin-critical-css` package defines `jsdom` as a peer dependency but as far as I can tell it doesn't use `jsdom` and non of it's dependencies require it.

#### 🔬 Minimal Reproduction

Install `@scullyio/scully-plugin-critical-css` and look for any references to `jsdom`. It's only referenced in the `package.json` file.

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 10.1.3
Node: 12.18.4
OS: darwin x64

Angular: 10.1.3
... animations, cli, common, compiler, compiler-cli, core
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.3
@angular-devkit/build-angular   0.1001.3
@angular-devkit/core            10.1.3
@angular-devkit/schematics      10.1.3
@schematics/angular             10.1.3
@schematics/update              0.1001.3
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Scully Version:**

<pre><code>

@scullyio/scully@1.0.2
@scullyio/scully-plugin-critical-css@0.0.2

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

Please let me know if you want me to provide a pull request to remove the peer dependency entry.

**Comment by SanderElias** [comment]
You are correct, and I will fix this.
