### ISSUE TITLE
Process not found error on npm run scully

### ISSUE THREAD

**Issue by skilletspecial** [scullyio/scully#1038]
### Description
When running `npm run scully` the static files seem to be generated correctly but an error ocurrs.

#### 🔬 Minimal Reproduction
1. Create a brand new Angular CLI project
2. Run `ng add @scullyio/init`
3. Run `ng build --prod`
4. Run `npm run scully`

#### 💻Your Environment

**Angular Version:**
10.0.8

**Scully Version:**
1.0.0

## 🔥 Exception or Error

```
$ npm run scully

> process-not-found-test@0.0.0 scully C:\Source\Code\Personal\process-not-found-test
> scully

using plugins from folder "./scully"
 ☺   new Angular build imported
 ☺   Started servers in background
(You can skip this, or any future question by using the --noPrompt flag)
Would you allow Scully to collect anonymous errors to improve our services? (Y/n)n
Finding all routes in application.
traversing app for routes
Pull in data to create additional routes.
Route list created in files:
  ".\dist\static\assets\scully-routes.json",
  "C:\Source\Code\Personal\process-not-found-test\dist\process-not-found-test\assets\scully-routes.json",
  "C:\Source\Code\Personal\process-not-found-test\src\assets\scully-routes.json"

Route "/" rendered into file: ".\dist\static\index.html"

Generating took 4.49 seconds for 1 pages:
  That is 0.23 pages per second,
  or 4497 milliseconds for each page.

  Finding routes in the angular app took 2.08 seconds
  Pulling in route-data took 1 milliseconds
  Rendering the pages took 975 milliseconds



⠙ ERROR: The process "49376" not found.
```

NOTE: The process id changes from run to run.

**Comment by skilletspecial** [comment]
Happy to try to run this down but no luck after a first look around.  Is there some non-obvious logging I could dig into?

**Comment by hubbertj** [comment]
I have seen "ERROR: The process "49376" not found" for a while now. I just assumed it was some dead process which they system is trying to close or something. Overall doesn't stop the static site from generating.

**Comment by SanderElias** [comment]
duplicate from #79
