### ISSUE TITLE
schematics: inputs should be sanitized

### ISSUE THREAD

**Issue by timdeschryver** [scullyio/scully#104]
# 🐞 Bug report

### Description

The inputs for the schematics to create a post or markdown should be sanitized.

## 🔬 Minimal Reproduction

The following command generated a new post as `/blog/first/post.md`, the `post` will not be found in this case.

```
ng g @scullyio/init:post --name="first/post"
```

A similar thing happens to the markdown schematic, this command creates invalid JSON in the config:

```
ng g @scullyio/init:markdown --name=my-test! --slug=my-test!
```

```json
exports.config = {
  projectRoot: "./src/app",
  routes: {
    '/my-test!/:my-test!': {
      type: 'contentFolder',
      my-test!: {
        folder: "./my-test!"
      }
    }
  }
};
```

## 💻Your Environment 
**Angular Version:**
<pre><code>
Latest
</code></pre>

**Scully Version:**
<pre><code>
Latest
</code></pre>

## 🔥 Exception or Error
<pre><code>
</code></pre>

**Comment by d-koppenhagen** [comment]
https://github.com/scullyio/scully/issues/23 should face this issue. I created some more tests check the options will be dasherized / camelized / normalized

**Comment by d-koppenhagen** [comment]
But I checked it again: special chars like "!" will still be kept. They should be filtered.

**Comment by d-koppenhagen** [comment]
I think replacing all special chars except `_` should be used additionally for dasherized and camelized parts:

```ts
const final = original.replace(/^[a-z0-9\-]$/g);
```

And replacing all special chars except `/` and `-` should be used additionally for the route parts parts:

```ts
const final = original.replace(/^[a-z0-9\-]$/g);
```

**Comment by d-koppenhagen** [comment]
I think there are two possibly ways to handle this:
a) filter all non numeric or ASCII characters and remove them except in a generated markdown file
b) throw an exception (The the way how it's handled by e.g. `ng g c foo!`)

@jorgeucano what do you think?

**Comment by jorgeucano** [comment]
fixed in the new version :)

**Comment by d-koppenhagen** [comment]
@jorgeucano shouldn't `toAscii` also be applied to the `route` option?

**Comment by d-koppenhagen** [comment]
send a PR: https://github.com/scullyio/scully/pull/210
