### ISSUE TITLE
Remove useless  _ngcontent dom attributes to the generated pages

### ISSUE THREAD

**Issue by pegaltier** [scullyio/scully#1063]
### Description

- I don't use the view encapsulation of Angular because i make a simple website with a shared css shared as asset file
- At the moment the generated html pages contains many useless  _ngcontent attributes such as:  _ngcontent-nwc-c11="" 
- It is useless code which increase the page size and make the diff impossible

### Describe the solution you'd like

- Solution 1: Use ViewEncapsulation.None
- Solution 2: Remove those  _ngcontent attributes

**Comment by pegaltier** [comment]
I close this issue since it's possible to fix using solution 1 or solution 2: ViewEncapsulation.None OR RegexPlugin

example with RegexPlugin
setPluginConfig(RegexPlugin, {
  replacements: [
    // regex to replace _ngcontent-abc-a16=""
    {
      from: new RegExp('(_ngcontent-([a-z]{3})-([a-z0-9]{3})="")', 'gi'),
      to: '',
    },
  ],
});

**Comment by SanderElias** [comment]
Also, If you are using normal angular encapsulation, they are not useless. Those are used in the css selectors that angular generates.
