### ISSUE TITLE
Plugins should be installed as dev dependencies

### ISSUE THREAD

**Issue by pegaltier** [scullyio/scully#1069]
### Description

At the moment in the readme of most of the plugin the installation guide is not complete or not correct. For instance there is no install command or it give a npm install command as dependency and not dev dependency (without -D or --save-dev)

No command:
- @scullyio/plugins/logrocket
- @scullyio/plugins/google-analytics
- @scullyio/scully-plugin-remove-scripts
- @scullyio/plugins/Sentry

Wrong dependency type:
- npm i @scullyio/scully-plugin-base-href-rewrite
- npm i @scullyio/scully-plugin-critical-css

Correct dependency type
- npm install -D scully-plugin-flash-prevention

### Fix

I think it's better if we install the plugins as dev dependencies?

I can do the MR to fix that if you want.

**Comment by SanderElias** [comment]
I agree that plugins should be a dev dependency. I would welcome a PR that aligns this across all plugins and uses a similar layout to show how to install them.

**Comment by pegaltier** [comment]
Thanks for your feedback, I will try to do that this week-end

**Comment by amycdurbin** [comment]
Done. PR merged
