### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by xmlking** [scullyio/scully#108]
# 🐞 Bug report
i am trying to add scullyio to an existing nrwl nx monorepo project (which is already angular 9 rc)

Cannot add @scullyio/init to my angular 9 project.
## 🔬 Minimal Reproduction
```
ng add @scullyio/init
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
    ✅️ Added dependency
    ✅️ Import HttpClientModule into root module
Cannot read property 'toString' of null
```
## 💻Your Environment 
**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.7
Node: 13.5.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@angular/cdk                      8.2.3
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Scully Version:**
<pre><code>
latest

</code></pre>
## 🔥 Exception or Error
<pre><code>
ng add @scullyio/init
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
    ✅️ Added dependency
    ✅️ Import HttpClientModule into root module
Cannot read property 'toString' of null
</code></pre>

**Comment by SanderElias** [comment]
@xmlking can you provide a repo that demonstrates this issue?
That will make it easier for @jorgeucano to reproduce the issue, so we can fix the schematics

**Comment by xmlking** [comment]
i create new project following nx guild https://nx.dev/angular/getting-started/getting-started
then i run the command `ng add @scullyio/init`  ,this caused above error

**Comment by jusefb** [comment]
I have just experienced the same issue

**Comment by adyngom** [comment]
@jorgeucano @SanderElias I can see a fix has been merge but the error is still present:
```sh
angom$ ng add @scullyio/init
Your global Angular CLI version (11.1.1) is greater than your local version (11.0.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Cannot read property 'toString' of null

angom$ nx --version
11.1.5

angom$ node --version
v15.7.0
```

**Comment by bilalshaikh42** [comment]
Having the same problem, but getting "cannot read property 'search' of null"
