### ISSUE TITLE
How to get code highlight in markdown?

### ISSUE THREAD

**Issue by xmlking** [scullyio/scully#111]
If I have the following markdown for blog application, how do I get syntax highlighted? 
do you have to add any 3rd party CSS ?

```md
---
title: My second page
author: Sander Elias
publish: true
publish_date: 2019-11-27
description: This is the second demo page in this sample.
---
# Page 3

## its a wild world after all

    ```typescript
      console.log('amazing')
    ```

```

**Comment by d-koppenhagen** [comment]
Hey, the rendered markdown code contains the class names matching with this ones used by prismjs.
So you can just include prismjs in your project and it will work.
In my repo https://github.com/d-koppenhagen/d-koppenhagen.de you can see how it will be implemented

**Comment by d-koppenhagen** [comment]
Nonetheless I think a small paragraph in the docs would be good to point this out.

**Comment by Villanuevand** [comment]
@d-koppenhagen 
Would you like add a small paragraph in [docs/blog.md](https://github.com/scullyio/scully/blob/master/docs/blog.md) with the explanation? 

Could you add it?

**Comment by d-koppenhagen** [comment]
Sure. I will send a PR later :)

**Comment by Villanuevand** [comment]
> Sure. I will send a PR later :)

No rush, Thanks @d-koppenhagen

**Comment by xmlking** [comment]
@d-koppenhagen I am getting `Copy to Clipboard plugin loaded before Toolbar plugin.` warning 
I am also not getting copy button for `code highlight` section.   Rest of the styling works. 
any suggestions to fix this?
Thanks 

![image](https://user-images.githubusercontent.com/627951/71607708-864f7400-2b30-11ea-844a-601adec78a84.png)

**Comment by d-koppenhagen** [comment]
Hmm good question. Can you compare it maybe with my implementation here: https://github.com/d-koppenhagen/d-koppenhagen.de/commit/330e4008646fa1b35709a56cb80d3b139b3ab62a ? I don't see this warning when starting my project.

**Comment by d-koppenhagen** [comment]
@SanderElias I am also thinking about a configuration option for an easier setup / integration. What do you think?
