### ISSUE TITLE
Fix documentation around `router plugin` and `router process plugin`

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#1116]
I was reading the docs for `router process plugin` because a client emailed me and asked how he could remove certain routes from his app. So I was going to tell him to use a `router process plugin` to do this. However, the way it is described is too much like a `router plugin`. We need to re-write the docs to describe exactly how to do this. I would need to read the source or test it out to understand how it works, cause the docs are providing very little guidance here. 

We need to fix this ASAP.

**Comment by AlexScigalszky** [comment]
Nnotify me when it's ready and i'll translate it into spanish
