### ISSUE TITLE
New logSeverity command line option does not work

### ISSUE THREAD

**Issue by EatonZ** [scullyio/scully#1119]
### Description

The new `logSeverity` command line option added https://github.com/scullyio/scully/pull/988 unfortunately does not appear to be working. A log file still gets created.

#### 🔬 Minimal Reproduction

`npm build` [this application](https://github.com/scullyio/scully/files/5512949/NewApp.zip), then `npm scully`. Observe the created `scully.log` file.
Notice how in `package.json`, I added `--logSeverity=none` to `scully`.

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 10.2.0
Node: 15.1.0
OS: win32 x64

Angular: undefined
...
Ivy Workspace: <error>

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1002.0 (cli-only)
@angular-devkit/core         10.2.0 (cli-only)
@angular-devkit/schematics   10.2.0 (cli-only)
@schematics/angular          10.2.0 (cli-only)
@schematics/update           0.1002.0 (cli-only)
</code></pre>

**Scully Version:**

<pre><code>
1.0.4
</code></pre>

**Comment by EatonZ** [comment]
@SanderElias @jorgeucano I'm sorry, but this still doesn't appear to be fixed. Have you actually tested this feature?
Re-run my sample app and you can still see a log file generated with Scully 1.0.6.

**Comment by SanderElias** [comment]
It didn't create one in my tests.  But I do have an suspiction

**Comment by EatonZ** [comment]
@SanderElias Have you had time to take a look?

**Comment by SanderElias** [comment]
Yes, it isn't fixed yet, but i'm working on a  pr that will solve this as a side-effect.

**Comment by EatonZ** [comment]
@SanderElias Which PR are you referring to? If it's already been merged let me know so I can check this and close if fixed.

**Comment by SanderElias** [comment]
I'm really unsure. If you check and find it id still open,  please let me know

**Comment by EatonZ** [comment]
@SanderElias Checked today and the log file is still generated despite `--logSeverity=none`.
Version 1.1.1

**Comment by SanderElias** [comment]
@EatonZ I just checked the code, and with the new setup of the way the background server is started, this should no longer create the file. (I checked 2.1.27). Can you confirm?

**Comment by EatonZ** [comment]
@SanderElias I attempted to build the sample project today, but it seems it's too old and throwing errors on `npm install`.
I'll take your word for it if you noticed the issue no longer occurs. I do not have any active Angular projects right now.
