### ISSUE TITLE
Could not connect to server Error  with nx  monorepo project

### ISSUE THREAD

**Issue by xmlking** [scullyio/scully#112]
# 🐞 Bug report

### Description
I have fresh nrwl nx monorepo.
i added blog module , then try to build static site.

`yarn run scully` throws `Could not connect to server` error .

the code works fine with `ng server` and open  `http://localhost:4200/home/blog`
## 🔬 Minimal Reproduction

```
git clone https://github.com/xmlking/yeti.git
cd yeti
ng build && yarn run scully 
# this throw error

yarn run scully serve
```

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 13.5.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@angular/cdk                      8.2.3
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**
<pre><code>
0.0.9

</code></pre>
## 🔥 Exception or Error
<pre><code>
 yarn run scully
yarn run v1.21.1
$ scully
Cleaned up /Users/schintha/Developer/Work/SPA/yeti/dist/scully/apps/webapp folder.
 ☺   new Angular build imported
started servers in background
Could not connect to server
✨  Done in 16.65s.
</code></pre>

**Comment by SanderElias** [comment]
Thanks for posting the workaround. This gives me some clues on where this is coming from.
We are using guess-parser to traverse the routes in the angular app. It seems that it can't track the NX libraries. I'm going to investigate this a bit deeper and will talk to Minko to see if there is a proper solution for this.

**Comment by mgechev** [comment]
Maybe we can close this issue and continue the discussion in #40?

**Comment by xmlking** [comment]
will be tracked in https://github.com/scullyio/scully/issues/40
