### ISSUE TITLE
add option to @scullyio/init:post  to specific blog directory

### ISSUE THREAD

**Issue by xmlking** [scullyio/scully#113]
# 🧩 Feature request

### Description
 `ng g @scullyio/init:post  --name="awesome owls" ` only added to `/blog` directory.  If i have two blogs, `post` command dont have option to specify the blog diretory 

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

 `ng g @scullyio/init:post  --name="awesome owls"  --directory="./clog"`

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by d-koppenhagen** [comment]
I think this goes hand in hand with https://github.com/scullyio/scully/issues/100

**Comment by SanderElias** [comment]
Closing to center communication in #100
