### ISSUE TITLE
Create a postrenderer to combine all styles inside style tags into one tag

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#1132]
## 🧩 Feature request

A video by @jeffwhelpley taught me some things. See it [HERE](https://www.loom.com/share/35330a858cd741ba92e8be0c0496ffbb). 

One of the things: for AMP, you must have all your styles inside one style tag in the head. Brilliant! Scully makes this EASY AF!

We need to build a series of AMP plugins for Scully Users. Once that takes all of the Styles from your pages <head> and combines them into one style tag during the post-render. 

Deploy this to npm as `@scullyio/scully-plugin-amp-css`. We will make a series of these. This can be the first one.

**Comment by aaronfrost** [comment]
Here is some starter code, as this plugin would be crazy easy to write. 

```typescript
const {
  registerPlugin,
  configValidator,
  logWarn,
  yellow
} = require('@scullyio/scully');
const jsdom = require('jsdom');
const { JSDOM } = jsdom;

const combineStylesPlugin = async (html, options) => {
  try {
    const dom = new JSDOM(html);
    const { window } = dom;
    const { document } = window;
    const { head } = document;   
    // Solution
    const styleTags = document.querySelectorAll('style');
    var totalStyles = ``;
    Array.prototype.forEach.call(styleTags, (style) => {
        const parent = style.parentNode;
        parent.removeChild(style);
        totalStyles+= style.innerHTML;
    });
    var newStyle = document.createElement('style');
    head.appendChild(newStyle);
    newStyle.innerHTML = totalStyles;
    return dom.serialize();
  } catch (e) {
    logWarn(
      `error in combineStylesPlugin, didn't parse for route "${yellow(route.route)}"`
    );
  }
  // in case of failure return unchanged HTML to keep flow going
  return html;
};

const validator = async config => [];
registerPlugin('render', 'combineStylesPlugin', combineStylesPlugin, validator);
```

**THIS MAY INFACT WORK!!!** I just don't have time to try it and make sure that it is working. 

Make sure and add to the docs for this that you must execute this plugin BEFORE the CriticalCSS plugin.

**Comment by pjlamb12** [comment]
@aaronfrost back from Thanksgiving break and gonna take a stab at this. I'm just not sure the best way to deploy it under the scullyio org. Also, do you have a preference for how the repo is set up?

**Comment by pjlamb12** [comment]
@SanderElias @jorgeucano any ideas on what you prefer for the repo? Do you want to create a GitHub repo under the scully org that the code can be added to? And then the plugin can be deployed under the npm org as well? Or where should the plugin code be stored?

**Comment by pjlamb12** [comment]
The code for this can be found in [this repo](https://github.com/pjlamb12/scully-plugin-amp-css). Its format is based off the [scully-plugins](https://github.com/notiz-dev/scully-plugins) repo.

Just running `ng build --prod` and `npm run scully` produce no `style` tags in the `index.html` file. Is there another plugin needed to render those styles?

@aaronfrost @jorgeucano @SanderElias

**Comment by aaronfrost** [comment]
I love it. You're awesome @pjlamb12. Good luck on this.

**Comment by pjlamb12** [comment]
This is coming along well. Having a little Jest/unit test issue, but once that's worked out the plugin should be about ready for a release.

**Comment by pjlamb12** [comment]
@aaronfrost @SanderElias @jorgeucano I just finished up the tests (thanks to Sander pushing the 1.0.8 version) and the plugin is ready to be deployed. I will need access to the scully organization in NPM to deploy to @scullyio/scully-plugin-amp-css. Or I can publish it under my own account. Whichever one you'd rather.

**Comment by pjlamb12** [comment]
@aaronfrost @SanderElias this ticket can now be closed. :)
