### ISSUE TITLE
Document the CriticalCSS/DiscountFlashPrevention plugins

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#1135]
## 🗄️ Docs report

Possibly two of the coolest plugins we've built in a while, and we haven't documented it.

**Comment by aaronfrost** [comment]
We need to add this Plugin to the docs, essentially: https://github.com/scullyio/scully/blob/48bff92cd7517fcfd1f0c0d8afa7517d84638db9/libs/plugins/scully-plugin-critical-css/README.md

**Comment by sumitparakh** [comment]
Hi @aaronfrost , I wanna contribute.

**Comment by aaronfrost** [comment]
@sumitparakh I am here for questions. Also @jorgeucano and @SanderElias are here for questions. Good luck on this. Thanks for your willingness to help.

**Comment by sumitparakh** [comment]
Hi @aaronfrost, I'm getting this error.

```
Cannot find module '@scullyio/scully-plugin-docs-link-update'
```

Am I missing something or I just have to install (globally?) the missing dependency?

![image](https://user-images.githubusercontent.com/4236211/100699860-142b8300-33c2-11eb-8b45-9183aabbc7ed.png)
