### ISSUE TITLE
Initial page shows before rendering internal pages directly

### ISSUE THREAD

**Issue by jsanta** [scullyio/scully#1137]
Hi.
Trying Scully with an Angular 11 app (this also happened before updating Angular version).
Defined my initial page / to be rendered. As the app has many other internal pages defined in the angular-routing files  the issue happens when navigating directly to any other internal page, different from the initial page.
The initial page gets rendered and it's visible for a few seconds before rendering the internal page.

I can suppose that the reason for this is that the generated index.html has the initial page fully rendered and also includes a placeholder for the typical router-outlet, so internal pages will forcefully pass through the initial page.
Tried with ``initialNavigation: 'enabled',`` on the app-routing.module file without any results. Also tried detaching the initial page from the DOM by wrapping it on a named div, and reattaching it when the route === initial_page ; same problem.

A workaround for this would be nice, as generating  static pages for all internal pages is not an option.
Regards.

**Comment by SanderElias** [comment]
@jsanta I'm unsure what you are asking? 
It looks to me you are using Scully on pages that are behind a login on something?
If I understand you correctly, you don't want Scully to render those pages? 
In that case, use the `ignored` router plugin for those routes you want to exclude.
Also, set up your server so it redirects a user landing on those pages directly to a page that handles those requests the way you lie them to be handled. As Scully only provides the static assets, there is not much it can do for those.

Or do I understand your request wrong?

**Comment by jsanta** [comment]
Hi thanks for answering.
I'm not using  Scully on any other pages  besides the home page.
My app has the following route structure (on the Angular routing-module):

```
/ -> this is the home page and the only page I want to be rendered by scully
/internal1 -> some internal page
/internal2 -> another internal page
/parent/child1 -> an internal page within a parent section
/parent/child2 -> another internal page within a parent section (siblings with child1)
/private -> internal page, parent for some other login protected pages
/private/private_child1 -> .... ok I guess you got the idea.
```

Direct navigation to / works perfectly.
But if I  navigate to any internal page, before getting the internal page rendered on the browser, I see the home page rendered, just for a few seconds or less, but enough to notice. I can suppose that the reason for this is that the generated index.html has the initial page fully rendered and also includes a placeholder for the typical router-outlet, so internal pages will forcefully pass through the initial page.

I've tried wrapping the home page inside a named div

```
<div id="home-wrapper">
    <!-- here's the home page content -->
</div>
```

and in my app-component intercepting the  navigation event so it removes this  block from the DOM if the URL does not match the initial page.

```
  activePage: string;
  homeWrapper: Array<any>;

  detach(node: any): Array<any> {
    return [ node.parentElement , node.parentElement.removeChild(node) ];
  }

//...
//...
router.events.subscribe(
      (event: RouterEvent): void => {
        if (event instanceof NavigationStart) {
          this.loading = true;
        } else if (event instanceof NavigationEnd) {
          this.loading = false;
          this.activePage = router.url;
          console.log('ActivePage: ', this.activePage);
          if (this.activePage !== 'home' && this.activePage !== '/' ) {
            this.homeWrapper = (!this.homeWrapper) ? this.detach(this.document.getElementById('home-wrapper')) : this.homeWrapper;
          } else {
            if (this.homeWrapper?.length > 0) {
              this.homeWrapper[0].addChild(this.homeWrapper[1]);
            }
          }
        }
      }
    );
  // ...
```

with no success, the initial page is still being rendered when navigating to any internal page, just before showing the internal's page content.

Also tried  playing with the router navigation extras:

```
@NgModule({
  imports: [RouterModule.forRoot(routes,
    {
    // preloadingStrategy: PreloadAllModules,
    onSameUrlNavigation: 'reload',
    initialNavigation: 'enabledBlocking',
    scrollPositionRestoration: 'enabled',
    relativeLinkResolution: 'corrected',
    urlUpdateStrategy: 'eager'
})],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

 tried most combinations for `initialNavigation: enabled | enabledBlocking | enabledNonBlocking` , `relativeLinkResolution: legacy | corrected ` and `urlUpdateStrategy: deferred | eager` with the same problem. 

I really want to use Scully for this page, and this  behavior  when navigating directly to internal pages is driving me nuts. Hope you can help me with this.

**Comment by SanderElias** [comment]
You should have the "internal' routes redirected to `404.html` which is the original `index.html` that is not pre-rendered. Again, this is a setting you should arrange for on your server. Not something Scully can provide much help in. If you use the original HTML, there will be not Scully pre-rendered content in there at all.

**Comment by jsanta** [comment]
> You should have the "internal' routes redirected to `404.html` which is the original `index.html` that is not pre-rendered. Again, this is a setting you should arrange for on your server. Not something Scully can provide much help in. If you use the original HTML, there will be not Scully pre-rendered content in there at all.

Makes some sense, though I don't like the redirection part.
Will give it a try and share my findings.
Thanks.

**Comment by kananlanginhooper** [comment]
Please check your redirect settings on your hosting.  For regular angular hosting, everything that's not an asset (img, css, js) gets redirected to index.html.  If that is still enabled, you'll see exactly what you're describing.  It'll do an internal redirect to index.html, show that static page, then when the angular takes over, it'll read the route from the url, and show the internal (detail) page.

**Comment by jsanta** [comment]
Thanks. That currently works, instead of making the nginx location configuration point to index.html on a 404 pointing it to 404.html makes angular deal with not found resources. Don't like it as we delegate this pain on server admins, but it's what we have. Thanks.

**Comment by SanderElias** [comment]
I'm going to close this, as this is not something Scully can solve. It needs to be solved using the server's redirect rules. Just as for _all_ static site hostings.
