### ISSUE TITLE
ERROR: The process "81564" not found.

### ISSUE THREAD

**Issue by saleemmalikraja** [scullyio/scully#114]
# 🐞 Bug report
I'm running Scully for the first time. When I run npm run scully it creates the static files but does not complete and gives the error ### ERROR: The process "81564" not found. Do i really have to update my cli version ??
## 🔬 Minimal Reproduction
ng add @scullyio/init
ng build
npm run scully

Then added below command and ran again
ng g @scullyio/init:blog
npm run scully

## 💻Your Environment 
**Angular Version:**
<pre><code>

Angular CLI: 8.3.4
Node: 10.15.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.4
@angular-devkit/core         8.3.4
@angular-devkit/schematics   8.3.4
@schematics/angular          8.3.4
@schematics/update           0.803.4
rxjs                         6.4.0
</code></pre>

**Scully Version:**
<pre><code>

{
  "name": "static-site-gen",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.5",
    "@angular/common": "~8.2.5",
    "@angular/compiler": "~8.2.5",
    "@angular/core": "~8.2.5",
    "@angular/forms": "~8.2.5",
    "@angular/platform-browser": "~8.2.5",
    "@angular/platform-browser-dynamic": "~8.2.5",
    "@angular/router": "~8.2.5",
    "@scullyio/init": "0.0.9",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.4",
    "@angular/cli": "~8.3.4",
    "@angular/compiler-cli": "~8.2.5",
    "@angular/language-service": "~8.2.5",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
</code></pre>
## 🔥 Exception or Error
<pre><code>

Generating took 32.14 seconds for 1 pages:
  That is 0.04 pages per second,
  or 32147 milliseconds for each page.

ERROR: The process "81564" not found.

</code></pre>

**Comment by Villanuevand** [comment]
Hi @saleemmalikraja you need Angular 9.x.x to run Scully, 
Please check our [Getting Started](https://github.com/scullyio/scully/blob/master/docs/getting-started.md) file...
