### ISSUE TITLE
Starting with scully

### ISSUE THREAD

**Issue by yelhouti** [scullyio/scully#1141]
### Description
We running the scully schematic, a folder scully is created with a dummy default plugin and the tsconfig.json
1- When I delete the plugin, For cleaner code I should be able to compile since this method is not used
2- The compile code (.js .js.map) should be put in the dist folder and used from there if needed, instead of polluting the source code.
3- scully.log should also be added to the dist folder or at least automatically  get added to .gitignore

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 10.2.0
Node: 12.17.0
OS: linux x64

Angular: 10.2.3

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
</code></pre>

## 🔥 Exception or Error
When I delete the plugins folder (and I think I should be able to, if I do not use any custom plugins), I get:
<pre><code>

using plugins from folder "./scully"
Typescript error while compiling plugins. the error is:
error TS18003: No inputs were found in config file './scully/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["./**/*spec.ts"]'.

</code></pre>

**Comment by kananlanginhooper** [comment]
#3 - scully.log is in .gitignore

**Comment by SanderElias** [comment]
1. if you remove the sample plugin, you should update the tsconfig in the scully folder too. Scully tells TS to compile everything in the `./scully/` subfolder. it throws if there is nothing in there. This is not something we can/want to fix. If you don't want user plugins, just delete the complete `./scully/` subfolder
2. Because we compile your TS files on the fly, and there is _no_ bundler involved, by default we keep them next to the source files. If you know a way to move them over to the dist folder, while keeping the relative imports in the Scully config working, I'm all ears. 
3. This should have been done already. @jorgeucano can you check this? while you are on it, can you also add the `.map` and `.d.ts` files inside the `./scully/' folder?

**Comment by diminutivesloop** [comment]
I just initialized a new Scully project w/ @scullyio/init@1.0.1 and `.gitignore` is still not updated. After building w/ Scully several files are generated and I would expect that most generated files should be ignored but it would be helpful if that was configured automatically when initializing the project.

**Comment by SanderElias** [comment]
@jorgeucano / @Brocco Can you take a look at the schematics and check if the following files are automatically added to the `.gitignore` in a project:
```
scully.log
scullyStats.json
.scully
/scully/**/*.js
/scully/**/*.js.map
/scully/**/*.d.ts
```
@diminutivesloop  That should be all of them, right?

**Comment by diminutivesloop** [comment]
@SanderElias That mostly matches what I have in my projects although I've also ignored `scully-routes.json` since it's auto-generated by Scully. Is there any reason that file shouldn't be ignored?

**Comment by SanderElias** [comment]
@diminutivesloop Personal preference mostly.
Still, if someone checks out the project, and runs `ng serve` there is a reasonable expectation that it doesn't error out for missing dependencies. 
I know it will be regenerated, but first impressions matter.

**Comment by fabioemoutinho** [comment]
> I just initialized a new Scully project w/ @scullyio/init@1.0.1 and `.gitignore` is still not updated. After building w/ Scully several files are generated and I would expect that most generated files should be ignored but it would be helpful if that was configured automatically when initializing the project.

I also want to add to this, when installing scully in a NX repo, it does not add to .gitignore (2.1.x)

**Comment by Brocco** [comment]
I am going to work on this, hope to have a PR up to address this issue shortly.

**Comment by SanderElias** [comment]
Thanks to @Brocco, our 2.1.18 schematics will now update the `.gitIgnore` file.
Going to close this now
