### ISSUE TITLE
Document resultsMapper for json plugin

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#1143]
Speaking with a user today, they needed better documentation on the JSON plugin. They weren't really reading the doc, so I sent them to the doc. But I noticed that the `resultsHandler` (or maybe it is called `resultsMapper`?) isn't documented in there. We need to document that better. We documented the `headers` config. But not how to map an object from the server into an array that we then pluck from. 

https://scully.io/docs/Reference/plugins/built-in-plugins/json/

**Comment by pjlamb12** [comment]
@aaronfrost  Looking at the page linked above, there is some documentation on the resultsHandler in the code block comments. Is there something more you want than what is there already?

**Comment by aaronfrost** [comment]
@pjlamb12 I think I fixed that and then pushed it out there. I should have closed this ticket.
