### ISSUE TITLE
Scully Starters

### ISSUE THREAD

**Issue by Gyrosh** [scullyio/scully#1159]
Starters are boilerplate projects that users can use to set up site quickly.

I was wondering about different section in showcase or separate page for Scully Starters for specific Headless CMS (like in Gatsby). 

What do you think about it?

I am currently testing [Scully Blog Starter](https://github.com/flotiq/scully-blog-starter) using [Flotiq CMS](https://flotiq.com) and i see they have
another one already: [Scully Products Starter](https://github.com/flotiq/scully-products-starter).

**Comment by SanderElias** [comment]
cc: @aaronfrost @jorgeucano @Brocco

**Comment by andrzejwp** [comment]
@SanderElias Hi there, Andrew from Flotiq team here. I'm thrilled to see that these projects are getting some traction! 
Let me know if we can help somehow to make these starters / boilerplates available to the Scully community. 

The list is actually a little longer:

- https://github.com/flotiq/scully-products-starter - Scully, Flotiq and Snipcart boilerplate
- https://github.com/flotiq/scully-event-calendar-starter - Scully, Flotiq, Google Calendar and Zapier demo
- https://github.com/flotiq/scully-recipes-starter - Scully and Flotiq starter for a culinary blog
- https://github.com/flotiq/scully-projects-starter - Scully and Flotiq - portfolio website starter
- https://github.com/flotiq/scully-blog-starter - Scully and Flotiq - simple blog boilerplate

**Comment by SanderElias** [comment]
@Gyrosh @andrzejwp We will add a page for starters soon. I'll post back here when it's in place.
When that is the case, you can PR your starters on that page. (can be done by using the 'edit' button on the page itself)

**Comment by andrzejwp** [comment]
Hi @SanderElias - any news on this?

**Comment by SanderElias** [comment]
@andrzejwp see pr #1229
