### ISSUE TITLE
Bug: the scully meta tag generator attribute is incorrect

### ISSUE THREAD

**Issue by pegaltier** [scullyio/scully#1165]
### Description

In the previous version of scully @scullyio/scully@1.0.2 the meta tag generator version was correct:
```
<meta name="generator" content="Scully 1.0.2">
```
Since i have upgrade to @scullyio/scully@1.0.8 the meta tag generator version is incorrect:
```
<meta name="generator" content="Scully 0.0.0">
```

#### 🔬 Minimal Reproduction

npm run scully

#### 💻Your Environment

**Angular Version:**

<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            9.1.12
@angular-devkit/schematics      9.1.12
@angular/cli                    11.0.4
@schematics/angular             9.1.12
@schematics/update              0.1100.4
rxjs                            6.6.0
typescript                      4.0.5
</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.8",
</code></pre>

**Comment by SanderElias** [comment]
This is closed by the above PR and will be fixed in the next release we will push out.
(let us know if you need it faster, and we will do an interim release)
