### ISSUE TITLE
scully-docs sample project not building locally

### ISSUE THREAD

**Issue by kananlanginhooper** [scullyio/scully#1179]
## 🐞 Bug report

scully-docs sample project not building locally when using: `node \dist\libs\scully\src\scully.js --tds --project=scully-docs`

`Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch (.....\node_modules\penthouse\node_modules\puppeteer\lib\Launcher.js:236:15)`

### Description

Issue with the penthouse ' critical path css generator' module.  It also loads in puppeteer in order to do the rending and find the css.

I would like to debug this issue myself.  However, I can't find any reference to penthouse in any of the scully code.  I don't know where to start.

#### 🔬 Minimal Reproduction

1. fork sully project
2. npm i
3. npm run build:code
4. node \dist\libs\scully\src\scully.js --tds --project=scully-docs

#### 💻Your Environment

**Angular Version:**

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.2.0
Node: 15.4.0
OS: win32 x64

Angular: 10.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cli                    10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
ng-packagr                      10.1.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Scully Version:**

<pre><code>
{
  "name": "scullyio",
  "version": "1.0.0",
  "license": "MIT",
  "url": "",
  "repository": {
    "type": "git",
    "url": "https://github.com/scullyio/scully.git"
  },
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "build:scully": "nx build scully --prod",
    "build:code": "nx run-many --target=build --all --prod ",
    "build:sample": "npm run scully -- --project sample-blog --RSD --scan ",
    "build:docs": "npm run scully -- --project scully-docs --RSD --scan",
    "scully": "node ./dist/libs/scully/src/scully.js",
    "test": "run-s build:scully server:kill build:code symlinks server:testDocs server:wait build:docs server:kill server:testSample server:wait build:sample  jest:test cypress:e2e",
    "lint": "nx workspace-lint && nx lint",
    "server:wait": "wait-on tcp:1668",
    "server:testSample": "npm run server:sample &",
    "server:testDocs": "npm run server:docs &",
    "server:sample": "npm run scully -- --project sample-blog --tds serve --404=baseOnly",
    "server:docs": "npm run scully -- --project scully-docs --tds serve ",
    "server:kill": "npm run scully -- killServer ",
    "e2e": "nx e2e",
    "docs": "run-s server:kill build:code symlinks build:docs deploy:docs",
    "debug": "nodemon --legacy-watch --watch ./dist/libs/scully --inspect=0.0.0.0:5858 --nolazy \"./dist/libs/scully/src/scully --pr sample-blog\"",
    "nozspredeb": "npm run build:scully",
    "nopreduration": "npx tsc -m commonjs scully.sample-blog.config.ts",
    "duration": "rm scully.log && npm run scully -- --cf=scully.heavy.config.ts --tds --RSD ",
    "deb": "node --inspect=0.0.0.0:5858 --nolazy ./dist/libs/scully/src/scully --pr sample-blog",
    "deploy:docs": "echo No deploy script yet",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points && npm run symlinks && git update-index --skip-worktree tests/assets/blog-files/page-6.md",
    "cypress:e2e": "cypress run --spec 'tests/cypress/integration/**/*' --browser chrome --headless",
    "cypress:e2e:server": "start-server-and-test scully:run:cypress http://localhost:1668 cypress:e2e",
    "scully:run:cypress": "node ./dist/libs/scully/src/scully serve --project=sample-blog --tds",
    "symlinks": "npx symlink-dir ./dist/libs ./node_modules/@scullyio",
    "jest:test": "npx jest",
    "changelog": "npx conventional-changelog -p scully -i ./CHANGELOG.md -s && git add ./CHANGELOG.md",
    "commit": "git add . && npx git-cz",
    "commit:select": "npx git-cz",
    "fullPublish": "nx workspace-schematic publish",
    "full-build": "npm i && npm run symlinks && npm run build:code && npm run build:sample && npm run build:docs && npm run jest:test && npm run cypress:e2e:server"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.2.0",
    "@angular/common": "~10.2.0",
    "@angular/compiler": "~10.2.0",
    "@angular/core": "~10.2.0",
    "@angular/forms": "~10.2.0",
    "@angular/platform-browser-dynamic": "~10.2.0",
    "@angular/platform-browser": "~10.2.0",
    "@angular/router": "~10.2.0",
    "@nrwl/nx-cloud": "^10.0.0",
    "@sentry/node": "^5.20.1",
    "@types/compression": "^1.7.0",
    "@types/cors": "^2.8.7",
    "@types/minimatch": "^3.0.3",
    "@types/ws": "^7.2.6",
    "chalk": "^4.1.0",
    "compression": "^1.7.4",
    "core-js": "^3.6.5",
    "cors": "^2.8.5",
    "critical": "^2.0.4",
    "cz-customizable": "^6.3.0",
    "express": "4.17.1",
    "got": "^11.6.0",
    "js-yaml": "^3.14.0",
    "jsdom": "^16.4.0",
    "minimatch": "^3.0.4",
    "npm-run-all": "^4.1.5",
    "os": "^0.1.1",
    "prism": "^4.1.2",
    "prismjs": "1.21.0",
    "rxjs": "^6.6.2",
    "semver": "^7.3.2",
    "ws": "^7.3.1",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.0",
    "@angular/cli": "~10.2.0",
    "@angular/compiler-cli": "~10.2.0",
    "@nrwl/angular": "10.0.10",
    "@nrwl/builders": "^7.8.7",
    "@nrwl/cli": "^10.2.1",
    "@nrwl/cypress": "10.0.10",
    "@nrwl/eslint-plugin-nx": "10.0.10",
    "@nrwl/express": "^10.4.4",
    "@nrwl/jest": "10.0.10",
    "@nrwl/node": "^10.4.4",
    "@nrwl/workspace": "^10.4.4",
    "@types/chalk": "^2.2.0",
    "@types/express": "4.17.7",
    "@types/fs-extra": "^9.0.1",
    "@types/http-proxy-middleware": "^0.19.3",
    "@types/jasmine": "^3.5.12",
    "@types/jasminewd2": "~2.0.8",
    "@types/jest": "26.0.9",
    "@types/js-yaml": "^3.12.5",
    "@types/json5": "^0.0.30",
    "@types/marked": "^1.1.0",
    "@types/node": "^14.14.10",
    "@types/path-to-regexp": "^1.7.0",
    "@types/puppeteer": "^3.0.1",
    "@types/request": "^2.48.5",
    "@types/yamljs": "^0.2.31",
    "@types/yargs": "^15.0.5",
    "angular-playground": "^7.0.3",
    "asciidoctor.js": "^1.5.9",
    "codelyzer": "^6.0.1",
    "conventional-changelog": "^3.1.21",
    "cypress": "^4.12.1",
    "cz-conventional-changelog": "^3.2.0",
    "dotenv": "8.2.0",
    "eslint": "^6.0.0",
    "eslint-config-prettier": "6.11.0",
    "front-matter": "^4.0.2",
    "fs-extra": "^9.0.1",
    "guess-parser": "^0.4.22",
    "http-proxy-middleware": "^1.0.6",
    "husky": "^4.2.5",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.2",
    "jest": "26.2.2",
    "jest-preset-angular": "8.2.1",
    "jest-serializer-html": "^7.0.0",
    "jsonc": "^2.0.0",
    "marked": "^1.2.5",
    "ng-packagr": "^10.1.2",
    "nodemon": "^2.0.4",
    "open": "^7.3.0",
    "osascript": "^1.2.0",
    "path-to-regexp": "^6.1.0",
    "prettier": "2.0.5",
    "pretty-quick": "^2.0.1",
    "protractor": "^7.0.0",
    "puppeteer": "^5.5.0",
    "start-server-and-test": "^1.11.3",
    "symlink-dir": "^4.1.0",
    "ts-jest": "^26.1.4",
    "tsickle": "^0.39.1",
    "tslib": "^2.0.1",
    "tslint": "~6.1.3",
    "typescript": "~4.0.3",
    "wait-on": "^5.2.0",
    "yamljs": "^0.3.0",
    "yargs": "^16.1.1"
  }
}

</code></pre>

## 🔥 Exception or Error

<pre><code>
nodejs\node.exe ...Scully-Fork\dist\libs\scully\src\scully.js --tds --project=scully-docs
Debugger listening on ws://127.0.0.1:60702/2e0f2ea1-78a4-4561-b610-d3c19beb7445
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
logging with severity "warning"
using plugins from folder "./scully"
 ☺   new Angular build imported
 ☺   Started servers in background
Finding all routes in application.
----------------------------------
Using stored unhandled routes!.
   To discover new routes in the angular app use "npm run scully -- --scanRoutes"
----------------------------------
Pull in data to create additional routes.
Finding files in folder ".\docs"
Route list created in files:
  ".\apps\scully-docs\src\assets\scully-routes.json",
  "...Scully-Fork\dist\static\doc-sites\assets\scully-routes.json",
  "...Scully-Fork\dist\apps\scully-docs\assets\scully-routes.json"

route: "/404" could not inline CSS Error: Browser is not downloaded. Run "npm install" or "yarn install"
route: "/docs/community/contributing" could not inline CSS Error: Browser is not downloaded. Run "npm install" or "y
arn install"
route: "/docs/community/code-of-conduct_es" could not inline CSS Error: Browser is not downloaded. Run "npm install"
 or "yarn install"
route: "/docs/community/contributing_es" could not inline CSS Error: Browser is not downloaded. Run "npm install" or
 "yarn install"
route: "/docs/community/code-of-conduct" could not inline CSS Error: Browser is not downloaded. Run "npm install" or
 "yarn install"
route: "/docs/community/issues" could not inline CSS Error: Browser is not downloaded. Run "npm install" or "yarn in
stall"
Route "/404" rendered into file: ".\dist\static\doc-sites\404\index.html"
Route "/docs/community/contributing" rendered into file: ".\dist\static\doc-sites\docs\community\contributing\index.
html"
Route "/docs/community/code-of-conduct_es" rendered into file: ".\dist\static\doc-sites\docs\community\code-of-condu
ct_es\index.html"
Route "/docs/community/contributing_es" rendered into file: ".\dist\static\doc-sites\docs\community\contributing_es\
index.html"
Route "/docs/community/code-of-conduct" rendered into file: ".\dist\static\doc-sites\docs\community\code-of-conduct\
index.html"
Route "/docs/community/issues" rendered into file: ".\dist\static\doc-sites\docs\community\issues\index.html"
⠼ Rendering Routes: 34/171Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch (...Scully-Fork\node_modules\penthouse\node_modules\puppeteer\lib\Launcher.js:2
36:15)
Waiting for the debugger to disconnect...

Process finished with exit code 0

</code></pre>

**Comment by jorgeucano** [comment]
@kananlanginhooper I'm just using a clean fork and work fine for me on win 10 node 15.

I'm run: 
```
npm i 
npm run build:code
node ./dist/libs/scully/src/scully --tds --project=sample-blog  OR npm run build:sample
```
In your log, you have an `npm error` .... Can you try removing the node_modules and installing them again! 
The GA/test works fine with the same command on linux.

**Comment by kananlanginhooper** [comment]
Well, you are very correct.  I was getting to a "clean" for by running `git checkout main && git reset head --hard`.  There must be some other files that are still hanging around.  node_modules for sure, but I still get the error when deleting that.  I'll look into it more, or just start from a fresh fork, like I had mentioned.  Thanks for looking at this.
