### ISSUE TITLE
Could not connect to server

### ISSUE THREAD

**Issue by falcon-Z** [scullyio/scully#1184]
### Description
I just installed Scully and it doesn't work as expected throws an error and exits when I npm run Scully

#### 💻Your Environment
Windows 10

**Angular Version:**

<pre><code>

Angular CLI: 11.0.5
Node: 12.19.0
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/flex-layout            10.0.0-beta.32
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Scully Version:**

<pre><code>

        "@scullyio/init": "^1.0.1",
        "@scullyio/ng-lib": "^1.0.0",
        "@scullyio/scully": "^1.0.0",

</code></pre>

## 🔥 Exception or Error

<pre><code>

logging with severity "warning"
using plugins from folder "./scully"
 ☺   new Angular build imported
 ☺   Started servers in background
Could not connect to server
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! portfolio@1.0.0 scully: `scully`
npm ERR! Exit status 15
npm ERR! 
npm ERR! Failed at the portfolio@1.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\madha\AppData\Roaming\npm-cache\_logs\2020-12-28T13_18_42_209Z-debug.log
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command npm run scully" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

</code></pre>

**Comment by SanderElias** [comment]
@falcon-Z What happens when you run `npm run scully:serve`?

**Comment by falcon-Z** [comment]
Scully-serve works
Also, I ran the project on WSL it worked fine with the config as in documentation. 
So I figured the problem in windows must be with launching chrome and I added no-default-browser-check and disable-gpu flags to Scully config file and it worked

**Comment by SanderElias** [comment]
@falcon-Z I'm glad you got it fixed. I'll close this issue now
