### ISSUE TITLE
Getting data from Firebase Cloud store to generate pages

### ISSUE THREAD

**Issue by kunjee17** [scullyio/scully#1185]
As per docs I have to put API and map ids to create un-handled pages.  What if I have to create page using firestore that is already there in application ? Or I have to create some api to access at build time for pages to get created?

**Comment by SanderElias** [comment]
@kunjee17 You can use firestore without an issue. The only thing you have to take into account, we do watch for page completion. Firebase observables usually don't complete, so your page will not reach the 'ready' state. 
An easy fix might be adding something like this to your pipe's:
```typescript
  take(isScullyRunning()?1:Number.MAX_SAFE_INTEGER)
```

**Comment by kunjee17** [comment]
@SanderElias Sorry if I was not clear. 

Here is what I m trying to do. We have a product page. And `product/:slug` will have product detail page. So, for now slug is not getting resolved obviously. So, only generated page is `product/index.html` . Then it will take care of fetching product details based on slug. 

Now, I want to generate page based on slug. Data is stored in firestore as mentioned earlier. Another thing I want to ask that what I can do if I don't want to fetch any data after generating of page. 

Means if page `product/iron/index.html` is crated. User can access using `product/iron` page. But after page is getting loaded it should not fetch all details of product. Obviously few details like stock etc should be updated after page is loaded. But Iron details should be rendered at the time of generation. 

Sorry for dumb question, I m little new to Scully so don't know api that well.

**Comment by SanderElias** [comment]
Ah, well you need to add your own route plugin then! (sorry for the late replay, I didn't work during the holidays)
something like this would probably work for you (not real code, but it should get you going!):

```typescript
import { firbaseGetThingie } from '@soemthign/firebaseThing';
import { registerPlugin } from '@scullyio/scully';
const extractIds= (data):string=> `Do some actual extracting in this function`
registerPlugin('router', 'myFirebaseThing', async (unhandledRoute) => {
  const slugsAsArray = await firbaseGetThingie('url').pipe(map(extractIds),take(1)).toPromise()
  return slugsAsArray.map(id => `/myRoute/${id}`)
})
```

I know that @jorgeucano did something like this too. @jorgeucano, anything to add?
Does that answer your question completely? if so, we can close the issue

**Comment by kunjee17** [comment]
Thanks for reply @SanderElias . And no need for sorry. No one should work on holidays. :) 

I guess I did understand what you are trying to tell. I ll wait for @jorgeucano 's reply. Else we can surely close it.

PS: Just to confirm. If I don't want data to be fetched, dynamically I can blocked using isScullyRunning right ?

**Comment by SanderElias** [comment]
Yep, thats right:
```ts
if (!isScullyRunning()) {
  // fetch data 
} else {
  // show placeholder
}
```
