### ISSUE TITLE
HubSpot chat bubble doesn't show up

### ISSUE THREAD

**Issue by stewwan** [scullyio/scully#1187]
### Description

I wanted to integrate the chat service from HubSpot but for some reason it's not working with the rehydration result generated from scully.

#### 🔬 Minimal Reproduction
needs a hubspot account (it's free) with chat widget configured (it's just a script paste into index.html)
https://www.hubspot.com/

then the normal workflow
ng build --prod and &&  npm run scully 

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 11.0.5
Node: 12.14.0
OS: darwin x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            9.1.12
@angular-devkit/schematics      9.1.12
@schematics/angular             9.1.12
@schematics/update              0.803.29
rxjs                            6.6.3
typescript                      4.0.2
</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "1.0.1",
    "@scullyio/ng-lib": "1.0.1",
    "@scullyio/scully": "1.0.9",
</code></pre>

## 🔥 Exception or Error

Chat bubble just doesn't show up. If I serve the result generated by angular in dist it works fine though.

**Comment by stewwan** [comment]
Managed to fix it by doing a few checks and loading the script dynamically.

Solution

```ts
 // on any page/component you want to load the script (can't be app.component) 
  canLoad = environment.production ? isScullyGenerated() : true;
  ngOnInit() {
    if (this.canLoad) {
        const node = document.createElement('script');
        node.src = '//js.hs-scripts.com/XXX.js';
        node.type = 'text/javascript';
        node.async = true;
        node.defer = true;
        node.id = 'hs-script-loader';
        document.getElementsByTagName('head')[0].appendChild(node);
    }
  }
```

**Comment by clark-97** [comment]
if I want to remove hubspot chat bubble on some page, how to use window.HubSpotConversations.widget.remove() on angular component? @stewones

**Comment by stewones** [comment]
As long as you have loaded HS script outside the scully process (as above), you should be able to call their api through global window object with no problem. 

This is the approach I'm taking for any third party dependency which needs to be loaded via script tags manually , to name a few: HubSpot, Stripe, Google/Facebook Ads Pixels and more
