### ISSUE TITLE
Issue with regular routes

### ISSUE THREAD

**Issue by baeteja** [scullyio/scully#1188]
I have been trying to convert my angular application to a static generated site with scully.
I have a feeling that I'm missing something here, as there seems to be a problem with regular routing on my application.

I have the following route
{ path: ':lang/home', component: Home }

I went through the faq (https://scully.io/docs/faq/) and tried to implement the solution for language parameters, I noticed however that scully does not seem to recognize the route once ":lang" gets replaced with an actual value.

So this:
'/en/home': { type: 'default' }

Still results in this:
No configuration for route "/:lang/home" found. Skipping

When I use "extraRoutes", everything is working as expected. However, this would result in issues for the future.
Am I missing something here?

I'm using angular 11 and
    "@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",

**Comment by SanderElias** [comment]
@baeteja The sample in the docs is just that, a sample. Aside from adding the routes, you can also have it add the needed extraRoutes automatically. 
```typescript
const preLangConfig: ScullyConfig = {
  /** settings */
  routes: {
    ':lang/route1': { type: 'default' },
    ':lang/route2': { type: 'default' },
    ':lang/route3': { type: 'default' },
    ':lang/route4': { type: 'default' },
  },
};
let resolve
const extraRoutes = new Promise<string[]>(res => resolve=res)
const ex=[];
export const config = {
  ...preLangConfig,
  routes: Object.fromEntries(
    // make sure you use a node-version that supports this, or use a reduce.
    Object.entries(preLangConfig.routes).reduce((all, [route, config]) => {
      if (route.includes(':lang')) {
        ['it', 'en', 'nl', 'sp'].forEach((
          lang // <-- language array
        ) => {
          const newRoute = route.split(':lang').join(lang);
          all.push([newRoute, config]);
          ex.push(newRoute)
        }
      } else {
        all.push([route, config]);
      }
      return all;
    }, [])
  ),
};
resolve(ex)
```
Something along those lines would work for you, right?
I think this answers your question, so I'm going to close this. If I did misunderstand your question, let me know, and I'll reopen it happily

**Comment by joeypedicini92** [comment]
I would like to reopen this as I'm having the same exact issue and I don't understand the answer here.

**Comment by SanderElias** [comment]
@joeypedicini92 The code in the sample replaces the routes in the config with routes that have the language already provided.
In my sample:
```ts
  routes: {
    ':lang/route1': { type: 'default' },
 }
 ```
will end up in the exported config as:
```typescript
  routes: {
    'it/route1': { type: 'default' },
    'en/route1': { type: 'default' },
    'sp/route1': { type: 'default' },
    'nl/route1': { type: 'default' },
 }
```
The code is replacing the routes in the config that have the string `:lang` inside them with multiple routes that have the actual language names. 
As it is code I just typed up in the answer and didn't test, it might not work when you copy/paste it. It's meant as a starting point for people that need something similar. 
Do you need me to write an example that does the same that is less terse?

**Comment by joeypedicini92** [comment]
scully.config.ts
```
import { ScullyConfig } from '@scullyio/scully';

const preLangConfig: ScullyConfig = {
  projectRoot: './src',
  projectName: 'X',
  outDir: './dist/static',
  routes: {
    ':lang': { type: 'default' },
  },
};
export const config = {
  ...preLangConfig,
  routes: Object.fromEntries(
    // make sure you use a node-version that supports this, or use a reduce.
    Object.entries(preLangConfig.routes).reduce((all, [route, config]) => {
      if (route.includes(':lang')) {
        ['en-us', 'en-gb'].forEach(
          (
            lang // <-- language array
          ) => all.push([route.split(':lang').join(lang), config])
        );
      } else {
        all.push([route, config]);
      }
      return all;
    }, [])
  ),
};

console.log(config.routes);

```

output:
```
% npx scully --scanRoutes --showGuessError
using plugins from folder "./scully"
{ 'en-us': { type: 'default' }, 'en-gb': { type: 'default' } }
 ☺   new Angular build imported
Starting background servers with: node ./node_modules/@scullyio/scully/src/scully.js serve --tds false --pjf false --ls warning --noCache true --project X
 ☺   Started servers in background
Finding all routes in application.
traversing app for routes
Pull in data to create additional routes.
No configuration for route "/:lang/changepassword" found. Skipping
***... all of our routes here, all with the same skipped message ...***
No configuration for route "/:lang/:slug" found. Skipping
Route list created in files:
  "./src/assets/scully-routes.json",
  "/Users/joey/Repos/X/dist/static/assets/scully-routes.json",
  "/Users/joey/Repos/X/dist/out-tsc/assets/scully-routes.json"

Route "" rendered into file: "./dist/static/index.html"

Generating took 62.94 seconds for 1 pages:
  That is 0.02 pages per second,
  or 62942 milliseconds for each page.
  
  Finding routes in the angular app took 35.02 seconds
  Pulling in route-data took 7 milliseconds
  Rendering the pages took 26.82 seconds
```

**Comment by joeypedicini92** [comment]
If that config code won't work I'd love to see a working example for our use case. We really only support those two langs for now, and every route we have has `:lang` at the start
