### ISSUE TITLE
Angular project without Angular Router

### ISSUE THREAD

**Issue by BenLune** [scullyio/scully#1189]
Hi there,
First of all, thank you and congratulations for this great project.
I am working on an Angular project without the Angular Router. I'm not sure Scully can manage it, am I wrong ?
I succeeded make it work with the CLI commands with extraRoutes, but when I add the ScullyLibModule in my AppModule, I have this runtime error : 
`NullInjectorError: R3InjectorError(AppModule)[ScullyLibModule -> IdleMonitorService -> Router -> Router -> Router]: 
  NullInjectorError: No provider for Router!`

**Comment by SanderElias** [comment]
The Angular router is mandatory for Scully. 
It can be used without, but you won't be able to use the `ng-lib`, which would put a load of responsibilities onto your code.

**Comment by VRa3** [comment]
@SanderElias Is there any chance to improve the error message? In my case it was:
`R3InjectorError(t)[t -> t -> t -> t -> t]: NullInjectorError: No provider for t!`
It took a while to found out it's about missing Router
