### ISSUE TITLE
WSL gets stuck at running scully

### ISSUE THREAD

**Issue by ruslanguns** [scullyio/scully#1190]
### Description

Having issues probably because my WSL. I followed the instructions adding the Puppeteer and adding the settings into my scully config file.

#### 🔬 Minimal Reproduction

1. Create a project with ng new
2. Add scully
3. Add blog `ng g @scullyio/init:blog`
4. Build and run scully `npm run build && npm run scully` <= this is where it gets stuck

#### 💻Your Environment

WSL 2 with Ubuntu 20

```bash
➜  blog-starter-kit git:(master) ✗ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

**Angular Version:**

<pre><code>

➜  blog-starter-kit git:(master) ✗ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.0.5
Node: 14.15.3
OS: linux x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
</code></pre>

## 🔥 Exception or Error

<pre><code>

# Just stuck at this point...
➜  blog-starter-kit git:(master) ✗ npm run scully

> blog-starter-kit@0.0.0 scully /home/ruslan/learn/angular/scully-projects/blog-starter-kit
> scully

logging with severity "warning"

**********************************************************
**********************************************************
You are using "WSL" as a terminal, if you get an
error please read the pre-requisites for Microsoft WSL.
https://scully.io/docs/learn/getting-started/installation/
**********************************************************
**********************************************************

using plugins from folder "./scully"
 ☺   new Angular build imported
Background servers already running.
Finding all routes in application.

----------------------------------
Using stored unhandled routes!.
   To discover new routes in the angular app use "npm run scully -- --scanRoutes"
----------------------------------
Pull in data to create additional routes.
Route list created in files:
  "./src/assets/scully-routes.json",
  "/home/ruslan/learn/angular/scully-projects/blog-starter-kit/dist/static/assets/scully-routes.json",
  "/home/ruslan/learn/angular/scully-projects/blog-starter-kit/dist/blog-starter-kit/assets/scully-routes.json"

⠙ Creating Route List: 3/3
</code></pre>

**Comment by SanderElias** [comment]
@jorgeucano Can you take a look? 
related: #1117 #892 
@ruslanguns have you seen the [WSL Pre-Requisites](https://scully.io/docs/learn/getting-started/installation/)

**Comment by ruslanguns** [comment]
Yes, I did.

**Comment by jorgeucano** [comment]
@ruslanguns  I tried and work for me, we need more info!
Can you share your project?

**Comment by ruslanguns** [comment]
So sorry for delay... 

Repository link: https://github.com/ruslanguns/blog-starter-kit

BTW I created a video for you Jorge Cano in Spanish https://www.youtube.com/watch?v=BfLjWQkdBcQ

**Comment by SanderElias** [comment]
@ruslanguns @jorgeucano Is this still an issue?

**Comment by ruslanguns** [comment]
@SanderElias I recorded that video 4 days ago, I can retry this afternoon if you want, after upgrading everything out.

**Comment by SanderElias** [comment]
@ruslanguns let's await @jorgeucano's reaction. I know he has a _large_ workload ATM.

**Comment by ruslanguns** [comment]
@SanderElias  @jorgeucano On Windows side works smoothly, just with the downside of WSL

![image](https://user-images.githubusercontent.com/19806968/104794316-b18a1d00-579e-11eb-8dc4-33893f672f91.png)

**Comment by SanderElias** [comment]
@ruslanguns Well, I work on Ubuntu (no WSL,  I run it bare bones in my system) and I have no issue.
I know Jorge is using windows and is also using the WSL without issue. 
As it is working on your computer when you are not using the WSL, it seems something in your WSL environment.
Probably it has something to do with setting up puppeteer and chromium in there. 
Have a look at the [puppeteer troubleshooting documentation](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md)

I will await your results, if there is anything we can do in Scully to fix this we would gladly do so.

**Comment by ruslanguns** [comment]
In my case I will switch over Windows to be able to work with Scully, eventually will retry from a clean environment (a fresh WSL) and will update this issue.

Thank you!

**Comment by SanderElias** [comment]
Ok, So, I'm going to close this issue for now. When you have new findings, let me know, and we will reopen the issue.

**Comment by ruslanguns** [comment]
Sure! Thanks 😊
