### ISSUE TITLE
CriticalCSS plugin prints error message when trying to process image files

### ISSUE THREAD

**Issue by chriskinzel** [scullyio/scully#1192]
### Description

When using the @scullyio/scully-plugin-critical-css plugin, the plugin does not automatically ignore image files and will instead error out and print an error message to the console during Scully build. The plugin handler is skipped so this does not result in build failure, but the generated error messages are noise in the console.

The ideal behaviour here would be to not print anything to the console and just skip the image file without an error.

Also, I believe there is a typo in the error message, the word "handler" is misspelled as "hander" (see exact error message in "🔥 Exception or Error" section below).

#### 🔬 Minimal Reproduction

Any Scully project using the @scullyio/scully-plugin-critical-css plugin in `defaultPostRenderers` of the Scully config with a fileHandler plugin registered e.g. `registerPlugin('fileHandler', 'png', imageFilePlugin);`.

#### 💻Your Environment

**Angular Version:**

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 14.8.0
OS: darwin x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "^1.0.1"
"@scullyio/ng-lib": "^1.0.0"
"@scullyio/scully": "^1.0.0"
"@scullyio/scully-plugin-critical-css": "0.0.2"

</code></pre>

## 🔥 Exception or Error

<pre><code>
Error during content generation with plugin "criticalCss" for ./projects/website/blog-posts/images/banner.jpg. This hander is skipped.
</code></pre>

**Comment by SanderElias** [comment]
The error is printed from _inside_ of the Critical tool, and can't be prevented. (I looked into this)
We have an outstanding discussion (#1161) that would somewhat take care of this, but there isn't much we can do otherwise.
Closing this as there is nothing actionable for us now. If you know/find a way to handle this, we will reopen this issue

**Comment by SanderElias** [comment]
@chriskinzel It just occurred to me that you can "fix" this in your config file.
somewhere in your config:
```typescript
console.log = (...args) => {let [first,...rest]=args;  first = first typeof 'string' ? first.slice(0,40) : first; log(first,...rest)}
console.error = (...args) => {let [first,...rest]=args;  first = first typeof 'string' ? first.slice(0,40) : first; logError(first,...rest)}
```

Those will overwrite the global console log and error, and make them more in line with the rest of Scully output
