### ISSUE TITLE
Scully doubles the body

### ISSUE THREAD

**Issue by fireflysemantics** [scullyio/scully#1193]
Within `app.component.html` I have markup like this:

```
<fs-toolbar></fs-toolbar>
<body class="MinimumPadding">
    <main class="Outlet">
        <router-outlet></router-outlet>
    </main>    
</body>
```

When Scully renders this page it wraps the body in another body with the `MinimumPadding` class on it.  Here's a screenshot:

![Screenshot from 2021-01-02 16-30-13](https://user-images.githubusercontent.com/25155787/103467777-131aa800-4d18-11eb-9f0a-faa851765186.png)
 

So since the minimum top padding is `10rem` this ends up being 20 REM.

I'm going to change the design, but this is the live site that this is happening in:

https://help-service-parts.fireflysemantics.com/

# Update

It ended up being a pretty simple fix.  Just moved the `MinimumPadding` class to the `main` element.

**Comment by SanderElias** [comment]
@fireflysemantics This is how Angular renders your page. Scully doesn't change that.
Also, [HTML semantics only allow 1 body element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body) and using multiple might have some other surprising effects.
