### ISSUE TITLE
Does Scully work without Angular Router ?

### ISSUE THREAD

**Issue by BenLune** [scullyio/scully#1199]
Hi There,
I wish you all a happy new year ! And congratulations for this great tool ! I'm working on Angular projects without the Router, and I would like to know if Scully can handle this kind of Angular project.
Thank you !
Benoît

**Comment by SanderElias** [comment]
@BenLune No, Scully does not work without the router.
If you really want, it can be done, but the out of the box experience requires the router.
When you want to go without the router, you need to manually set it up, and there is no guidance. It _is_ possible, but there is no documentation or help available if you want to do so.
