### ISSUE TITLE
Exclude some routes from prerendering

### ISSUE THREAD

**Issue by daniloff200** [scullyio/scully#1201]
I'm looking for ability to exclude some routes from prerendering.

That was mentioned in https://github.com/scullyio/scully/issues/154 and looks to be fixed by `voidPlugin`, but, I can't find anything about that in the docs, or, some examples.

So,  my question is: **Does this plugin works for now?**

I also have some routes in the app (mostly some dynamic routes, which number can increase every day, let's say, it's some personnel page for a user with some info, and it has a path, like,` /info/:userId` (and `userId` is a random string, so, can't use it like `/1, /2`, etc), and, I think, the best solution for me here is to exclude it from prerender, but, I can't do it for now.

**Comment by darxx** [comment]
I had similar question related to route id. What helped in my case [The Angular Jamstack with Scully by Aaron Frost](https://www.youtube.com/watch?v=XJ1WzPKPSQo). Let us know if it helps in Your case.

**Comment by daniloff200** [comment]
hey, @darxx 
Thanks for the link, I've watched all the video, also, found the repo, presented here (https://github.com/aaronfrost/DonutStore, and checked all the steps here, but, couldn't find something, related to my question). Could you describe your solution?

**Comment by daniloff200** [comment]
I assume I can use `ignored` plugin for that, but, in this case, I don't get generated HTML in static folder, but, when I try to go to such route and reload the page, I get two type of errors

Like,` cannot get /route/page`
or
`404 - URL not provided in the app Scully is serving
The url "/route/abc" is not provided in the scully.routes.json, so it can't be generated`

**Comment by darxx** [comment]
In my case we had API endpoint that's return all id that need to be static pages. And by json plugin we able to get all routes that's as it was shown in YouTube link. In our case we need to generate all /product/:id. Hope @SanderElias can help You more.

**Comment by daniloff200** [comment]
@darxx yeah, in general, I also ended with such solution, and created api calls for such case
