### ISSUE TITLE
Scully Strips Web Components from Generated Content

### ISSUE THREAD

**Issue by fireflysemantics** [scullyio/scully#1204]
### Description

If we include a web component inside content that scully should create static content for, it strips the web component.

For example if we have content like this:

```
  <h1> Scully Custom Element Test</h1>
  <fs-image url="https://fireflysemantics.github.io/i/developer/instant-html-vscode.png"></fs-image>
```

The custom element gets stripped from the output.

#### 🔬 Minimal Reproduction

https://github.com/fireflysemantics/scully-custom-element-test

The generate route is '' and this is the component generated into that route.

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  template: '<p [innerHTML]=html></p>',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  html:string = `
  <h1> Scully Custom Element Test</h1>
  <fs-image url="https://fireflysemantics.github.io/i/developer/instant-html-vscode.png"></fs-image>
  `
  constructor() { }

  ngOnInit(): void {
  }

}


```

If you run Scully and look at `index.html` you'll see that the web component gets stripped.
#### 💻Your Environment

**Angular Version:**

11

<pre><code>

</code></pre>

**Scully Version:**
```
    "@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
```

## Stackoverflow Question About This

https://stackoverflow.com/questions/65744660/using-web-components-with-scully

**Comment by SanderElias** [comment]
When I run your application, this is what is presented to Scully:
```html
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Test</title>
  <base href="/">
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1"
  >
  <link
    rel="icon"
    type="image/x-icon"
    href="favicon.ico"
  >
  <link
    rel="stylesheet"
    href="styles.09e2c710755c8867a460.css"
  >
  <style></style>
</head>

<body
  data-new-gr-c-s-check-loaded="14.991.0"
  data-gr-ext-installed=""
>
  <app-root
    _nghost-aoj-c3=""
    ng-version="11.0.9"
  >
    <router-outlet _ngcontent-aoj-c3=""></router-outlet>
    <app-home _nghost-aoj-c2="">
      <p _ngcontent-aoj-c2="">
      <h1> Scully Custom Element Test</h1>

      </p>
    </app-home>
    <!---->
  </app-root>
  <script
    src="runtime.0e49e2b53282f40c8925.js"
    defer=""
  ></script>
  <script
    src="polyfills.1f3b39c11fffb306d5a3.js"
    defer=""
  ></script>
  <script
    src="main.30df6ebad07b05698939.js"
    defer=""
  ></script>

</body>

</html>
```
As you can see, the  `fs-image` element is not in there. It's impossible for Scully to render something that is not present.
Your app doesn't generate the element, so Scully can _not_ magically add it to your output HTML files.

**Comment by fireflysemantics** [comment]
AH - I see what you are saying.  Angular is still stripping it even though the custom element Schema is in place.
