### ISSUE TITLE
Arguments other than strings and Errors are lost when enhancedLog is called

### ISSUE THREAD

**Issue by Markus-Ende** [scullyio/scully#1205]
### Description

Arguments other than strings and Errors are lost when enhancedLog is called. 

#### 🔬 Minimal Reproduction

1. Start scully in watch mode
2. Look at the `enable reload on port`, which is missing the port number, because it has type `number`
#### 💻Your Environment

**Angular Version:**

<pre><code>
11.1.5
</code></pre>

**Scully Version:**

<pre><code>
1.0.11
</code></pre>

**Comment by SanderElias** [comment]
Closed by #1206
Thanks @Markus-Ende
