### ISSUE TITLE
No pages generated for blog route

### ISSUE THREAD

**Issue by diminutivesloop** [scullyio/scully#1207]
### Description
I followed [the instructions to add blog support](https://scully.io/docs/learn/create-a-blog/add-blog-support/) but when I rebuilt w/ `ng build && scully` no pages were generated for the blog route even though matching markdown files exist in the content folder.

#### 🔬 Minimal Reproduction
https://github.com/diminutivesloop/scully-blog-test

#### 💻Your Environment

**Angular Version:**

<pre><code>Angular CLI: 11.0.7
Node: 12.20.1
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5</code></pre>

**Scully Version:**

<pre><code>"@scullyio/init": "^1.0.1",
"@scullyio/ng-lib": "^1.0.0",
"@scullyio/scully": "^1.0.0",</code></pre>

**Comment by jorgeucano** [comment]
Hi @diminutivesloop I check your repo and you have here the published false, if you change to true this will work!
https://github.com/diminutivesloop/scully-blog-test/blob/master/blog/2021-01-16-blog.md

**Comment by diminutivesloop** [comment]
@jorgeucano I published the post as you described, but Scully still only renders the `"/"` route.
```
> scully-blog-test@0.0.0 scully G:\projects\scully-blog-test
> scully

logging with severity "warning"
using plugins from folder "./scully"
 ☺   new Angular build imported
Starting background servers with: node .\node_modules\@scullyio\scully\src\scully.js serve --tds false --pjf false --ls warning --project scully-blog-test
 ☺   Started servers in background
Finding all routes in application.

----------------------------------
Using stored unhandled routes!.
   To discover new routes in the angular app use "npm run scully -- --scanRoutes"
----------------------------------
Pull in data to create additional routes.
Route list created in files:
  ".\src\assets\scully-routes.json",
  "G:\projects\scully-blog-test\dist\static\assets\scully-routes.json",
  "G:\projects\scully-blog-test\dist\scully-blog-test\assets\scully-routes.json"

Route "/" rendered into file: ".\dist\static\index.html"

Generating took 3.75 seconds for 1 pages:
  That is 0.27 pages per second,
  or 3755 milliseconds for each page.

  Finding routes in the angular app took 3 milliseconds
  Pulling in route-data took 0 milliseconds
  Rendering the pages took 1.37 seconds
```

**Comment by SanderElias** [comment]
@diminutivesloop :
```bash
➜  scully-blog-test git:(master) ✗ npx scully
logging with severity "warning"
using plugins from folder "./scully"
 ☺   new Angular build imported
Starting background servers with: node ./node_modules/@scullyio/scully/src/scully.js serve --tds false --pjf false --ls warning --project scully-blog-test
 ☺   Started servers in background
(You can skip this, or any future question by using the --noPrompt flag)
Would you allow Scully to collect anonymous errors to improve our services? (Y/n)y
Finding all routes in application.
traversing app for routes
Pull in data to create additional routes.
Finding files in folder "./blog"
Route list created in files:
  "./src/assets/scully-routes.json",
  "/home/sander/Documents/temp/scully-blog-test/dist/static/assets/scully-routes.json",
  "/home/sander/Documents/temp/scully-blog-test/dist/scully-blog-test/assets/scully-routes.json"

Launching puppeteer with executablePath /home/sander/.apps/chrome-linux/chrome
Route "" rendered into file: "./dist/static/index.html"
Route "/blog/2021-01-16-blog" rendered into file: "./dist/static/blog/2021-01-16-blog/index.html"

Generating took 3.32 seconds for 2 pages:
  That is 0.61 pages per second,
  or 1662 milliseconds for each page.
  
  Finding routes in the angular app took 1.75 seconds
  Pulling in route-data took 4 milliseconds
  Rendering the pages took 868 milliseconds
```
It works for me

**Comment by diminutivesloop** [comment]
Ok I'm not sure what the issue was but after I successfully got the build working on another machine I deleted and reinstalled `node_modules` on the original machine and the build is now working there too.
