### ISSUE TITLE
Fragment Links aren't generated properly

### ISSUE THREAD

**Issue by pjlamb12** [scullyio/scully#1222]
## 🐞 Bug report
Fragment links (# info, for example) aren't generated properly from Markdown files

### Description
In my blog posts, I have the titles set up to be fragment links, so you can link to /blog/my-post#some-section, but the fragment links are not generated properly from the Markdown. Instead of /blog/my-post#some-section, the link is /#some-section.

#### 🔬 Minimal Reproduction
Create a blog post, and then add a link like this:

```md
[link](#fragment)
```

#### 💻Your Environment

**Angular Version:**

<pre><code>
Your global Angular CLI version (11.1.1) is greater than your local version (11.0.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.0.3
Node: 14.14.0
OS: darwin x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1000.5
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            9.1.12
@angular-devkit/schematics      9.1.12
@schematics/angular             9.1.12
@schematics/update              0.1100.3
rxjs                            6.6.2
typescript                      4.0.5</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "^1.0.1",
"@scullyio/ng-lib": "^1.0.0",
"@scullyio/scully": "^1.0.8",
"@scullyio/scully-plugin-critical-css": "0.0.2",
</code></pre>

**Comment by SanderElias** [comment]
@pjlamb12 This is how those links should behave according to specs. 
I agree that is not very useful, so to fix this, [we have a plugin](https://www.npmjs.com/package/@scullyio/scully-plugin-docs-link-update)

**Comment by pjlamb12** [comment]
Thanks for the heads up!
