### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by adrian-ub** [scullyio/scully#1245]
## 🐞 Bug report

i am trying generate a plugin using schematics in a monorepo with Nx

#### 🔬 Minimal Reproduction

```shell
ng generate @scullyio/init:add-plugin --name=lazy --project=website --pluginType=render
Cannot read property 'toString' of null
```

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 11.1.2
Node: 14.15.1
OS: win32 x64

Angular: 11.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.1.2
@angular/service-worker         11.1.2
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/init": "^1.0.1",
"@scullyio/ng-lib": "^1.0.0",
"@scullyio/scully": "^1.0.0",
</code></pre>

## 🔥 Exception or Error

<pre><code>

Cannot read property 'toString' of null
</code></pre>

**Comment by SanderElias** [comment]
@jorgeucano can you check this out.

**Comment by SanderElias** [comment]
@jorgeucano Is this part of your other issues/fixes?

**Comment by jorgeucano** [comment]
yes, its fixed
