### ISSUE TITLE
How to method POST external data api and modify routes

### ISSUE THREAD

**Issue by adrian-ub** [scullyio/scully#1248]
## 🧩 Feature request

Example or idea to obtain an external API and modify the data of the routes.

### Description

Can retrieve external data from api, in my example it is get data from github api and include it in my scully generated routes.

I have tried as follows but it doesn't work

### Example

```ts
export async function repository(
  routes: HandledRoute[]
): Promise<HandledRoute[]> {
  return of(routes)
    .pipe(
      map((routes: HandledRoute[]) =>
        routes.filter((route) => route.templateFile)
      ),
      switchMap((routes: HandledRoute[]) =>
        forkJoin(
          routes.map((route: HandledRoute) => {
            if (route.route.startsWith('/r/')) {
              const repository = route.data.repository;
              return fetchRepo(repository.username, repository.name).pipe(
                map((data) => {
                  route.data.repository = {
                    ...route.data.repository,
                    data,
                  };
                  log(`Done replacing repository for ${green(route.route)}.`);
                  return route;
                })
              );
            }
            return route;
          })
        )
      )
    )
    .toPromise<HandledRoute[]>();
}
```

**Comment by SanderElias** [comment]
There are multiple ways you can add already do this.
1. a routeing plugin. this would make the most sense. create a route in your app like '/github/:user` and map that to your plugin.
2. use a route process plugin, where you add in the extra routes.
3. use the extraRoutes config option.  It handles a `promise<string[]>` just fine, so you can hookup whatever there.

No matter what option you use, if your angular doesn't handle the route,  it doesn't end up in the end result.|
I'm unsure what you are trying to achieve that is not already covered by the above methods

**Comment by adrian-ub** [comment]
I am making a portfolio with github repositories, I have started a route with the contentFolder plugin to store basic data of the repository and the content, then with the basic data that would be user and repository name, consult the Github api to obtain extra data, but for me it would be better to only consult the api during the generation of the site than to consult it every time the user enters the site.

What I try to do is that the extra data that I consult from the api, store it in the `scully-routes.json` according to the project route

Because it is an asynchronous function I have not managed to store the renewed information of the api

**Comment by adrian-ub** [comment]
For now I chose for the plugin to disable angular

**Comment by SanderElias** [comment]
@adrian-ub I think in your case its the easy way to use the Scully transfer-state from within your angular app. It does embedd the data into the HTML itself.
