### ISSUE TITLE
devops, automate tagged releases

### ISSUE THREAD

**Issue by SanderElias** [scullyio/scully#1257]
Add functionality, so we can set a flag on a pr and then:
1. it should check which publishable are updated
2. update their patch version
3. publish them to NPM under the latest tag.

A follow up on the will be how to handle minor versions/

**Comment by pjlamb12** [comment]
@SanderElias  So from what I can see, the workspace uses Nx, right? So GitHub Actions should be able to do the heavy lifting here I think. This is a link to an action that I use to run affected tests on libs/apps in a workspace, but you can do similar things to publish affected apps.

https://github.com/pjlamb12/ng-utah-nx-demo-app/blob/main/.github/workflows/nx-affected-tests.yaml

Essentially, you add a new target that can run a bash script if you need to, or a series of commands, and that would build and publish the library. The hard part would be determining the patch version manually if you can't use something like the standard-version package or something. I think there's a similar option for Nx workspaces.

I know at a high level how to do this, and could get most of it set up through GitHub Actions, but the specifics on updating the patch version and publishing with that new tag to NPM would be the trickiest part.

https://www.prestonlamb.com/blog/deploying-nx-affected-apps-from-github-actions

**Comment by SanderElias** [comment]
Most of the scripting needed for this is in place already. 
The nx toolset only gives an offset of the latest nx build, not of a previous version released to NPM.

**Comment by SanderElias** [comment]
this is done
