### ISSUE TITLE
Clarify the purpose of the two started servers when running `npm run scully:serve`

### ISSUE THREAD

**Issue by d-koppenhagen** [scullyio/scully#126]
# 🗄️ Docs report

### Description

Hello,  I was wondering what's the purpose of the two started servers when running `npm run scully:serve`:

```text
Scully static server started on "http://localhost:1668/" 
Angular distribution server started on "http://localhost:1864/"
```

I assume that the scully static site server is just a simple web server like nginx or similar that can be used to check the scully result.
But what's the purpose of the "Angular distribution server"? And whats the difference between this one and the one started by Angular when running "ng serve"?

### Reproduction Steps**
 ```
npm run scully:serve
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by SanderElias** [comment]
@d-koppenhagen You are right, and this is something we need to add to the documentation.
the first server is serving the angular app as it is in the dist folder, so Scully can scrape all the pages.
the second one is there as a courtesy. it serves the result from Scully, so you can locally interact with the results without needing any third party.

@Villanuevand we need some documentation around this.

**Comment by aaronfrost** [comment]
@jorgeucano can you describe here why we have the two servers? @SanderElias do you know?

One serves the built directory: `/dist/app-name`
Static one serves the static dir: `/dist/static`

So it helps you see if where your errors are.

**Comment by Villanuevand** [comment]
@aaronfrost @SanderElias 

Let's meet with @jorgeucano to  add the explanation to the docs....

**Comment by SanderElias** [comment]
> The first server is serving the angular app as it is in the dist folder, so Scully can scrape all the pages.
The second one is there as a courtesy. it serves the result from Scully, so you can locally interact with the results without needing any third party.

**Comment by Villanuevand** [comment]
@SanderElias  @aaronfrost  @d-koppenhagen 
Im going to create a new issue to add this data to the docs..
