### ISSUE TITLE
Scully could not find the <.scully-content>. tag in this page.

### ISSUE THREAD

**Issue by gbumanzordev** [scullyio/scully#1261]
### Description
When I create run `npm run scully -- --scanRoutes` it gives me a warning that the `<scully-content></scully-content>` is not found and that I should head to `http://localhost:4200` and query it in the console. I do that and it works, however. when I serve scully and try to go to a certain blog post, I get this:

```
Scully could not find the <.scully-content>. tag in this page.
This error can happen when you forgot to put the mandatory "scully-content" in the component that is rendering this page?

Or when the tag is not shown on page load. Did you put it inside an `*ngIf`?
```

#### 🔬 Minimal Reproduction
You can check my blog's repository here: https://github.com/gbumanzordev/blog
The branch I've been working on is feature/SCULLY
#### 💻Your Environment

**Angular Version:**

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.4
Node: 14.15.1
OS: win32 x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
</code></pre>

## 🔥 Exception or Error

<pre><code>

Route "/post/this-is-my-post" rendered into file: ".\dist\static\post\this-is-my-post\index.html"

      ----------------
      Error, missing "<scully-content>" in route "/post/2021-02-18-blog"
      without <scully-content> we can not render this route.
      Make sure it is in there, and not inside any conditionals (*ngIf)
      You can check this by opening "http://localhost:4200/post/2021-02-18-blog"
      when you serve your app with ng serve and then in the browsers console run:
      document.querySelector('scully-content')
      ----------------

</code></pre>

**Comment by SanderElias** [comment]
@gbumanzordev I pulled your repo and ran Scully. It did work as expected?
Can I close this issue?
![image](https://user-images.githubusercontent.com/1249083/108694456-5bc43580-74ff-11eb-8364-7fd7474869df.png)

**Comment by gbumanzordev** [comment]
> @gbumanzordev I pulled your repo and ran Scully. It did work as expected?
> Can I close this issue?
> ![image](https://user-images.githubusercontent.com/1249083/108694456-5bc43580-74ff-11eb-8364-7fd7474869df.png)
> 

Yes, please!

Turns out after I added the blog I had to build again, since I didn't read that in the docs I didn't think it was necessary.

Thanks for your support.
