### ISSUE TITLE
Better description of how to include a written plugin

### ISSUE THREAD

**Issue by d-koppenhagen** [scullyio/scully#127]
# 🗄️ Docs report

### Description

Currently in the docs it is described how a plugin (e.g. Router Plugin) is build:
https://github.com/scullyio/scully/blob/master/docs/plugins.md

I couldn't find any hint of where to put the plugin file should be put ideally and from where `registerPlugin` plugin is called.

### What's the affected URL?**
https://github.com/scullyio/scully/blob/master/docs/plugins.md

### Expected vs Actual Behavior**

The docs should include:

- [ ] The import of `registerPlugin` (I think it comes from `@scullyio/scully` doesn't it?
- [ ] Where to put the plugin configuration file? Is there a naming convention for this file? Is it a `*.js` or `*.ts` file? Or is it may just part of `scully.config.js`?  
- [ ] How will scully find this plugin? Is there a configuration flag which links to the file(s)?

Best regards,
Danny

**Comment by aaronfrost** [comment]
I agree. We need to nail this down. You are right. We are locking down the plugins right now, and this is about to get better.

**Comment by Villanuevand** [comment]
@d-koppenhagen We just add more information about `registerPlugin` in [plugins.md](https://github.com/scullyio/scully/blob/master/docs/plugins.md#register-plugin)
