### ISSUE TITLE
Test for new project doesn't use packaged version of schematics

### ISSUE THREAD

**Issue by SanderElias** [scullyio/scully#1271]
### Description
Currently the test for a new project does used the latest version of the schematics pulled from the Scully repo.
It should be using the packaged @develop version.

Also while doing this test, it should pull the @develop version over the @latest

**Comment by Jefiozie** [comment]
@SanderElias I think this one can be closed now #1312 is closed?

**Comment by Jefiozie** [comment]
Closing this in favor of: #1312
