### ISSUE TITLE
Using deprecated plugin type:"render"  use "postProcessByHtml" instead

### ISSUE THREAD

**Issue by klexxp** [scullyio/scully#1289]
### Description
Hi, getting these errors after a new install. Don't know if I have the correct versions? 
Thanks in advance

#### 🔬 Minimal Reproduction
<pre><code>
import { ScullyConfig, setPluginConfig } from '@scullyio/scully';
import './scully/plugins/multi-params';
import { environment } from './src/environments/environment';

const { DisableAngular } = require('scully-plugin-disable-angular');
const { MinifyHtml } = require('scully-plugin-minify-html');
const {
  getFlashPreventionPlugin,
} = require('@scullyio/scully-plugin-flash-prevention');
const fouc = require('@notiz/scully-plugin-fouc');

setPluginConfig(DisableAngular, 'render', {
  removeState: true,
});
const postRenderers = [
  DisableAngular,
  fouc,
  getFlashPreventionPlugin,
  MinifyHtml,
];

export const config: ScullyConfig = {
  projectRoot: './src',
  projectName: 'matrix-landingpages',
  outDir: './dist/compiled-pages',
  defaultPostRenderers: postRenderers,
  routes: {
    '/:platform/:language/:gameId': {
      type: 'multiParams',
      platforms: environment.platforms
    },
  },
  puppeteerLaunchOptions: {
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  },
};
</code></pre>
#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 11.2.3
Node: 12.13.1
OS: win32 x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Scully Version:**

<pre><code>

"dependencies": {
    "@angular/animations": "~11.2.4",
    "@angular/common": "~11.2.4",
    "@angular/compiler": "~11.2.4",
    "@angular/core": "~11.2.4",
    "@angular/platform-browser": "~11.2.4",
    "@angular/platform-browser-dynamic": "~11.2.4",
    "@angular/router": "~11.2.4",
    "@scullyio/init": "^1.0.1",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.1.0",
    "contentful": "^8.1.4",
    "marked": "^1.2.7",
    "rxjs": "~6.6.0",
    "scully-interceptor": "0.0.8",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^11.1.0",
    "@angular-devkit/build-angular": "~0.1102.3",
    "@angular/cli": "~11.2.3",
    "@angular/compiler-cli": "~11.2.4",
    "@gammastream/scully-plugin-http404": "^1.0.4",
    "@notiz/scully-plugin-fouc": "^0.2.0",
    "@scullyio/scully-plugin-critical-css": "0.0.2",
    "@scullyio/scully-plugin-flash-prevention": "^1.0.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "del": "^6.0.0",
    "fast-xml-parser": "^3.17.4",
    "gulp": "^4.0.2",
    "gulp-brotli": "^3.0.0",
    "gulp-multi-dest": "^1.3.7",
    "path-to-regexp": "^0.1.7",
    "scully-plugin-disable-angular": "^6.2.0",
    "scully-plugin-minify-html": "^5.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2",
    "xmlbuilder": "^13.0.2"
  }
</code></pre>

## 🔥 Exception or Error

<pre><code>

Using deprecated plugin type:"render"  use "postProcessByHtml" instead
Using deprecated plugin type:"render"  use "postProcessByHtml" instead
Using deprecated plugin type:"render"  use "postProcessByHtml" instead
Using deprecated plugin type:"render"  use "postProcessByHtml" instead
Plugin "disableAngular" of type "render" is not found, can not store config
</code></pre>

**Comment by SanderElias** [comment]
The plugins that you are using need to be updated to use the new plugin structure. Its not breaking, but it _is_ deprecated.
The last one is a rtp party plugin, that they need to update. I think I did a PR on that already.

**Comment by klexxp** [comment]
Ok, thanks.
Using version 1.0.0 until they are updated.
