### ISSUE TITLE
broken installation: ng-lib not installed automatically and no scully config file generated.

### ISSUE THREAD

**Issue by hchings** [scullyio/scully#1297]
## 🐞 Bug report
Scully does not generate scully config file upon installation.

### Description
I'm trying to add Scully to an existing Angular 9 project by running `ng add @scullyio/init`.
It run through, however, it does not generate a scully config file under the top-level folder.

From the installation console output, it seems multiple installation steps didn't got triggered. 
(See "Exception or Error")

#### 🔬 Minimal Reproduction
Not sure.

#### 💻Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.11
Node: 12.0.0
OS: darwin x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router, upgrade
Ivy Workspace: No

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.11
@angular-devkit/build-angular              0.901.11
@angular-devkit/build-ng-packagr           0.901.11
@angular-devkit/build-optimizer            0.901.11
@angular-devkit/build-webpack              0.901.11
@angular-devkit/core                       9.1.11
@angular-devkit/schematics                 9.1.11
@angular/cdk                               9.1.0
@angular/cli                               9.1.11
@angular/flex-layout                       9.0.0-beta.31
@angular/http                              7.2.16
@angular/material                          9.1.0
@ngtools/webpack                           9.1.11
@nguniversal/builders                      9.1.1
@nguniversal/common                        9.1.1
@nguniversal/express-engine                9.1.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        9.1.11
@schematics/update                         0.901.11
ng-packagr                                 9.1.5
rxjs                                       6.6.0
typescript                                 3.8.3
webpack                                    4.42.0

</code></pre>

**Scully Version:**
<pre><code>
 "@scullyio/init": "^1.1.2",
 "@scullyio/ng-lib": "^1.1.0",
</code></pre>

## 🔥 Exception or Error
When running ``, the console only output the followings without errors:
```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
```

It does not run nor show the followings installation steps that I see when trying Scully on a blank project:
```
Install ng-lib
    ✅️ Added dependency
UPDATE src/app/app.module.ts (1144 bytes)
UPDATE src/polyfills.ts (3758 bytes)
UPDATE package.json (5074 bytes)
✔ Packages installed successfully.
    ✅️ Update package.json
    ✅️ Created scully configuration file in scully.exampleapp.config.ts
CREATE scully.exampleapp.config.ts (192 bytes)
UPDATE package.json (5148 bytes)
CREATE scully/tsconfig.json (450 bytes)
CREATE scully/plugins/plugin.ts (305 bytes)
```

**Comment by hchings** [comment]
Any help on this? Thanks

**Comment by SanderElias** [comment]
I'm sorry, but we can't reproduce your issue.
You might want to manually add Scully.
generate a new project, and look at the changes.
On top of my head, it is:
npm i @scullyio/scull @scullyio/ng-lib
add `ScullyLibModule` to your `app.module.ts`
create a `config.projectname.config.ts`  it should be something like this:
```typescript
import {ScullyConfig} from '@scullyio/scully';

const defaultPostRenderers:string[] = [];
export const config: ScullyConfig = {
  projectRoot: './src',
  projectName: 'demo',
  // distFolder: './dist/demo',
  outDir: './dist/static',
  defaultPostRenderers,
  routes: {},
  },
};
```

**Comment by hchings** [comment]
Issue solved w/ manual installed and modify relevant files. Still unsure about the root cause but can run Scully now. Thanks.

**Comment by SanderElias** [comment]
@hchings The root cause might be an `angular.json` that has an invalid json.  
We found that the parser used by the CLI is more forgiving than the one that is inside of the angular schematics. The Scully schematics silently fails in this case, leaving you in this spot.

**Comment by WhyINeedToFillUsername** [comment]
I have the same problem, and I'm trying to init scully (`ng add @scullyio/init`) on the official angular tour of heroes project (https://angular.io/generated/zips/toh-pt6/toh-pt6.zip).

There should be some more information to the console at least.

**Comment by WhyINeedToFillUsername** [comment]
Is there any log or some switch I could add to the command to get more information about why it failed?
I tried `ng add @scullyio/init --verbose`, but there's no more output.

**Comment by AbdurRKhalid** [comment]
I have to abandoned one of my personal project due to this problem. The reason is that the documentation has not mentioned to solve the peered dependency issue and it can be solved with the following command:

`npm install --legacy-peer-deps`

After doing that and After doing everything correctly there was again error present that was saying that the configuration file does not exists and after doing some more debugging and other experiments I came to know that this is the right command that we are supposed to run:

`ng add @scullyio/init --project=projectName`

After doing everything and solving every problem, I was not able to generate the template of module and basic components as well.

**Comment by LorenzoPaciotti** [comment]
I just did the same thing, I'm not an expert in any way (following a tutorial) but I have the same issues as others. I did try to install manually, but subsequent commands like ng generate @scullyio/init:markdown fail with various issues.

> I have to abandoned one of my personal project due to this problem. The reason is that the documentation has not mentioned to solve the peered dependency issue and it can be solved with the following command:
> 
> `npm install --legacy-peer-deps`
> 
> After doing that and After doing everything correctly there was again error present that was saying that the configuration file does not exists and after doing some more debugging and other experiments I came to know that this is the right command that we are supposed to run:
> 
> `ng add @scullyio/init --project=projectName`
> 
> After doing everything and solving every problem, I was not able to generate the template of module and basic components as well.

I just did the same thing, I'm not an expert in any way (following a tutorial) but I have the same issues as you. I did try to install manually, but subsequent commands like ng generate @scullyio/init:markdown fail with various issues.

**Comment by TatyanaMolchanova** [comment]
> 
Here is the type error:

npm i @scullyio/scull 

The right one is:
npm i @scullyio/scully

**Comment by isaac-manubag** [comment]
> ng add @scullyio/init --project=projectName

i'm running with Angular 14 and I have the same issue.. I guess its safe to assume scully is not Angular 14 (maybe even Angular 13 ready yet)

**Comment by MKaranusic** [comment]
> I have to abandoned one of my personal project due to this problem. The reason is that the documentation has not mentioned to solve the peered dependency issue and it can be solved with the following command:
> 
> `npm install --legacy-peer-deps`
> 
> After doing that and After doing everything correctly there was again error present that was saying that the configuration file does not exists and after doing some more debugging and other experiments I came to know that this is the right command that we are supposed to run:
> 
> `ng add @scullyio/init --project=projectName`
> 
> After doing everything and solving every problem, I was not able to generate the template of module and basic components as well.

To add on to @AbdurRKhalid solution, if you still are experiencing problems with "Config file ".\scully.undefined.config.ts" not found", add deprecated  "defaultProject": "yourProjectName" to angular.json

**Comment by offwork** [comment]
I don't understand any shit! Is this `ng add @scullyio/init` not enough to create the init file? That's what it says in the fucking [document](https://scully.io/docs/learn/getting-started/installation/) because...

**Comment by TongTC** [comment]
You should the angular commandline version 13.3.11

I already try it can generate config file.

Thanks
