### ISSUE TITLE
For tracking, add `scully-version` attr to the body on Scully pages

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#130]

**Comment by SanderElias** [comment]
Does this really need to be on the body tag?

**Comment by aaronfrost** [comment]
No. It can be anywhere on the page. As long as it is close to the root, and in the HTML (not buried inside of some JS somewhere). That way we can query it from the server.

**Comment by SanderElias** [comment]
did this as a drive-by in pr #178 
When that is merged, this can be closed
