### ISSUE TITLE
Building with BaseHref plugin does not produce correct index.html

### ISSUE THREAD

**Issue by hchings** [scullyio/scully#1306]
### Description
Everything works fine when building in dev mode. 
However, when we build with production configuration and with [scully-base-href-rewrite ](https://github.com/scullyio/scully/tree/main/libs/plugins/base-href-rewrite)plugin, index.html generated from different routes all have the same content.

```
npm run build:prod:en
npx scully --scanRoutes
```
Scully config:
```
import {ScullyConfig, setPluginConfig} from '@scullyio/scully';
import { baseHrefRewrite } from '@scullyio/scully-plugin-base-href-rewrite';

const defaultPostRenderers = ['seoHrefOptimise', baseHrefRewrite];
setPluginConfig(baseHrefRewrite, {href: 'https://somedomain.com'});
export const config: ScullyConfig = {
  projectName: 'project name',
  outDir: './dist/static',
  defaultPostRenderers,
  routes: {
    '/cases/:id': {
      type: 'json',
      id: {
        url: 'https://someapi.com',
        property: 'id',
      },
    }
  }
};
```
From the console out put of running Scully, things look correct and there's no error/warnings:
```
Rewritten 'base href' to https://somedomain.com, for route: /cases/2523332
Route "/cases/2523332" rendered into file: "./dist/static/cases/2523332/index.html"
```
However, the index.html generated has incorrect content.

This is the product config in angular.json:

```
 "production-en": {
              .....
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "outputPath": "dist/browser/",
}
```

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.1.11
Node: 12.0.0
OS: darwin x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router, upgrade
Ivy Workspace: No

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.11
@angular-devkit/build-angular              0.901.11
@angular-devkit/build-ng-packagr           0.901.11
@angular-devkit/build-optimizer            0.901.11
@angular-devkit/build-webpack              0.901.11
@angular-devkit/core                       9.1.11
@angular-devkit/schematics                 9.1.11
@angular/cdk                               9.1.0
@angular/cli                               9.1.11
@angular/flex-layout                       9.0.0-beta.31
@angular/http                              7.2.16
@angular/material                          9.1.0
@ngtools/webpack                           9.1.11
@nguniversal/builders                      9.1.1
@nguniversal/common                        9.1.1
@nguniversal/express-engine                9.1.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        9.1.11
@schematics/update                         0.901.11
ng-packagr                                 9.1.5
rxjs                                       6.6.0
typescript                                 3.8.3
webpack                                    4.42.0

</code></pre>

**Scully Version:**

<pre><code>
 "@scullyio/init": "^1.1.2",
 "@scullyio/ng-lib": "^1.0.0",
 "@scullyio/scully": "^1.0.0",
 "@scullyio/scully-plugin-base-href-rewrite": "^1.1.1",
</code></pre>

## 🔥 Exception or Error

All the index.htmls generated from different routes have the same and incorrect content.

**Comment by SanderElias** [comment]
Are you still having question regarding this?

**Comment by hchings** [comment]
Yes. We still need help on how to set up Scully correctly for the production build.

The production build happens on a Jenkin server that is currently not listed in the CSRF_TRUSTED_ORIGINS of the backend in prod. So the root cause should be that the Angular app Scully tentatively runs for pre-rendering does not have access to backend APIs in prod that is required for prerendering.

Specifically, our questions are:

1.   Is it possible to configure Scully to pre-render the app using non-prod HTTP backend APIs with the same data as in prod, but makes the prod build still remain the correct prod settings (having `rootUrl` in `environment.prod` points to prod API. having the correct BaseHref, etc )? If yes, how?

2. If #1 is not possible, how to configure Scully to serve Angular app using HTTPs rather than HTTP when scanning routes? Is it done by using `--ssl` flag when running `npx scully -scanRoutes`?

3. When running `npx scully serve --host=0.0.0.0 --ssl --ssl-cert=certificate.crt --ssl-key=private.key`, the non Scully version running at port `1864` works as expected. But the Scully one at port `1668` cannot work due to the below error:

`Mixed Content: The page at 'https://XXXX:1668/' was loaded over HTTPS, but requested an insecure script 'http://www.googletagmanager.com/gtag/js?id=XXXXX&l=dataLayer&cx=c'. This request has been blocked; the content must be served over HTTPS.`

And if understood correctly, this HTTP call is triggered from Scully:
`<html lang="en" class="eventlistener localstorage sessionstorage queryselector js-focus-visible js no-touch csstransforms3d csstransitions" data-js-focus-visible=""><head><meta name="generator" content="Scully 1.1.0">` in index.html.

How to resolve these?  Thanks!

**Comment by hchings** [comment]
Resolved and closing this question.
