### ISSUE TITLE
Using Netlify CMS with Netlify Identity causing dual login screens

### ISSUE THREAD

**Issue by JoeyMckenzie** [scullyio/scully#1315]
## 🐞 Bug report
**To preface, this only seems to be an issue and reliably reproducible when integrating Scully and Netlify CMS within Nx.**

When integrating Scully and Netlify CMS in an Nx monorepo, the admin page is displaying [two login widgets](https://user-content.gitter-static.net/9f89ee5c36b66c9aef0e1f1f8e967b3c7e9b8cb4/68747470733a2f2f66696c65732e6769747465722e696d2f3565303264376637643733343038636534666434666331652f59747a612f7468756d622f696d6167652e706e67). This is verifed when inspecting the page and seeing two instances of the `nc-root` element and corresponding widget `iframe`s.

### Description
I've recently began a project for a client that I was hoping to use Scully and Netlify CMS in my current Nx monorepo. Following @pjlamb12's [blog post](https://medium.com/ngconf/using-scully-and-netlify-cms-91b47aa77307) (which is awesome btw, great work!), the issue arises when integrating Netlify CMS into a generated admin route using script injection (example [here](https://github.com/JoeyMckenzie/nx-scully-netlify-cms-issue/blob/main/apps/nx-scully-issue/src/app/modules/admin/admin.component.ts)). The tl;dr of integrating Netlify CMS into an application is to expose Netlify's CMS library underneath an `/admin` route in your application where the package takes over administration of static content on your site. This all works fine within a single project context, but I'm having trouble getting this to work when integrating into a multi-project Nx monorepo.

I'm new to Scully (coming from Next/Nuxt on other projects in the past) so I'm uncertain whether it's a configuration issue I have self-induced along the way. Inspecting output in the `dist` folder, I'm seeing Scully generate what _seems_ to be the correct HTML with only one Netlify script and `iframe`'d widget, however, when serving the app with Scully, the login widget appears twice in the rendered DOM.

If this is a Netlify issue, please close this out and I'll post it over there. The only reason I'm posting it here is this doesn't seem to be an issue when serving the app as a traditional Angular app, only when serving through Scully. 

#### 🔬 Minimal Reproduction
1. Clone the [example repo](https://github.com/JoeyMckenzie/nx-scully-netlify-cms-issue) I created that loosely mimics my monorepo project.
2. Run `npm run build:prod:nx-scully-issue`
3. Serve the app with `npx scully --project nx-scully-issue`
4. Navigate to `localhost:1668/admin`
5. Observe two Netlify login widgets

I'm aware that flagging each command with a specific project is not necessary here as there is only one project in the Nx workspace, but the context of this issue is within a monorepo containing multiple Angular projects.

#### Workarounds
To get around this issue, inspect the `workaround` branch of the example repository. The changes include removing the `admin` module entirely and creating a separate `admin.html` to be served as a static page entirely outside the scope of your Angular project. 

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 10.0.8
Node: 14.16.0
OS: win32 x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.9
webpack                           4.43.0

</code></pre>

1.1.0

<pre><code>
{
  "name": "nx-scully-issue",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
    "nx": "nx",
    "start": "ng serve",
    "build": "ng build",
    "build:prod:nx-scully-issue": "ng build --prod --project=nx-scully-issue && npx scully --project nx-scully-issue --scanRoutes",
    "test": "ng test",
    "lint": "nx workspace-lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "ng update @nrwl/workspace",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "scully": "npx scully --",
    "scully:serve": "npx scully serve --"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.0.0",
    "@angular/common": "^10.0.0",
    "@angular/compiler": "^10.0.0",
    "@angular/core": "^10.0.0",
    "@angular/forms": "^10.0.0",
    "@angular/platform-browser": "^10.0.0",
    "@angular/platform-browser-dynamic": "^10.0.0",
    "@angular/router": "^10.0.0",
    "@nrwl/angular": "10.2.0",
    "@scullyio/init": "^1.1.3",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
    "rxjs": "~6.5.5",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular/cli": "~10.0.0",
    "@nrwl/workspace": "10.2.0",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "eslint": "6.8.0",
    "typescript": "~3.9.3",
    "prettier": "2.0.4",
    "@angular/compiler-cli": "^10.0.0",
    "@angular/language-service": "^10.0.0",
    "@angular-devkit/build-angular": "~0.1000.0",
    "codelyzer": "~5.0.1",
    "jest-preset-angular": "8.2.1",
    "@nrwl/jest": "10.2.0",
    "jest": "26.2.2",
    "@types/jest": "26.0.8",
    "ts-jest": "26.1.4",
    "cypress": "^4.1.0",
    "@nrwl/cypress": "10.2.0"
  }
}

</code></pre>

## 🔥 Exception or Error

<pre><code>
Not applicable.
</code></pre>

**Comment by SanderElias** [comment]
@JoeyMckenzie Is this still an issue? If so, we do need a way to reproduce the issue.

**Comment by SanderElias** [comment]
Closing, as this doesn't seem relevant anymore. If anything changes, we are happy to reopen
