### ISSUE TITLE
[DOcs][Starters]: unclear table of contents

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#1317]
### Description

On the starter [page](https://scully.io/docs/community/starters/) of the docs, the table of contents only contains 'details' sections.
It's both unclear and misleading.

![image](https://user-images.githubusercontent.com/32737308/114195297-a20b1200-9950-11eb-9c7a-6164be49ecb0.png)

### What's the affected URL?\*\*

https://scully.io/docs/community/starters/

### Expected vs Actual Behavior\*\*

I would suggest to change as followed : 
- Moving the name above as an `h2`
- - changing the dropwdown name to 'Details'

![image](https://user-images.githubusercontent.com/32737308/114197547-c10aa380-9952-11eb-994d-44260f43278f.png)

It's somehow how the faq part works : https://scully.io/docs/faq/

I can submit a PR if you approve this change.

## 📷Screenshot

already provided

## 🔥 Exception or Error

there is no exception/error

## 🌍 Your Environment

not relevant

### Browser info

not relevant

### Anything else relevant?

no

**Comment by SanderElias** [comment]
Hmm, the word details should be replaced by the title of the section.

**Comment by geromegrignon** [comment]
closed by #1320
