### ISSUE TITLE
[DOCS][FAQ] Hierarchy of File locations section

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#1318]
### Description

Onto the faq [page](https://scully.io/docs/faq/), is the 'File Locations' supposed to be a sub part of 'Docker and CI/CD'?
![image](https://user-images.githubusercontent.com/32737308/114198297-7178a780-9953-11eb-8b2f-12d3891754a5.png)

While it may happen, it isn't directly related.
I would suggest to move this section from `h3` to `h2`

## 🔬 Minimal Reproduction

https://scully.io/docs/faq/

### Reproduction Steps\*\*

Navigate to https://scully.io/docs/faq/

### Expected vs Actual Behavior\*\*

the 'File locations' section should be as the same level as the other ones.

I can submit a PR if you approve this change.

## 📷Screenshot

Already provided

## 🔥 Exception or Error

there is no exception/error.

### Browser info

not relevant.

### Anything else relevant?

no

**Comment by geromegrignon** [comment]
Hey @Jefiozie, can you assign me this issue? I'll submit a related PR later this week.

**Comment by Jefiozie** [comment]
Hi @geromegrignon sure thing thank you for picking this up. 🙏🏼
