### ISSUE TITLE
[Docs] Create a plugin page not published

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#1322]
### Description

The 'Create a Plugin' [page](https://github.com/scullyio/scully/blob/main/docs/learn/create-a-plugin/create-a-plugin.md) is not published. But i can't track any work in progress issue which would explain it's not published yet.
### What's the affected URL?\*\*

https://github.com/scullyio/scully/blob/main/docs/learn/create-a-plugin/create-a-plugin.md

### Reproduction Steps\*\*

Look at metadata of the markdown file : https://github.com/scullyio/scully/blob/main/docs/learn/create-a-plugin/create-a-plugin.md

### Expected vs Actual Behavior\*\*

If the page is ready to be used, it should be published, otherwise it should be track into an issue.

## 📷Screenshot

not relevant

## 🔥 Exception or Error

there is no related exception/error

### Browser info

not relevant

### Anything else relevant?

no

**Comment by Jefiozie** [comment]
Thanks @geromegrignon the only thing to do is to set published to true in the metadata at the top.

I'm adding a`hacktoberfest` label and mark it also as a `good first issue`.

Thanks for creating the issue

**Comment by geromegrignon** [comment]
Thanks for the update @Jefiozie, I unintentionally deactivated notifications on the project and missed the hacktoberfest invitation to fix this issue!

**Comment by Jefiozie** [comment]
No worries, thank you for creating the issue.
