### ISSUE TITLE
ng add @scullyio/init is not working 

### ISSUE THREAD

**Issue by Ambuj8105** [scullyio/scully#1327]
**Description**
on running this command ng add @scullyio/init i get the following error 
Error: ENOENT: no such file or directory, stat '/home/knoldus/knoldus_Project/Testing_knoldus/Knoldus-New-Website/scullyio/ng-lib-v8.tgz'

**Angular Version:**
Angular CLI: 8.3.29
Node: 14.15.4
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.29
@angular-devkit/build-angular     0.803.29
@angular-devkit/build-optimizer   0.803.29
@angular-devkit/build-webpack     0.803.29
@angular-devkit/core              8.3.29
@angular-devkit/schematics        8.3.29
@angular/cli                      8.3.29
@angular/fire                     5.4.2
@ngtools/webpack                  8.3.29
@schematics/angular               8.3.29
@schematics/update                0.803.29
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

**Comment by SanderElias** [comment]
@Ambuj8105 We don't support version 8 anymore. It looks like you are trying to install a custom v8 lib, that's not in your project.
you might have success by using an older version like this:
```bash
ng add @scullyio/init@1.0.0
```
but I have no idea which version you should pick.
