### ISSUE TITLE
Scully does not create blog module when starting ng generate @ scullyio / init: blog

### ISSUE THREAD

**Issue by EdwinFdoGarcia** [scullyio/scully#1328]
### Description
After installing angular with routing I follow the documentation process for Scully.
`ng new AmplifyAngular`
`ng add @scullyio/init`
` ng generate @scullyio/init:blog`
Here I only create the blog folder, but it does not create any module or files inside `/src/app/`
```ng generate @scullyio/init:blog
    ✅️ Update scully.AmplifyAngular.config.ts
UPDATE scully.AmplifyAngular.config.ts (293 bytes)
UPDATE src/app/app-routing.module.ts (335 bytes)
    ✅️ Blog ./blog/2021-04-13-blog.md file created
CREATE blog/2021-04-13-blog.md (97 bytes)
```

Then I try creating:
`ng generate @scullyio/init:markdown`
It asks me the expected questions but it does not create any module within `/src/app/`

```
ng generate @scullyio/init:markdown
? What name do you want to use for the module? blog
? What slug do you want for the markdown file? title
? Where do you want to store your markdown files? mdblog
? Under which route do you want your files to be requested? blog
    ✅️ Update scully.AmplifyAngular.config.ts
UPDATE scully.AmplifyAngular.config.ts (401 bytes)
UPDATE src/app/app-routing.module.ts (427 bytes)
    ✅️ Blog ./mdblog/2021-04-13-blog.md file created
CREATE mdblog/2021-04-13-blog.md (97 bytes)
```

#### 🔬 Minimal Reproduction

<img width="1285" alt="Captura de Pantalla 2021-04-13 a la(s) 4 27 23 p  m" src="https://user-images.githubusercontent.com/35706123/114623662-2e7d4380-9c75-11eb-80d9-9a2abad524b1.png">

#### 💻Your Environment

- Mac OS Big sur 11.2.3 
- Node v15.14.0
- Angular CLI: 11.2.8
- OS: darwin x64

**Angular Version:**

<pre>
   _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.8
Node: 15.14.0
OS: darwin x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.8
@angular/cli                    11.2.8
@schematics/angular             11.2.8
@schematics/update              0.1102.8
rxjs                            6.6.7
typescript                      4.1.5
    
- <code>

</code></pre>

**Scully Version:**

<pre>
    "@scullyio/init": "^1.1.3",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
<code>

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

### Loom Video:
https://www.loom.com/share/8090fc55c06c475880dd0a18811b1c21

**Comment by SanderElias** [comment]
This is a duplicate, I know @Jefiozie  is already working on fixing this. I'll push out the update as soon as its ready

**Comment by Jefiozie** [comment]
HI @EdwinFdoGarcia,  there is a new version of the Scully schematics release `1.1.4`. This should resolve the issue that you reported. I will close this issue as it should be resolved, in case it isn't feel free to reopen it.
