### ISSUE TITLE
Wrong link to CONTRIBUTING.md

### ISSUE THREAD

**Issue by Villanuevand** [scullyio/scully#134]
# 🗄️ Docs report

### Description
 
The link to `CONTRIBUTING` inside [scully.md](https://github.com/scullyio/scully/blob/master/docs/scully.md) is wrong
### What's the affected URL?**
 
https://github.com/scullyio/scully/blob/master/docs/scully.md  =>  `CONTRIBUTING` link redirect to 
https://github.com/scullyio/scully/blob/master/docs/CONTRIBUTING.md instead https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by d-koppenhagen** [comment]
Issue can be closed, can't it?

**Comment by Villanuevand** [comment]
Solved id #135
