### ISSUE TITLE
Replace npm run with npx in Scully Docs

### ISSUE THREAD

**Issue by mainawycliffe** [scullyio/scully#1340]
### Description

Update Scully docs to use `npx` instead of `npm run` when executing Scully commands.

So instead of 

```sh
npm run scully
```

This becomes

```sh
npx scully
```

**Comment by mainawycliffe** [comment]
PS: I would like to tackle this update.

**Comment by SanderElias** [comment]
@aaronfrost In our docs, we have a mixture of 'npm run scully' and 'npx scully' and iirc a few other variants.
@mainawycliffe wants to go over, and update all of those. Are you happy with this too?

@mainawycliffe When you are going to do this, make sure you find all the different variants too.

**Comment by mainawycliffe** [comment]
@SanderElias i can start as soon as I get the go ahead.

**Comment by SanderElias** [comment]
@mainawycliffe I'm fairly sure @aaronfrost was kind of busy last week. IIRC he was hosting some conference ;)
If he doesn't respond by Tuesday, you can go ahead, and do it. I'm fine with this.
