### ISSUE TITLE
Scanning of Lazy Loaded Routes Inside any Particular Modules not working

### ISSUE THREAD

**Issue by mrigank-taxak** [scullyio/scully#1342]
#### 💻Your Environment

**Angular Version:**

<pre><code>

@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cli                    11.0.7
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/scully": "^1.0.0",

</code></pre>

## 🔥 Exception or Error

<pre><code>

scully-routes.json ---
[{"route":"/"}]

app-routing.module.ts -----
const routes: Routes = [
  {
    path: '',
    loadChildren: () => import('../app/users/users.module').then((m) => m.UsersModule),
  },
];

users.module.ts -------
const routes: Routes = [
  {
    path: '', component: UsersComponent, redirectTo: 'users'
  },
  {path: 'users', loadChildren: () => import("../users/user-listing/user-listing.module").then(
    (m) => m.UserListingModule) 
  },
  {path: 'details', loadChildren: () => import("../users/user-details/user-details.module").then(
    (m) => m.UserDetailsModule) 
  }
]
</code></pre>

**Comment by SanderElias** [comment]
@mrigank-taxak Can you provide a reproduction. We are only using lazy-loaded routes in our test apps.

**Comment by mrigank-taxak** [comment]
@SanderElias https://github.com/mrigank-taxak/scully-testing.git this is my repo of the project, I have removed the Scully configuration for now.

**Comment by Jefiozie** [comment]
Hi @mrigank-taxak, I think I see where the issue could be. All your routes point to a top-level root approach
For example, the default route is pointing to the `app` folder, however, this route is incorrect as the hierarchy of the folder structure is that it is a subfolder of the current dir. To explain it a bit more see the example:

your current route: 
```typescript
    loadChildren: () => import('../app/users/users.module').then((m) => m.UsersModule),
```

what is should be 

```typescript
    loadChildren: () => import('./users/users.module').then((m) => m.UsersModule),
```

This pattern should be used for all the different routes that you have in your workspace. When this is done I believe that Scully will run as it should. Could you check and verify that this is fixing your issue?

**Comment by SanderElias** [comment]
I'm going to close this, as we can not reproduce, and didn't receive more input from the OP. 
We are happy to reopen when this changes, or there is more information
