### ISSUE TITLE
Can't find routes that are spread into the Route config

### ISSUE THREAD

**Issue by AlexAegis** [scullyio/scully#1346]
I have a fresh Angular application, with a `routes.ts` file and the following content:

```ts
export const routes: Routes = [
	{
		path: '',
		component: SiteFrameComponent,
		children: [
			{
				path: 'a',
				loadChildren: () => ...
			},
			{
				path: 'b',
				loadChildren: () => ...
			},
			{
				path: '404',
				component: NotFoundComponent,
			},
		],
	},
	{ path: '**', redirectTo: '/404' },
];
```

This is then imported in the AppModule into `RouterModule.forRoot(routes)`

This is pretty straightforward and common, and it works perfectly.

However, as soon as I want to move out some routes to a separate variable, and then spread it back into the config, scully can't follow:

```ts
export const mainPages: Routes = [
	{
		path: 'a',
		loadChildren: () => ...,
	},
	{
		path: 'b',
		loadChildren: () => ...,
	},
];

export const routes: Routes = [
	{
		path: '',
		component: SiteFrameComponent,
		children: [
			...mainPages,
			{
				path: '404',
				component: NotFoundComponent,
			},
		],
	},
	{ path: '**', redirectTo: '/404' },
];
```

> I separated some routes because I imported it elsewhere to render out links to these routes with an ngFor. So I would get new links by just adding a new route.

I get the following error from guess:

```sh
Finding all routes in application.
traversing app for routes
⠸ Loading guess-parser TypeError: Cannot read property 'values' of undefined
    at getObjectProp (<project-folder>/node_modules/guess-parser/dist/guess-parser/index.js:444:32)
    at Object.exports.readLoadChildren (<project-folder>/node_modules/guess-parser/dist/guess-parser/index.js:471:16)
    at Object.exports.getLazyEntryPoints (<project-folder>/node_modules/guess-parser/dist/guess-parser/index.js:400:26)
    at collectEntryPoints (<project-folder>/node_modules/guess-parser/dist/guess-parser/index.js:921:30)
    at Array.forEach (<anonymous>)
    at collectEntryPoints (<project-folder>/node_modules/guess-parser/dist/guess-parser/index.js:925:31)
    at visitTopLevelRoutes (<project-folder>/node_modules/guess-parser/dist/guess-parser/index.js:909:13)
    at visitNodes (<project-folder>/node_modules/typescript/lib/typescript.js:27858:30)
    at Object.forEachChild (<project-folder>/node_modules/typescript/lib/typescript.js:28032:24)
    at NodeObject.forEachChild (<project-folder>/node_modules/typescript/lib/typescript.js:146142:23)
```

Versions:

```json
	"@angular/core": "11.2.12",
	"@scullyio/ng-lib": "^1.1.1",
	"@scullyio/scully": "^1.1.1",
```

**Comment by AlexAegis** [comment]
Workaround:

It looks like it's only the spread operator that it can't handle, if I just make two arrays, and concat them together there, it works:

```ts
export const mainPages: Routes = [
	{
		path: 'a',
		loadChildren: ...
	},
	{
		path: 'blog',
		loadChildren: ...
	},
];

const otherPages: Routes = [
	{
		path: '404',
		component: NotFoundComponent,
	},
];

export const routes: Routes = [
	{
		path: '',
		component: SiteFrameComponent,
		children: mainPages.concat(otherPages),
	},
	{ path: '**', redirectTo: '/404' },
];

```

**Comment by SanderElias** [comment]
@AlexAegis Thanks for digging into this, and reporting back your findings. 
This is the behavior of the [GuessParser](https://github.com/guess-js/guess/tree/master/packages/guess-parser). 
@mgechev would it be possible to support the spread operator in routes?

**Comment by mgechev** [comment]
Route definitions need to be statically analyzable. We can make some of them work, but it'll be impossible in the general case. 

There's no way to discover dynamically assembled routing config at build time. Imagine a dependency on `localStorage`:

```ts
export const routes: Routes = [
  {
    path: '',
    component: SiteFrameComponent,
    children: mainPages.concat(JSON.parse(localStorage.getItem('otherPages'))),
    },
    { path: '**', redirectTo: '/404' },
];
```

We can't know what's in the user's `localStorage`. To simplify the parsing algorithm, we're also not interpreting expressions in route definitions.

**Comment by SanderElias** [comment]
@mgechev The question of @AlexAegis was:
Why does this work:
```typescript
export const mainPages: Routes = [
	{path: 'a',  loadChildren: ...	},
	{path: 'blog', loadChildren: ...	},
];

const otherPages: Routes = [
	{path: '404',  component: NotFoundComponent },
];

export const routes: Routes = [
	{
		path: '',
		component: SiteFrameComponent,
		children: mainPages.concat(otherPages),
	},
	{ path: '**', redirectTo: '/404' },
];
```
while this doesn''t:
```typescript
export const mainPages: Routes = [
	{path: 'a',  loadChildren: ...	},
	{path: 'blog', loadChildren: ...	},
];

const otherPages: Routes = [
	{path: '404',  component: NotFoundComponent },
];

export const routes: Routes = [
	{
		path: '',
		component: SiteFrameComponent,
		children: [...mainPages, ...otherPages, {path:'xxx', component: yyy}],
	},
	{ path: '**', redirectTo: '/404' },
];
```

Both of them seem to be statically analyzable?

**Comment by SanderElias** [comment]
given the answer from @mgechev 
> We can't know what's in the user's localStorage. To simplify the parsing algorithm, we're also not interpreting expressions in route definitions.
There is nothing actionable left in here, so I'm going to close this

**Comment by AlexAegis** [comment]
@SanderElias  This problem has nothing to do with `localStorage`, you yourself commented the core of the problem. If `concat` works, why doesn't spreading. Every route is available to be statically analized in this scenario.
