### ISSUE TITLE
Puppeteer option 'timeout' being ignored in rendering

### ISSUE THREAD

**Issue by jsanta** [scullyio/scully#1354]
## 🐞 Bug report

We have a Scully configuration for one of our company's project. As there have been some changes on the underlying API some pages are taking more time to get all the information so we began getting a:
`Puppeteer error while rendering "/some_url/final_url" TimeoutError: Navigation timeout of 30000 ms exceeded  we will retry rendering this page up to 3 times.`

We tried adding the timeout option in the `puppeteerLaunchOptions` section of our Scully config without any results.

#### 🔬 Minimal Reproduction
Scully config file extract:

```
export const config: ScullyConfig = {
  puppeteerLaunchOptions: {
    // slowMo: 1750, // Relentiza la ejecucion de Puppeteer
    args: [
      '--disable-gpu',
      '--renderer',
      '--no-sandbox',
      '--no-service-autorun',
      '--no-experiments',
      '--no-default-browser-check',
      '--disable-dev-shm-usage',
      '--disable-setuid-sandbox',
      '--no-first-run',
      '--no-zygote',
      '--single-process',
      '--disable-extensions',
      '--user-agent=\'Scully Navigator\''
    ],
    executablePath: '/usr/local/bin/chromium',
    timeout: 120000
  },
  projectRoot: './apps/frontend/project/src',
// other configurations...
};
```

Execute:
`npx scully  --prod --showGuessError --showBrowser=false --pluginsError=false --logSeverity=normal --project frontend-project`

After a while many endpoints still launch the same error pointing to a `Navigation timeout of 30000 ms exceeded` even though the configuration states a timeout of 120000 ms.
I think this might be a Puppeteer issue and not Scully's fault, but anyway Scully lacks an option that allows increasing the navigation timeout.

#### Workaround
I edited directly the `node_modules/@scullyio/scully/src/lib/renderPlugins/puppeteerRenderPlugin.js`  in order to increase the timeout when navigating  the pages.

```

        // enter url in page
        await page.goto(path, , { waitUntil: 'domcontentloaded', timeout: 120000 });

```
Some sites suggest using `{ waitUntil: 'load', timeout: 0 }` . See https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagegotourl-options for all available options.

#### 💻Your Environment

**Angular Version:**

<pre><code>

[12:19:39] → ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.10
Node: 14.15.5
OS: darwin x64

Angular: 11.2.11
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.10
@angular-devkit/core            11.2.10
@angular-devkit/schematics      11.2.10
@angular/cdk                    11.2.10
@angular/cli                    11.2.10
@angular/flex-layout            10.0.0-beta.32
@angular/material               11.2.10
@schematics/angular             10.2.3
@schematics/update              0.1102.10
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.0.3

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "1.0.1",
    "@scullyio/ng-lib": "1.0.0",
    "@scullyio/scully": "^1.1.1-BETA.94615"

</code></pre>

We are using the @develop version of Scully as @SanderElias suggested on https://github.com/scullyio/scully/issues/1348#issuecomment-831397694 

I hope you can help us with this. We have a CI pipeline for our deploys and I'll have to make a special version with the workaround to make things work again (the cleanest option is to make a pull request and submit the fix, but ... ¯\_(ツ)_/¯

Thanks in advance for any help.

**Comment by SanderElias** [comment]
The option isn't there by design. 
when you have one or more pages that require an extra-long timeout, you can switch those pages to [manualIdle](https://scully.io/docs/Reference/ngLib/idle-monitor-service/ ). You can then fire the `I'm ready` event when all your data is in.

Let me know if you need more then that

**Comment by jsanta** [comment]
Thanks @SanderElias , that should work for routes defined on the routes object of our _ScullyConfig_. 

How about the extraRoutes defined in the configuration?

The documentation points that using the manualIdle option in the app.module like:
```
ScullyLibModule.forRoot({
  useTransferState: true,
  alwaysMonitor: false,
  manualIdle: true,
});
```

> will cause Scully to fall-back to using a 25 second timeout, on every page rendered. 

What if the default 25 seconds are not enough? Shouldn't that timeout be configurable? as an enhancement I think.

In our project we are also using a custom _routeProcess_ plugin which takes the first URL and navigates it using puppeteer in order to extract all available links from this first page, so they can be added to the route rendering. 
The handler function returns a `Promise<Array<{ route: string }>>`.
 I can't see clearly where to add the `manualIdleCheck: true` property in the urls obtained by our plugin (will be glad to share it if required).

I think the manualIdle can work for us, we'll have to make a few adjustments to our code, but it falls short in many of our cases.
As I said any additional comments or observations on this can help us very much.
Thanks in advance.

**Comment by jsanta** [comment]
@SanderElias a quick question. Is there a way of overriding the default puppeteer render plugin in Scully? In that way we could adjust the code from the original one and use it, instead of the dirty code patching we're applying.

**Comment by jsanta** [comment]
> @SanderElias a quick question. Is there a way of overriding the default puppeteer render plugin in Scully? In that way we could adjust the code from the original one and use it, instead of the dirty code patching we're applying.

Nevermind, figured it out by myself. Had to  read again the documentation and take a good look over Scully's internals.
Ended up making a copy of the PuppeteerRenderPlugin, as an _enterprise_ plugin as it matches the signature for the pluginHandler function, and making some additions in order to make some parameters adjustable.

```
const customRenderConfig: CustomRenderConfig = {
  puppeteerTimeout: 120000,
  scullyTimeout: 45,
  scullyRetries: 5,
  scullyExitOnError: false
};
```

and in the routes section, every route that requires the "special treatment" includes the renderPlugin attribute:
```
   '/': {
      type: 'default',
      renderPlugin: getCustomPuppeteerRender(customRenderConfig),
      postRenderers: [QueryRoutesPlugin, ...defaultPostRenderers]
    }
```

_QueryRoutesPlugin_ is a custom plugin we made to generate the route listing from a sitemap endpoint and the links included in a Puppeteer rendered / route.

Thanks for all your help.

**Comment by SanderElias** [comment]
@jsanta that is the reason the enterprise plugins are there, so you can override whatever you need. I designed Scully so, that almost everything is a plugin, that can be swapped out when needed.
You even can replace existing plugins if you like.

**Comment by jsanta** [comment]
Thanks @SanderElias I really appreciate all your help. 
The only thing that IMHO should be improved (not for me as I already read a good part of the  code) is the documentation on how to replace or override a plugin. Examples are not _that_ clear.

**Comment by SanderElias** [comment]
Yeah, writing documentation is even harder as writing code.

**Comment by hunhavoc** [comment]
hi @jsanta ,

we just came up with the very same requirements on our project, and I'm asking if you could share your enterprise plugin with me?

**Comment by jsanta** [comment]
Hi @hunhavoc . Sorry about my delayed answer, I've been a little crazy at work.
Just made a gist with the code: https://gist.github.com/jsanta/df581338debf95f9e092927ec73f5dad

Hope it helps. Remember to adjust your values according to your own project requirements.
Best regards and stay safe.

**Comment by hunhavoc** [comment]
Hi @jsanta ,

No need to say sorry, you just made me a favour :) Thank you for sharing, it definitely helps a lot!

Stay safe
