### ISSUE TITLE
Corporate Proxy support for JsonRoutePlugin

### ISSUE THREAD

**Issue by tenoriojuann** [scullyio/scully#1355]
### Description

Tried to play with the proxy config to be able to send my requests through a corporate proxy but was unsuccessful. The agent field is never populated in the jsonRoutePlugin

#### 🔬 Minimal Reproduction

route config:

```typescript
{
        '/cell-phones/smartphones/:deviceUrl': {
            type: 'json',
            deviceUrl: {
                url: 'https://CUSTOMER_FACING_URL',
                resultsHandler: (response) => {
                    return response.filter((page) => {
                        return page.skus.every((sku) => {
                            return sku.startsWith('D');
                        });
                    }).map((page) => {
                        return page.urlList[0];
                    });
                },
                property: 'url'
            }
        }
}
```

```typescript
const PROXY_CONFIG = {
    '/cloudassets/cms/*': {
        target: 'CORP_PROXY',
        logLevel: 'debug',
        changeOrigin: true,
        secure: false

    }
};
```

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 11.2.12
Node: 12.13.0
OS: darwin x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.12
@angular-devkit/build-angular   0.1102.12
@angular-devkit/core            9.1.15
@angular-devkit/schematics      9.1.15
@angular/cdk                    11.2.12
@angular/cli                    11.2.12
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             9.1.15
@schematics/update              0.803.29
rxjs                            6.5.5
typescript                      4.1.5
    

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "^1.1.4",
    "@scullyio/ng-lib": "^1.1.1",
    "@scullyio/scully": "^1.1.1",
</code></pre>

## 🔥 Exception or Error
<pre><code>

Could not fetch data for route: ROUTE

I went deep into the library and saw that the actual error is a timeout.
</code></pre>

<pre><code>

</code></pre>

**Comment by SanderElias** [comment]
The proxy is there for your application. The Scully plugins don't run in there, they run in a node context, and can reach out to your APIs directly, they are not going through the proxy. Your config should not use customer-facing URI's but access them directly.
The following doesn't contain a valid URL, and will never work
```typescript
 url: 'https://CUSTOMER_FACING_URL',
```
The Scully config is _not_ part of your distribution, and is not used client-side

**Comment by tenoriojuann** [comment]
Hi,

I am using the plugin to be able to fetch the values for my unhandled routes. I have to use the proxy to be able to retrieve those values.

I can try to call the API by myself and save the info to a file but I wasn't sure if the proxy would do the trick.

**Comment by SanderElias** [comment]
@tenoriojuann Your plugins are run in nodeJs, not in a browser. So you can fetch it from wherever you like. There is no CORS in nodeJs.  You can directly use the data, or you can save it to a file and reuse the file, but as it is only used once (probably) I don't see the added value of doing that.

**Comment by tenoriojuann** [comment]
Hi,

I understand the plugin does not run on the browser and is not part of the distribution. And that is NodeJS that is running it.

I guess I worded my issues/feature request wrong.

Using the following route configuration: (where I'm not putting the real URL for this example)

``` typescript
{
        '/cell-phones/smartphones/:deviceUrl': {
            type: 'json',
            deviceUrl: {
                url: 'https://CUSTOMER_FACING_URL',
                resultsHandler: (response) => {
                    return response.filter((page) => {
                        return page.skus.every((sku) => {
                            return sku.startsWith('D');
                        });
                    }).map((page) => {
                        return page.urlList[0];
                    });
                },
                property: 'url'
            }
        }
}
```

Is there a way to provide an HTTP agent to the config? I am behind a firewall and need to use my company's proxy to be able to hit the URL. If I run my backend locally I am successful in retrieving my values for my unhandled route.

If currently there is no way to provide an HTTP agent, I will save the response to a file using `axios` or `node-fetch`, just need to know if it is at all possible first.

**Comment by Jefiozie** [comment]
Hi @tenoriojuann,just to understand you correctly. With  http agent do you mean a user-agent? Like a user agent header that needs to be in the request?

**Comment by tenoriojuann** [comment]
Hi,

I'm talking about node's Http Agent option.

https://nodejs.org/api/http.html#http_class_http_agent

if that can get exposed to the JsonPlugin I can create a Proxy Agent using something a custom implementation of the Agent class or use this https://www.npmjs.com/package/https-proxy-agent.

**Comment by Jefiozie** [comment]
Closing the as the PR has been merged. If needed please reopen an issue thank you.
