### ISSUE TITLE
Don't render certain elements marked with specific data-attribute

### ISSUE THREAD

**Issue by denisyilmaz** [scullyio/scully#1360]
## 🧩 Feature request or Docs Update

When rendering pages with Scully all scripts that the page will load are executed on the server.
This can cause some problem with Scripts like for example Cookie Banner scripts (like cookiebot.com)  that need to be inserted in the head of the index.html

```html
<script
  id="Cookiebot"
  src="https://consent.cookiebot.com/uc.js"
  data-cbid="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  data-blockingmode="auto"
  type="text/javascript"
></script>
```

As the HTML of the banner is rendered via Scully the resulting banner is not interactive anymore and the layout is broken.

I checked the `isScullyRunning()` function and found the internal check that is used. I then adapted the insertion-script to check for `window && window["ScullyIO"] === "running"` and only then insert the script in the head. But this is not really future proof as any change in Scully regarding the global variable might break this.

```html
    <script>
      (function (i, s, o, g, a, m) {
        if (window && window["ScullyIO"] === "running") return;
        (a = s.createElement(o)), (m = s.getElementsByTagName(o)[0]);
        a.id = "Cookiebot";
        a.setAttribute("data-cbid", "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX");
        a.setAttribute("data-blockingmode", "auto");
        a.type = "text/javascript";
        a.src = g;
        m.parentNode.insertBefore(a, m);
      })(window, document, "script", "https://consent.cookiebot.com/uc.js");
    </script>
```

### Describe the solution you'd like

I would love to just add a data attribute to elements (in and especially **outside** of Angular!) like `data-scully-ignore="true` which then scully removes from the DOM before rendering.

### Describe alternatives you've considered

A working Gist of my solution described above can be found here: https://gist.github.com/denisyilmaz/29d8ff1c601e1a9084d271df65e08bf6

I guess this is also a valid solution. Maybe this could be added as a note to the Docs for people having similar problems.

**Comment by SanderElias** [comment]
@denisyilmaz You can safely take that this will not change. Significant parts of our system depend on it.
The change you propose is possible, but very costly, as we need to analyze all elements on all pages on every render.
If this is what you want, you can create a plugin, and use that to take out the things you want to take out
```typescript
registerPlugin('postProcessByDom', 'removeAttributeReove', async (dom, route) => {
    /** traverse dom and remove/replace */
    return dom;
}
```
But it does take its time, on every page where it is used.
That is why we do provide the global on the window, as this is a very cost-effective way to create execeptions
