### ISSUE TITLE
Schematics uses deprecated ID property

### ISSUE THREAD

**Issue by Jefiozie** [scullyio/scully#1363]
### Description

With Angular V12 there is a deprecation warning when adding Scully to a Angular project.

#### 🔬 Minimal Reproduction

1. install angular/cli@12
2. ng new app
3. add a route
4. ng add @scullyio/init
5. see message:

![image](https://user-images.githubusercontent.com/17835373/118405004-b6d87500-b675-11eb-8114-2dc500265488.png)

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 12.0.0
Node: 12.22.0
Package Manager: npm 6.14.11
OS: linux x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Scully Version:**

<pre><code>

</code></pre>

## 🔥 Exception or Error

<pre><code>
1.1.1
</code></pre>

**Comment by Jefiozie** [comment]
I will try to pick this one up in upcoming week

**Comment by geromegrignon** [comment]
I think the issue shouldn't be closed as the changes have not been released yet on npm (so the warning still appears when doing `ng add @scullyio/init`).

**Comment by kalkoby** [comment]
I have the exact same problem with the same version.  I hope one of you do not mind telling me how to pull some changes with some step by step.  I am learning Angular_cli and using github. 
Thanks in advance.

**Comment by SanderElias** [comment]
@kalkoby Its a warning you can ignore, as we already did fix it. We are working on being able to release a new version
