### ISSUE TITLE
304 redirect when updated to angular v12

### ISSUE THREAD

**Issue by jordankkk** [scullyio/scully#1367]
## 🐞 Bug report
once updated to angular v12 the home page will automatic 304 redirect, but the angular v11 is ok

### Description
current plugins: defaultPostRenderers: [GoogleAnalytics, 'seoHrefOptimise', Http404Plugin]

#### 💻Your Environment
Windows 10

**Angular Version:**
12.0.0

**Scully Version:**
"@scullyio/init": "^1.1.4",
"@scullyio/ng-lib": "^1.1.1",
"@scullyio/scully": "^1.1.1",

**Comment by SanderElias** [comment]
We need more details here. 304 redirects are sent out by the server, and there is very little that Scully can influence there.

**Comment by jordankkk** [comment]
Hi @SanderElias, Thanks for the fast response, can I know what details should I provide? So far have tested in localhost (localhost:1864, localhost:1668) is still same with 304 redirect

Thanks

**Comment by SanderElias** [comment]
304 is how a server forwards a client(browser) to the `index.html` if you try to load a `folder`. 
That is a server setting. Our dev-tool uses an express server, and we kept this behavior, as it is what most servers do. The Scully server is not something you should use outside f dev, that is outright dangerous, as we on purpose allow unsafe things.
However, most servers have a way to configure this behavior.
This is up to your deployment.  There is nothing Scully can do to change the config of your chosen server.
Also, in your app itself, you are in control of the URLs used, so you can add an `/index.html` to internal URLs

**Comment by jordankkk** [comment]
After upgraded to the angular latest version 12.0.2 seems is ok right now, but still have same issue (loaded twice) like #1370 mention

**Comment by jordankkk** [comment]
In my case for the angular v12 if the home page routing use lazy loading (loadChildren) then this issue will happen and load twice mention in (#1367).

When changed back to normal routing (component) then is ok

Thanks

**Comment by SanderElias** [comment]
That makes sense. LoadChildren is async, and by that, it means that it will cause a navigation effect after boot. 
There is no way for Scully to detect that you are navigating to the same page. There is a chicken-egg situation in there.
I will close this now, but eel free to keep discussing this.
