### ISSUE TITLE
Why do you get index.html second time?

### ISSUE THREAD

**Issue by flexWhale** [scullyio/scully#1370]
Hi guys!
Thank you for your work! I have question. Why don't you read state from variable in window? Why do you get index.html second time?
https://github.com/scullyio/scully/blob/712789eb64dbb49e4ff8087da4a50e87b2208a20/libs/ng-lib/src/lib/transfer-state/transfer-state.service.ts#L233

**Comment by SanderElias** [comment]
We do get the state from the window variable, during the load process.
However, if you start navigating after that, the window variable doesn't reflect the state of that "page" anymore, and we need to read it from the server.
As we don't know what happens with window vars after the app has started, we do re-fetch it if you revisit your 'startup' page.

**Comment by flexWhale** [comment]
Probably I have bug. I'm not using navigation. I just open url and see two request for my index.html.
[https://eng4.me/exercise-test/123/master](url)
![1](https://user-images.githubusercontent.com/11042093/119775841-d6b93580-becc-11eb-913b-dc3159462769.PNG)

**Comment by jordankkk** [comment]
same here after the home page loaded finished then the page reload one time again

**Comment by flexWhale** [comment]
> same here after the home page loaded finished then the page reload one time again

Page doesn't reload in my case. TransferStateService just gets index.html when inlineStateOnly=true and it's angular v11.

**Comment by jordankkk** [comment]
@flexWhale in my case angular v12 will reload but v11 is no problem

**Comment by SanderElias** [comment]
@flexWhale can you create a small repo on GitHub that shows your issue? It is not what we are seeing.

**Comment by SanderElias** [comment]
@jordankkk I just tried manually with V12 and `inlineStateOnly: true` but I don't see that behavior, can you create a way so I can reproduce your issue?

**Comment by jordankkk** [comment]
@SanderElias this issue like #1367 i guess is lazy loading routes issue, for angular v12 I have changed the home page route from lazyloading to normal route (component) then it was fixed, but I still not sure why angular v11 don't have this issue : )

`inlineStateOnly: true` not test this config yet

Thanks

**Comment by SanderElias** [comment]
This seems resolved. If I'm mistaken, please let me know, and I'l reopen the issue
