### ISSUE TITLE
Npm update broken scully 

### ISSUE THREAD

**Issue by nolafs** [scullyio/scully#1381]
## 🐞 Bug report

After updating to the latest npm 7.15.1 and to Angular 12.0.2, scully no longer builds.

Puppeteer cannot find or launch the browser. (by default chrome)
 Try adding 'puppeteerLaunchOptions: {executablePath: CHROMIUM_PATH}'
 to your scully.*.config.ts file.
Also, this might happen because the default timeout (60 seconds) is to short on this system
this can be fixed by adding the --serverTimeout=x cmd line option.
   (where x = the new timeout in milliseconds)
When this happens in CI/CD you can find some additional information here:
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

#### 💻Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.2
Node: 14.15.5
Package Manager: npm 7.15.1
OS: darwin x64

Angular: 12.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@angular/cdk                    12.0.2
@angular/cli                    12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4
    

</code></pre>

**Scully Version:**

<pre><code>
{
  "name": "stryker",
  "version": "0.0.0",
  "scripts": {
    "prebuild": "node updateRoute.js",
    "ng": "ng",
    "start": "ng serve",
    "start:local": "npx netlify-cms-proxy-server",
    "build": "ng build",
    "build:dev": "ng build --configuration development",
    "test": "ng test",
    "scully": "npx scully --",
    "scully:watch": "npx scully -- --watch",
    "scully:serve": "npm run scully && npx scully serve --",
    "netlify": "npm run build && npm run scully"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "12.0.0",
    "@angular/cdk": "^12.0.2",
    "@angular/common": "12.0.0",
    "@angular/compiler": "12.0.0",
    "@angular/core": "12.0.0",
    "@angular/forms": "12.0.0",
    "@angular/material": "12.0.0",
    "@angular/material-moment-adapter": "12.0.0",
    "@angular/platform-browser": "12.0.0",
    "@angular/platform-browser-dynamic": "12.0.0",
    "@angular/router": "12.0.0",
    "@auth0/auth0-spa-js": "^1.15.0",
    "@fortawesome/angular-fontawesome": "^0.9.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fullcalendar/angular": "4.4.5-beta",
    "@fullcalendar/core": "4.4.2",
    "@fullcalendar/daygrid": "4.4.2",
    "@fullcalendar/interaction": "4.4.2",
    "@fullcalendar/list": "4.4.2",
    "@fullcalendar/moment": "4.4.2",
    "@fullcalendar/rrule": "4.4.2",
    "@fullcalendar/timegrid": "4.4.2",
    "@scullyio/init": "^1.1.4",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
    "apexcharts": "3.26.2",
    "crypto-js": "3.3.0",
    "highlight.js": "10.7.2",
    "lodash-es": "4.17.21",
    "moment": "2.29.1",
    "ng-apexcharts": "1.5.9",
    "ngx-markdown": "11.1.3",
    "ngx-quill": "14.0.0",
    "ngx-sharebuttons": "^8.0.5",
    "perfect-scrollbar": "1.5.1",
    "quill": "1.3.7",
    "rrule": "2.6.8",
    "rxjs": "6.6.7",
    "swiper": "^6.6.2",
    "tslib": "2.2.0",
    "web-animations-js": "2.3.2",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.0.2",
    "@angular-eslint/builder": "12.0.0",
    "@angular-eslint/eslint-plugin": "12.0.0",
    "@angular-eslint/eslint-plugin-template": "12.0.0",
    "@angular-eslint/schematics": "12.1.0",
    "@angular-eslint/template-parser": "12.0.0",
    "@angular/cli": "12.0.2",
    "@angular/compiler-cli": "12.0.0",
    "@angular/language-service": "12.0.0",
    "@scullyio/scully-plugin-flash-prevention": "^1.1.1",
    "@tailwindcss/aspect-ratio": "0.2.0",
    "@tailwindcss/line-clamp": "0.2.0",
    "@tailwindcss/typography": "0.4.0",
    "@types/chroma-js": "2.1.3",
    "@types/crypto-js": "3.1.47",
    "@types/highlight.js": "10.1.0",
    "@types/jasmine": "3.6.11",
    "@types/lodash": "4.14.169",
    "@types/lodash-es": "4.17.4",
    "@types/node": "12.20.13",
    "@typescript-eslint/eslint-plugin": "4.23.0",
    "@typescript-eslint/parser": "4.23.0",
    "autoprefixer": "10.2.5",
    "chroma-js": "2.1.2",
    "eslint": "7.26.0",
    "eslint-plugin-import": "2.23.0",
    "eslint-plugin-jsdoc": "34.2.2",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "fs": "0.0.1-security",
    "jasmine-core": "3.7.1",
    "jasmine-spec-reporter": "5.0.2",
    "karma": "6.3.2",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage": "2.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.6.0",
    "lodash": "4.17.21",
    "postcss": "8.2.15",
    "protractor": "7.0.0",
    "scully-plugin-flash-prevention": "^0.0.41",
    "tailwindcss": "2.1.2",
    "typescript": "4.2.4"
  }
}

</code></pre>

## 🔥 Exception or Error

<pre><code>
=================================================================================================
Puppeteer cannot find or launch the browser. (by default chrome)
 Try adding 'puppeteerLaunchOptions: {executablePath: CHROMIUM_PATH}'
 to your scully.*.config.ts file.
Also, this might happen because the default timeout (60 seconds) is to short on this system
this can be fixed by adding the --serverTimeout=x cmd line option.
   (where x = the new timeout in milliseconds)
When this happens in CI/CD you can find some additional information here:
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
=================================================================================================

</code></pre>

**Comment by SanderElias** [comment]
NPM 7 is incompatible with Angular right now.  There is not much we can change about that.

**Comment by hisham** [comment]
According to https://github.com/angular/angular-cli/issues/19957#issuecomment-786177315 it is compatible now?
