### ISSUE TITLE
Backslash not escaped by TransferState

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#1382]
### Description
Having data like `{"amount": "450\45g"}` breaks the page when data is read from the TransferState script on `JSON.parse()`. It works great when it's received by the `data.json` though.
#### 🔬 Minimal Reproduction
Pass  `{"amount": "450\45g"}` to TransferState and load the page directly.
#### 💻Your Environment

**Angular Version:**

<pre><code>Angular CLI: 11.2.4
Node: 14.16.0
OS: win32 x64

Angular: undefined
...
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.4 (cli-only)
@angular-devkit/core         11.2.4 (cli-only)
@angular-devkit/schematics   11.2.4 (cli-only)
@schematics/angular          11.2.4 (cli-only)
@schematics/update           0.1102.4 (cli-only)
typescript                   4.0.7
</code></pre>

**Scully Version:**

<pre><code>"@scullyio/ng-lib": "^1.1.1",
"@scullyio/scully": "^1.1.1",
</code></pre>

## 🔥 Exception or Error
JSON.parse fails on `\4`

**Comment by hunhavoc** [comment]
Can this be fixed by extending the special char escaping arrays?

I mean this list and it's escaped pair:

```    const unescapedText = {
        '_~q~': "'",
        '_~b~': '`',
        '_~o~': '$',
        '_~s~': '/',
        '_~l~': '<',
        '_~g~': '>',
    };```
    
    If yes, I'm going to open a PR for it.

**Comment by SanderElias** [comment]
@hunhavoc That is what I tried initially, but it doesn't work. It needs a bit more. For testing, put a `\` in the user-data in `libs/scully/src/lib/testData/users-testdata.ts`
Something like this would do the job:
```ts
  {
    id: 2,
    name: 'Ervin `Howell`',
    username: 'Anton\\ette',
    email: 'Shanna@melissa.tv',
    address: {
      street: 'Victor Plains',
      suite: 'Suite 879',
      city: 'Wisokyburgh',
      zipcode: '90566-7771',
      geo: {
        lat: '-43.9509',
        lng: '-34.4618',
      },
    },
    phone: '010-692-6593 x09125',
    website: 'anastasia.net',
    company: {
      name: 'Deckow-Crist',
      catchPhrase: 'Proactive \n```\nconsole.log("euhm")\n```\n didactic contingency',
      bs: 'synergize scalable supply-chains',
    },
  },
```
If you can find out a way to do that, and pass all the tests. I'm more then willing to merge a PR.
