### ISSUE TITLE
No route declaration array was found that corresponds to router module at line XX in src/app/app-routing.module.ts

### ISSUE THREAD

**Issue by BruneXX** [scullyio/scully#1389]
## 🐞 Bug report
After run the following command ` ng g @scullyio/init:blog --project my-project` and I'm receiving the following error:
`No route declaration array was found that corresponds to router module at line XX in src/app/app-routing.module.ts`

The app-routing module is present
#### 🔬 Minimal Reproduction
install scully in angular project and run those commands

#### 💻Your Environment
- Node 14.17.0
- Typescript 4.2.

**Angular Version:**
- Angular 12

**Scully Version:**
6.14.13

**Comment by SanderElias** [comment]
When I do:
```bash
 npx @angular/cli@12 new demoThnng --skipGit  --routing --style css --minimal --strict
cd demoThnng 
ng add @scullyio/init
ng g @scullyio/init:blog
```
Everything works as expected.
(there are a few msgs about keyword `id`, but those will disappear with the next release.)
So, we need a way to reproduce your issue, before we can fix it.

**Comment by SanderElias** [comment]
Closing as there is no actionable context here. If there is please provide it, and we will gladly reopen
