### ISSUE TITLE
Support Nx Workspace.json v2

### ISSUE THREAD

**Issue by sonicparke** [scullyio/scully#1394]
### Description

 Nx workspace configuration now supports the ability to extend the architect targets. In order to do this, you need to rename the project's `architect` property to `targets`. This causes Scully to break since it is looking explicitly for the `architect` property within the project.
https://nx.dev/previous/angular/core-concepts/configuration#targets

### Describe the solution you'd like

 To future proof it a bit I think adding an optional `scullyConfig` property that defaults to `architect` is probably the best way forward.

### Describe alternatives you've considered

 I tried just simply renaming the `targets` property back to `architect` for the appropriate project but when generating a new lib or app via Nx that property is then renamed back to `targets` by Nx.

**Comment by sonicparke** [comment]
I'm working on a PR for this and should have it up shortly.

**Comment by Jefiozie** [comment]
I'm closing this issue as I believe this is resolved. In case it is not don't hesitate to reopen a new issue for this.

**Comment by sonicparke** [comment]
> I'm closing this issue as I believe this is resolved. In case it is not don't hesitate to reopen a new issue for this.

Thanks! I totally forgot to come back and close it.
