### ISSUE TITLE
Scully Exits Process before Finishing Execution

### ISSUE THREAD

**Issue by lucasvieirasilva** [scullyio/scully#1397]
### Description

I have been used the beta version in my local projects for a few weeks, and I have noticed that change https://github.com/scullyio/scully/pull/1334 is making the CLI exits the process before this code https://github.com/scullyio/scully/blob/main/libs/scully/src/scully.ts#L164-L171 being executed.

So, keeping the server process open to the next execution.

#### 🔬 Minimal Reproduction

- Install some beta version that has this PR https://github.com/scullyio/scully/pull/1334 changes.
- Run any Scully command
- If you are using Linux/Mac, run this command `sudo lsof -i :1864`

The process still be opened.

#### 💻Your Environment

**Angular Version:**

```text
Angular CLI: 11.2.4
Node: 12.22.1
OS: darwin x64

Angular: 11.2.14
... common, core
Ivy Workspace: <error>

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1102.4
@angular-devkit/build-angular       0.1102.4
@angular-devkit/core                11.2.4
@angular-devkit/schematics          11.2.4
@angular/animations                 11.2.7
@angular/cdk                        11.2.4
@angular/cli                        11.2.4
@angular/compiler                   11.2.5
@angular/compiler-cli               11.2.5
@angular/forms                      11.2.7
@angular/language-service           11.2.5
@angular/platform-browser           11.2.7
@angular/platform-browser-dynamic   11.2.5
@angular/platform-server            11.2.5
@angular/router                     11.2.5
@schematics/angular                 11.2.4
@schematics/update                  0.1102.4
rxjs                                6.6.3
typescript                          4.1.3
```

**Scully Version:**

```text
"@scullyio/scully": "1.1.1-BETA.140239",
```

## 🔥 Exception or Error

There are no errors, the `serve` just stays open.

![image](https://user-images.githubusercontent.com/12723594/123807010-de05a180-d8c5-11eb-90ec-0c29a4a994a3.png)

**Comment by SanderElias** [comment]
@lucasvieirasilva I'm closing this, as I believe its solved with the latest release.
If the problem still pops up for you, let us know and I will reopen the issue
