### ISSUE TITLE
Additional routes labeled as "/blog/:id" not matching app-routing.module "blog/:slug"

### ISSUE THREAD

**Issue by nelsynelz** [scullyio/scully#1400]
### Description
When running npx scully and npx scully serve, the terminal displays a list of routes that are unhandled:
```
No configuration for route "/blog/:id" found. Skipping
```

However, in my app-routing.module.ts file, the route is configured as:
```
{ path: "blog/:slug", component: ArticleComponent }
```

This forces me to configure scully config to the below: 
```
routes: {
  "/blog/:id": {
    type: "json",
    id: {
      url: "https://api.cmssystem.com/articles",
      property: "slug"
    }
  }
}
```
But I would think it _should_ be configured like the below to match the route declaration:
```
routes: {
  "/blog/:slug": {
    type: "json",
    slug: {
      url: "https://api.cmssystem.com/articles",
      property: "slug"
    }
  }
}
```

#### 🔬 Minimal Reproduction
Create routes with a non standard "/:id" path.

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 12.0.4
Node: 16.3.0
Package Manager: npm 7.15.1
OS: win32 ia32

Angular: 12.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4
@angular-devkit/build-angular   12.0.4
@angular-devkit/core            12.0.4
@angular-devkit/schematics      12.0.4
@schematics/angular             12.0.4
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "^1.1.4",
"@scullyio/ng-lib": "^1.0.0",
"@scullyio/scully": "^1.0.0",
</code></pre>

**Comment by nelsynelz** [comment]
I think this is a caching issue, when deploying in my CI/CD pipeline I get the expected output in the logs...

```
No configuration for route "/blog/:slug" found. Skipping
```

Any tips for fixing this locally?

**Comment by A7xSV** [comment]
Worth trying out the --scanRoutes command line option - https://scully.io/docs/Reference/command-line-options/#scanroutes

**Comment by SanderElias** [comment]
The routes are cached. We use Minko's Geuss-parser for route discovery. But it takes its time, especially on bigger apps.
And as add/changing routes in an app is usually a low-frequency thing, we decided to cache this.
you can use the `--scanRoutes` cmd line option like this:
```
npx scully --scanRoutes
```
And Scully will discover your route changes/addition/subtractions. (and cache them again)

I'm closing this as it looks like it working as expected.  If that isn't the case, provide additional details, and we will reopen the issue

**Comment by nelsynelz** [comment]
That solved the issue. Thanks all!
