### ISSUE TITLE
Scully requires Angular project to import RouterModule 

### ISSUE THREAD

**Issue by bdetry** [scullyio/scully#1401]
Little issue because most of the people are not concerned but I was trying Scully with a simple angular project. A project **without any routes or any RouterModule module** import and the files generated in` ./dist/static ` were not static.

I simply added a RouteModule and the following route and everything worked properly. 

`const routes: Routes = [
  { path: '' , component: AppComponent }
];` 

I think it should be specified in docs if it's normal behavior. 

Thank you!

Was angular `12.1.1` and Scully : 
` "@scullyio/init": "^1.1.4",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",`

**Comment by Jefiozie** [comment]
Hi @bdetry, thank you for creating this issue. Scully needs at least one route this is required. There is already documentation about this you can have a look at it [here](https://scully.io/docs/learn/getting-started/requirements/).
