### ISSUE TITLE
SyntaxError: Unexpected token 'export' when running npx scully

### ISSUE THREAD

**Issue by alessandro-tucci-visiontech** [scullyio/scully#1406]
### Description
Our Scully plugins reference one of our dependencies, a library which we developed and maintain, targeted **ES2015**. When running `npx scully`, we are returned the error mentioned in the subject. It looks like a lack of support for ES6/ES2015 syntax.
First of all: is it due to Scully itself, or to the Node.js tools?
In the latter case, do you have a standard way to deal with the ES6/ES2015 syntax, which does not involve using Babel.js?

#### 🔬 Minimal Reproduction
Run `npx scully` in a project containing a Scully plugin which references a ES6/ES2015 module
#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 11.2.13
Node: 15.14.0
OS: win32 x64

Angular: 11.2.14
... common, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: No

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cli                    11.2.13
@angular/google-maps            12.0.2
@schematics/angular             11.2.13
@schematics/update              0.1102.13
typescript                      4.1.5
</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "^1.1.4",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
</code></pre>

## 🔥 Exception or Error

The project name is masked with the placeholder _PROJECT_NAME_.
The project directory is masked with the placeholder _PROJECT_DIR_.
The module we are referencing, i.e. the library we developed and maintain, is masked with the placeholder _LIBRARY_NAME_.
<pre><code>
> npx scully

---------
 We encountered an error executing the config file. ".\scully.PROJECT_NAME.config.ts"
 Check the error below, and try again later
---------
PROJECT_DIR\node_modules\LIBRARY_NAME\dist\index.js:4
export * from './lib/trace.service';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1022:15)
    at Module._compile (node:internal/modules/cjs/loader:1056:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (PROJECT_DIR\src\model\model.js:11:25)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
</code></pre>

**Comment by SanderElias** [comment]
This is a syntax error in your config. I suspect you are loading something that's not compiled to JS.
Scully will compile the config for you, and all the things you import from `./scully`, but it its not in there, it need to be compiled manually.
For some things, you might get away with that by adding it to the `tsconfig.json` inside of that folder.
