### ISSUE TITLE
Cannot find module scully-plugin-flash-prevention

### ISSUE THREAD

**Issue by NEDIX** [scullyio/scully#1409]
## 🐞 Bug report

Following the steps for setting up the flash prevention plugin as found [here](https://github.com/scullyio/scully/tree/main/libs/plugins/scully-plugin-flash-prevention#2-use-the-plugin) results in build error:
<code>
Error: Cannot find module 'scully-plugin-flash-prevention'
</code>

#### 🔬 Minimal Reproduction

Contents of scully.app.config.ts
<pre><code>
import { ScullyConfig } from '@scullyio/scully';

const { getFlashPreventionPlugin } = require('scully-plugin-flash-prevention');

export const config: ScullyConfig = {
  projectRoot: "./src",
  projectName: "app",
  outDir: './dist/static',
  defaultPostRenderers: [getFlashPreventionPlugin({appRootSelector: 'app-root'})],
  routes: {
  }
};
</pre></code>

Attempt to require the plugin using the @scullyio namespace results in the same error.

<pre><code>
const { getFlashPreventionPlugin } = require('@scullyio/scully-plugin-flash-prevention');
</pre></code>

#### 💻Your Environment

**Angular Version:**

<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.3
@angular-devkit/build-angular   12.1.3
@angular-devkit/core            12.1.3
@angular-devkit/schematics      12.1.3
@angular/language-service       12.0.5
@schematics/angular             12.1.3
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Scully Version:**

<pre><code>
 @scullyio/ng-lib@1.1.1
 @scullyio/scully@1.1.1
 @scullyio/scully-plugin-flash-prevention@1.1.1
</code></pre>

## 🔥 Exception or Error

<pre><code>
---------
 We encountered an error executing the config file. "./scully.app.config.ts"
 Check the error below, and try again later
--------- 
Error: Cannot find module 'scully-plugin-flash-prevention'
Require stack:
- /home/user/Repositories/scully-app/scully.app.config.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/compileConfig.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/config.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/renderPlugins/launchedBrowser.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/handlers/defaultAction.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/handlers/index.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/index.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/fileHanderPlugins/asciidoc.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/pluginManagement/systemPlugins.js
- /home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/scully.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user/Repositories/scully-app/scully.app.config.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/Repositories/scully-app/scully.app.config.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/compileConfig.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/config.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/renderPlugins/launchedBrowser.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/handlers/defaultAction.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/handlers/index.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/utils/index.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/fileHanderPlugins/asciidoc.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/lib/pluginManagement/systemPlugins.js',
    '/home/user/Repositories/scully-app/node_modules/@scullyio/scully/src/scully.js'
  ]
}
</code></pre>

**Comment by BenLune** [comment]
Hi,
I just had the same problem.
You just need to import it like that : 
`import { getFlashPreventionPlugin } from '@scullyio/scully-plugin-flash-prevention';`
rather than
`const { getFlashPreventionPlugin } = require('scully-plugin-flash-prevention');`

Be sure you installed the plugin before via npm or yarn.

**Comment by SanderElias** [comment]
@NEDIX, @BenLune The plugin's npm package name is: `@scullyio/scully-plugin-flash-prevention`
make sure you npm installed it, and then import or require it from the correct npm name.
