### ISSUE TITLE
Cannot setup a Scully project in a fresh Nx workspace

### ISSUE THREAD

**Issue by Bjeaurn** [scullyio/scully#1411]
### Description
When I generate a fresh Nx workspace, both an empty or one based on Angular, there are errors when adding Scully as described in the installation guide.

#### 🔬 Minimal Reproduction
```
└ ❯ npx create-nx-workspace@latest test    
✔ What to create in the new workspace · angular
✔ Application name                    · landing
✔ Default stylesheet format           · scss
✔ Use Nx Cloud? (It's free and doesn't require registration.) · No
```

```
npm install @scullyio/init
 nx g @scullyio/init:install -- --project=landing
```

#### 💻Your Environment

```
Angular CLI: 12.1.3
Node: 14.16.1
Package Manager: npm 7.11.1
``` 

Nx looks like version `12.6.2` but `nx version` returns Angular CLI.

**Scully Version:**

<pre><code>
    "@scullyio/init": "^1.1.4",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
</code></pre>

## 🔥 Exception or Error

<pre><code>
"@scullyio/init" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
    Install ng-lib
    ✅️ Added dependency
✔ Packages installed successfully.
"@scullyio/init:scully" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
    ✅️ Update package.json
    ✅️ Created scully configuration file in scully.landing.config.ts
"@scullyio/init:pluginTS" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
InvalidInputOptions [Error]: Schematic input does not validate against the Schema: "landing"
Errors:

  Data path "" must be object.

</code></pre>

**Comment by Jefiozie** [comment]
Hi @Bjeaurn I think this is a bug that is already fixed in the develop version. would you mind verifying this with the `develop` version?

**Comment by SanderElias** [comment]
@Bjeaurn I agree with Jeffery and going to close this now. If it's still an issue, after our net release (sorry, this can take a bit we are facing some issues) ping us, and we will reopen this issue.
