### ISSUE TITLE
Possibility to add postRenderers to extraRoutes

### ISSUE THREAD

**Issue by BenLune** [scullyio/scully#1412]
### Description

Hi there !
Thank you for Scully !
I'm working on an Angular App, with the Router and Scully, but not with the default urls provided by route configuration.
Thanks to Angular UrlSerializer, I can get some nice SEO friendly urls coming from a CMS (Drupal), mapped to an internal Angular route. So my app works well with both urls, the technical angular ones and the content oriented Drupal ones.
When I render Scully, I ask Drupal for all the paths of my contents thanks to extraRoutes, and it works well.

I'm using : 
`@scullyio/scully@^1.1.1-BETA.140239`
`@scullyio/scully-plugin-flash-prevention@^1.1.1`

### Describe the solution you'd like

The problem/question I try to solve is that I would like to use the FlashPreventionPlugIn to test it and see if it improves my rendering or not. With ExtraRoutes I don't see how to do it. I tried to add the plug-in in `defaultPostRenderers` property but it doesn't work.
Do you have an idea how to do it ?

### Describe alternatives you've considered

Instead of returning an array of url as string, return a map, with the url as key, and an object as value, like the routes ones. I don't know if it is a good idea ;-)

**Comment by SanderElias** [comment]
Exrtaroutes are just added to the unhandled route list, so they are _not different_ from any other route Scully tråvereses. 
Adding the flashprevention to the `defaultPostRenderers` should do the trick. 
I would need to have access to a way to reproduce your issue, so I can work on fixing it.

**Comment by BenLune** [comment]
Ok, thank you @SanderElias , I'll try again to add flashprevention `defaultPostRenderers` and let you know here.

**Comment by BenLune** [comment]
Hi @SanderElias,
I could add the `scully-plugin-flash-prevention` in `defaultPostRenderers` config and it works well. I'm almost sure I add a problem doing it earlier. Maybe it was due to older version of Scully. 
Thank you!
