### ISSUE TITLE
Layout shift when loading page

### ISSUE THREAD

**Issue by maxcodefaster** [scullyio/scully#1414]
### Description

The layout shift drastically when the page is loaded (see video). How to omit this? I guess scully shows the prerendered text before the css is loaded.

#### 🔬 Minimal Reproduction

Add scully to any ionic angular project and reload the page with clean cache.

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 12.1.4
Node: 16.6.0 (Unsupported)
Package Manager: npm 7.20.3
OS: linux x64

Angular: 12.1.4
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Scully Version:**

<pre><code>

 "@scullyio/init": "^1.1.2",
 "@scullyio/ng-lib": "^1.1.1",
 "@scullyio/scully": "^1.1.1",
</code></pre>

## 🔥 Exception or Error

<pre><code>

https://user-images.githubusercontent.com/35369883/127923687-9a6e7c38-7488-476b-84b9-da19edb41619.mp4

</code></pre>

**Comment by maxcodefaster** [comment]
My app-routing:

```ts
@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      preloadingStrategy: PreloadAllModules,
      initialNavigation: 'enabled',
    }),
  ],
  exports: [RouterModule],
})
```

**Comment by SanderElias** [comment]
Can you provide a repo that reproduces this?
Ionic uses web-components, and this might be the problem. Perhaps when you switch to manual idle, the result is better.
We still have an open issue on being ionic compatible. That might be the problem too.

**Comment by SanderElias** [comment]
I'm going to close this due to lack of activity. As far as I can see this is a duplicate of the ionic compatibility issue. 
If not please provide a reproduction repo, and we can take a look, and eventually reopen the issue.
