### ISSUE TITLE
ENOENT : no such file or directory, unlink 'path to config.js file'

### ISSUE THREAD

**Issue by BenLune** [scullyio/scully#1415]
### Description
When I trigger scully CLI command, I have this error, not everytime but often. Both locally and remote on Gitlab CI.

#### 💻Your Environment

Mac OS, GitLab CI

**Angular Version:**

Angular 12.1.2

<pre><code>

</code></pre>

**Scully Version:**
"@scullyio/init": "1.1.4-BETA.163207"
"@scullyio/ng-lib": "^1.1.1-BETA.163207"
"@scullyio/scully": "^1.1.1-BETA.163207"

## 🔥 Error

```

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ENOENT: no such file or directory, unlink '/Users/user/WebstormProjects/my-projectscully.my-projectconfig.js'
    at Object.unlinkSync (fs.js:1052:3)
    at removeConfigJsFile (/Users/user/WebstormProjects/my-project/node_modules/@scullyio/scully/src/lib/utils/compileConfig.js:77:22)
    at exitHandler (/Users/user/WebstormProjects/my-project/node_modules/@scullyio/scully/src/lib/utils/exitHandler.js:20:13)
    at process.emit (events.js:323:22)
    at process.EventEmitter.emit (domain.js:482:12)
    at process.exit (internal/process/per_thread.js:165:15)
    at /Users/user/WebstormProjects/my-project/node_modules/@scullyio/scully/src/scully.js:171:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by SanderElias** [comment]
@BenLune That points to the code that removes the compiled config.js, As the file _is_ there (otherwise there is no way to reach that particular line) it is strange that it errors out on removing the file.
Does your setup start Scully from another folder perhaps? Scully should be executed from the project's root folder.|
Aside from that, this doesn't reproduce for me, so I need a project that does expose this behavior, and then I can diagnose the issue.

**Comment by BenLune** [comment]
Hi @SanderElias,
Thank you for your answer. Yes I looked at the source code managing this file removal. It seems to be well protected, it checks if the file exists.
Yes the config file is at the root folder of the project. After having aligned the versions of Scully for @scullyio/init, @scullyio/ng-lib and @scullyio/scully, it seems to be better.
I'll tell you here, in this issue, if the problem occurs again, because yes, it's very strange.

**Comment by BenLune** [comment]
Hi @SanderElias,
I have the problem again, this time on Gitlab CI, the job never ends : 
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ENOENT: no such file or directory, unlink '/home/gitlab/ci/builds/Ez_cEkkJ/0/quickshop/ngx-quickshop/scully.ngx-quickshop.config.js'
    at Object.unlinkSync (fs.js:1136:3)
    at removeConfigJsFile (/home/gitlab/ci/builds/Ez_cEkkJ/0/quickshop/ngx-quickshop/node_modules/@scullyio/scully/src/lib/utils/compileConfig.js:77:22)
    at exitHandler (/home/gitlab/ci/builds/Ez_cEkkJ/0/quickshop/ngx-quickshop/node_modules/@scullyio/scully/src/lib/utils/exitHandler.js:20:13)
    at process.emit (events.js:326:22)
    at process.EventEmitter.emit (domain.js:483:12)
    at process.exit (internal/process/per_thread.js:168:15)
    at /home/gitlab/ci/builds/Ez_cEkkJ/0/quickshop/ngx-quickshop/node_modules/@scullyio/scully/src/scully.js:171:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by BenLune** [comment]
I don't know why it is possible to get this error. But it may be great to add a catch block to this function, in order to get the process finished if it occurs. Every pages are rendered but the process never ends because of this not caught error.

**Comment by BenLune** [comment]
I still have this error.

**Comment by SanderElias** [comment]
@BenLune Thanks for the update. The hanging is an ongoing investigation pain point. 
I will wrap the function in another try-catch, but as said, it really should not be possible to get an error there. I would like to know why/when that happens...

**Comment by SanderElias** [comment]
@BenLune I just added some code to our exitHandler that should prevent this from happening.
Can you give the latest `@develop` version a go? `npm i @scullyio/scully@develop` should do the trick.

**Comment by SanderElias** [comment]
Closing this as it seems solved by the `@develop` update. If this issue still is ongoing, please let us know and we will reopen
