### ISSUE TITLE
Cant run the app.

### ISSUE THREAD

**Issue by Johnniexson** [scullyio/scully#142]
# 🐞 Bug report

## 💻Your Environment 
**Angular Version:**
<pre><code>

Node: 12.13.1
OS: win32 x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**
<pre><code>

"@scullyio/init": "0.0.9",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</code></pre>
## 🔥 Exception or Error
<pre><code>

The option outFolder isn't configured, using default folder "C:\Users\PC\Favorites\Projects\my-scully-app\dist\static\".
Cleaned up C:\Users\PC\Favorites\Projects\my-scully-app\dist\static\ folder.
 ☺   new Angular build imported
started servers in background
servers available
Finding all routes in application.
Pull in data to create additional routes.
Finding files in folder "C:\Users\PC\Favorites\Projects\my-scully-app\blog"
Route list created in files:
      src\assets\scully-routes.json
      C:\Users\PC\Favorites\Projects\my-scully-app\dist\static\assets\scully-routes.json
Route "" rendered into file: "C:\Users\PC\Favorites\Projects\my-scully-app\dist\static\index.html"
<html lang="en"><head>
  <meta charset="utf-8">
  <title>MyScullyApp</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>/* You can add global styles to this file, and also import other style files */
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9DOlxcVXNlcnNcXFBDXFxGYXZvcml0ZXNcXFByb2plY3RzXFxteS1zY3VsbHktYXBwL3NyY1xcc3R5bGVzLnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEsOEVBQUEiLCJmaWxlIjoic3JjL3N0eWxlcy5zY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLyogWW91IGNhbiBhZGQgZ2xvYmFsIHN0eWxlcyB0byB0aGlzIGZpbGUsIGFuZCBhbHNvIGltcG9ydCBvdGhlciBzdHlsZSBmaWxlcyAqL1xuIl19 */</style><style>
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL2FwcC5jb21wb25lbnQuc2NzcyJ9 */</style><script charset="utf-8" src="blog-blog-module-es2015.js"></script><style>[_ngcontent-yro-c22]::slotted(h1)  {
  color:rgb(51, 6, 37);
  background-color: rgb(248, 211, 236);
  padding: 5px;
  border-radius: 5px;
  width: -webkit-fit-content;
  width: -moz-fit-content;
  width: fit-content;
}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvYmxvZy9ibG9nLmNvbXBvbmVudC5jc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Q0FFQztFQUNDLG9CQUFvQjtFQUNwQixvQ0FBb0M7RUFDcEMsWUFBWTtFQUNaLGtCQUFrQjtFQUNsQiwwQkFBa0I7RUFBbEIsdUJBQWtCO0VBQWxCLGtCQUFrQjtBQUNwQiIsImZpbGUiOiJzcmMvYXBwL2Jsb2cvYmxvZy5jb21wb25lbnQuY3NzIiwic291cmNlc0NvbnRlbnQiOlsiXHJcblxyXG4gOjpzbG90dGVkKGgxKSAge1xyXG4gIGNvbG9yOnJnYig1MSwgNiwgMzcpO1xyXG4gIGJhY2tncm91bmQtY29sb3I6IHJnYigyNDgsIDIxMSwgMjM2KTtcclxuICBwYWRkaW5nOiA1cHg7XHJcbiAgYm9yZGVyLXJhZGl1czogNXB4O1xyXG4gIHdpZHRoOiBmaXQtY29udGVudDtcclxufVxyXG5cclxuIl19 */</style><style>
      :host {
        display: none;
      }
      scully-content {
        display: none;
      }
    </style></head>
<body>
  <app-root _nghost-yro-c21="" ng-version="9.0.0-rc.7"><router-outlet _ngcontent-yro-c21=""></router-outlet></app-root>
<script src="runtime-es2015.js" type="module"></script><script src="runtime-es5.js" nomodule="" defer=""></script><script src="polyfills-es5.js" nomodule="" defer=""></script><script src="polyfills-es2015.js" type="module"></script><script src="styles-es2015.js" type="module"></script><script src="styles-es5.js" nomodule="" defer=""></script><script src="vendor-es2015.js" type="module"></script><script src="vendor-es5.js" nomodule="" defer=""></script><script src="main-es2015.js" type="module"></script><script src="main-es5.js" nomodule="" defer=""></script>

</body></html>
Route "/blog/1-4-2020-blog" rendered into file: "C:\Users\PC\Favorites\Projects\my-scully-app\dist\static\blog\1-4-2020-blog\index.html"
Route list created in files:
      src\assets\scully-routes.json
      C:\Users\PC\Favorites\Projects\my-scully-app\dist\static\assets\scully-routes.json

Generating took 36.15 seconds for 2 pages:
  That is 0.06 pages per second,
  or 18080 milliseconds for each page.

ERROR: The process "6452" not found.
</code></pre>

**Comment by SanderElias** [comment]
@Johnniexson From your output, I can see Scully does run for you.
The error you are seeing is explained in #79 
However, you seem to encounter a timeout somehow. Can you provide a repo so we can check what is causing your issue?

**Comment by Johnniexson** [comment]
Okay, here is the repo:
https://github.com/Johnniexson/my-suclly-app-starter

**Comment by SanderElias** [comment]
@Johnniexson Scully cant create pages for an app that doesn't work.
You forgot to import the `httpClientModule` which is mandatory for Scully in your app, so your app errored out on boot. 
After adding the module everything will work as expected. 
I'm going to close this issue, but @Villanuevand will check if the mandatory dependency on is documented, and @jorgeucano will check (after his vacation) if we should add this to our schematics.
Thanks for bringing this issue to our attention,

**Comment by Johnniexson** [comment]
I added the httpClientModule to my app.module.ts but still get the error.

<pre>
import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";
import { HttpClientModule } from "@angular/common/http";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, AppRoutingModule, HttpClientModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
</pre>

Btw I heard someone with same issue said this problem is associated with windows that it actually works on mac (don't know how true cus i don't run on mac).

<pre>
Generating took 11.11 seconds for 2 pages:
  That is 0.19 pages per second,
  or 5556 milliseconds for each page.

ERROR: The process with PID 10468 (child process of PID 8644) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 10588 (child process of PID 8644) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 8744 (child process of PID 8644) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 10132 (child process of PID 8644) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 8644 (child process of PID 11340) could not be terminated.
Reason: There is no running instance of the task.
</pre>

Running npm run scully again...
<pre>
Generating took 11.41 seconds for 2 pages:
  That is 0.18 pages per second,
  or 5707 milliseconds for each page.

ERROR: The process "11380" not found.
</pre>

**Comment by SanderElias** [comment]
I added the import to your app, and it is actually working fine on my system (Linux)
And it is actually working fine on your computer too.
You can ignore the:
```bash
ERROR: The process with PID 10468 (child process of PID 8644) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 10588 (child process of PID 8644) could not be terminated.
Reason: The operation attempted is not supported.
ERROR: The process with PID 8744 (child process of PID 8644) could not be terminated.
Reason: There is no running instance of the task.
...
```
(read through #79 for a more in-depth explanation) But it is fluke on windows, and not affecting the functionality of Scully at all. 
check your `dist/static` folder to inspect the results of Scully.

**Comment by Johnniexson** [comment]
Okay, i just figured out where i was getting it wrong.
Well 'npm run scully' only generates the static files but does not run/load the app such as ng server do for a regular angular app which then shows the url to view the app or opens the browser. But for scully, i think the documentation should state this for getting started cus i had to use [https://www.npmjs.com/package/http-server](url) in order to see scully in action. 
As a suggestion twill be better if "npm run scully" can start a development server to actually load and view the app as "gatsby develop" does for gatsby. I presume this is what "npm run scully:serve" was meant to do, but it actually doesn't render for the routes.

**Comment by SanderElias** [comment]
We are working towards that.  the `scully serve` command does serve the generated static site. 
there are a number of features in flight that will make de DX better as it is now. 
Remember that we are still at very early stages.

**Comment by Johnniexson** [comment]
Yea I get, great work and a big well done to the team. 👏
