### ISSUE TITLE
Scully serves old version of application

### ISSUE THREAD

**Issue by sometimesvlad** [scullyio/scully#1424]
### Description. 
Just changed some styles in global scss file, ran ``npx scully serve``  and old version of application appears in browser. First I thought I need to clean my static folder or rebuild app, tried ``npx scully`` and got messages:
`` new Angular build imported. `` and ``Started servers in background``. But new version didnt appear

#### 🔬 Minimal Reproduction. 
1) create minimal app and build it
2) change some styles/layout etc..
3) rebuild app
4) serve static version and i suggest you wont see changes

#### 💻Your Environment
MacOS 11.5.2. 
Node 16.4.2

**Angular Version: ~12.1.1**

<pre><code>
Angular CLI: 12.1.4
Node: 16.4.2 (Unsupported)
Package Manager: npm 6.14.14
OS: darwin x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cli                    12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Scully Version: ^1.0.0**

<pre><code>
{
  "name": "scully-ssg",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "scully": "npx scully --",
    "scully:serve": "npx scully serve --"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.1.1",
    "@angular/common": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/forms": "~12.1.1",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@scullyio/init": "^1.1.4",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular/cli": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.7.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "typescript": "~4.3.2"
  }
}
</code></pre>

Didn't got any errors or exceptions but still see old version, tried to clean static folder by myself and it didnt solve problem. 
Thanks everyone for help !

**Comment by SanderElias** [comment]
Are you sure you did an `ng build`? 
If so, are you using caching? 
Can you try again? use those commands in this order: (assuming mac/Linux/wsl, otherwise use the windows equivalent)
```bash
rm -fr dist
 npx ng build
 rm -fr .scully   // Only if you used the scully cache!
npx scully --scanRoutes
```

Let us know what happens

**Comment by SanderElias** [comment]
Closing this, as there seems nothing left to do.
We will happily reopen when needed
