### ISSUE TITLE
build problem scully

### ISSUE THREAD

**Issue by RyadBenmanser** [scullyio/scully#1425]
i have installe scully in my angular project using the command "ng add @scullyio/init" everything is generated the scully folder and  plugins folder and scully.projectname.config.ts is generated but when i build my project using the command "ng build" the static folder isn't generated and i don't know how to solve this problem

**Comment by Jefiozie** [comment]
Hi @RyadBenmanser , I just checked your repo and I don't see any issue. I can just run scully, below the steps I've taken.

1. Clone the rpeo
2. npm install
3. ng build --prod (and ng build)
4. npm run scully

The I can see your app.

**Comment by zaracooper** [comment]
@RyadBenmanser  if you're still running into this issue, [someone mentioned a fix for it here](https://github.com/scullyio/scully/issues/1108#issuecomment-879828845). I followed it and it worked. 

> I run into your same problem. I was running Scully in a folder having a parent which contains whitespaces (which is pretty normal, on Windows).
> 
> I was able to make it work by applying on Scully's JS files (yes, in the node_modules folder :( ) a fix which corresponds to turning this line:
> 
> https://github.com/scullyio/scully/blob/6d55e6234b93754ea919e67f94aacdb1aeaf0c2c/libs/scully/src/lib/utils/compileConfig.ts#L109
> 
> 
> into `` exec(`npx tsc -p "${configPath}"`, (err, res) => { `` (please note the double quotes)
> After this fix, everything worked. do you want me to open a specific issue for this?

**Comment by SanderElias** [comment]
@zaracooper I would love a PR, good catch!
