### ISSUE TITLE
Dockerfile angular scully

### ISSUE THREAD

**Issue by skorpmeister** [scullyio/scully#1428]
Hi, 
Im trying to make a Dockerfile with angular scully and nginx.

There is a way to do this?

**Comment by SanderElias** [comment]
@skorpmeister Yes, this is totally possible. IIRC there is a hint on how to docker in our FAQ page, 
Also, there are some issues discussing this issue in a bit more depth.
When you are done with this, I would love a blog, or some documentation/sample around it, as I think it may benefit other users.
