### ISSUE TITLE
Support independent project configuration files in Nx workspaces

### ISSUE THREAD

**Issue by sonicparke** [scullyio/scully#1429]
### Description

In version 2 workspaces, project configurations can also be independent files, referenced by angular.json. For instance, an angular.json may contain projects configured as below.

https://nx.dev/latest/angular/core-concepts/configuration#projectjson

Currently, Scully doesn't know how to deal with these configs not being directly present as an object in either `angular.json` or `workspace.json`.

### Describe the solution you'd like

If the project in `angular.json` or `workspace.json` is a string and not an object Scully should take that path string and get the project config from the `project.json` in the specified project path.

### Describe alternatives you've considered

Not sure of any alternatives at the moment.

**Comment by sonicparke** [comment]
I'm working on a PR for this. I've gotten part of the way through but trying to track down an error.

**Comment by SanderElias** [comment]
Cool, drop me a DM if you need help!

**Comment by daton89** [comment]
Hi guys, I'm using scully 2.1.0 and I'm getting an error that the project i point out is not found in the angular.json. 
I'm using nx with the new project.json structure cause I have a big project. 

![image](https://user-images.githubusercontent.com/6856342/147989637-92d418aa-8b60-4297-8c3d-c798f462e062.png)
```json
    "@scullyio/init": "^2.1.0",
    "@scullyio/ng-lib": "^2.1.0",
    "@scullyio/platform-server": "^2.1.0",
    "@scullyio/scully": "^2.1.0",
    "@scullyio/scully-plugin-puppeteer": "^2.1.0",
```

I see the error but scully seems to work, I don't know if something is wrong. 

Should I open a new issue for that?

**Comment by sonicparke** [comment]
@daton89 Do you have `target: 'targets',` in your scully config file? By default, it looks for `architect` so maybe that's the difference?

**Comment by daton89** [comment]
Hi @sonicparke, adding `target: 'targets'` solved the issue, thanks!
