### ISSUE TITLE
Remove unneeded console line

### ISSUE THREAD

**Issue by Jefiozie** [scullyio/scully#1436]
### Description

In the [watchmode](https://github.com/scullyio/scully/blob/main/libs/scully/src/lib/watchMode.ts#L110) file we have an unneeded `console.log` This line can be removed as there is no reason to leave it there.

**Comment by AgneseB2** [comment]
Can you assign it to me?

**Comment by rutuja1121** [comment]
I would like to work on this

**Comment by Jefiozie** [comment]
Hi everybody, I would love to assign one of you to the job but somebody ready made a PR #1437

**Comment by TomJWilliams** [comment]
@Jefiozie given that the PR was closed by @SanderElias because the CLA was not signed will you be assigning this issue out. If so could you assign it to me please?

**Comment by Jefiozie** [comment]
Hi @TomJWilliams somebody already made a pr for this issue. But thank for willing to fix it.

#1447
