### ISSUE TITLE
Wrong type for puppeteer launch options is used

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#1451]
### Description
I tried to update to Scully v2.0.0, but I have an error in my config saying that `args` in `puppeteerLaunchOptions` does not exist, but it actually does. I think that Scully config uses wrong type for `puppeteerLaunchOptions`. It is currently typed as `LaunchOptions`  but should be `PuppeteerNodeLaunchOptions`.
If I am right and it's a simple typing change that doesn't break anything else I am happy to submit a PR.
#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 12.2.12
Node: 14.18.1
Package Manager: npm 7.15.1
OS: win32 x64

Angular: 12.2.12
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.12
@angular-devkit/build-angular   12.2.12
@angular-devkit/core            12.2.12
@angular-devkit/schematics      12.2.12
@schematics/angular             12.2.12
rxjs                            6.6.3
typescript                      4.3.5
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/ng-lib": "^2.0.0",
"@scullyio/scully": "^2.0.1",
</code></pre>

## 🔥 Exception or Error

<pre><code>
Type '{ args: string[]; }' is not assignable to type 'LaunchOptions'.
Object literal may only specify known properties, and 'args' does not exist in type 'LaunchOptions'
</code></pre>

**Comment by SanderElias** [comment]
I think you are right, go for it
