### ISSUE TITLE
Can't install after update to Angular 13

### ISSUE THREAD

**Issue by Sergiobop** [scullyio/scully#1458]
## 🐞 Bug report
I can't use `npm install` without the force command after updating to Angular 13

### Description
I can't use `npm install` without the force command after updating to Angular 13

#### 🔬 Minimal Reproduction
Update to Angular 13

#### 💻Your Environment

**Angular Version:**
13

**Scully Version:**
<pre><code>
"@scullyio/init": "^2.0.1",
"@scullyio/ng-lib": "^2.0.0",
"@scullyio/scully": "^2.0.1",
</code></pre>

## 🔥 Exception or Error
<pre><code>
Found: @angular/common@13.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"13.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"12.x.x" from @scullyio/ng-lib@2.0.0
npm ERR! node_modules/@scullyio/ng-lib
npm ERR!   @scullyio/ng-lib@"^2.0.0" from the root project
</code></pre>

**Comment by SanderElias** [comment]
This is fixed by the release of 2.0.2 of the schematics. 
Please lt us know if its not working for you still.
