### ISSUE TITLE
npm install fails after installing in NX project using angular 12.2.0

### ISSUE THREAD

**Issue by pietschy** [scullyio/scully#1462]
### Description
npm fails to install after running `ng add @scullyio/init` in a single app nx angular project.

#### 💻Your Environment

**Angular Version:**
<pre><code>12.10.0
</code></pre>

**Scully Version:**
<pre><code>    "@angular/animations": "^12.2.0",
    "@angular/cdk": "^12.2.13",
    "@angular/common": "^12.2.0",
    "@angular/compiler": "^12.2.0",
    "@angular/core": "^12.2.0",
    "@angular/forms": "^12.2.0",
    "@angular/platform-browser": "^12.2.0",
    "@angular/platform-browser-dynamic": "^12.2.0",
    "@angular/router": "^12.2.0",
    "@nrwl/angular": "12.10.0",
    "@scullyio/init": "^2.0.2",
    "@scullyio/ng-lib": "^2.0.0",
    "@scullyio/scully": "^2.0.0",
    "angular-animations": "^0.11.0",
    "lodash": "^4.17.21",
    "message-format": "^6.2.3",
    "rxjs": "~6.6.0",
    "tailwindcss": "^2.2.19",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
</code></pre>

## 🔥 Exception or Error

<pre><code>
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^12.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">12.x.x" from @scullyio/ng-lib@2.0.1
npm ERR! node_modules/@scullyio/ng-lib
npm ERR!   @scullyio/ng-lib@"^2.0.1" from the root project
</code></pre>

**Comment by Jefiozie** [comment]
Would you try the following steps as described in the docs:

```
npm/ yarn install @scullyio/init
nx g @scullyio/init:install -- --project=<projectName>
```

Do you still see this error then?

**Comment by pietschy** [comment]
Yep, same error.
```
$ nx g @scullyio/init:install -- --project=website
    ⚠️  Skipping polyfills.ts
    Install ng-lib
    ✅️ Added dependency
⠼ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nyt@0.0.0
npm ERR! Found: @angular/common@12.2.13
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^12.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">12.x.x" from @scullyio/ng-lib@2.0.1
npm ERR! node_modules/@scullyio/ng-lib
npm ERR!   @scullyio/ng-lib@"^2.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by SanderElias** [comment]
@pietschy I pushed an updated `@scullyio/ng-lib' to npm, with a different version number notation in the `package.json`
can you give that a try?
