### ISSUE TITLE
Rendering pages took NaN seconds

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#1485]
### Description
Been seeing this in all my projects:
![image](https://user-images.githubusercontent.com/15785773/144065219-ce29e3a6-fb0a-452d-bae4-3ed482deefc3.png)
I think something is messed up in the calculations of these numbers.

#### 🔬 Minimal Reproduction
Init scully in your project and run it.

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 13.0.2
Node: 14.18.1
Package Manager: npm 7.24.0
OS: win32 x64

Angular: 13.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router, service-worker
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            12.2.10
@angular-devkit/schematics      12.2.10
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/ng-lib": "^2.0.2",
"@scullyio/scully": "^2.0.3",

</code></pre>

**Comment by SanderElias** [comment]
@BlindDespair We don't seem to be able to reproduce, can you provide a bit more info? 
What is your environment, os? Perhaps a GitHub repo we can check?

**Comment by BlindDespair** [comment]
@SanderElias It happens for me both on windows and on Ubuntu in my CI. Here is the minimal repro repo: https://github.com/BlindDespair/scully-nan-issue-repro.

**Comment by BlindDespair** [comment]
It also appears to be a regression, in version `1.1.1` it was working from what I can tell.

**Comment by SanderElias** [comment]
@BlindDespair when I run your repo:
![image](https://user-images.githubusercontent.com/1249083/144229880-657305da-6354-4dd4-95b1-cb10e66f222a.png)

I'm on ubuntu 20.

**Comment by BlindDespair** [comment]
@SanderElias That is interesting. What version of Node and npm did you use?

**Comment by SanderElias** [comment]
After some talking to @BlindDespair it turns out that this is an issue with node 14 and performance-timers.

**Comment by d-koppenhagen** [comment]
I can verify this issue. I have the same behaviour and be able to reproduce it.

**Comment by SanderElias** [comment]
I looked into this, and it turns out there is something in node V14 that prevents the performance tracking to work correctly. I suspect this has to do with V8 and the spectre bug that was going around in that time frame. (it worked fine in earlier, and later versions)
As this is non-essential for the normal working of Scully, and creating a workaround would take quite some time and seems to take quite an amount of code, I'm going to mark this as "will not fix"

**Comment by hunhavoc** [comment]
I can confirm that the issue is only appearing when using node 14. Node 12 and 16 are fine.
