### ISSUE TITLE
Not able to use custom plugin

### ISSUE THREAD

**Issue by samvloeberghs** [scullyio/scully#150]
# 🐞 Bug report

### Description

When defining a custom plugin and registering it, it can't be used as type,  as defined in the documentation https://github.com/scullyio/scully/blob/master/docs/plugins.md

## 🔬Minimal Reproduction

1) Start from a new empty angular-cli project with one route, for example `/about`.
2) Add scully, following the docs
3) Create a new plugin `voidPlugin.js` in the root of the project.

```js
function voidPlugin(html, route) {
  return Promise.resolve(html);
}
module.exports.voidPlugin = voidPlugin;
```

4) import and register the plugin in the scully.config.js

```js
const { registerPlugin } = require('@scullyio/scully/bin');
const { voidPlugin } = require('./voidPlugin');

registerPlugin('render', 'void', voidPlugin);

exports.config = {
  projectRoot: "./src/app",
  routes: {
    "/about": {
      "type": "void"
    }
  }
};
```

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 12.14.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**
<pre><code>
"@scullyio/init": "0.0.9",
"@scullyio/ng-lib": "latest",
 "@scullyio/scully": "latest",
</code></pre>

## 🔥 Exception or Error
<pre><code>
> scully

The option outFolder isn't configured, using default folder "/Users/samvloeberghs/Projects/Kwerri/ng-v9-scullyio/dist/static/".
Unknown type "void" in route "/about"
</code></pre>

I think an example repo is not really required, because it's actually just the most basic example of setting up a render plugin. But if really needed I have just pushed my test code here: https://github.com/samvloeberghs/ng-v9-scullyio

**Comment by stewwan** [comment]
same in here
https://github.com/stewwan/stewan-io

- npm install
- ng build
- npm run scully

**Comment by jorgeucano** [comment]
@SanderElias is working in a fix for that

**Comment by SanderElias** [comment]
@samvloeberghs You can only list routePlugins in the types. 
When you want to add a (couple) of renderPlugins, you can use the
 `postRenderers: ['plugins','by', 'name']` option in your config
I created a small table of contents plgin that show how this can be done in #161  (might be merged in master by now)

**Comment by samvloeberghs** [comment]
@SanderElias cool, will try it out as soon as it hits master/latest

**Comment by SanderElias** [comment]
@samvloeberghs its in master since yesterday. I did push out a new version to NPM too.

**Comment by samvloeberghs** [comment]
@SanderElias I don't think it's solved now. I had to the impression I could add a plugin that gets executed post-render. Basically I just want to run a post-render function that takes the HTML and modifies it. How can this be achieved.

If I'm not mistaken, `postRenderers` is part of `HandledRoute`but that is part of the router plugins?

**Comment by SanderElias** [comment]
@samvloeberghs, The type field needs a route-plugin. It will not work with render plugins.
try this:
```js
require('./plugins/testPlugin');

exports.config = {
  projectRoot: './src/app',
  routes: {
    '/about': {
      type: 'default'.
      postRenderers: ['test'],
    }
  }
}
```
We really need a bit more documentatin around this.

**Comment by samvloeberghs** [comment]
@SanderElias  I tried this, and it doesn't work:

error:
```
Unknown type "default" in route "/"
Unknown type "default" in route "/about"
Unknown type "default" in route "/not-found"
```

```
// scully.config.js
require('./plugins/testPlugin');

exports.config = {
  projectRoot: './src/app',
  routes: {
    '/': {
      type: 'default',
      postRenderers: ['test'],
    },
    '/about': {
      type: 'default',
      postRenderers: ['test'],
    },
    '/not-found': {
      type: 'default',
      postRenderers: ['test'],
    }
  }
};

```

**Comment by aaronfrost** [comment]
@SanderElias there is no plugin with `default`. You have it all configured, but never build it. HAHA!

**Comment by aaronfrost** [comment]
Use this plugin as `type`:

```javascript
const {registerPlugin, configValidator} = require('@scullyio/scully');
function voidPlugin() {
  const name = `voidPlugin-${Math.ceil(Math.random() * 1000)}`;
  voidPluginFunction[configValidator] = async () => [];
  registerPlugin('router', name, voidPluginFunction);
  return name;

  function voidPluginFunction(r){
    return Promise.resolve([{route: r}]);
  }
}
```

Add this to your config as follows: 
```
...
'/about' : {
  type: voidPlugin(),
  postRenderers: ['minifyHtml'],
}
```

I cloned your project, and did this, and it worked fine.

**Comment by SanderElias** [comment]
@samvloeberghs Turns out, I didn't activate the default plugin :-D 
However, yes, there is a `defaultPostRenderers`, and you can add that to the generic part of your config like:
```js
require('./plugins/testPlugin');

exports.config = {
  projectRoot: './src/app',
  defaultPostRenderers: ['test']
  routes: {
    '/': {
      type: 'default',
    },
    '/about': {
      type: 'default',
    },
    '/not-found': {
      type: 'default',
    }
  }
};
```
If you specify the `postrenderers` in a route, those will be use _instead_ of the default ones, not in addition

**Comment by samvloeberghs** [comment]
@SanderElias this is what I needed, thanks!

The route configuration is not required anymore either, as these are auto-discovered by Scully.

```js
require('./plugins/testPlugin');

exports.config = {
  projectRoot: './src/app',
  defaultPostRenderers: ['test']
};
```

is enough

**Comment by SanderElias** [comment]
@samvloeberghs If this works for you, can I close the issue?
