### ISSUE TITLE
Scully sever not exiting after rendering static files

### ISSUE THREAD

**Issue by sonicparke** [scullyio/scully#1513]
### Description
When running scully it doesn't appear that the servers are stopping when scully is done building the static files

#### 💻Your Environment

**Angular Version:**
<pre><code>

13.2.3
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/init": "^2.1.0",
"@scullyio/ng-lib": "^2.1.0",
"@scullyio/scully": "^2.1.0",
"@scullyio/scully-plugin-puppeteer": "^2.1.0",
</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by Jefiozie** [comment]
Hi @sonicparke thanks for reporting this issue, do you have by example a repo for reproduction? We have seen sort of these issues in the past so we would like to look if this has to due because of configuration or any edge case.

**Comment by sonicparke** [comment]
@Jefiozie unfortunately I don't. It's running in a private nx repo. If you aren't able to reproduce it in a fresh setup I can try to setup a repo that will reproduce it.

**Comment by hisham** [comment]
I think I'm getting this too. 

When I run scully:serve, the server immediately exits with the following errors: 

```
hisham@mb3 frontend % npm run scully:serve

> @essential/frontend@1.0.0 scully:serve
> scully serve --project website

  ✔ Starting servers for project "website"
  ✔ Scully development Servers stopped, and exited
  ✔ Scully development Servers stopped, and exited
```

I see there is a running process as follows: 

` |--- 03014 hisham Scully-dev-server-website            
`

after I kill this process, I'm able to run scully:serve again.

**Comment by nikhilnxvverma1** [comment]
> I think I'm getting this too.
> 
> When I run scully:serve, the server immediately exits with the following errors:
> 
> ```
> hisham@mb3 frontend % npm run scully:serve
> 
> > @essential/frontend@1.0.0 scully:serve
> > scully serve --project website
> 
>   ✔ Starting servers for project "website"
>   ✔ Scully development Servers stopped, and exited
>   ✔ Scully development Servers stopped, and exited
> ```
> 
> I see there is a running process as follows:
> 
> `|--- 03014 hisham Scully-dev-server-website `
> 
> after I kill this process, I'm able to run scully:serve again.

This worked for me too. But its not very elegant. And BTW, I did it from the activity monitor because I can't ps | grep shit
