### ISSUE TITLE
dependency conflict RE 'animations'

### ISSUE THREAD

**Issue by joeclark-phd** [scullyio/scully#1523]
### Description
Maybe this is a "newbie to npm" bug, but I followed the installation instruction from the project website, and my installation fails due to a dependency conflict.

#### 🔬 Minimal Reproduction
> `ng new testproject --routing`
> `cd testproject`
> `ng add @scullyio/init`

'Yes' to proceed
'Scully platform server' as route renderer

OUTPUT:
```
    Installing ng-lib
    Installing Scully Platform Server plugin
UPDATE src/app/app.module.ts (466 bytes)
UPDATE src/polyfills.ts (2531 bytes)
UPDATE package.json (1256 bytes)
⠧ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: testproject@0.0.0
npm ERR! Found: @angular/animations@13.1.1
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"12.2.15" from @angular/platform-server@12.2.15
npm ERR! node_modules/@angular/platform-server
npm ERR!   @angular/platform-server@"^12" from the root project
```

#### 💻Your Environment

**Angular Version:**

<pre><code>Angular CLI: 13.1.2
Node: 16.13.2
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@angular/platform-server        <error>
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
</code></pre>

**Scully Version:**

<pre><code>    "@scullyio/init": "^2.1.5",
    "@scullyio/ng-lib": "^2.1.0",
    "@scullyio/platform-server": "^2.1.0",
    "@scullyio/scully": "^2.1.0",
</code></pre>

## 🔥 Exception or Error

<pre><code>npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: testproject@0.0.0
npm ERR! Found: @angular/animations@13.1.1
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"12.2.15" from @angular/platform-server@12.2.15
npm ERR! node_modules/@angular/platform-server
npm ERR!   @angular/platform-server@"^12" from the root project
</code></pre>

**Comment by SanderElias** [comment]
This is an issue with NPM, and has nothing to do with Scully. use the option `--legacy-peer-deps` with npm to get a working install/
I'm closing this for now, but feel free to discuss this further. I will be happy to reopen when needed

**Comment by olierxleben** [comment]
While the `npm install --legacy-peer-deps` works, it is triggered by the schematic and someone ran into this very easily. And quite often this is your first interaction with Scully so the DX has no giddy starting point imo.
