### ISSUE TITLE
Cannot refresh or access dynamic paths directly.

### ISSUE THREAD

**Issue by nigamkaushal** [scullyio/scully#1525]
### Description

I am having a dynamic route in my app -

**/search/:searchType/:destination**

This **destination** will always be random so I don't want this page to be prerendered.

```
const routes: Routes = [{
    path: ':searchType/:destination',
    component: SearchPageComponent,
    runGuardsAndResolvers: 'always',
  }
];
@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class SearchRoutingModule {}
```

#### 🔬 Minimal Reproduction

If I try to access this route 

> /search/hotel/destination

 via ***routerLink***, it works as expected.
But if I try a refresh on this page or access this route directly it gives me 

> Cannot GET /search/hotel/destination

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 12.2.14
Node: 16.13.1 (Unsupported)
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   12.2.14
@angular-devkit/core            12.2.14
@angular-devkit/schematics      12.2.14
@angular/cli                    12.2.14
@nguniversal/builders           12.1.3
@nguniversal/express-engine     12.1.3
@schematics/angular             12.2.14
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Scully Version:**

<pre><code>
{
  "name": "travel-websites",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "scully": "ng build --configuration development && scully --scanRoutes",
    "scully:serve": "npx scully serve --"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.2.15",
    "@angular/common": "^12.2.15",
    "@angular/compiler": "^12.2.15",
    "@angular/core": "^12.2.15",
    "@angular/forms": "^12.2.15",
    "@angular/platform-browser": "^12.2.15",
    "@angular/platform-browser-dynamic": "^12.2.15",
    "@angular/platform-server": "^12.2.15",
    "@angular/router": "^12.2.15",
    "@nguniversal/express-engine": "^12.1.3",
    "@scullyio/init": "^2.1.4",
    "@scullyio/ng-lib": "^2.1.4",
    "@scullyio/platform-server": "^2.1.4",
    "@scullyio/scully": "^2.1.4",
    "@scullyio/scully-plugin-puppeteer": "^2.1.4",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "localstorage-polyfill": "^1.0.1",
    "moment": "^2.29.1",
    "ng-otp-input": "^1.8.1",
    "ngb-toast": "0.0.6",
    "ngx-cookie": "^5.0.2",
    "ngx-cookie-backend": "^5.0.2",
    "ngx-pagination": "^5.1.1",
    "rxjs": "~6.6.0",
    "rxjs-compat": "^6.6.7",
    "swiper": "^7.3.4",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^12.1.3",
    "@angular-devkit/build-angular": "^12.2.14",
    "@angular/cli": "^12.2.14",
    "@angular/compiler-cli": "^12.2.15",
    "@nguniversal/builders": "^12.1.3",
    "@types/express": "^4.17.0",
    "@types/file-saver": "^2.0.4",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.20.38",
    "blob-polyfill": "^6.0.20211015",
    "brotli-webpack-plugin": "^1.1.0",
    "compression-webpack-plugin": "^9.2.0",
    "jasmine-core": "~3.8.0",
    "karma": "^6.3.9",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.5"
  }
}

</code></pre>

## 🔥 Exception or Error

<pre><code>
**Cannot GET /search/hotel/destination**
![Capture](https://user-images.githubusercontent.com/48838401/149634431-dc718aa3-ef79-43c6-8140-e7f2a6fc1daf.PNG)

</code></pre>

**Comment by nigamkaushal** [comment]
#1237 Same problem as this one.

**Comment by SanderElias** [comment]
By design, the Scully dev server doesn't serve any pages that will not be generated. 
This is done because this mimics the default setup of most servers where static apps will be deployed. i believe we even have documented this behavior, but not 100% sure about that. If not, I would welcome an docs PR (or at least an issue)

We do have the [`handle404` option](https://scully.io/docs/Reference/config/#handle404) (which also can bu use as `--404` on the cmd-line) 

If you need this option, make sure that your deployment server handles 404 in the same way!
