### ISSUE TITLE
TransferStateService blocks Angular resolvers

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#1529]
### Description
Scully [`TransferStateService`](https://github.com/scullyio/scully/blob/main/libs/ng-lib/src/lib/transfer-state/transfer-state.service.ts) relies on `NavigationEnd` event to find out which url `data.json` should be loaded for. This makes it impossible to use [Angular Resolvers](https://angular.io/api/router/Resolve) to load the data while using `TransferStateService` inside of them. It essencially creates a dead lock situation where `TransferStateService` is waiting for navigation to end and resolver is waiting for the data.
We can benefit from using resolvers even while using scully when navigating within the site using Angular navigation to make sure all the data is available before rendering starts.
#### 🔬 Minimal Reproduction
1. Create a simple scully  app with 1 route
2. Add a Resover to that route and use `TransferStateService` inside it

#### Proposed solution
I believe there is a better event choice for defining when scully should load the data in `TransferStateService` such as [`ResolveStart`](https://angular.io/api/router/ResolveStart) or [`GuardsCheckEnd`](https://angular.io/api/router/GuardsCheckEnd) that both have `urlAfterRedirects` in them to make sure the data is loaded for the correct page and not block resolvers at the same time.
I can submit a PR if this sounds good.

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 13.0.2
Node: 14.18.1
Package Manager: npm 7.24.0
OS: win32 x64

Angular: 13.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router, service-worker
... youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            12.2.10
@angular-devkit/schematics      12.2.10
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/ng-lib": "^2.0.2",
"@scullyio/scully": "^2.0.3",

</code></pre>

**Comment by SanderElias** [comment]
@BlindDespair, Are you sure `ResolveStart` or `GuardsCheckEnd` are fired on routes that don't have resolvers or guards?

**Comment by BlindDespair** [comment]
[Docs](https://angular.io/api/router/ResolveStart#description) say that that's the case at the moment. It says that it may change in the future but I do believe that if it does change there will be a way to tell if there are things to be resolved or not.

**Comment by BlindDespair** [comment]
`ResolveStart` does not appear on initial navigation though, but `GuardsCheckEnd` is there for every navigation regardless if there are guards are not which makes a lot of sense. Since Scully does not load routing data on the first navigation still either of these 2 events could work. We patched `TransferStateService` locally and I can confirm that it works.
