### ISSUE TITLE
Build time for scully is very poor

### ISSUE THREAD

**Issue by Amith278** [scullyio/scully#1536]
### Description
Scully build is very slow and not at all suitable for a production code. 
Rendering 57 pages took: 12 minutes, which is very poor. This is in both AWS build and Github Build. 
Rendering in local is relatively faster. 

![image](https://user-images.githubusercontent.com/79908235/152497140-c3ca8e2e-80e5-4e78-9d80-ac1d6339c437.png)

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 13.0.4
Node: 14.16.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cdk                    12.2.13
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            6.6.7
typescript                      4.4.4

</code></pre>

**Scully Version:**

<pre><code>

  "@scullyio/init": "^1.1.4",
  "@scullyio/ng-lib": "^1.0.0",
  "@scullyio/scully": "^1.1.1",

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by SanderElias** [comment]
@Amith278 This is not something I recognize
This is from our own tests in [Github actions](https://github.com/scullyio/scully/runs/5026329751?check_suite_focus=true):
```text
Total time used 90.59 seconds
  197 pages have been created
  Rendering the pages took 86.74 seconds
  That is 2.28 pages per second,
  or 441 milliseconds for each page.
  
  Finding routes in the angular app took 3.7 seconds
  Pulling in route-data took 142 milliseconds
```
or using the SPS render
```text
Total time used 32.04 seconds
  197 pages have been created
  Rendering the pages took 20.75 seconds
  That is 9.5 pages per second,
  or 106 milliseconds for each page.
  
  Finding routes in the angular app took 3.91 seconds
  Pulling in route-data took 145 milliseconds
```

So, it might be that your pages are taking a long time to load. Scully has to wait until the page is completely done before it can read out the HTML.
If you can make a minimal reproduction repo, that shows the same behaviour, there might be something we can to to help you.

**Comment by SanderElias** [comment]
Closing, for now, Will reopen when there is an actionable reproduction
