### ISSUE TITLE
Scully is not generating the build for the routes that has trailing slash.

### ISSUE THREAD

**Issue by adityakoushikr11** [scullyio/scully#1543]
## 🐞 Bug report
We have a angular application whose routing is configured in such a way that it adds a trailing slash in the end of every route.  I am pasting a snippet of angular routes that we have.
`
  { path: "home/.", component: Component1 },
  { path: "technologies/.", component: Component2 },
`
When we try to prerender the pages, scully is not recognizing the above routes. Routes not configured for home/.. 
#### 🔬 Minimal Reproduction
This is not a common scenario, I am getting this error only for routes that as trailing slash in the end.
#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 13.2.2
Node: 14.15.0
Package Manager: npm 6.14.8
OS: win32 x64

Angular: <error>
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.2.1
@angular-devkit/core            13.2.2 (cli-only)
@angular-devkit/schematics      13.2.2 (cli-only)
@angular/cli                    13.1.4
@angular/compiler-cli           13.1.3
@schematics/angular             13.2.2 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>
</code></pre>
**Scully Version:**
<pre><code>

    "@scullyio/init": "^2.1.10",
    "@scullyio/ng-lib": "2.1.5",
    "@scullyio/scully": "^2.1.10",
    "@scullyio/scully-plugin-puppeteer": "^2.0.0",
</code></pre>

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by SanderElias** [comment]
@adityakoushikr11 We can only render routes that are in your angular app. A route that ends with `xyz/.` will load an `index.html` file from the `xyz` folder. This is not something that angular supports out of the box as far as I know.
Can you show me your route definitions in your angular app?

**Comment by SanderElias** [comment]
Closing due to lack of actionable context. We will reopen if there is any.
