### ISSUE TITLE
TS Compiling error - Unable to setup TS plugin

### ISSUE THREAD

**Issue by gfsd3v** [scullyio/scully#1559]
## 🐞 Bug report
Config file not understanding TS syntax 

### Description
I'm trying to setup a custom plugin, I've created a TS plugin file with a `router` plugin. When I run `npx scully` I receive an error message from the import statement. 

#### 💻Your Environment

**Angular & Scully Version** 

<pre><code>

  "dependencies": {
    "@angular-devkit/schematics": "^13.2.6",
    "@angular/animations": "~13.2.6",
    "@angular/common": "~13.2.6",
    "@angular/compiler": "~13.2.6",
    "@angular/core": "~13.2.6",
    "@angular/forms": "~13.2.6",
    "@angular/platform-browser": "~13.2.6",
    "@angular/platform-browser-dynamic": "~13.2.6",
    "@angular/router": "~13.2.6",
    "@scullyio/init": "^2.1.24",
    "@scullyio/ng-lib": "^2.1.24",
    "@scullyio/scully": "^2.1.24"
    "@scullyio/scully-plugin-puppeteer": "^2.1.24",
    "graphql": "^15.5.0",
    "node-fetch": "^3.2.2",
    "rxjs": "~7.5.5",
    "ts-results": "^3.3.0",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.5"
  },

</code></pre>

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/36668882/158059051-f974deac-a15d-414d-b806-e4493b1e643f.png)

<pre><code>

scully.[project].config.ts

import { ScullyConfig } from '@scullyio/scully';
import '@scullyio/scully-plugin-puppeteer';
import './scully/plugins/postsPagesPlugin';

export const config: ScullyConfig = {
  projectRoot: './src',
  projectName: '[project]',
  outDir: './dist/static',
  routes: {
    '/p/:slug': {
      type: 'postsPagesPlugin',
    },
  },
};

</code></pre>

<pre><code>

postsPagesPlugin.ts

import { HandledRoute, registerPlugin } from '@scullyio/scully';
import { PostService } from '@pages/static/post/post.service';
import { ErrorService } from '@shared/error.service';

registerPlugin(
  'router',
  'postsPagesPlugin',
  async (): Promise<HandledRoute[]> => {
    const errorService = new ErrorService();
    const postService = new PostService(errorService);
    const articlesResponse = await postService.getPostsPages();
    if (articlesResponse.ok) {
      return Promise.resolve(
        articlesResponse.val.articles.data.map((article) => ({
          route: `/p/${article.attributes.slug}`,
        }))
      );
    }
    return Promise.reject('Error on getting posts data');
  }
);

</code></pre>

**Comment by SanderElias** [comment]
We have plugins set up this way in our tests, so I'm sure this can work.
A couple of questions:
1. what version of Scully/angular/node are you using
2. are you sure the tsconfig in the Scully folder is set up correctly?
3. From the error, it looks you are trying ESM. did you add a package.json with `{ "type": "module" }` ?
4. If you are using ESM, are you sure all your dependencies are also available as ESM modules?
5. Are you sure the other import you are pulling in are compiled already?

**Comment by SanderElias** [comment]
Closing by lack of actionable context
