### ISSUE TITLE
When scully build failed, scully.xxx.config.ts won't be compiled again.

### ISSUE THREAD

**Issue by UchihaYuki** [scullyio/scully#1560]
#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 12.2.16
Node: 16.13.1 (Unsupported)
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 12.2.16
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.16
@angular-devkit/build-angular   12.2.16
@angular-devkit/core            12.2.16
@angular-devkit/schematics      12.2.16
@schematics/angular             12.2.16
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/init": "^2.1.25",
</code></pre>

## 🔥 Exception or Error

<pre><code>

If scully build failed, then the scully.xxx.config.js won't be deleted, and scully.xxx.config.ts won't be compiled again. 
(By the way, dist/static should be deleted before every new build starts, or there will be lots of junk files)
</code></pre>

**Comment by SanderElias** [comment]
@UchihaYuki 
> (By the way, dist/static should be deleted before every new build starts, or there will be lots of junk files)

Scully can do a partial run, I'm sure in such a case you don't want to remove what's there already. Also, when you deploy to production, you don't want to kill off the people currently using the app, by removing the version they are currently using, right?
By default, Scully doesn't delete the contents of the static folder. We will always default to the save side. When you want to remove the files you can use the cmd-line option [`--RSD`](https://scully.io/docs/Reference/command-line-options/#removestaticdist)

For your other issue, I believe this is already solved in our `@next` version.
For now, a simple workaround is removing the file from your package.json script. Something like this will do:

```json
  "scripts": {
    "build.static" : "rm scully.&.config.js && npx scully "    
  }
```
