### ISSUE TITLE
Adding .scully/settings.yml to .gitignore file

### ISSUE THREAD

**Issue by SaadMouline** [scullyio/scully#1569]
In our team we are two developers working on the same project. We both have to run scully locally to test our changes before releasing them.

When ran locally, scully modifies the values of **homeFolder** and **outDir** in my settings.yml file. They are changed to match the app's home folder and the folder where the static html files live on my machine. If I push the modified version of settings.yml it will affect the other developer in the team, as the paths will not match. 

Is it okay to add the settings.yml file to the .gitignore file and stop tracking it, or is there a better option?

**Comment by SanderElias** [comment]
You can add the entire `.scully`folder to your gitIgnore without an issue.
The only thing is you need to add the `--noPrompt` CLI option in CI/CD
