### ISSUE TITLE
Sitemap Generator

### ISSUE THREAD

**Issue by evolkmann** [scullyio/scully#157]
# 🧩 Feature request

Sitemap Generator

### Description
Alongside scully's route detection mechanism, a `sitemap.xml` file could be generated.

### Describe the solution you'd like
Could be implemented as a new scully plugin

### Describe alternatives you've considered
Using external build systems such as gulp would be possible, but is not really a nice and clean solution.

-------------

I just learned about Scully today and migrated one of our sites. It works great! Previously, I had been using a similar prerendering-solution which I developed for several projects (https://github.com/exportarts/angular-universal-utils). There was already a sitemap feature present and I would be happy to develop a scully plugin to cover the feature.

**Comment by SanderElias** [comment]
There is already an routes.json generated, with all the details about every route in there.
It's easy enough to create a sitemap.xml from that. I will see if I can provide a sample for that.

**Comment by evolkmann** [comment]
Hi @SanderElias, thanks for your response. You don't need to provide a sample, the process is clear.
I will try that out in the next days when I come back to a project!

**Comment by SanderElias** [comment]
@evolkmann Given that you don't seem to need the sample, I'm closing this issue. 
Feel free to open a new issue if you do need help generating a site-map

**Comment by stevemurch** [comment]
Just fyi, I've got some Python code that some people might want to work from in their devops build. See this post:

[Generating Sitemap from Scully Routes](https://www.stevemurch.com/generating-sitemap-from-scully-routes/2021/01)

**Comment by tritren** [comment]
```
const fs = require('fs');
const routes = require('./assets/scully-routes.json');
const builder = require('xmlbuilder');
const doc = builder.create('urlset').att('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9');
routes.forEach(v=> {
  doc.ele('url')
    .ele('loc')
      .txt(`${v.route}`)
    .up()
    .ele('lastmod')
      .txt(new Date().toISOString())
    .up()
    .ele('priority')
      .txt('0.80')
    .up()
  .up()
})

fs.writeFile('./src/sitemap.xml', doc.toString({ pretty: true }), (err)=>{
  if (err) throw err;
  console.log('sitemap.xml is created successfully!');
});
```
