### ISSUE TITLE
Incremental regeneration a la Nextjs

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#1572]
### Description

 we need to add incremental regeneration https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration

### Describe alternatives you've considered

 This is currently possible for any Scully user to build on top of Scully. But we need to provide it for them. It's a complex problem to solve.

**Comment by SanderElias** [comment]
@aaronfrost This is on our [roadmap](https://scully.io/docs/roadmap/) as `Build On Demand server`.
We currently lack time/funding to work on this feature.
