### ISSUE TITLE
Scully skips routes with an empty path

### ISSUE THREAD

**Issue by AmineAML** [scullyio/scully#1578]
### Description
Any route in the routing module like this gets skipped:
```
{
    path: '',
    loadChildren: () => import('src/app/..
},
```
In the console log where it shows the pages generated, any page with an empty route won't show nor get counted in the total pages and it doesn't get added to the scully routes file.
The only way to get it to work is by adding a name in the path.
I'm also using the sitemap plugin which won't have those pages added in the sitemap file.

#### 🔬 Minimal Reproduction
You can try this on this [repo](https://github.com/AmineAML/Portfolio), make sure to comment lines 41 & 44 and uncomment line 45, you can also do this to the lines 116 & 118 & 119. then run scully using the npm script.

#### 💻Your Environment

**Project's Angular Version:12**
**Global Angular Version:13**

<pre><code>

Angular CLI: 13.2.4
Node: 16.14.0
Package Manager: npm 8.3.1
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.4 (cli-only)
@angular-devkit/core         13.2.4 (cli-only)
@angular-devkit/schematics   13.2.4 (cli-only)
@schematics/angular          13.2.4 (cli-only)
</code></pre>

**Scully Version:2.1.29**

<pre><code>

    "@scullyio/init": "^2.1.29",
    "@scullyio/ng-lib": "^2.1.29",
    "@scullyio/platform-server": "^2.1.29",
    "@scullyio/scully": "^2.1.29",
    "@scullyio/scully-plugin-flash-prevention": "^2.1.29",
    "@scullyio/scully-plugin-puppeteer": "^2.1.29",
</code></pre>

**Comment by SanderElias** [comment]
I just checked, and it works fine.
However, you really need to have the router configured correctly to have the guess-parser pick up the routes.
That means that you need to add `pathMatch: 'full',` in a setup like yours, otherwise the parser can't distinguish it from its parent, which doesn't have a component, but just children.
 ```typescript
     path: WebsiteLanguage.English, children: [
      {
        path: '',
        pathMatch: 'full', // <=== you really need this!!
        loadChildren: () => import('src/app/layouts/welcome/welcome.languages.module').then(m => m.WelcomeEnModule),
        data: {
          metadata: {
            title: 'Amine Amellouk | Freelance Software Developer & DevOps',
            description: 'A software developer with a background in economics who\'s developing APIs, SPAs and Jamstack applications.'
          },
          animation: 'welcome'
        }
      },
      ...
      ]
```
