### ISSUE TITLE
Prerender just on page

### ISSUE THREAD

**Issue by maxcodefaster** [scullyio/scully#1580]
### Description

Is it possible to just prerender just one page, let's say a welcome page for logged out users and let the normal router handle all other routes?

**Comment by SanderElias** [comment]
There are multiple ways to do this. I think the simplest is just filtering out the routes you don't want using a `routeProcess` plugin.
in your config, something like this will work:
```ts
registerPlugin('routeProcess','KeepOnlyWhatIWant',async (handledRoutes) => {
  const keeps = ['someRouteToKeep', 'anotherRouteToKeep'];
  return handledRoutes.filter(route => keeps.includes(route.route));
})
```

Another way is using the route Filters cmd-line options:
- [baseFilter](https://scully.io/docs/Reference/command-line-options/#basefilter) for filtering on unhandled routes
- [routeFilter](https://scully.io/docs/Reference/command-line-options/#routefilter) for filtering out handled routes

Then there is another possibility to replace the default route handler with the ignored handler, but that's not really recommended.
