### ISSUE TITLE
Generate `.html` files instead of directory

### ISSUE THREAD

**Issue by anuj-scanova** [scullyio/scully#1611]
### Description
Using Scully to migrate our existing static website into Angular and thus our existing static website the URL patterns like
```
https://example.com/                        -> serves /index.html
https://example.com/about-us.html
https://example.com/privacy-policy.html
```

But in angular, the URLs are given as `about-us` and `privacy-policy` which result generates the following rendered files
```
/static/index.html                               -> homepage
/static/about-us/index.html              
/static/privacy-policy/index.html
```
and the URLs are accessible like
```
https://example.com
https://example.com/about-us
https://example.com/privacy-policy
```

I want to keep the URLs with `.html` extension as previously. To achieve this, I renamed the angular route to have `.html` in the page, but then it generates the paths liks
```
/static/index.html
/static/about-us.html/index.html              
/static/privacy-policy.html/index.html
```
and the URL `https://example.com/about-us.html` is giving 301 redirections to `https://example.com/about-us.html/`

### Describe the solution you'd like
I would like to skip the directory creation and have the `.html` files created for each route directory.

### Describe alternatives you've considered
Plugin can be created to change the rendering of the pages.

**Comment by SanderElias** [comment]
I get why you want this option, but it goes against the grain and will create other issues.  This is not something we will not support OOB with Scully.
However, that being said, this is something you can handle yourself. you can replace the plugin that writes out the data to the filesystem.
The source is [here](https://github.com/scullyio/scully/blob/main/libs/scully/src/lib/systemPlugins/writeToFs.plugin.ts)
you can do something like this in your config file:
```ts
registerPlugin(scullySystem, WriteToStorage, async (route: string, content: string): Promise<string> => {
  try {
    const file = join(scullyConfig.outDir, route+'.html');
    createFolderFor(file);
    writeFileSync(file, content);
    return file
  } catch (e) {
    logError(`Error during file write`, e);
  }
  return '';
});
```

Make sure you add some handing of the json files, when you are using transferState. You can see how in the linked source.

**Comment by anuj-scanova** [comment]
Thanks, @SanderElias for the help.

I tried adding the shared script in  the `scully.my-project.config.ts` file but it gives the following error
```
> npx scully --project my-project "--scanRoutes" "--noPrompt"

  ✔ Folder "./scully" used for custom plugins
  ⚠ Using deprecated plugin type:"render"  use "postProcessByHtml" instead
  x 
---------
 We encountered an error executing the config file. "./scully.my-project.config.ts"
 Check the error below, and try again later
--------- 
Error: Plugin writeToStorage already exists
    at registerPlugin (/Users/user/code/org/my-project/node_modules/@scullyio/scully/src/lib/pluginManagement/pluginRepository.js:74:15)
    at Object.<anonymous> (/Users/user/code/org/my-project/scully.my-project.config.js:79:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/user/code/org/my-project/node_modules/@scullyio/scully/src/lib/utils/compileConfig.js:68:76
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Also tried renaming the plugin and using it in `defaultPostRenderers` but the plugin does not run.
