### ISSUE TITLE
Prism.js (syntax highlighting) enable line numbers

### ISSUE THREAD

**Issue by tomastrajan** [scullyio/scully#1623]
### Description

It would be great if we could enable prism.js line numbers with a simple option similar to already existing

`setPluginConfig('md', { enableSyntaxHighlighting : true });`

### Describe the solution you'd like

For example ``setPluginConfig('md', { enableSyntaxHighlighting : true, enableLineNumbers: true });``

### Describe alternatives you've considered

I have tried to add `line-number` css class to parent element to no avail. Most likely because this has to be enabled on the markdown plugin level (and use prism.js line numbers plugin under the hood)

**Comment by SanderElias** [comment]
You can load the needed plugin from within your config, ad it will work. There is no need to configure anything.
