### ISSUE TITLE
Support for Angular 15: Has Scully been abandoned?

### ISSUE THREAD

**Issue by knoake** [scullyio/scully#1640]
There have been no new commits or releases since September 2022. And unless I'm mistaken there is no official support for Angular 13, 14 or 15.

Has Scully been abandoned?

**Comment by SanderElias** [comment]
@knoake No, it is not. But All contributors are currently working full-time on other projects. So, yes progress has slowed down.
Full Angular V15 support is there, but not ready for release by a long shot. I'm currently working on a refactor, but it will take at least a couple of weeks, probably months before anything will be visible.

**Comment by knoake** [comment]
Good to know. Thank you for all your hard work.
