### ISSUE TITLE
Parallelize route creation to improve prerender performance

### ISSUE THREAD

**Issue by marcell93** [scullyio/scully#1647]
### Description

In my web project I have more than 400 different routes and the prerender is taking about 1 hour. It would be great if we could parallelize the creation of all the routes so that it takes less time.

### Describe the solution you'd like

Maybe add some initial configuration to turn on parallelism and have other puppeteer instances work at the same time on the prerender

**Comment by SanderElias** [comment]
This is already done. From the start Scully used parralell tabs inside ppt to speed up rendering
