### ISSUE TITLE
Init schematic not generating the required files for ng version 16

### ISSUE THREAD

**Issue by gadepalliharish** [scullyio/scully#1667]
## 🐞 Bug report
Scully init schematic unable to generate the required files 
### Description
When I try to select pupeeteer to be my router ... the init schematic doesn't add any required files
#### 💻Your Environment

**Angular Version:**

<pre><code>

![image](https://github.com/scullyio/scully/assets/15201973/e7024d04-627c-4d46-87f9-93a1b1be5933)

</code></pre>

**Scully Version:**

<pre><code>

{
  "name": "test-angular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.1.0",
    "@angular/common": "^16.1.0",
    "@angular/compiler": "^16.1.0",
    "@angular/core": "^16.1.0",
    "@angular/forms": "^16.1.0",
    "@angular/platform-browser": "^16.1.0",
    "@angular/platform-browser-dynamic": "^16.1.0",
    "@angular/router": "^16.1.0",
    "@scullyio/init": "^2.1.21",
    "@scullyio/ng-lib": "^2.1.41",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.1.4",
    "@angular/cli": "~16.1.4",
    "@angular/compiler-cli": "^16.1.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.1.3"
  }
}

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by gadepalliharish** [comment]
![image](https://github.com/scullyio/scully/assets/15201973/6aae0af2-9eff-4c6d-b93c-c686ff3b1838)

**Comment by tbholejcastellon1994** [comment]
The same happens to me. Also in applications that are bootstrapped via a standalone component, importing ScullyLibModule doesn't seem to work either.

**Comment by gadepalliharish** [comment]
> The same happens to me. Also in applications that are bootstrapped via a standalone component, importing ScullyLibModule doesn't seem to work either.

yeah ... how do we solve this
