### ISSUE TITLE
Weird behavior of Observable

### ISSUE THREAD

**Issue by lacolaco** [scullyio/scully#171]
# 🐞 Bug report

### Description

I hit a weird error around Observable returned from ScullyRoutesService.

![image](https://user-images.githubusercontent.com/1529180/72113654-73d10800-3384-11ea-8e3a-e80c8c59d11a.png)

`getCurrent()` method returns an Observable but its `subscribe` method seems not right one.

`available$` is no problem. It's so weird...

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.3
Node: 10.16.0
OS: darwin x64
Angular: 9.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

</code></pre>

**Scully Version:**
<pre><code>
    "@scullyio/init": "^0.0.8",
    "@scullyio/ng-lib": "^0.0.8",
    "@scullyio/scully": "^0.0.53",
</code></pre>
## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by lacolaco** [comment]
That error is solved when I add a type assertion of `Observable<ScullyRoute>`

![image](https://user-images.githubusercontent.com/1529180/72114250-4be2a400-3386-11ea-8024-e9a74cc9d314.png)

Originally returned type`getCurrent()` is `Observable<any[]> | Observable<ScullyRoute>` but `any[]` and `ScullyRoute` are not compatible. I think it should be `Observable<ScullyRoute | null>`.

**Comment by SanderElias** [comment]
@lacolaco thanks for reporting. I'll update the types.

**Comment by aaronfrost** [comment]
@SanderElias I have gotten this working. You cool if I take it?
