### ISSUE TITLE
.bin/scully is published as CRLF

### ISSUE THREAD

**Issue by lacolaco** [scullyio/scully#192]
# 🐞 Bug report

### Description

after package installed, `node_modules/.bin/scully` is written with CRLF. It occurs error like below

```
$ yarn scully
yarn run v1.17.3
$ scully
env: node\r: No such file or directory
error Command failed with exit code 127.
```

Similar issue: https://github.com/mrmlnc/svg2sprite-cli/issues/4

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.3
Node: 10.16.0
OS: darwin x64
Angular: 9.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
</code></pre>

**Scully Version:**
<pre><code>
    "@scullyio/init": "^0.0.11",
    "@scullyio/ng-lib": "^0.0.9",
    "@scullyio/scully": "^0.0.55",
</code></pre>
## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by jorgeucano** [comment]
Hey @lacolaco I'm tested in windows & mac and @SanderElias tested in linux and work in all OS...
Can you give me more information for reproduce this issue?
