### ISSUE TITLE
How to implement a custom router plugin?

### ISSUE THREAD

**Issue by msprogramando** [scullyio/scully#200]
# 🗄️ Docs report

### Description

First of all, thanks for scully! I am almost done with my setup. All routes that are related to routing modules are recognized by scully but when it comes to dynamic route rendering (/brand/:slug) it is not clear how to implement it for me.

Normally there is the option to add it directly to the scully.config.js but the result I get is an object that has another property (stories) that holds the array of page objects. So the scully config below "routes" is the wrong place right? I would have to access the result like data.stories first.

What I have tried inside the scully conf
```
exports.config = {
  projectRoot: "./src/app",
  outFolder: './dist/static',
  routes: {
    '/brands/:brandSlug': {
      type: 'json',
      brandSlug: {
        url: 'https://...',
        headers: {
          "Accept": "application/json",
          "Content-Type": "application/json",
        },
        property: 'slug'
    }
    },
  },
};
```

So, if I am on the right way, I have to create a custom plugin to solve it, right? In the docs there is someting written about "How to make a router plugin"
https://github.com/scullyio/scully/blob/master/docs/plugins.md#-how-to-make-a-router-plugin

Do I have to place the custom router plugin in a separate file or can I use the scully conf?

From where do I get the registerPlugin function? 
In some examples I found:
`const {registerPlugin} = require('../dist/scully');`
but when I start running scully i get
```
Error: Cannot find module '../dist/scully'
At the end:
projectRoot missing in "scully.config.js"
No routes defined in "scully.config.js"
```

### Reproduction Steps**
My current scully conf
```
const {registerPlugin} = require('../dist/scully');

const brandSlugPlugin = async (route, options) => {
  // const result = {
  //   stories: [
  //     {
  //       "name": "Adidas",
  //       "slug": "adidas",
  //       "full_slug": "brands/adidas",
  //     },
  //     {
  //       "name": "Puma",
  //       "slug": "puma",
  //       "full_slug": "brands/puma",
  //     },
  //   ]
  // }

  // just for testing
  return [
    {route: '/brands/puma'},
    {route: '/brands/adidas'},
  ]
};

registerPlugin('router', 'brandSlugs', brandSlugPlugin);

exports.config = {
  projectRoot: "./src/app",
  outFolder: './dist/static',
  routes: {
    '/brands/:brandSlug': {
      type: 'brandSlugs',
    },
  },
};
```

**Comment by SanderElias** [comment]
@msprogramando You don't have `../dist/scully` that is something we have to do in our monorepo to test things. replace it with `@scullyio/scully` and it should work for you.
IIRC we just updated the docs to reflect this.

**Comment by SanderElias** [comment]
BTW, I think you can still use our JSON plugin. it has the possibility to add add a function so you can extract the data as you need it.
```
    '/brands/:brandSlug': {
      type: 'json',
      brandSlug: {
        url: 'https://...',
        headers: {
          "Accept": "application/json",
          "Content-Type": "application/json",
        },
        resultsHandler: rawData => result.stories.map(row => row.full_slug.split('/').pop())
    }
```
should probably do the trick.

**Comment by msprogramando** [comment]
@SanderElias thanks for your response, I really appreciate!

```
const {registerPlugin} = require('@scullyio/scully/pluginManagement/pluginRepository');

const brandSlugPlugin = async (route, options) => {
  // const result = {
  //   stories: [
  //     {
  //       "name": "Adidas",
  //       "slug": "adidas",
  //       "full_slug": "brands/adidas",
  //     },
  //     {
  //       "name": "Puma",
  //       "slug": "puma",
  //       "full_slug": "brands/puma",
  //     },
  //   ]
  // }

  // just for testing
  return [
    {route: '/brands/adidas'},
    {route: '/brands/puma'},
  ]
};

registerPlugin('router', 'brandSlugs', brandSlugPlugin);

exports.config = {
  projectRoot: "./src/app",
  outFolder: './dist/static',
  routes: {
    '/brands/:brandSlug': {
      type: 'brandSlugs',
    },
  },
};
```

While running scully now he is still complaining about
```
---------------
   Route plugin "brandSlugs" should have an config validator attached to 'brandSlugPlugin[configValidator]'
---------------
```
Perhaps you can add an example for this to the documentation as well.

Thanks for your second reply and the hint to solve it via resultsHandler. I will try it.

**Comment by Villanuevand** [comment]
@msprogramando, 

Thanks for your feedback, at this moment we are updating the docs with this information #208 .

### You error: 
```
---------------
   Route plugin "brandSlugs" should have an config validator attached to 'brandSlugPlugin[configValidator]'
---------------
```

It's due from the last released version the `registerPlugin` method has a fourth parameter, the
validation function. 

```
const {registerPlugin} = require('@scullyio/scully/pluginManagement/pluginRepository');

const brandSlugPlugin = async (route, options) => {
  // const result = {
  //   stories: [
  //     {
  //       "name": "Adidas",
  //       "slug": "adidas",
  //       "full_slug": "brands/adidas",
  //     },
  //     {
  //       "name": "Puma",
  //       "slug": "puma",
  //       "full_slug": "brands/puma",
  //     },
  //   ]
  // }

  // just for testing
  return [
    {route: '/brands/adidas'},
    {route: '/brands/puma'},
  ]
};

const validator = async conf => []; // plugins vallidations

registerPlugin('router', 'brandSlugs', brandSlugPlugin, validator);

exports.config = {
  projectRoot: "./src/app",
  outFolder: './dist/static',
  routes: {
    '/brands/:brandSlug': {
      type: 'brandSlugs',
    },
  },
};
```

If you have other questions just let us know.
