### ISSUE TITLE
`ng g @scullyio/init:post`: Let users specify file extension

### ISSUE THREAD

**Issue by d-koppenhagen** [scullyio/scully#213]
# 🧩 Feature request

### Description

As Scully supports AsciiDoc and markdown files out of the box, a user should be able to generate a `.adoc` file as well.

### Describe the solution you'd like

I think it would be good to prompt the user for the target file type (`.md` set by default) or set it via an option directly:

```bash
ng g @scullyio/init:post --name="my asciidoc post" --type="adoc"
```

This should do the following:
- create the target file with the correct file extension ('.md' or '.adoc')

I think the following things should be considered:
- The prompt should a user select from an enum (`md`, `adoc`)
- The `metaDataFile` option should still be available, also for AsciiDoc file. But AsciiDoc uses another meta data format. So the `yml` template should be either converted, ignored, or complemented by another template for asciidoc files

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by SanderElias** [comment]
@d-koppenhagen I like the idea. However, people are free to add their own file-handlers.
As they will do this during runtime, we don't have a list of what parsers will be used.

**Comment by d-koppenhagen** [comment]
Ah, I see. So the extension should be a Sting and set to `md` by default I think.

**Comment by d-koppenhagen** [comment]
Files with extensions that aren't processed by any file plugin could then may be identified by a better logging. I created a separate issue for that:
https://github.com/scullyio/scully/issues/215

**Comment by SanderElias** [comment]
@d-koppenhagen I'm not sure that is a good idea, Users might store related files in the same folder.
For example, if you have images for your blog, you might put them alongside the content files.
(yes deploying those is another issue!)

**Comment by SanderElias** [comment]
I see another problem. If we are going to generate some other formats too, we need to _know_ what to put n there. For example, the `.adoc` format is very different from the `.md`. It makes no sense to put in sample markdown content in such a file.

**Comment by d-koppenhagen** [comment]
Okay, but putting those images into the folder (e.g. an image) and link in the markdown won't work as they aren't served from this directories are they?

**Comment by SanderElias** [comment]
No, but that is a deployment issue, not a Scully issue. 
Assets management is still something on our radar but is a hard problem to solve.

**Comment by jorgeucano** [comment]
Hey @d-koppenhagen Do you think you can re-write this? With the new structure?

**Comment by d-koppenhagen** [comment]
sure :)

**Comment by d-koppenhagen** [comment]
here it is: https://github.com/scullyio/scully/pull/558
