### ISSUE TITLE
better logging for file plugins

### ISSUE THREAD

**Issue by d-koppenhagen** [scullyio/scully#215]
# 🧩 Feature request

### Description

For debug / investigation purpose it would be good to have some more logs related to the file plugins when running `scully serve`.

### Describe the solution you'd like

I think it would be good to list the matches for the file plugin

```bash
...
Finding files in folder "/some/path/blog"
   Processed 5 files in './blog' handled by the 'markdown' file plugin.
   Processed 3 files in './blog' handled by the 'asciidoc' file plugin.
   Found 2 unhandled files in './blog'.
   Processed 3 files in './foo' handled by the 'foobar' file plugin.
   Found 2 unhandled files in './foo'.
Route list created in files:
...
```

**Comment by jorgeucano** [comment]
I close the issue due to inactivity
