### ISSUE TITLE
Error compiling and serving scully app

### ISSUE THREAD

**Issue by danmt** [scullyio/scully#223]
# Error compiling and serving scully app

I created this issue because I'm having problems creating my first scully app. After following the steps in the Getting Started tutorial I'm getting unexpected responses in the console. Everything goes well until I get to the serve/build step.

I created this [minimal reproduction of the issue](https://github.com/danmt/scully-building-issue).

If I execute `npm run scully` I get as an output:

```

> my-scully-app@0.0.0 scully /home/danmt/Blogging/Scully/my-scully-app
> scully

Cleaned up /home/danmt/Blogging/Scully/my-scully-app/dist/static folder.
 ☺   new Angular build imported
Background servers already running.
Could not connect to server
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! my-scully-app@0.0.0 scully: `scully`
npm ERR! Exit status 15
npm ERR!
npm ERR! Failed at the my-scully-app@0.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/danmt/.npm/_logs/2020-01-22T23_35_18_956Z-debug.log

```

If I execute `npm run scully:serve` I get as an output:

```

> my-scully-app@0.0.0 scully:serve /home/danmt/Blogging/Scully/my-scully-app
> scully serve

starting static server
Adding all extra routes (1)
Could not start Scully serve TypeError: Cannot read property 'length' of undefined

```

I updated the `scully.config.js` file to this:

```javascript
exports.config = {
  projectRoot: "./src/app",
  outDir: "./dist/static",
  routes: {
    "/blog/:slug": {
      type: "contentFolder",
      slug: {
        folder: "./blog"
      }
    }
  },
  extraRoutes: [""]
};
```

**Comment by SanderElias** [comment]
@danmt I solved the issue with the extra routes.
It looks to me you had a stale _old_ version running. 
```
Cleaned up /home/danmt/Blogging/Scully/my-scully-app/dist/static folder.
 ☺   new Angular build imported
Background servers already running.
Could not connect to server
npm ERR! code ELIFECYCLE
```
The message `Background servers already running.` tells me you already had a version running.
If you see a message like that, you should run `npx scully killServer` so you are sure you are on the new version.
We will take some precations so we will make sure your server ends on installing a new version.

**Comment by danmt** [comment]
You guys are so awesome! Once I get off the clock I'm gonna give it a try. Thanks a lot @SanderElias
