### ISSUE TITLE
Docs: Describe the intention of `IdleMonitorService`

### ISSUE THREAD

**Issue by d-koppenhagen** [scullyio/scully#237]

**Comment by SanderElias** [comment]
@Villanuevand can you find a place for this?

> We use it to hook into zonejs, so we know when angular goes idle (more precise, when all outgoing HTTP-requests are settled) and then we trigger puppeteer, so it knows its ready to render. Without this, we have to resort to a (25seconds) timeout. this is both slower and unprecise. some pages need even more time.

**Comment by Villanuevand** [comment]
@d-koppenhagen  At this moment into the docs we have [scully-lib-core.mmd](https://github.com/scullyio/scully/blob/master/docs/scully-lib-core.md) file. 

In there you can find explanation about: 
- IdleMonitor
- Router Service
- Scully Content
- Transfer State
- Utils methods

Im going to close this issue, if you think some is missing please open other Issue.
