### ISSUE TITLE
Use Title and Meta services

### ISSUE THREAD

**Issue by thuchede** [scullyio/scully#247]
# 🧩 Feature request
##  Description
Since SSG are often/sometimes used for SEO purposes, I'd expect the `create-markdown`/`blog` schematics to make use of title and description fields in frontmatter out of the box.

## Describe the solution you'd like
I'd like to make some changes to the default `ScullyContentComponent` class to include angular [`Title`](https://angular.io/api/platform-browser/Title) and [`Meta`](https://angular.io/api/platform-browser/Meta) services, then get the current route through the `ScullyRoutesService` to set title and meta tags accordingly.
In order to leave the possibility to disable this feature, I'd also introduce a new input, `metadataOptions`, that could look like this : 
```typescript
@Input()
metadataOptions = {
  title: true,
  description: true
};
```

## Describe alternatives you've considered
Let users do the work manually and just provide a snippet in the docs ?

Maybe this is related to #80  ?

**Comment by SanderElias** [comment]
@thuchede As every developer has a strong opinion on how to handle meta-data, we are only providing this data through the `ScullyRouteService.getCurrentRoute` observable. 
This will fire on navigation, so you can easily update your page from within the controller of your content route (a sample is the blog route)

I'm currently looking into a way to do a app-scan that will _not_ build the HTML files, but will find all the data that goes into the route file. That way, you can utilize this data in your blog components before you have the actual content rendered.

**Comment by SanderElias** [comment]
This is taken care of by pr #252, Scully will now first prepare all route information, and only then do the rendering of the pages, with up to date information

**Comment by yringler** [comment]
@SanderElias is this elaborated in the docs?
I'm using the json plugin, and added a title and description to the response.
The title is used to create a title tag, but the description isn't.

Also, in addition to <title> and <description>, I want to set all the other tags - og, twitter card, etc ([ngx-sec](https://www.npmjs.com/package/ngx-seo) handles all of them. would be great if that worked with scully)
