### ISSUE TITLE
Contentful Plugin

### ISSUE THREAD

**Issue by peterbsmith2** [scullyio/scully#249]
### Description

[Feature Parity with Gatsby Source Contentful](https://www.npmjs.com/package/gatsby-source-contentful)

### Describe the solution you'd like

[Feature Parity with Gatsby Source Contentful](https://www.npmjs.com/package/gatsby-source-contentful)

#### Including
- [ ] accept `spaceId` and `accessToken` from contentful for auth
- [ ] optionally use [contentful preview API](https://www.contentful.com/developers/docs/references/content-preview-api/) 
- [ ] [Download assets for static distribution option](https://www.npmjs.com/package/gatsby-source-contentful#download-assets-for-static-distribution) 
- [ ] accept optional `host` for overriding default `cdn.contentful.com` host
- [ ] `environment` option for selecting [Contentful Environment](https://www.contentful.com/developers/docs/concepts/multiple-environments/)
- [ ] `localFilter` option
- [ ] `forceFullSync` option
- [ ] `proxy` for axios proxy configuration (potentially wasteful)
- [ ] support to query both types of contentful nodes, `ContentType` and `Asset`

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by jorgeucano** [comment]
Hey @peterbsmith2 Can you tell us what is the current state of this ?

**Comment by jorgeucano** [comment]
Hey @peterbsmith2 Can you tell us what is the current state of this ?

**Comment by jorgeucano** [comment]
I close the issue due to inactivity
