### ISSUE TITLE
Problem with npx scully killServer

### ISSUE THREAD

**Issue by hmuschett** [scullyio/scully#251]
## 🐞 Bug report
I am following this tutorial https://medium.com/angular-in-depth/scully-the-static-site-generator-for-angular-d0608cb028ae
### Description
the error is when I trying to runng g @scullyio/init:blog
#### 💻Your Environment
<pre><code>
win 8.1
Angular CLI: 8.3.23
Node: 12.14.0
OS: win32 x64
Angular: 8.2.14
</code></pre>

**Scully Version:**

<pre><code>
latest

</code></pre>

## 🔥 Exception or Error

<pre><code>
 ng add @scullyio/init
Installing packages for tooling via npm.
Installed packages for tooling via npm.
    Install ng-lib for Angular v8
    ✅️ Added dependency
UPDATE package.json (1400 bytes)
UPDATE src/app/app.module.ts (387 bytes)
UPDATE src/polyfills.ts (3031 bytes)

> deasync@0.1.15 install D:\Nueva carpeta\scullyDemo\blogpostdemo\node_modules\deasync
> node ./build.js

`win32-x64-node-12` exists; testing
Binary is fine; exiting

> puppeteer@2.1.0 install D:\Nueva carpeta\scullyDemo\blogpostdemo\node_modules\puppeteer
> node install.js

> @scullyio/scully@0.0.62 postinstall D:\Nueva carpeta\scullyDemo\blogpostdemo\node_modules\@scullyio\scully
> npx scully killServer

npm WARN rollback Rolling back node-pre-gyp@0.14.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\Nueva carpeta\scullyDemo\blogpostdemo\node_modules\@angular\compiler-cli\node_modules\fsevents\node_modules'
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\Nueva carpeta\scullyDemo\blogpostdemo\node_modules\@angular\compiler-cli\node_modules\fsevents\node_modules'
npm WARN karma-jasmine-html-reporter@1.5.1 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.
npm WARN guess-parser@0.4.15 requires a peer of typescript@~3.7.5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @scullyio/scully@0.0.62 postinstall: `npx scully killServer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @scullyio/scully@0.0.62 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Milagros\AppData\Roaming\npm-cache\_logs\2020-01-30T09_59_54_289Z-debug.log
Package install failed, see above.
</code></pre>

**Comment by SanderElias** [comment]
@hmuschett We can not reproduce your issue, can you provide some more information?
I suspect everything went well. The post-install step is just there to make sure there is no old version running anymore.
If this is not the case, can you provide us the complete detailed logfile from npm?

**Comment by SanderElias** [comment]
We reproduced it and fixed the issue with pr #261
