### ISSUE TITLE
Home Route ignored with scully-0.0.63 & ng-lib-v8-0.0.16

### ISSUE THREAD

**Issue by journeyman88** [scullyio/scully#263]
## 🐞 Bug report
The home '' route gets ignored with scully-0.0.63 & ng-lib-v8-0.0.16 , worked fine in scully-0.0.62 & ng-lib-v8-0.0.15

### Description
After the upgrade of the npm packages, the npx scully operation compiled all but the '' route, while the other routes were statically built without problems

#### 🔬 Minimal Reproduction
ng n test-home;
cd test-home
ng g c home
ng add @scullyio/init
Fix app.modules import (from 'ng-lib' to 'ng-lib-v8')
Add route "{path: '', component: HomeComponent}"
ng build
npx scully

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 8.3.24
Node: 12.14.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.24
@angular-devkit/build-angular     0.803.24
@angular-devkit/build-optimizer   0.803.24
@angular-devkit/build-webpack     0.803.24
@angular-devkit/core              8.3.24
@angular-devkit/schematics        8.3.24
@angular/cli                      8.3.24
@ngtools/webpack                  8.3.24
@schematics/angular               8.3.24
@schematics/update                0.803.24
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Scully Version:**

<pre><code>

{
...
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@scullyio/init": "0.0.21",
    "@scullyio/ng-lib-v8": "latest", //0.0.63
    "@scullyio/scully": "latest", //0.0.15
    "bulma": "^0.8.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.21",
    "@angular/cli": "~8.3.21",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

</code></pre>

**Comment by SanderElias** [comment]
This is addressed by #266
