### ISSUE TITLE
use defined project prefix if set

### ISSUE THREAD

**Issue by d-koppenhagen** [scullyio/scully#27]
generating a blog using scully should use the defined app prefix from `angular.json` file instead of always `app`.

Running this:

```bash
ng g @scullyio/init:blog
```

... will currently always lead to this `blog.component.ts` file content:

```ts
...
@Component({
  selector: 'app-blog',
  ...
})
...
```

If a prefix is set in `angular.json` (path: `projects` => `<project name>` => `prefix`) it should be used by scully for setting it:

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  ...
  "projects": {
    "my-project": {
      ...
      "prefix": "foo",
    }
  }
}  
```

```ts
...
@Component({
  selector: 'app-blog',
  ...
})
...
```

**Comment by jorgeucano** [comment]
thanks for the issue! 
WIP in schematics/project-prefix

**Comment by jorgeucano** [comment]
fixed and merged :) thanks for report
