### ISSUE TITLE
Extend blog plugin to support multi-level folders

### ISSUE THREAD

**Issue by jorgeucano** [scullyio/scully#270]
### Description

Currently, the blog only supports a flat folder for its content.
But if there is a very active blog, the user might want to
go for a structure like /blog/year/month/filename or even /blog/subject/year/month/day/filename
We need to extend the current plugin to support that.

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by Ant59** [comment]
This would be super-useful for documentation site too. I would like to be able to just copy all of my directory-structured Markdown to Scully, register a single route to point to it, and have Scully generate HTML for all the Markdown files at the correct paths.

**Comment by jorgeucano** [comment]
yes, thats the idea :) 
I finished the pr :) https://github.com/scullyio/scully/pull/290
