### ISSUE TITLE
Root route is not supported anymore

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#275]
### Description
I have routes list that looks like this: 
```
const routes: Routes = [
  { path: 'landing', pathMatch: 'full', loadChildren: () => import('./landing/landing.module').then(m => m.LandingModule) },
];
```
After upgrading to @scullyio/scully to 0.0.63 or 0.0.64 this page won't prerender anymore. I looked around source code and this specific line looked suspicious:
```
const handledRoutes = await addOptionalRoutes(
      unhandledRoutes.filter((r: string) => r && r.startsWith(baseFilter))
    );
```
Basically my route is getting filtered out by this because `''` is falsy. What was the intention of doing this check? Was it supposed to check for null or undefined? I can submit pull request just don't get inital context what falsy were expecting there? I would recommend doing explicit checks everywhere instead of relying on falsy. It's a bad practice imo.

#### 🔬 Minimal Reproduction
Read description.

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.0.0-rc.8
Node: 12.14.0
OS: linux x64

Angular: 9.0.0-rc.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>

0.0.64
</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by aaronfrost** [comment]
@SanderElias did you see this bug? We should consider taking care of it. It looks to be a legit oversite. We should also add a test for it. I bet that it will appear again and again and again. We need to add a default route to our sampleBlog. We need to get rid of the redirect on the `/` route. It should render something so that we can test what most apps will have. Most apps have that default route load something. @jorgeucano can you make the app have this default route and test that it works and doesn't get filtered out.

**Comment by SanderElias** [comment]
This is already solved, but I didn't pr it yet. It is on my agenda for today.
