### ISSUE TITLE
Wrong path to tsconfig: `could not find "src/tsconfig.app.json"`

### ISSUE THREAD

**Issue by d-koppenhagen** [scullyio/scully#279]
### Description

Scully will warn that it cannot find the file `src/tsconfig.app.json`.
This file is located in the root by default (after a fresh Angular CLI setup): `tsconfig.app.json`

#### 🔬 Minimal Reproduction

```
npm i -g @angular/cli@next
ng new example
cd example
ng add @scullyio/init
ng g @scullyio/init blog
npm run build -- --prod
npm run scully
npm run scully:serve
```

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 9.0.0-rc.14
Node: 10.14.0
OS: darwin x64

Angular: 9.0.0-rc.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.14
@angular-devkit/build-angular     0.900.0-rc.14
@angular-devkit/build-optimizer   0.900.0-rc.14
@angular-devkit/build-webpack     0.900.0-rc.14
@angular-devkit/core              9.0.0-rc.14
@angular-devkit/schematics        9.0.0-rc.14
@angular/cdk                      9.0.0-rc.9
@ngtools/webpack                  9.0.0-rc.14
@schematics/angular               9.0.0-rc.14
@schematics/update                0.900.0-rc.14
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/ng-lib": "^0.0.17",
...
"@scullyio/init": "^0.0.21",
"@scullyio/scully": "^0.0.64",
</code></pre>

## 🔥 Exception or Error

<pre><code>
...
servers available
Finding all routes in application.
We could not find "src/tsconfig.app.json". Using the apps source folder as source. This might lead to unpredictable results
Pull in data to create additional routes.
...
</code></pre>

**Comment by SanderElias** [comment]
Should be closed by #282
