### ISSUE TITLE
Allow blog content to use Angular components

### ISSUE THREAD

**Issue by tieppt** [scullyio/scully#286]
## 🧩 Feature request
Suppose we have Carousel component and in some blog post we want to render multiple images as a carousel.
### Description

We need some kind of custom [shortcode] to render Angular component in side blog content.

### Describe the solution you'd like

Gatsby use MDX format and parsing the content to wrap custom component.

**Comment by SanderElias** [comment]
There are multiple solutions for this. I would use a custom-element for the carousel, and then you can just inject the thing directly into your markdown. The custom element can be an Angular Element, or something framework agnostic. 

Another solution is to create a plugin that takes care of updating your shortcode to HTML during rendering. 
Yet another possibility is, monitor the content in your blog-component, and upgrade from there.

Depending on needs and demands, there are probably even more way's to solve this, and it is possible already. 
Perhaps I'm missing something in your question, so in that case, can you elaborate?
If not, can you close the question?

**Comment by tieppt** [comment]
For now, I think Web Component is best solution. But if we're using Angular Elements, the script bundle will slow down the performance.
Btw, I'll experiment fews more solutions.

**Comment by SanderElias** [comment]
I agree on the angular elements, but now version 9 is out, I expect the story there to improve rapidly. (at least that's one of my hopes!)
I will close this for now, because we have nothing actionable in here now. 
If you or someone else feels we need to readdress this, let us know and we will reopen the issue.
