### ISSUE TITLE
Navigating to / tries to load index.html from non existing location

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#298]
### Description
Navigating to a route `/` produces error because it tries to load `index.html` like `https://index.html` instead of using domain.

#### 🔬 Minimal Reproduction
I have a `/` route in my applcication where my landing is located. It loads great if it's the first page I am asking for, however when I try to navigate there from another page with a `routerLink` it fails to load.

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.0.2
Node: 12.14.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>

0.0.70
</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by jorgeucano** [comment]
@SanderElias @BlindDespair this is finish? We can close this?
