### ISSUE TITLE
Running ng add @scullyio/init a second time should not break the app

### ISSUE THREAD

**Issue by beeman** [scullyio/scully#30]
# Issue
When running `ng add @scullyio/init` a second time in the same app, it makes the same updates to `src/app/app.component.ts` (which breaks the app) and `src/polyfills.ts`. 

It's probably nice to add a check to see if the content already exists in those files and skip the addition if so ([here](https://github.com/scullyio/scully/blob/master/schematics/scully/src/ng-add/index.ts#L28) and [here](https://github.com/scullyio/scully/blob/master/schematics/scully/src/ng-add/index.ts#L37)).

**Comment by SanderElias** [comment]
Good find!, thanks for the PR.
