### ISSUE TITLE
Reloading page on / route leads to flickering

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#300]
### Description
I have a landing page on `/` route. It prerenders great, but when I refresh it flickers.
#### 🔬 Minimal Reproduction
Just create a route like this:
```
{ path: '', pathMatch: 'full', loadChildren: () => import('./landing/landing.module').then(m => m.LandingModule) },
```
Put some content there that would use `TransferStateService` and open the page.

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.0.2
Node: 12.14.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>

0.0.70
</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by msacket** [comment]
What about adding the `initialNavigation` flag to your router configuration.  

```
RouterModule.forRoot(routes, { initialNavigation: 'enabled’} )
```
That takes care of the flicker for me; however, using the `TransferStateService` may cause an additional flicker issue I'm not aware of.

**Comment by BlindDespair** [comment]
@msacket Thanks for an idea, but this issue was coming from TransferStateService for sure, please check my commit if you're interested.
