### ISSUE TITLE
Resetting state in TransferStateService is probably not the best idea

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#302]
I've been experimenting a little and to me the line:
```
/** reset the state, so new components will never get stale data */
    tap(() => this.stateBS$.next(undefined)),
```
Seems more like a source of flashing rather than improvement. Consider following structructe:
app.component (hosts `<route-outlet>`
  landing.component (hosts `<page-layout>`)
  about.component (hosts `<page-layout>`)

Then in page-layout.component there is a header, content projection and a footer. Each part gets content for itself from `TransferStateService`.
Now what happens when you go from landing to about is that components page-layout gets recreated but since data is not there yet at time of creation it will lead to flashing which looks really like bad UX. What I could do in my app to resolve this is put page-layout in app.component instead, but that limits flexibility, because then I cannot easily create a page that would need to have a different structure.

I think that `tap(() => this.stateBS$.next(undefined)),` should be dropped or somehow made configurable. Thing is that if the service won't clear state, I would be able to handle when I want to reset it myself. But this way it's a bit more tricky imo.

**Comment by SanderElias** [comment]
There will be no flash in the case you are describing. 
The filter in the `state$` prevents the `undefined` from prolongation into existing components.
Only when the routing is complete, new information might come in, and all interested parties will get an update. As the new route might update all levels in the app, this is exactly as designed.

**Comment by BlindDespair** [comment]
There is a flash, because component is initialized before TransferStateService gets the data, at least that's my impression so far, but I think you're right I should probably try to solve it from within my app somehow.

**Comment by BlindDespair** [comment]
After we talked in chat I decided to go with solution I mentioned in original description, that I will move common parts outside of `router-outlet` and prevent rerendering of those completely. To achieve flexibility nested empty path `router-outlet can be used`. Example config:
```
[{
 path: '',
 component: PageLayout,
 children: [
    { path: '', pathMatch: 'full', loadChildren: () => import('./landing/landing.module').then(m => m.LandingModule) },
    { path: '404', loadChildren: () => import('./not-found/not-found.module').then(m => m.NotFoundModule) },
 ]
},
{ path: 'login', loadChildren: () => import('./login/login.module').then(m => m.LoginModule) },
{ path: '**', redirectTo: '404' },
]
```
Then in `app.component` only `<router-outlet>` would sit while in `page-layout` `<router-outlet>` would be wrapped with extra content
