### ISSUE TITLE
ScullyRoutesService observables filtering for wrong property

### ISSUE THREAD

**Issue by mchl18** [scullyio/scully#316]
### Description

When trying to use ScullyRoutesService observables such as `available$` or `unPublished$` it seem that there are two different property names being used for telling wether a post is published or not.

e.g. `ScullyRoutesService`

```
...
 available$ = this.allRoutes$.pipe(
    map(list => list.filter(r => (r.hasOwnProperty('published') ? r.published !== false : true))),
    shareReplay({refCount: false, bufferSize: 1})
  );
...
```

Looking at the JSON of the produced `scully-routes.json` however I found that this property in fact is called `publish`. As a consequence of this all posts are always available.

#### 🔬 Minimal Reproduction

Actually this is reproducible with the most basic setup:

1. Create project with scully as described in: https://github.com/scullyio/scully/blob/master/docs/getting-started.md
2. Create a post: `ng g @scullyio/init:post --name="This is my post"`
This post should be created with `publish: false`
3. Subscribe to `ScullyRoutesService.available$`. Despite not being published it is being shown in the list.

#### 💻Your Environment

**Angular Version:**

```
Angular CLI: 9.0.2
Node: 10.16.3
OS: darwin x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.2
@angular-devkit/build-angular              0.900.2
@angular-devkit/build-ng-packagr           0.900.2
@angular-devkit/build-optimizer            0.900.2
@angular-devkit/build-webpack              0.900.2
@angular-devkit/core                       9.0.2
@angular-devkit/schematics                 9.0.2
@angular/cli                               9.0.2
@angular/http                              7.2.16
@ngtools/webpack                           9.0.2
@nguniversal/express-engine                v8.2.6
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        9.0.2
@schematics/update                         0.900.2
ng-packagr                                 9.0.1
rxjs                                       6.5.4
typescript                                 3.7.5
webpack                                    4.41.2

```
**Scully Version:**

```
    "@scullyio/init": "0.0.23",
    "@scullyio/ng-lib": "0.0.18",
    "@scullyio/scully": "0.0.75",
```

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by SanderElias** [comment]
@mchl18 I'm going to look deeper into this before I will merge your PR.
I see your issue. However, the current setup is working in our tests. I want to know why, before I'll merge your pr.

**Comment by mchl18** [comment]
I just set this Pr up in kind of a rush. I wanna dig deeper into this and maybe even write some tests for the angular service

**Comment by SanderElias** [comment]
Your PR is merged, so I'm going to close the issue.
Turned out, the schematics where out of sync, and that was not where I was looking.
