### ISSUE TITLE
Put routed pages in folders

### ISSUE THREAD

**Issue by MagnusBrzenk** [scullyio/scully#321]
### Description

Went through the intro example. Surprised to see that the output routed pages are not put into folder of same name. This means that if I serve my site from a file server like apache and enter the site from a routed page, then apache will look for a folder of that name, not find it, and fail. I can fix that with apache rewrite rules, but I was hoping scully would save me that hassle. I expected this to be the default behavior. If outputting routed pages to folders  is supported, then I didn't see how in my brief scan through your documentation. 

### Describe the solution you'd like

I expected output to folders of the route name to be the default behavior. 

### Describe alternatives you've considered

Apache rewrite rules.

**Comment by SanderElias** [comment]
@MagnusBrzenk If I understand you correctly you are saying that the output files are not matching the routes?
Here is an example output of tree in the static folder. Can you use that to explain your issue to me?
![image](https://user-images.githubusercontent.com/1249083/75235470-972d0680-57bc-11ea-934e-cc3f8342cbc9.png)

**Comment by MagnusBrzenk** [comment]
Agh. Apologies. It is using folders. Not sure how I missed it! Thanks.
