### ISSUE TITLE
[Documentation] Missing Code of Conduct

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#322]
### Description

The Code of Conduct is missing from the Contribution guidelines

### Describe the solution you'd like

I know the addition of the Code of Conduct is planned before the end of the alpha phase of the development as stated [here](https://github.com/scullyio/scully/blob/master/docs/CODE_OF_CONDUCT.md) but it might be useful to add a default one as the [Contribution Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct/) at least.

I might make a PR and  would just need contact information for the PR for this part :  
`
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at [INSERT CONTACT METHOD]. All complaints will be reviewed and investigated promptly and fairly.
`

**Comment by SanderElias** [comment]
@aaronfrost I would say yes, but I want your opinion hee too
