### ISSUE TITLE
Load statics from md using angular serve

### ISSUE THREAD

**Issue by sandyeveliz** [scullyio/scully#33]
This is more a enhancement

When the app is running with the angular serve does not load the static content, only after runing with scully it works fine.
I think this is expected in alpha, but to improve the development of a blog or any content page based on MD it would be good to also load the statics from Angular.

Running the up with 

> npm run scully serve

works fine
![image](https://user-images.githubusercontent.com/29709496/70949568-e2989b00-203c-11ea-85e3-81c61f95a92d.png)

But runing with angular  

> ng serve 

dosn't show the static content in the markdown

![image](https://user-images.githubusercontent.com/29709496/70949643-15429380-203d-11ea-8829-718d0b62988d.png)

**Comment by SanderElias** [comment]
I'm going to close this for now. 
`ng serve` is using its own virtual, in-memory, file-system to serve the files for your app in development.
There is no way to access that we know of. 
Then there is this issue that Scully is designed to work with actual files.
Still, we have a planned feature, where Scully watches, a single blog file, and updates it in the browser as soon as you update the markdown, (or as you rebuild the angular app)
This is planned _after_ the first beta drop for now.

**Comment by wenqi73** [comment]
I also faced this issue now, rebuilding takes a bad development experience. The `<scully-content></scully-content>` will render page through `location.href`, maybe could generate the blog static files also in Angular `assets` in some way? Then it will be rendered during `ng serve`. Finally, thank you for building this library!
