### ISSUE TITLE
Add meta tag "generator" in the header of the generated html files

### ISSUE THREAD

**Issue by webbegg** [scullyio/scully#331]
### Description

Add the meta tag ```<meta content="Scully {{scully_version}}" name="generator" /> ``` to the generated html files on building time. The meta tag is mainly used for statistics on the use of the frameworks.

**Comment by SanderElias** [comment]
@aaronfrost, @jorgeucano May I have your votes, please?

**Comment by SanderElias** [comment]
This is done in pr #355
