### ISSUE TITLE
Rename event `AngularReady` to `ScullyReady`

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#337]
## 🧩 Feature request

Rename the idleMonitorService from `AngularReady` to `ScullyReady`. 

### Description

Rename `AngularReady` to `ScullyReady` from `IdleMonitorService` to something else. Once done, re-deploy 

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by aaronfrost** [comment]
May need to release 0.1.0 as this will break the API.

**Comment by SanderElias** [comment]
@aaronfrost its not a breaking feature. However, the events signal that angular is ready, and Scully can begin scraping. O can rename iff you want, but the name would not cover the intention anymore.
