### ISSUE TITLE
ScullyServer keeps running even though I quit it with Cmd + C or "q"

### ISSUE THREAD

**Issue by juristr** [scullyio/scully#339]
### Description

I run Scully with `yarn scully`. If I press "q" (or even Cmd + C) the shell exists

![image](https://user-images.githubusercontent.com/542458/75614287-74da1680-5b37-11ea-80e6-7899c9c5f471.png)

But the page is still being served at `http://localhost:1864/`. And in fact, ScullyServer seems to still run

![image](https://user-images.githubusercontent.com/542458/75614299-9affb680-5b37-11ea-8787-093819356c31.png)

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.0.4
Node: 12.14.0
OS: darwin x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/init": "^0.0.23",
"@scullyio/ng-lib": "latest",
"@scullyio/scully": "latest",
</code></pre>

**Comment by aaronfrost** [comment]
Same issue here: 
![image](https://user-images.githubusercontent.com/662832/75643873-8f76c300-5bfd-11ea-83ea-a405e2648e94.png)

**Comment by SanderElias** [comment]
This should be closed by pr #349.
Please let us know if the problem persists. (Give us a day to release the latest version to NPM)
