### ISSUE TITLE
Enable `manualIdleDetection` per route, instead of only global

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#345]
## 🧩 Feature request
We need a way that people can only do a per-route manualIdleDetection

### Description

It would be nice to be able to opt into manualIdleDetection for only some of my routes. The current global setting is cool, but if only one route needs it, I don't want to have to manually wire up all of my routes to report that they are fully ready. 

So it would be nice to have a way to only turn it on per route. 

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 
Make a postRenderer that will add a global when my route config is set. And then modify the `IdleMonitorServer` to look for the global.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by SanderElias** [comment]
Will be closed by pr #344
