### ISSUE TITLE
Large sites and incremental builds

### ISSUE THREAD

**Issue by panakour** [scullyio/scully#363]
Does scully support incremental builds? to resolve issues that exists in other SSG like gatsbyjs https://github.com/gatsbyjs/gatsby/issues/9083

**Comment by SanderElias** [comment]
It does support partial builds right now. 
Can you explain what you mean by incremental builds?

**Comment by panakour** [comment]
@SanderElias  With Incremental builds I mean to prevent rebuilds the entire site (all the pages) each time run scully. For example let's say that we have a blog site with its categories and pagination. After scully run the first time will generate all the pages. Then I run again the scully after 1 hour to add my new article or updated one. This time I want from the scully to generate only the necessary pages to add this new article only. 

I know this is not that easy to implement.

**Comment by SanderElias** [comment]
@panakour For a blog with physical files, it's actually not that hard, and if you enter watch mode, it will just generate the updated blog file(s) already. 
However, when your restart, right now, yes it has to regenerate everything, as we have no way of knowing what has updated.
Right now you can manually use the --baseFilter option to just generate a single unhandled route. 
on the plan board is a way to filter handled routes. 
Monitoring changes between builds is out of our scope for now. We might offer a SAAS service for that in the future.

**Comment by panakour** [comment]
@filipwiniarski  thank you for your approach. for my use case (50k pages) only [hugo](https://github.com/gohugoio/hugo) can handle. No gatsby nor scully.

**Comment by SanderElias** [comment]
@panakour We now have a Scully Platform Server renderer.
With this, on my system, I can render ~100 pages a second.
Also, take a look at our roadmap. we are going to have some helpers in the future. How far away in the future is depending on how much funding we can raise. 
50K pages not going to be a big problem, but right now, it needs some extra work.
