### ISSUE TITLE
Move ScullyIO-transfer-state to footer (SEO)

### ISSUE THREAD

**Issue by MikeOne** [scullyio/scully#365]
## 🧩 Feature request

Move ScullyIO-transfer-state to footer (SEO)

### Description

At the moment, the ScullyIO-transfer-state script block in the generated HTML lives in the header of the page. With large data blocks, this means the actual readable content on the page (content interesting for the Google spider for example) - starts way lower in the DOM. I think this is also the reason why Transfer-State in Universal is actually appended just before \</htm\>.

### Describe the solution you'd like

Move ScullyIO-transfer-state to just before \</html\>

### Describe alternatives you've considered

Can't think of an alternative for this.

**Comment by MikeOne** [comment]
After doing some more research and finding this marvellous new feature that puts the transferstate also in data.json, I'd like to expand on this feature request and also request to add a flag that completely removes the ScullyIO-transfer-state from the DOM...

**Comment by SanderElias** [comment]
I need the Scully variables to exist before the angular app gets loaded, so I can't really move it to just before the </html> But I will move it down quite a bit.

**Comment by MikeOne** [comment]
Yes - that'll be excellent. ignore the remove request - I initially thought that it would request data.json always - but it doesn't on a hard load so the current solution is the best!

**Comment by aaronfrost** [comment]
Great issue @MikeOne. Thanks for helping out.
