### ISSUE TITLE
Add a .hasKey method on the transferStateService

### ISSUE THREAD

**Issue by MikeOne** [scullyio/scully#366]
## 🧩 Feature request

Add a .hasKey method on the transferStateService

### Description

At the moment there is no (straight-forward) way to find out if the transferState has a certain key set. In order to determine in Services if an actual request to an API should be done, it would be beneficial to be able to check the transferState for the existence of the key.  

### Describe the solution you'd like

Add a .hasKey(name) method to the transferStateService (identical to what Universal TransferState provides).

### Describe alternatives you've considered

Technically I could just do a try on getState(name) and test for a fail...

**Comment by SanderElias** [comment]
```typescrpt
const hasKey = (key) => getState(key)!==undefined
```
I'll add a method for that, as it can save a few keystrokes while using Scully.
