### ISSUE TITLE
Unable to render any blog pages because of some error

### ISSUE THREAD

**Issue by AhsanAyaz** [scullyio/scully#368]
## 🐞 Bug report
With a fresh project, upon adding the blog support and creating a post, I'm unable to get it to work with the commands mentioned in the docs.
### Description
The problem seems to be only on my machine. **It doesn't work on my machine 🤷‍♂ ** is something you rarely hear. Lol.
Here's my repository:
https://github.com/ahsanayaz/ngJam

#### 🔬 Minimal Reproduction
I'm not sure if you can reproduce this, but...
- Clone the repository
- `npm i`
- `npm run build && npm run scully`
- check http://localhost:1668/blog/ahsan-ayaz

This is what I get:
![image](https://user-images.githubusercontent.com/9844254/76211978-b8074a00-6207-11ea-8d69-c7a2c804e1ef.png)

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.0.5
Node: 12.13.1
OS: darwin x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/scully": {
      "version": "0.0.79",
}
"@scullyio/init": {
      "version": "0.0.23",
}
"@scullyio/ng-lib": {
      "version": "0.0.20",
}

</code></pre>

## 🔥 Exception or Error

<pre><code>

Pull in data to create additional routes.
Finding files in folder "/Users/ahsanayaz/Experiments/ngJam/blog"
Route list created in files:
  "/Users/ahsanayaz/Experiments/ngJam/src/assets/scully-routes.json",
  "/Users/ahsanayaz/Experiments/ngJam/dist/static/assets/scully-routes.json",
  "/Users/ahsanayaz/Experiments/ngJam/dist/ngJam/assets/scully-routes.json"

Route "/" rendered into file: "/Users/ahsanayaz/Experiments/ngJam/dist/static/index.html"
Route "/blog" rendered into file: "/Users/ahsanayaz/Experiments/ngJam/dist/static/blog/index.html"
Error, probably missing "<scully-content>" for /Users/ahsanayaz/Experiments/ngJam/blog/ahsan-ayaz.md
TypeError: Cannot read property 'split' of undefined
    at contentRenderPlugin (/Users/ahsanayaz/Experiments/ngJam/node_modules/@scullyio/scully/renderPlugins/contentRenderPlugin.js:21:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async wrap (/Users/ahsanayaz/Experiments/ngJam/node_modules/@scullyio/scully/pluginManagement/pluginRepository.js:63:18)
    at async /Users/ahsanayaz/Experiments/ngJam/node_modules/@scullyio/scully/renderPlugins/routeContentRenderer.js:16:24
Route "/blog/ahsan-ayaz" rendered into file: "/Users/ahsanayaz/Experiments/ngJam/dist/static/blog/ahsan-ayaz/index.html"
Error during file write TypeError: Cannot read property 'includes' of undefined
send reload

Generating took 27.49 seconds for 3 pages:
  That is 0.11 pages per second,
  or 9164 milliseconds for each page.

  Finding routes in the angular app took 2 milliseconds
  Pulling in route-data took 16 milliseconds
  Rendering the pages took 25.77 seconds

The server is available on "http://localhost:1668/"
</code></pre>

**Comment by jorgeucano** [comment]
@AhsanAyaz 
I clone your project and build fine for me in windows and mac 
@SanderElias clone and test in ubuntu and work fine to!

Can you create another project and check all again? we can not reproduce the error!

**Comment by SanderElias** [comment]
When I open the link after building without issue: 
![image](https://user-images.githubusercontent.com/1249083/76230113-843a1d80-6223-11ea-916c-96318e4f73ff.png)

I'm sorry, but I don't have any idea what this can be, it seems something on your computer.
What you can try is:
```shell
rm -fr node_dist
npm i
rm -fr dist
npm run build && npm run scully
```
 Or perhaps power-cycle your computer?

Can you let us know the progress on that?

**Comment by jorgeucano** [comment]
hey @AhsanAyaz I will close this, if you need more help or you're still with the same issue, you can reopen this one or create a new issue

**Comment by AhsanAyaz** [comment]
Sure. Thanks @jorgeucano
