### ISSUE TITLE
Create better docs and update styles

### ISSUE THREAD

**Issue by jorgeucano** [scullyio/scully#377]
For support the web, we need update all the .MD files from the DOCS folder.

List: 

- [ ]  blog
- [ ]  CODE_OF_CONDUCT
- [ ]  getting-started
- [ ] getting-started_es
- [ ] issues
- [ ] learn
- [ ] plugins
- [ ] polyfills
- [ ] pre-requisites
- [ ] recommended-plugins
- [ ] release-for-v8
- [ ] scully
- [ ] scully-cmd-line
- [ ] scully-configuration
- [ ] scully-lib-core
- [ ] showcase
- [ ] utils

**Comment by jorgeucano** [comment]
@GuzmanPI is the person in charge of this.
Israel you can put some tips in case someone wants to collaborate.
@Villanuevand please talk with Israel for work together.

**Comment by geromegrignon** [comment]
I'll help if needed

**Comment by GuzmanPI** [comment]
Thx @geromegrignon I'll add the requirements for the docs to be considered as completed ASAP here, and then we can talk in Gitter for the details

**Comment by GuzmanPI** [comment]
Language requirenments:

- [ ] correct grammar both in English and Spanish
- [ ] formal language. In other words no slang, use the "you" pronoun

Style requirenments:

- [ ] Spaces between paragraphs, hedears, links and lists. Use 8px increments where 16px = 1rem
Note: Ignore the space undeaneath the code card, becaus I will fix the the component. Hence, fixing all those spaces."

**Comment by jorgeucano** [comment]
@GuzmanPI Can you tell us about the progress?

**Comment by GuzmanPI** [comment]
Almost half of the docs are done, and I'll be done with the rest today.

**Comment by GuzmanPI** [comment]
This has been finished.
