### ISSUE TITLE
Pressing "r" or "q" in `scully` does nothing MacOS

### ISSUE THREAD

**Issue by crutchcorn** [scullyio/scully#379]
## 🐞 Bug report

When running `npm run scully`, I get the following message at the footer:

```
------------------------------------------------------------
Press r for re-run Scully, or q for close the servers.
------------------------------------------------------------
```

However, on my version of MacOS it does nothing and I have to use `Ctrl+C` to stop the execution.

#### 🔬 Minimal Reproduction

`npm run scully`, then try to press `r` or `q`

#### 💻Your Environment

- MacOS Mojave
- `@scullyio/scully@0.0.80`
- iTerm 2 `Build 3.3.10beta2`
- Node v12.9.0

**Angular Version:**

<pre><code>

Angular CLI: 9.0.6
Node: 12.9.0
OS: darwin x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "0.0.23",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</code></pre>

**Comment by MikeOne** [comment]
I can confirm that *sometimes* it doesn't work. For me it usually works fine. Expect when you accidentally hit CTRL-C in that terminal window (which happens to me quite a lot). Then Q and R consistently stops working.

**Comment by jorgeucano** [comment]
thanks for the report... Is happening in the first time only ??? or when you have some re-runs ??
Im trying to get more information for reproduce this case!

**Comment by MikeOne** [comment]
For me - it happens everytime when I hit CTRL-c in the scully terminal window..

**Comment by jorgeucano** [comment]
Ok, thanks for this! I will work now... If you have another information please add here

**Comment by jorgeucano** [comment]
Done, waiting for new build :) ..

**Comment by jorgeucano** [comment]
@crutchcorn & @MikeOne We published a new version :) ... Please check if work for you :D If you have any problem please reopen this issue
