### ISSUE TITLE
Defualt created app throws error at build time

### ISSUE THREAD

**Issue by BrsJsk** [scullyio/scully#419]
## 🐞 Bug report
I've got interested in Scully and decided to check it out.

### Description
I've followed these steps:
https://www.netlify.com/blog/2019/12/16/introducing-scully-the-angular-static-site-generator/
Everything was fine until it came to ng build which threw an error
#### 🔬 Minimal Reproduction
https://github.com/BrsJsk/scully-test-app
#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 8.3.25
Node: 12.14.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/ng-lib-v8": "latest",
 "@scullyio/scully": "latest",

</code></pre>

## 🔥 Exception or Error

<pre><code>
ERROR in src/app/app.module.ts:6:33 - error TS2307: Cannot find module '@scullyio/ng-lib'.

6 import { ScullyLibModule } from '@scullyio/ng-lib';
</code></pre>

**Comment by geromegrignon** [comment]
There is a bug to fix but you can make it work changing the import into your AppModule file so it matchs the dependancy :

```
import { ScullyLibModule } from '@scullyio/ng-lib-v8'
```

BUG : 

The [add schematic](https://github.com/scullyio/scully/blob/master/schematics/scully/src/ng-add/index.ts) doesn't check the angular version for the `ScullyLibModule ` import added into the AppModule file as the name of the dependancy changes depending on the angular version.

**Comment by BrsJsk** [comment]
Tried that..worked but now theres a new problem..
```
Generating ES5 bundles for differential loading...
An unhandled exception occurred: [BABEL] C:\Users\Lenovo8gen\Documents\gitlab\mallot-scully\dist\mallot-scully\blog-blog-module-es2015.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "C:\\Users\\Lenovo8gen\\Documents\\gitlab\\mallot-scully\\node_modules\\@babel\\preset-env\\lib\\index.js")
See "C:\Users\LENOVO~1\AppData\Local\Temp\ng-PzsN0m\angular-errors.log" for further details.
```

**Comment by geromegrignon** [comment]
Add `"@babel/compat-data": "7.8.0"` to your devDependancies.
Here is a [related issue](https://github.com/angular/angular-cli/issues/17262) on angular/cli repo.

**Comment by jorgeucano** [comment]
Hey, we check the Angular version, I will download your project and test
