### ISSUE TITLE
`ng g @scullyio/init:post`: Special characters cause failure during render

### ISSUE THREAD

**Issue by andrewhdev** [scullyio/scully#425]
### Description
I created a blog post with parenthesis in the title, example: "This is a test (with parenthesis)". Whenever I run "npm run scully" It takes a long time and then I see this error:

```bash
Error, probably missing "<scully-content>" for /Users/andrewhinton/Documents/Dev/projects/test-blog/blog/this-is-a-test-(with-parenthesis).md
TypeError: Cannot read property 'split' of undefined
    at contentRenderPlugin (/Users/andrewhinton/Documents/Dev/projects/test-blog/node_modules/@scullyio/scully/renderPlugins/contentRenderPlugin.js:21:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async wrap (/Users/andrewhinton/Documents/Dev/projects/test-blog/node_modules/@scullyio/scully/pluginManagement/pluginRepository.js:69:18)
    at async /Users/andrewhinton/Documents/Dev/projects/test-blog/node_modules/@scullyio/scully/renderPlugins/routeContentRenderer.js:16:24
Route "/blog/this-is-a-test-(with-parenthesis)" rendered into file: "/Users/andrewhinton/Documents/Dev/projects/test-blog/dist/static/blog/this-is-a-test-(with-parenthesis)/index.html"
Error during file write TypeError: Cannot read property 'includes' of undefined
send reload

Generating took 28.85 seconds for 3 pages:
  That is 0.11 pages per second,
  or 9618 milliseconds for each page.
  
  Finding routes in the angular app took 0 milliseconds
  Pulling in route-data took 1 milliseconds
  Rendering the pages took 25.86 seconds

The server is available on "http://localhost:1668/"
------------------------------------------------------------
Press r for re-run Scully, or q for close the servers.
------------------------------------------------------------
```

#### 🔬 Minimal Reproduction

```bash
ng new test-blog
cd test-blog
ng add @scullyio/init
ng g @scullyio/init:blog
ng g @scullyio/init:post --name="This is a test (with parenthesis)" —target=“blog”
npm run build
npm run scully
```

#### 💻Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.7
Node: 10.19.0
OS: darwin x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.4
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Scully Version:**
<pre><code>

"@scullyio/init": "0.0.23",
"@scullyio/ng-lib": "0.0.21",
"@scullyio/scully": "0.0.82",
</code></pre>

## 🔥 Exception or Error

<pre><code>

Error, probably missing "<scully-content>" for /Users/andrewhinton/Documents/Dev/projects/test-blog/blog/this-is-a-test-(with-parenthesis).md
TypeError: Cannot read property 'split' of undefined
    at contentRenderPlugin (/Users/andrewhinton/Documents/Dev/projects/test-blog/node_modules/@scullyio/scully/renderPlugins/contentRenderPlugin.js:21:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async wrap (/Users/andrewhinton/Documents/Dev/projects/test-blog/node_modules/@scullyio/scully/pluginManagement/pluginRepository.js:69:18)
    at async /Users/andrewhinton/Documents/Dev/projects/test-blog/node_modules/@scullyio/scully/renderPlugins/routeContentRenderer.js:16:24
Route "/blog/this-is-a-test-(with-parenthesis)" rendered into file: "/Users/andrewhinton/Documents/Dev/projects/test-blog/dist/static/blog/this-is-a-test-(with-parenthesis)/index.html"
Error during file write TypeError: Cannot read property 'includes' of undefined
send reload

Generating took 28.85 seconds for 3 pages:
  That is 0.11 pages per second,
  or 9618 milliseconds for each page.
  
  Finding routes in the angular app took 0 milliseconds
  Pulling in route-data took 1 milliseconds
  Rendering the pages took 25.86 seconds

The server is available on "http://localhost:1668/"
------------------------------------------------------------
Press r for re-run Scully, or q for close the servers.
------------------------------------------------------------

</code></pre>

**Comment by SanderElias** [comment]
I checked out this issue. What happens is that Angular itself fails on parsing routes with `()`.

![image](https://user-images.githubusercontent.com/1249083/77558858-bf8f4a00-6ebb-11ea-9765-2abd729b67d7.png)
It produces the above error and redirects to home (where there is no `<scully-contetn>`) 

So, it turns out that Scully works well, but Angular fails in this case. 
@jorgeucano Can you add the `()` to the function that cleans out unwanted chars in the schematic for this?
