### ISSUE TITLE
scanRoutes error (Puppeteer error while rendering "d2020-03-26-articles" Protocol error (Page.navigate))

### ISSUE THREAD

**Issue by wickstargazer** [scullyio/scully#427]
## 🐞 Bug report
I am getting this error when running `yarn scully --scanRoutes`
`Puppeteer error while rendering "d2020-03-26-articles" Error: Protocol error (Page.navigate): Cannot navigate to invalid URL`

#### 🔬 Minimal Reproduction

```
exports.config = {
  projectRoot: "./src/app/<projectname>/app/src",
  distFolder: "./dist/apps/<projectname>",
  outDir: "./dist/static/apps/<projectname>",
  routes: {
    '/home/:article': {
      type: 'contentFolder',
      article: {
        folder: "./content"
      }
    }
  }
};
```

#### 💻Your Environment
OSX

**Angular Version:**
`^8.2.0`

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.23
Node: 12.16.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.23
@angular-devkit/build-angular              0.803.23
@angular-devkit/build-ng-packagr           0.803.25
@angular-devkit/build-optimizer            0.803.23
@angular-devkit/build-webpack              0.803.23
@angular-devkit/core                       8.3.23
@angular-devkit/schematics                 8.3.23
@angular/cdk                               8.2.3
@angular/cli                               8.3.23
@angular/http                              7.2.16
@angular/material                          8.2.3
@angular/material-moment-adapter           8.2.3
@angular/service-worker                    8.2.12
@ngtools/webpack                           8.3.23
@nguniversal/common                        8.2.6
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.23
@schematics/update                         0.803.23
ng-packagr                                 5.7.1
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2
</code></pre>
``

<pre><code>

"@scullyio/ng-lib-v8": "latest"

</code></pre>

## 🔥 Exception or Error

<pre><code>

Puppeteer error while rendering "d2020-03-26-articles" Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
Puppeteer error while rendering "dwho-is-new" Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
Puppeteer error while rendering "d2020-03-26-articles" Error: Protocol error (Page.navigate): Cannot navigate to invalid URL

</code></pre>

**Comment by SanderElias** [comment]
I Can not reproduce this.
One thing that might be in issue is that your distfolder should be a subfolder of 'dist', not the 'dist' folder itself. That is a setting you can change in `angular.json`

Can you provide a git (or other) repo so we can reproduce your error?

**Comment by wickstargazer** [comment]
Yes i got that correct, i actually edit and remove my project path in the issue description and also that i am using nx workspace

**Comment by SanderElias** [comment]
@wickstargazer I'm still unable to reproduce your issue.
Please provide a way for us so we can, otherwise, it is impossible to help

**Comment by SanderElias** [comment]
@wickstargazer I finally was able to reproduce. This happened when the start of the route and the start of the folderPath were different. Fixed this bug
Pushed out an update to NPM (v0.0.85) that will fix this.

**Comment by wickstargazer** [comment]
Thats awesome coz using with nx is the whole idea, good catch sorry couldn’t response, havent had time to get back to it! Will look at it and publish soon!
