### ISSUE TITLE
Problem with base-href

### ISSUE THREAD

**Issue by dominika-zajac** [scullyio/scully#429]
## 🐞 Bug report

After building an angular app with base-href flag, value from that flag is ignored when importing /assets/scully-routes.json.

#### 🔬 Minimal Reproduction
ng build --prod --base-href=/prefix/ --deploy-url=/prefix/
npm run scully
check in browser from assets/scully-routes.json is imported - link should contains prefix

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 9.1.0
Node: 10.16.3
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Scully Version:**
<pre><code>
"@scullyio/init": "0.0.23",
</code></pre>

## 🔥 Exception or Error
404 error on GET <domain>/assets/scully-routes.json (should call  <domain>/<base-href>/assets/scully-routes.json

**Comment by MikeOne** [comment]
So are you trying to load or reference the scully-routes.json file from your app? I actually don't think that scully needs to do anything with base href. Links to assets inside your HTML (images etc) should be done without the initial slash I believe - the browser will then take care of prepending the path from base href. If you're are trying to get a json file from that assets folder using a http.get, you'll have to sort out the base href yourself (probably through environment or something) - but that really is unrelated to Scully as Angular also doesn't do anything with your service URL's as far as I understand it. You'll have to resolve this yourself (for example: http://www.projectcodify.com/angular-set-base-url-dynamically)

**Comment by dominika-zajac** [comment]
OK, thank you for the response.

**Comment by dominika-zajac** [comment]
Hi, I check that again and to use angular logic you need links in form like './assets/...' -> in your source code it's '/assets/...' (without trailing dot). I believe it causes the issue

**Comment by SanderElias** [comment]
@dominika-zajac I'll will add a test and a fix for this shortly.
