### ISSUE TITLE
scully serve not working inside windows 10

### ISSUE THREAD

**Issue by mbaljeetsingh** [scullyio/scully#43]
I have run `ng build` & `npm run scully`

# 🐞 npm run scully:serve not working or start the server

### When I run npm run scully:serve, it shows starting static server..., but then it stops automatically.
![image](https://user-images.githubusercontent.com/872762/71020686-cc650a80-2122-11ea-849f-ba2a4e20edfd.png)Description

## 💻Your Environment 
**Angular Version:**
![image](https://user-images.githubusercontent.com/872762/71020856-1cdc6800-2123-11ea-8dec-8d9275cc1312.png)

** Scully Version:**
`0.0.8`

**Comment by jorgeucano** [comment]
Hello @mbaljeetsingh im working on windows 10! 
For scully you need an angular 9 project! 
Can you tell me what steps you try?
This is one example in windows 10
![Annotation 2019-12-17 154453](https://user-images.githubusercontent.com/5982204/71024695-44601000-20e4-11ea-8a5d-4639ffcbaa7b.png)

**Comment by mbaljeetsingh** [comment]
Hi @jorgeucano 

Yes, I'm using it inside the Angular 9 project.

Steps I have taken are as follows:

- npx @angular/cli new scully-project --routing --style=scss
- ng add @scullyio/init
- ng build
- npm run scully
- npm run scully:serve

**Comment by robertbaker** [comment]
From the screenshots displaying your version, you using v8, not v9

**Comment by mbaljeetsingh** [comment]
> From the screenshots displaying your version, you using v8, not v9

Oh yeah, This is because, I haven't used the global cli for the scully demo project, I just npx to create create project.

Here's the package.json screenshot,
![image](https://user-images.githubusercontent.com/872762/71064671-a4fb5580-2195-11ea-922e-b1408e2c94aa.png)

**Comment by jorgeucano** [comment]
@mbaljeetsingh `npm run scully` just show this and never finish?

**Comment by mbaljeetsingh** [comment]
`npm run scully` runs successfully, but getting some weird error at the end.

> ERROR: The process "6208" not found.

![image](https://user-images.githubusercontent.com/872762/71088363-38e41600-21c4-11ea-8382-45d90e13ae98.png)

**Comment by jorgeucano** [comment]
ohhh ok, is not an error really @mbaljeetsingh , we are killing the process and for this show this `error`, now we are in alpha and for this you see this error.
We are working and focus in other place now, after finish some task, we will work in this `error`!
So if this the unique "error" you have, please tell me and close this issue :) 

thanks!

**Comment by mbaljeetsingh** [comment]
Alright, Yes the build is successful with `npm run scully`.
Actually, this issue is related to `npm run scully:serve`. Can you share how it works?

**Comment by jorgeucano** [comment]
Scully serve is for create 2 servers
the first server is a http server with the scully compile version.
the second server is a http server with the angular build version.

We found a bug when try to run the serve and you have a gost process...
So please, Can you try to start the `npm run scully:serve` and if dont run anything check in your task manager if you have any node process running, if you have, please kill the process and try again to run `npm run scully:serve` and check if work!

thanks

**Comment by SanderElias** [comment]
@mbaljeetsingh As @jorgeucano explained, we are still in alpha.
There are a number of issues with `scully serve` which we are already addressing. 
You issue is one of them. We expect to have this fixed in one or two days.
`Scully serve` in meant to be a developer tool so you can try the results of scully without any 3rth party tool. 
Also, we are using it to 'serve' your distribution files, so we can run our generator against it. That is the reason  it opens up 2 ports (when all fixes are in)

I assume I answered all your questions, and will close the issue now.
When you want to know more, feel free to add in more comments on the closed issue, and I will make sure I'll answer those.
