### ISSUE TITLE
Initial Dialog persists

### ISSUE THREAD

**Issue by KreLou** [scullyio/scully#432]
## 🐞 Bug report
Intital Mat-Dialog closes but the same dialog persists.

### Description
I have an intital dialog which will promt on first visit. By clicking [OK] a flag will set atthe localStorage and prevent this dialog again.
But on static pages the closing animation occurs but the dialog persist and is unable to close.

This method (handlePageVisit()) will called in the NgOnInit() of the app.component.ts.

#### 🔬 Minimal Reproduction
<code>
  private isAgeOK(): boolean {
    return localStorage.getItem('agecheck') != null;
  }

  constructor(private dialoag: MatDialog) { }

  public handlePageVisit() {
    if (this.isAgeOK()) return;

    const dialoagRef = this.dialoag.open(AskVisitorForAgeCheckComponent, {
      width: '450px',
      disableClose: true,
      backdropClass: 'blur-background'
    });
    dialoagRef.afterClosed().subscribe((result: boolean) => {
      if (result && result === true) {
        localStorage.setItem('agecheck', (new Date()).toString());
      } else {
        //this.window.close();
      }
    });
</code>
ng build --prod
npm run scully

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 9.0.7
Node: 10.13.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.2.0
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.0
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "0.0.23",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",

</code></pre>

## 🔥 Exception or Error
---
<pre><code>

</code></pre>

**Comment by MikeOne** [comment]
My guess is that this is not actually a Scully 'bug'. What happens here I think is that when Scully runs - it does not find the localStorage flag - so it will trigger the dialog. This dialog is then rendered in the static page as HTML - but the reference to the dialog is orphaned (so it can no longer be closed). The solution to this is probably to check if Scully is running - and if it is - to not run the dialog logic. 

To check if Scully is running you can import the isScullyRunning() function. If that function returns true - you return the isAgeOkay flag as true as well (to prevent the dialog).

**Comment by aaronfrost** [comment]
Yeah. I agree with @MikeOne this isn't a Scully bug. @KreLou in your code that opens the dialog, you need to add the following:

```typescript
if(!isScullyRunning()){
    // put code here to open dialog
}
```

This will prevent the phantom dialog from being added to the page during pre-render. And once the Angular app loads, it can open the dialog properly.

**Comment by aaronfrost** [comment]
I am going to close this for now. If @KreLou disagrees and has some additional information, I am more than willing to reopen this and get on a video chat to see how we can help.

**Comment by KreLou** [comment]
Thanks that helped.
