### ISSUE TITLE
Make watch mode optional

### ISSUE THREAD

**Issue by SanderElias** [scullyio/scully#434]
### Description

Right now, Scully defaults to have the watch mode on. 
this means that that in CI, and testing the run will hang unless the `--no-watch` flag is added.

In my opinion `npm run Scully` is more comparable to `ng build` as to `npm serve`
`ng build --watch`  has the same optional watch. 

This will make unpleasant surprises during automated deploy/test/.. less common.

 A clear and concise description of the problem or missing capability...

**Comment by d-koppenhagen** [comment]
I totally agree.
A good thing would be to re-introduce the `--watch` flag. And for an easy setup and a good developer experience add two npm scripts when running the schematics initially:

```json
{
  ...
  "scully": "scully",
  "scully:serve": "scully --watch"
}
```

**Comment by jorgeucano** [comment]
Waiting for the next deploy
