### ISSUE TITLE
Page that lists the happy users of Scully

### ISSUE THREAD

**Issue by mr-sige** [scullyio/scully#437]
Do you guys have or want to create a page where you can list all the happy users of scully? I totally want to be on that list.
Like what docusaurus does: https://docusaurus.io/en/users

I'm also happy to help.

**Comment by jorgeucano** [comment]
The page is Showcase :)

**Comment by phodal** [comment]
I had build in production with sitemap.xml, how can I join this? https://devops.phodal.com/home

**Comment by jorgeucano** [comment]
Please create a PR to /docs/showcase.md :)
