### ISSUE TITLE
New pages are prerendered as Cannot GET

### ISSUE THREAD

**Issue by BlindDespair** [scullyio/scully#438]
### Description
A while ago I experienced this problem, that when I create a new page in my angular app, scully fails to prerender it. First the new routes are not picked up by scully at all. I have to delete `node_modules` and reinstall it, then scully finds the new routes but again fils to prerender because it fails to open it from an angular app with a message like `Cannot GET /terms-and-conditions`. After this I need to restart my machine and then it works again. The problem about this is that I get this issue every single time I add pages to my app and it even happened on the CI once (I guess because I didn't clear the caches).
Running `scully --killServer` didn't do any change. Only methods I described above helped me so far.
Here is an example of how such page gets prerendered:
```
<!DOCTYPE html><html lang="en"><head><meta name="generator" content="Scully 0.0.86">
<meta charset="utf-8">
<title>Error</title>
<script>window['ScullyIO']='generated';</script></head>
<body scully-version="0.0.86">
<pre>Cannot GET /terms-and-conditions</pre>
</body></html>
```

#### 🔬 Minimal Reproduction
To reproduce it you should create an app, add some routes and prerender it. Then add new routes and try to prerender again. In my case only the new routes are affected by this issue
#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.0.2
Node: 12.14.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/init": "0.0.13",
"@scullyio/ng-lib": "0.0.22",
"@scullyio/scully": "0.0.86",
</code></pre>

**Comment by geromegrignon** [comment]
The actual Scully strategy is to reduce the time needed to run `npm run scully` by not scanning the routes of the project if a `scully-routes.json` file already exists inside `src/assets` (created the first time you run `npm run scully`).

In order to discover new routes, you need to add `--scan` option when running `npm run scully` :

```bash
npm run scully --scan
```

It's included inside the docs but it might need to be more visible without having to dig inside it.
I'll consider finding a way to make it more visible for new users.

**Comment by BlindDespair** [comment]
@geromegrignon thank you for your response. I will try it next time. Thing is that I am using scully for around 2-3 months now and I don't follow all the updates and changes and I think back then it did not work this way.

**Comment by SanderElias** [comment]
@BlindDespair I was puzzled by this too, and I wrote this ;) Today we are going to beta, and breaking changes like this, will get proper documentation! 
Closing this, as it works as expected
