### ISSUE TITLE
Feature request: Translation of Getting Started documentation

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#452]
### Description

In line with the spanish version of  [Getting started with Scully](https://github.com/scullyio/scully/blob/master/docs/getting-started.md), would you be interested with a french version of this file?

### Describe the solution you'd like

It would add a `getting-started_fr.md` file with a translated version of [Getting started with Scully](https://github.com/scullyio/scully/blob/master/docs/getting-started.md).

**Comment by jorgeucano** [comment]
Yes :) ... We will work in add the i18n for the next builds (for the web) ... Im working in the docs now writing and changing some texts... We can talk after this. I will add you in the review if you like

**Comment by geromegrignon** [comment]
Sure.
closing the issue for now.

**Comment by jorgeucano** [comment]
We can Create a issue for I18n  :)
