### ISSUE TITLE
[ScullyDocs] double focus on navigation

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#454]
### Description

Using tabulation to navigate on [scully.io](https://scully.io/) header navigation, each button is focused twice. It sounds like it's due to an `href="/undefined"` being added.
I tried to fix it but couldn't manage to find out when it's being added as it isn't present in the ScullyDocs codebase.

#### 🔬 Minimal Reproduction

Navigate to [scully.io](https://scully.io/)
Use tabulation on the navigation header.

#### Environment

reproduced on Chrome, Edge and FIrefox.

**Comment by jorgeucano** [comment]
I will check, I add the content there, but I have the same, the problem is the tab use the component and the tag a, and for this is the "double" focus

**Comment by geromegrignon** [comment]
Here is a [stackblitz](https://stackblitz.com/edit/angular-fedgty?file=src%2Fapp%2Fapp.component.html) example.

Given two components with the tag a : 
 - there is a double focus if the tag a includes a href
- there is a single focus without the href
