### ISSUE TITLE
ng generate @scullyio/init:post with wrong prop publish

### ISSUE THREAD

**Issue by s0l0c0ding** [scullyio/scully#455]
### Description
when i generate a new post with :
`ng generate @scullyio/init:post --name="This is my post"`

the output  file is like:

> ---
> title: This is my post
> description: blog description
> publish: false
> ---

but in the scullyRoute interface, 
`export interface ScullyRoute {
    route: string;
    title?: string;
    slugs?: string[];
    published?: boolean;
    slug?: string;
    sourceFile?: string;
    [prop: string]: any;
}`
the tag "publish" is under published , so the 
`  this.links$  = this.scully.available$;`
doesn't work properly  
#### 🔬 Minimal Reproduction
just generate a new post and try to use the ScullyRoutesService.available$, will not work as there is a wrong properties matching 
#### 💻Your Environment

**Angular Version:**

Angular CLI: 9.1.0
Node: 10.15.2
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.1.0
@schematics/angular               9.0.7
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0
</code></pre>

**Scully Version:**

<pre><code>
 "@scullyio/init": "0.0.23",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</code></pre>

## 🔥 Exception or Error

<pre><code>
no error 
</code></pre>

**Comment by geromegrignon** [comment]
@jorgeucano 

The `add-post` schematic generates a header based on this : 

```
let metaData = {
      title: '',
      description: 'blog description',
      published: false,
    };
```

But the generated file includes *publish* rather than *published*.

**Comment by jorgeucano** [comment]
I publish the new version! 
If you have any new problem, please create another ticket :)

**Comment by s0l0c0ding** [comment]
i  confirm the issue is resolved now
