### ISSUE TITLE
I18n docs

### ISSUE THREAD

**Issue by jorgeucano** [scullyio/scully#456]
### Description

We have some members of the community wanting to contribute to the documentation by translating into different languages ​​... I am going to open this ticket so that we can speak and see the steps to follow as well as the languages ​​we are going to translate it in!

**Comment by jorgeucano** [comment]
@geromegrignon french version :)

**Comment by jorgeucano** [comment]
@facurodriguez spanish version :)

**Comment by raeffs** [comment]
I would offer to translate to german if that helps you ;)

**Comment by jorgeucano** [comment]
The code is in master, We need just start to translate the docs! thanks all !
