### ISSUE TITLE
Cannot find module 'fs-extra', when running scully npm script

### ISSUE THREAD

**Issue by Markus-Ende** [scullyio/scully#46]
# 🐞 bug report

### Description
`npm run scully` fails with message: 

`Error: Cannot find module 'fs-extra'`

(Fixed by installing fs-extra)

## 🔬 Minimal Reproduction

0. Create new Angular 9 project
0. Install scully
0. Run `npm run scully`

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.6
Node: 12.14.0
OS: linux x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@angular/cdk                      8.2.3
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Scully Version:**
<pre><code>
    "@scullyio/init": "0.0.8",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</code></pre>
## 🔥 Exception or Error
<pre><code>
<pre>Error: Cannot find module &apos;fs-extra&apos;
Require stack:
- /(...)/node_modules/@scullyio/scully/bin/scully.js
<font color="#555753">    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)</font>
<font color="#555753">    at Function.Module._load (internal/modules/cjs/loader.js:690:27)</font>
<font color="#555753">    at Module.require (internal/modules/cjs/loader.js:852:19)</font>
<font color="#555753">    at require (internal/modules/cjs/helpers.js:74:18)</font>
    at Object.&lt;anonymous&gt; (/(...)/node_modules/<u style="text-decoration-style:single">@scullyio</u>/scully/bin/scully.js:7:20)
<font color="#555753">    at Module._compile (internal/modules/cjs/loader.js:959:30)</font>
<font color="#555753">    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)</font>
<font color="#555753">    at Module.load (internal/modules/cjs/loader.js:815:32)</font>
<font color="#555753">    at Function.Module._load (internal/modules/cjs/loader.js:727:14)</font>
<font color="#555753">    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)</font> {
  code: <font color="#4E9A06">&apos;MODULE_NOT_FOUND&apos;</font>,
  requireStack: [
    <font color="#4E9A06">&apos;/(...)/node_modules/@scullyio/scully/bin/scully.js&apos;</font>
  ]
</pre>
</code></pre>

**Comment by jorgeucano** [comment]
@Markus-Ende thanks for open the issue... We have the fix for this, today we will publish the new version with the fix!

**Comment by jorgeucano** [comment]
fixed in version 0.0.45! thanks for the report!
