### ISSUE TITLE
generated Scully code breaks build when compiler option `noUnusedParameters` is activated

### ISSUE THREAD

**Issue by Markus-Ende** [scullyio/scully#47]
# 🐞 bug report

### Description
With TypeScript compiler option `noUnusedParameters`activated, generated Scully code breaks the build:
```ts
export class AppComponent {
  constructor(private idle: IdleMonitorService) {} // unused parameter idle

  title = "xyz";
}
```
Fixed by changing generated code to:

```ts
export class AppComponent {
  constructor(idle: IdleMonitorService) {
    idle.init();
  }

  title = "xyz";
}
```

## 🔬 Minimal Reproduction

0. Create new Angular 9 project
0. Install scully
0. Run ng build

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.6
Node: 12.14.0
OS: linux x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@angular/cdk                      8.2.3
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Scully Version:**
<pre><code>
    "@scullyio/init": "0.0.8",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</code></pre>

**Comment by jorgeucano** [comment]
@Markus-Ende the IdleMonitorService is only for scully, we need this inject, but we dont need run line....

@SanderElias @aaronfrost we have 2 options

1- add to the documentation if the project use `noUnusedParameters`, the dev need add the ts-ignore.
2- is read in the schematics the tsconfig and add the ts-ignore.

I really prefer the first

**Comment by SanderElias** [comment]
@Markus-Ende Thanks for taking the time to fie an issue.
However, this is working according to design. By default the CLI doesn't have this option on.
If you want to use this more restrictive as the default CLI Typescript linting rule, the responsibility is upon you to put in adequate measures.
In this case you need to put in the following line:
```typescript
 // tslint:disable-next-line: noUnusedParameters
```
Calling the `init` method will result in unforeseeable issues in the future, as its primary use is meant for rendering inside Scully only.

I will ask our friend @Villanuevand to make a note for this in the documentation, so this confusion will not be there in the future.

**Comment by Markus-Ende** [comment]
Ok thanks for the clarification. This is a TypeScript compiler option though, so `tslint:disable-next-line` will not do.
For future reference: the only way to fix this is to add `// @ts-ignore` above the constructor.

Just a quick follow-up question: is it important to add the service as property or is it enough to inject it? Because if the later is true, this would also be possible:
```
constructor(_: IdleMonitorService) {}
```
