### ISSUE TITLE
D3 chart not rendering on page generated from markdown file

### ISSUE THREAD

**Issue by jahnreektor** [scullyio/scully#478]
### Description
I created a D3 chart within a blog markdown file, and the chart flashes on screen momentarily before disappearing. See https://qf-dev-4d604.firebaseapp.com/blog/2020-04-18-blog. I noticed if I delete the polyfill JS files and deploy, the charts are not clobbered and the chart displays properly.

I'm unsure if this is an Angular thing or a Scully thing.

#### 🔬 Minimal Reproduction

In a scully blog markdown file, add the following code to generate a d3 graph:
```
<div class="chart"></div>
<script src="https://d3js.org/d3.v3.min.js"  charset="utf-8"></script>
<script>
var data = [4, 8, 15, 16, 23, 42];

var x = d3.scale.linear()
.domain([0, d3.max(data)])
.range([0, 420]);

d3.select(".chart")
.selectAll("div")
.data(data)
.enter().append("div")
.style("width", function(d) { return x(d) + "px"; })
.text(function(d) { return d; });
</script>
<style>.chart div {
    font: 10px sans-serif;
    background-color: steelblue;
    text-align: right;
    padding: 3px;
    margin: 1px;
    color: white;
}

body {
  background: white;
  color: black;
}
</style>
```

#### 💻Your Environment

**Angular Version:**

<pre><code>
9.1.2

</code></pre>

**Scully Version:**

<pre><code>
0.0.25

</code></pre>

**Comment by jorgeucano** [comment]
Is not a Scully error, Angular take this as inject script and remove...
