### ISSUE TITLE
scully tries to kill a server which process is already killed

### ISSUE THREAD

**Issue by willi84** [scullyio/scully#479]
### Description
Scully tried to kill a process of an internal server, which does not exists anymore. sometimes one process, somtimes the subprocesses of a process

#### 🔬 Minimal Reproduction
* using windows10 and run scully
 I logged at these two positions:
* https://github.com/scullyio/scully/blob/019a77d999ae4c5703a5ea106d757b19a7c0bdf2/scully/utils/serverstuff/waitForServerToBeAvailable.ts#L30
* https://github.com/scullyio/scully/blob/10950b5771fd4d82b5b4b2c31df7737523dad044/scully/scully.ts#L93

#### 💻Your Environment
* Windows 10 (build 10.0.18353)
* node 12.16.1
happened all also at similar windows 10 environments. happens not at apple as it looks

**Angular Version:**

* doesn't matter (I am using 9.1.0)

**Scully Version:**
* doesn't matter (I am using 0.0.86)

## 🔥 Exception or Error
the terminal says it can't kill the process

![200419-scully-process](https://user-images.githubusercontent.com/6207308/79696920-dd17bf80-827f-11ea-8c9e-f6956cffb45d.jpg)

**Comment by willi84** [comment]
@SanderElias what kind of further infos do you need?

**Comment by jorgeucano** [comment]
Hey @willi84 We think this is resolved, because we add more logs to the render. If you need any more please open another ticket.
