### ISSUE TITLE
Created index.html is not static 

### ISSUE THREAD

**Issue by Markus-Ende** [scullyio/scully#48]
# 🐞 bug report

### Description

The created index.html is not a static html file but the original index.html.

## 🔬 Minimal Reproduction

0. Create new Angular 9 project
0. Install scully
0. Run `npm run scully`

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.6
Node: 12.14.0
OS: linux x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@angular/cdk                      8.2.3
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Scully Version:**
<pre><code>
    "@scullyio/init": "0.0.8",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</code></pre>

**Comment by jorgeucano** [comment]
@Markus-Ende thanks for open the issue, but this is not a bug, is part of how work scully.
You can check in this video about how work and the mix mode with and without javascript!

https://www.youtube.com/watch?v=Sh37rIUL-d4

**Comment by Markus-Ende** [comment]
@jorgeucano ok, but then maybe this should be mentioned in the documentation? In [Getting started -> Test](https://github.com/scullyio/scully/blob/master/docs/getting-started.md#test) it says, I should try and disable JavaScript in the browser to check if static rendering works. But this can't work if the initial app component is added via JavaScript..

Content of my index.html:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Markusende</title>
    <base href="/" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
  </head>
  <body>
    <me-root></me-root>
  <script src="runtime-es2015.js" type="module"></script><script src="runtime-es5.js" nomodule defer></script><script src="polyfills-es5.js" nomodule defer></script><script src="polyfills-es2015.js" type="module"></script><script src="styles-es2015.js" type="module"></script><script src="styles-es5.js" nomodule defer></script><script src="vendor-es2015.js" type="module"></script><script src="vendor-es5.js" nomodule defer></script><script src="main-es2015.js" type="module"></script><script src="main-es5.js" nomodule defer></script></body>
</html>

```

**Comment by Markus-Ende** [comment]
Content of my app.component is `hello world!`, so shouldn't the index html look like below?

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Markusende</title>
    <base href="/" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
  </head>
  <body>
    <me-root>hello world!</me-root>
  <script src="runtime-es2015.js" type="module"></script><script src="runtime-es5.js" nomodule defer></script><script src="polyfills-es5.js" nomodule defer></script><script src="polyfills-es2015.js" type="module"></script><script src="styles-es2015.js" type="module"></script><script src="styles-es5.js" nomodule defer></script><script src="vendor-es2015.js" type="module"></script><script src="vendor-es5.js" nomodule defer></script><script src="main-es2015.js" type="module"></script><script src="main-es5.js" nomodule defer></script></body>
</html>
```

**Comment by SanderElias** [comment]
@Markus-Ende Can you show me your route for the top level? If you don't have one, there is no static content in the index.html. And that is according to design. 
Scully will render all of your routes, but if you don't have an:
```typescript
routes = [
 { path:='', component:SomeComponent },
 /** more routes **/
]
```
There is actually no static file for that.

@Villanuevand Can you put somethign about this in the documentation?

@Markus-Ende if this doesn't answer your question, please make me understand what we are missing, otherwise, please close your issue.

**Comment by Markus-Ende** [comment]
Hi @SanderElias, thanks for the clarification. That's my setup:

```ts
const routes: Routes = [{ path: 'hello', component: HelloComponent }];
```
app.component.html:
```html
app
<router-outlet></router-outlet>
```
hello.component.html:
```html
hello
```
After ng build && npm run scully i have in dist/static 2 index.html files with the following body content:

dist/static/hello/index.html
```html
    <me-root _nghost-fsv-c22="" ng-version="9.0.0-rc.6">app
<router-outlet _ngcontent-fsv-c22=""></router-outlet><me-hello>hello</me-hello><!--container--></me-root>
```
dist/static/index.html
```html
<me-root></me-root>
```

I would expect dist/static/index.html to have something like the following content:
```html
    <me-root _nghost-fsv-c22="" ng-version="9.0.0-rc.6">app
<router-outlet _ngcontent-fsv-c22=""></router-outlet></me-root>
```

I understand now, that it is not this way by design, but may I ask why? Many apps have content plus router-outlet in the bootstrap component. I think it might be also confusing for others, especially when trying Scully for the first time, that the default Angular app created by the CLI can't be rendered statically.

**Comment by SanderElias** [comment]
@Markus-Ende 
What happens if you do an `ng serve` and open `http://localhost:4200` in your browser?
I'm fairly sure it will not have `<me-root>` either.
We can not render something that your app is not rendering.

**Comment by Markus-Ende** [comment]
I tried my example (without a `''` route) using Angular universal (using the Angular 8 example project from the [Universal tutorial](https://angular.io/guide/universal)). This is what is rendered on server side and what I'd expect:

```html
<me-root _nghost-sc0="" ng-version="8.2.14">app
		<router-outlet _ngcontent-sc0=""></router-outlet>
	</me-root>
```

I still do not understand what's the difference, but it's not a big issue anyway once it is documented. Thanks for your time and work!
