### ISSUE TITLE
After redirecting, static page flashes but disappears after Angular mounts

### ISSUE THREAD

**Issue by jahnreektor** [scullyio/scully#481]
### Description
I have deployed my portfolio app to Firebase hosting at http://visualizeearth.com. Given that the app is a single route, I have configured all paths to redirect to index.html in both the firebase.json _and_ the app-routing.module.ts.

Whenever a user goes to http://visualizeearth.com/somerandompath, the traffic gets redirected, but the page renders as entirely blank. It appears that the static page flashes briefly before the Angular app mounts. The following error appears in the console:
```
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'somerandompath'
Error: Cannot match any routes. URL Segment: 'somerandompath'
```
However, I'm thinking this error shouldn't apply given 1) it's a statically rendered app, and 2) if it weren't, the angular app routing module forwards all paths to the root path.

#### 🔬 Minimal Reproduction

1. Create and deploy a one-page statically generated app, and configure all paths on your server to redirect to the index.html page. I used Firebase with these settings:
```{
  "hosting": {
    "public": "dist/static",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```
2. Try to access any path, e.g., yourdomain.com/somepath.
3. Notice that page blank page renders, with static page momentarily flashing.

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular: 9.1.2

</code></pre>

**Scully Version:**

<pre><code>
0.0.25

</code></pre>

## 🔥 Exception or Error

<pre><code>
 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'somerandompath'
Error: Cannot match any routes. URL Segment: 'somerandompath'
</code></pre>

**Comment by jorgeucano** [comment]
When you change a static page to another is a full reload, When angular change to another page, is only changing the angular router and the components.
So, is not a flash, is a simple new full load./
