### ISSUE TITLE
Wrong import in markdown module component.spec template under Linux

### ISSUE THREAD

**Issue by atao60** [scullyio/scully#500]
### Description

`@scullyio/init:markdown` generates a  component.spec.ts file where the import of the component file still starts with capitalized component name. It doesn't work under linux.

#### Change to apply

On `schematics/scully/src/files/markdown-module/\_\_name@dasherize\_\_.component.spec.ts.template`:

```
@@ -1,6 +1,6 @@
 import { async, ComponentFixture, TestBed } from '@angular/core/testing';
 
-import { <%= classify(name) %>Component } from './<%= classify(name) %>.component';
+import { <%= classify(name) %>Component } from './<%= dasherize(name) %>.component';
 
 describe('<%= classify(name) %>Component', () => {
   let component: <%= classify(name) %>Component;

```

#### 🔬 Minimal Reproduction
Any time with:
```
npx ng new bug-scully-blog --routing --strict --style scss

cd bug-scully-blog

ng add @scullyio/init

ng generate @scullyio/init:markdown --name=projects --slug=projectId --sourceDir=projects --route=projects

cat src/app/projects/projects.component.spec.ts
import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { ProjectsComponent } from './Projects.component';
-------------- bug ------------------^
describe('ProjectsComponent', () => {
  let component: ProjectsComponent;
  let fixture: ComponentFixture<ProjectsComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ ProjectsComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(ProjectsComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

```
#### 💻Your Environment

**System**
```
cat /etc/issue
Ubuntu 18.04.2 LTS \n \l

uname -a
Linux [...] 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Angular Version:**

<pre><code>
Angular CLI: 9.0.7
Node: 12.3.1
OS: linux x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2
    

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "0.0.25",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by jorgeucano** [comment]
Fixed in new version! Thanks for the report!
