### ISSUE TITLE
Include ScullyRoute when explaining ScullyRoutesService

### ISSUE THREAD

**Issue by donmckenna** [scullyio/scully#501]
### Description

In https://scully.io/docs/getting-started#inject-the-route-service, the `TS` example console.logs the array of routes from the `ScullyRoutesService.available$` observable.

However, it is unclear what shape that observable takes because the example only uses `<any>`
```typescript
links$: Observable<any> = this.scully.available$;

constructor(private scully: ScullyRoutesService) {}
```
When looking at the `ScullyRoutesService` class in `scully-routes.service.d.ts`, the `available$` observable has a type of `ScullyRoute[]`

![image](https://user-images.githubusercontent.com/22125230/80267718-b1218300-865f-11ea-920d-6472b955d211.png)

If the example of `available$` is being used in the docs, and `available$` has a type in the type definition file, wouldn't it make sense to include it in the docs instead / as well, like this?
```typescript
links$: Observable<ScullyRoute[]> = this.scully.available$;
```

This could make it clearer what shapes can be expected to be extracted from `available$`, and maybe provide better conceptual understanding of how Scully is passing data around.

So instead of
![image](https://user-images.githubusercontent.com/22125230/80267337-71599c00-865d-11ea-9484-12c8b2a30f80.png)

..we could see something like
![image](https://user-images.githubusercontent.com/22125230/80266921-d0b6ac80-865b-11ea-8d67-e5813b703ca3.png)

..and understand the values Scully can make available to us without having to `Alt + click` through the code.

Additionally, this could go alongside a simple `.md` example to show the structure of a `@scullyio/init:post` and how its shape relates to the `ScullyRoute`s you can pull out of `ScullyRoutesService`.

It could then be inferred, or simply stated how, through this structure, one can insert custom properties into the "head" of a `.md` file and access them in an Angular template.

Once I could "visualize" this relationship, this aspect of Scully clicked for me. 
Perhaps it's a simple enough example to partially include in the "Getting Started" docs page, or as an addition to the "Blogs in Scully" page, helping paint these shapes and relationships to new users, so when they see
```typescript
<li *ngFor="let page of links$ | async">{{ page.route }}</li>
```
..they may have a better idea of what `page` means, what is included in it, and how they can add to it themselves.

If my understanding is correct, I'd be happy to submit a PR for this if it could be useful.

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by geromegrignon** [comment]
Great idea;
Feel free to open a PR.

I would use the existing *Getting Started* file to explain the relationship between the .md file shape and the *ScullyRoute* interface as the Core lib file only focus on the ScullyRouteService and the *Blog Support* file only focus on the generated files.

**Comment by donmckenna** [comment]
Sounds good, I'll start on a PR soon.
