### ISSUE TITLE
TransferState does not handle fragments properly

### ISSUE THREAD

**Issue by cmgriffing** [scullyio/scully#502]
### Description

The transferstate does not get fetched properly in the client when the page is loaded freshly with a fragment in the url.

The page handles fragments fine if the initial load was without a fragment.

#### 🔬 Minimal Reproduction

See: https://scully-image.github.io/docs/components and scroll down the page to one of the components. You will see the image fade in properly.

Then navigate to: https://scully-image.github.io/docs/components#traced

I believe something like this would fix it, I just wanted to get an opinion of if its the right approach before making the pr:
![image](https://user-images.githubusercontent.com/1195435/80292404-69f0cc00-870b-11ea-86d4-cde5d9516c3b.png)

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 9.0.7
Node: 13.10.1
OS: darwin x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-ng-packagr   0.900.7
@angular-devkit/build-optimizer    0.900.7
@angular-devkit/build-webpack      0.900.7
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@angular/cdk                       9.2.1
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.1
@ngtools/webpack                   9.0.7
@schematics/angular                9.0.7
@schematics/update                 0.900.7
ng-packagr                         9.1.0
rxjs                               6.5.5
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
// currently resolving to below in package-lock.json:
    "@scullyio/ng-lib": {
      "version": "0.0.22",
...
    "@scullyio/scully": {
      "version": "0.0.88",
</code></pre>

## 🔥 Exception or Error

An attempt to fetch a value by key on that page results in:
![image](https://user-images.githubusercontent.com/1195435/80292246-13cf5900-870a-11ea-9232-310e931ad61f.png)

**Comment by SanderElias** [comment]
I would welcome a PR for this. But is you are unsure, I do have an overhaul of this part of the code on my calendar anyway because I also need to factor in query params.

**Comment by SanderElias** [comment]
issue #439 is closely related

**Comment by SanderElias** [comment]
closed by #516
