### ISSUE TITLE
Installation fails on non-default directory structure

### ISSUE THREAD

**Issue by TomHAnderson** [scullyio/scully#503]
## 🐞 Bug report

```sh
[Pro@~/Projects/apiskeletons/gaveldown.bid/www (master)]$ ng add @scullyio/init

Installing packages for tooling via npm.
Installed packages for tooling via npm.
    error into import SculyLib
File ./src/app/app.module.ts does not exist.
```

This issue reports on the use of non-ng-file structures.

Scully relies on the `sourceRoot` configuration in `angular.json` to determine how to 
find other project files such as `app.module.ts`.

From ~/schmatics/scully/src/utils/utils.ts
```ts
export function getSrc(host: Tree, project: string) {
  const angularConfig = JSON.parse(host.read('./angular.json').toString());
  const defaultProject = getProject(host, project);
  return angularConfig.projects[defaultProject].sourceRoot;
}
```

Called from `schematics/scully/src/ng-add/index.ts`:
```ts
const importScullyModule = (project: string) => (tree: Tree, context: SchematicContext) => {
  try {
    const mainFilePath = `./${getSrc(tree, project)}/app/app.module.ts`;
```
I would like to see all hardcoding of paths removed and replaced with a configuration.

This hard-coding of directories is the issue at hand.  Solutions to this may be to add a new configuration to `angular.json` such as `appModulePath` which is used if the file cannot be found via sourceRoot.
**Perhaps a full configuration file with paths to each file Scully interacts with directly?**

### Description

I use an alternate directory structure for my Angular applications which I consider a large improvement over the default structure.  I presented this structure at the Utah Angular Meetup on 2019-09-24

Complete details of the structure are here:  https://angular-folder-structure.readthedocs.io/en/latest/neolithic.html

i don't expect you to support any custom directory layout.  I am reporting this bug because I believe 
```sh
 ng add @scullyio/init
```
should not error when ran initially.  I think a good fix for this would be a command line parameter or prompt for the location of app.module.ts if not found using the default ng-created directory structure.

#### 🔬 Minimal Reproduction

The following instruction are augmented with the Neolithic directory structure after `cd` to the project directory:

```sh
ng new test
cd test

# Begin convert default layout to Neolithic
# See: https://angular-folder-structure.readthedocs.io/en/latest/neolithic.html

mkdir media
mkdir src/module
mkdir src/styles && mkdir src/styles/themes
mv src/app src/module
mkdir src/module/app/layout
cd src && ln -s . app & cd .
sed -i .bak 's/.\/app/.\/module\/app/g' src/main.ts
ng generate module module/Shared
ng generate module module/Data
json --version || npm install -g json
json -f tsconfig.json -I -c "this.baseUrl = './src'"
json -f tsconfig.json -I -c "this.compilerOptions.paths = {}"
json -f tsconfig.json -I -e "this.compilerOptions.paths['@app/*'] = ['module/app/*']" \
  -e "this.compilerOptions.paths['@shared/*'] = ['module/shared/*']" \
  -e "this.compilerOptions.paths['@module/*'] = ['module/*']" \
  -e "this.compilerOptions.paths['@env/*'] = ['environment/*']" \
  -e "this.compilerOptions.paths['@data/*'] = ['module/data/*']"
mkdir -p .vscode
test -f .vscode/settings.json || echo "{}" > .vscode/settings.json
json -f .vscode/settings.json -I -e "this['files.exclude'] = {'**src/app': true}"

# End convert to Neolithic

# With the directory structure now converted away from `ng new` try to install scully.
# The reported error will now manifest:

ng add @scullyio/init
```

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 8.1.3
Node: 13.8.0
OS: darwin x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Scully Version:**

<pre><code>

    "@scullyio/init": "0.0.25",

</code></pre>

## 🔥 Exception or Error

<pre><code>

    error into import SculyLib
File ./src/app/app.module.ts does not exist.

</code></pre>

**Comment by TomHAnderson** [comment]
I can appreciate the artistic flair of defining file locations via `angular.json` but this minimalistic approach is not feasible for projects with advanced directory (or whatever) layouts.

I would like to see a solution for Scully which supports both the existing divination of directories via hard coded paths **and** a solution where the paths to any file in my application which scully can be coded directly without any path discovery.

**Comment by SanderElias** [comment]
@TomHAnderson I'm going to close this. We are rewriting our schematics to be independent of angular. Also we already did change this in Scully. It no longer depends on the angular.json. 
If there is one, it will be used, and it will extract the paths from there.
However, you are able to overwrite all of the paths in the Scully config file already.
So your tier 1 and 3 are already there. 
Path aliases are a typescript thing, and we can't use this during runtime, without a lot of extra code that will add a lot of complexity with only little pay-off. In the short term, we don't have the resources to do that.

So, I'm closing this for now, as there is no further action I can take now. 
Feel free to keep discussing in this thread.

**Comment by TomHAnderson** [comment]
I request this issue be re-opened.  Browsing the repository at https://github.com/scullyio/scully/blob/master/schematics/scully/src/ng-add/index.ts#L45 **still shows hard-coded path parts**.  I went over the entirety of the documentation located here:  https://github.com/scullyio/scully/blob/master/docs/scully-configuration.md and there is not a configuration variable to the `app.module.ts` and Scully there.  

To restate what this issue is actually about:  The hard coded `/app` path should NOT be hard coded.

**Comment by TomHAnderson** [comment]
This is the hard coded path giving so much trouble:
```
    const mainFilePath = `./${getSrc(tree, project)}/app/app.module.ts`;
```

**Comment by TomHAnderson** [comment]
@SanderElias I'll keep tabs on this.  My expectation is all hard coded paths, including minutia as shown in my immediate previous post, will be part of the configuration and assumptive paths like `/app/` will no longer exist.

**Comment by SanderElias** [comment]
@TomHAnderson That is one I missed, I'll move it into the config.

**Comment by SanderElias** [comment]
@TomHAnderson Ok, I now know why I missed it. It is not part of Scully itself.
@jorgeucano This seems to be a schematics issue, and I agree it should be optionally configurable
