### ISSUE TITLE
Scully or scully?  Proper naming is important!

### ISSUE THREAD

**Issue by TomHAnderson** [scullyio/scully#504]
### Description

Is Sully proper as your README.md file shows at the top or is it sspelled in lowercase as your logo, directly under where it says Scully, show: scully?

## 🔬 Minimal Reproduction

Browse here: https://github.com/scullyio/scully/blob/master/README.md

### What's the affected URL?\*\*

https://github.com/scullyio/scully/blob/master/README.md

### Reproduction Steps\*\*

Open https://github.com/scullyio/scully/blob/master/README.md and compare spellings of Scully || scully

### Expected vs Actual Behavior\*\*

I would expect this project to be consistent in nameing.

## 📷Screenshot

![Screen Shot 2020-04-26 at 2 47 01 PM](https://user-images.githubusercontent.com/493920/80319252-d7186600-87cc-11ea-8c02-718cecb30c09.png)

## 🔥 Exception or Error

<pre><code>
None

</code></pre>

**Comment by SanderElias** [comment]
It is Scully with a capital, except for the use in the logo.  There has been a long discussion on this, and this is how it's going to be. I don't disagree with you, but on the other hand, the logo with 2 capital `s`'s in a row looks _really_ off. 
Closing as decided upon in past discusions
