### ISSUE TITLE
Flash Prevention Plugin `defaultPostRenderers` rather than `postRenderers` in scully.config

### ISSUE THREAD

**Issue by mtopping** [scullyio/scully#506]
### Description

The README says to add the plugin to the `postRenderers` property in `scully.config`.

In the context of scully.config, the property is `defaultPostRenderers`.

### What's the affected URL?\*\*

https://github.com/scullyio/scully/tree/master/plugins/scully-plugin-flash-prevention

**Comment by SanderElias** [comment]
The flash prevention should only be on routes that need it. The documentation is lacking this insight indeed. 
We don't encourage to put is on the defaultpostRenderers. It is a helper to prevent big flashes on routes where there is no way to create a proper solution.

**Comment by mtopping** [comment]
@SanderElias Makes sense. Does the PR now better explain where to add the plugin?

**Comment by jorgeucano** [comment]
I saw a PR for this and is merged... Can i close this?

**Comment by Splaktar** [comment]
As mentioned in https://github.com/scullyio/scully/pull/507#issuecomment-850931982, the fix for this appears to have gotten lost in the move of the plugins folder.
