### ISSUE TITLE
missing "<scully-content>" in route "/blog/ Github actions / pages

### ISSUE THREAD

**Issue by s0l0c0ding** [scullyio/scully#523]
## 🐞 Bug report
 Error, missing scully-content tag in route "/blog/eng_spring_spring_posts"
   without scully-content tag we can not render this route.
   Make sure it is in there, and not inside any conditionals (*ngIf)
   You can check this by opening "http://localhost:4200//blog/eng_spring_spring_posts"
   when you serve your app with ng serve and then in the browsers console run:
   document.querySelector('scully-content')nt')
### Description
Trying to build my app with github actions and deploy to github pages, for some reason the markdown files does not get rendered.
Locally work fine with `ng build --prod`, after digging , i think the problem is with href attribute `ng build --prod --base-href /solocoding-blog/`
#### 🔬 Minimal Reproduction
here you can find my deploy [yaml](https://github.com/s0l0c0ding/solocoding-blog/blob/master/.github/workflows/deploy.yml)
#### 💻Your Environment

**Angular Version:**
**on my PC**
<pre><code>
Angular CLI: 9.1.4
Node: 12.16.3
OS: linux x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.1
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0
</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "0.0.25",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",

</code></pre>

## 🔥 Exception or Error

<pre><code>
DOMException {}
Route "/blog/eng_spring_spring_posts" rendered into file: "/home/runner/work/solocoding-blog/solocoding-blog/dist/static/blog/eng_spring_spring_posts/index.html"
</code></pre>

**Comment by SanderElias** [comment]
I looked into this, and it is the base_href. 
You can do this, but you have to move the output of `ng build` onto a subfolder of dust that has the same structure as your base ref. in your case, that would be `/solocoding-blog/`
The easy way is to update you `angular.json` to have this extra folder, and then make sure the Scully config file has a setting where the `distFolder` is one level higher than that.

**Comment by s0l0c0ding** [comment]
> I looked into this, and it is the base_href.
> You can do this, but you have to move the output of `ng build` onto a subfolder of dust that has the same structure as your base ref. in your case, that would be `/solocoding-blog/`
> The easy way is to update you `angular.json` to have this extra folder, and then make sure the Scully config file has a setting where the `distFolder` is one level higher than that.

actually the angular.json is not the problem, here it is : 
`"options": {
            "outputPath": "dist/soloCoding-blog",`
and scully config is in the default position, so it's in the root of the project (same level as dist).

The problem is github deployment , as angular documentation [says](https://angular.io/guide/deployment#deploy-to-github-pages) we have to use base-href. I aslo tried [Scully Publish](https://github.com/cmgriffing/scully-gh-pages-action), the deployment didn't give any error, but only the home page working, and no markdown get rendered.

Now i am looking to another hosting and i confirm it works fine on firebase and netlify. Looking fwd to share the link of the final product  with you (I am excited).
