### ISSUE TITLE
Generate a Changelog and Use GitHub Releases

### ISSUE THREAD

**Issue by evolkmann** [scullyio/scully#524]
### Description

The scully repo currently contains zero releases/tags and the changelog file is not maintained since v0.0.2. On npm however, new versions are released every few days.

This makes it unclear which issues are addressed in new releases and what the actual changes are.

Therefore I guess it would be a nicer experience using scully if this kind of information was available more transparently. Since you are using conventional commits already, it is no big effort to generate the changelog and version, e.g. with lerna.

### What's the affected URL?

- https://github.com/scullyio/scully/blob/master/CHANGELOG.md
- https://github.com/scullyio/scully/releases
- https://www.npmjs.com/package/@scullyio/scully

**Comment by jorgeucano** [comment]
With the NX monorepo, we will add all for the changelog :D

**Comment by evolkmann** [comment]
Okay, nx is also fine of course. I am exited to get my first release notification :)

**Comment by KingDarBoja** [comment]
I would recommend using [semantic-release](https://github.com/semantic-release/semantic-release) to automate the release process and changelog generation.

**Comment by jorgeucano** [comment]
https://github.com/scullyio/scully/blob/main/CHANGELOG.md
