### ISSUE TITLE
[Docs-Showcase] add link on images 

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#538]
### Description

The showcase page of the official documentation might look cleaner by having the link to the website directly on the logo rather than with a separate link

Actual Documentation 

![scully io_docs_showcase_](https://user-images.githubusercontent.com/32737308/81512024-aa606480-931d-11ea-9499-f1083e4344b8.png)

Proposition

![scully io_docs_showcase](https://user-images.githubusercontent.com/32737308/81512012-9b79b200-931d-11ea-96a2-38c5c53d6197.png)

### Describe the solution you'd like

Use following markdown syntax

[![alt text](image link)](website link)

I can handle a PR if accepted.

**Comment by SanderElias** [comment]
@geromegrignon Good catch!. We are doing some refactorings now, and I will pick this up while I'm working on that.

**Comment by jorgeucano** [comment]
@GuzmanPI Can you take a look?

**Comment by GuzmanPI** [comment]
Yes @jorgeucano  I'll take a look at it

**Comment by GuzmanPI** [comment]
This has been addresed
