### ISSUE TITLE
npm run scully not working

### ISSUE THREAD

**Issue by DYEWolf** [scullyio/scully#543]
### Description
I follow the tutorial in the docs to create a new scully app, everything works fine until I have to run the command *npm run scully*, then i got the following error: 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-scully-app@0.0.0 scully: `scully`
npm ERR! Exit status 1

#### 💻Your Environment

**Angular Version:**

<pre><code>

    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.5
Node: 12.16.2
OS: win32 x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cli                      9.1.5
@ngtools/webpack                  9.1.5
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Scully Version:**

<pre><code>

  {
  "name": "my-scully-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.1",
    "@angular/common": "~9.1.1",
    "@angular/compiler": "~9.1.1",
    "@angular/core": "~9.1.1",
    "@angular/forms": "~9.1.1",
    "@angular/platform-browser": "~9.1.1",
    "@angular/platform-browser-dynamic": "~9.1.1",
    "@angular/router": "~9.1.1",
    "@scullyio/init": "0.0.26",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
</code></pre>

## 🔥 Exception or Error

<pre><code>

C:\Users\angel\Documents\Development\my-scully-app\node_modules\tslib\tslib.js:237
        Object.defineProperty(o, "default", { enumerable: true, value: v });
               ^

TypeError: Cannot redefine property: default
    at Function.defineProperty (<anonymous>)
    at C:\Users\angel\Documents\Development\my-scully-app\node_modules\tslib\tslib.js:237:16
    at Object.__importStar (C:\Users\angel\Documents\Development\my-scully-app\node_modules\tslib\tslib.js:246:9)
    at Object.<anonymous> (C:\Users\angel\Documents\Development\my-scully-app\node_modules\@scullyio\scully\utils\cli-options.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-scully-app@0.0.0 scully: `scully`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-scully-app@0.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
</code></pre>

**Comment by dalelarsen** [comment]
Exact same issue here.

**Comment by stevermeister** [comment]
I found that that problem is with **tslib**.
it works with version    

```
"tslib": "1.11.1",
```

(without ^)

**Comment by DYEWolf** [comment]
> I found that that problem is with **tslib**.
> it works with version
> 
> ```
> "tslib": "1.11.1",
> ```
> 
> so not "tslib": "^1.10.0", because it gets to **1.12** after install

You are right, with that modification works but I assume this is not a fix of the issue right? just a workaround?

**Comment by stevermeister** [comment]
@DYEWolf yes, right, I just put it here to help unblock developers and provide some extra infromation for contributors.

**Comment by jorgeucano** [comment]
Hey, good morning! I created a new project from scratch with the angular CLI, installing v9.1.6, and all work for me! 


```D:\example\t1 (master -> origin)
λ ng add @scullyio/init
Installing packages for tooling via npm.
Installed packages for tooling via npm.
    Install ng-lib for Angular v9
    ✅️ Added dependency
UPDATE src/app/app.module.ts (466 bytes)
UPDATE src/polyfills.ts (3028 bytes)
UPDATE package.json (1334 bytes)
√ Packages installed successfully.
    ✅️ Update package.json
    ✅️ Created scully configuration file in scully.t1.config.ts
CREATE scully.t1.config.ts (177 bytes)
UPDATE package.json (1394 bytes)

D:\example\t1 (master -> origin)
λ ng g @scullyio/init:blog
    ✅️ Update scully.t1.config.ts
CREATE src/app/blog/blog-routing.module.ts (428 bytes)
CREATE src/app/blog/blog.component.html (160 bytes)
CREATE src/app/blog/blog.component.spec.ts (639 bytes)
CREATE src/app/blog/blog.component.ts (508 bytes)
CREATE src/app/blog/blog.component.css (138 bytes)
CREATE src/app/blog/blog.module.ts (391 bytes)
UPDATE scully.t1.config.ts (281 bytes)
UPDATE src/app/app-routing.module.ts (336 bytes)
    ✅️ Blog ./blog/2020-05-14-blog.md file created
CREATE blog/2020-05-14-blog.md (97 bytes)

D:\example\t1 (master -> origin)
λ ng g @scullyio/init:markdown --name="blog" --source-dir="libs/blog/posts1" --route="/home/blog/"
? What slug do you want for the markdown file? ng build
    ✅️ Update scully.t1.config.ts
UPDATE scully.t1.config.ts (407 bytes)
UPDATE src/app/app-routing.module.ts (432 bytes)
UPDATE src/app/blog/blog-routing.module.ts (431 bytes)
UPDATE src/app/blog/blog.component.html (160 bytes)
UPDATE src/app/blog/blog.component.spec.ts (639 bytes)
UPDATE src/app/blog/blog.component.ts (508 bytes)
UPDATE src/app/blog/blog.component.css (138 bytes)
UPDATE src/app/blog/blog.module.ts (391 bytes)
    ✅️ Blog ./libs/blog/posts1/2020-05-14-blog.md file created
CREATE libs/blog/posts1/2020-05-14-blog.md (97 bytes)

D:\example\t1 (master -> origin)
λ ng build --prod
Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @scullyio/ng-lib : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {0} runtime-es2015.e6aa4b4473646ca63ba9.js (runtime) 2.24 kB [entry] [rendered]
chunk {0} runtime-es5.e6aa4b4473646ca63ba9.js (runtime) 2.23 kB [entry] [rendered]
chunk {3} polyfills-es2015.41c53f59c4ec84d6c10d.js (polyfills) 37.4 kB [initial] [rendered]
chunk {1} 1-es2015.7a994ba3802ef4eea512.js () 1.19 kB  [rendered]
chunk {1} 1-es5.7a994ba3802ef4eea512.js () 1.66 kB  [rendered]
chunk {4} polyfills-es5.9899f08f819f59a9b743.js (polyfills-es5) 130 kB [initial] [rendered]
chunk {2} main-es2015.6a5fd4cf21cd8c8404f4.js (main) 264 kB [initial] [rendered]
chunk {2} main-es5.6a5fd4cf21cd8c8404f4.js (main) 315 kB [initial] [rendered]
chunk {5} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]
Date: 2020-05-14T13:07:14.436Z - Hash: 58917c18ceb57a202de7 - Time: 34697ms



D:\example\t1 (master -> origin)
λ npm run scully

> t1@0.0.0 scully D:\example\t1
> scully

starting
D:\example\t1 D:\example\t1
going to load
(node:20164) ExperimentalWarning: The fs.promises API is experimental
config loaed
before build
 ☺   new Angular build imported
 ☺   Started servers in background
Finding all routes in application.

----------------------------------
Using stored unhandled routes!.
   To discover new routes in the angular app use "npm run scully -- --scanRoutes"
----------------------------------
Pull in data to create additional routes.
No configuration for route "/blog/:ngbuild" found. Skipping
Finding files in folder "D:\example\t1\libs\blog\posts1"
Route list created in files:
  "D:\example\t1\src\assets\scully-routes.json",
  "D:\example\t1\dist\static\assets\scully-routes.json",
  "D:\example\t1\dist\t1\assets\scully-routes.json"

Route "/" rendered into file: "D:\example\t1\dist\static\index.html"
Route "/homeblog/___UNPUBLISHED___ka6sfdc6_Nd6v8d4Quvs42sL4wdEjp0NS8FaSNmZm" rendered into file: "D:\example\t1\dist\static\homeblog\___UNPUBLISHED___ka6sfdc6_Nd6v8d4Quvs42sL4wdEjp0NS8FaSNmZm\index.html"
send reload

Generating took 1.89 seconds for 2 pages:
  That is 1.06 pages per second,
  or 947 milliseconds for each page.

  Finding routes in the angular app took 4 milliseconds
  Pulling in route-data took 7 milliseconds
  Rendering the pages took 638 milliseconds

````

package.json
```
{
  "name": "t1",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.6",
    "@angular/common": "~9.1.6",
    "@angular/compiler": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@scullyio/init": "0.0.28",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler-cli": "~9.1.6",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
```

**Comment by stevermeister** [comment]
@jorgeucano which version of  "tslib": "^1.10.0", you got installed?

**Comment by jorgeucano** [comment]
```
D:\example\t1 (master -> origin)
λ more node_modules\tslib\package.json
{
  "_from": "tslib@^1.10.0",
  "_id": "tslib@1.13.0",
  "_inBundle": false,
```

I just from the CLI, I do not add anything, but we will block for this version `1.10.0` for now and check why don't work with the new version.

**Comment by stevermeister** [comment]
@jorgeucano I've checked *1.13.0* - it works for me as well. 
the problem was with *1.12*

**Comment by SanderElias** [comment]
Closing this, as it was a deps conflict from the CLI, and the updated version of the CLI doesn't have the conflicting tslib version anymore
