### ISSUE TITLE
 Config file ".../scully.blog.config.ts" not found

### ISSUE THREAD

**Issue by stevermeister** [scullyio/scully#551]
## 🐞 Bug report

it's strange that 

```
ng add @scullyio/init
```

generates **js** file for you but after that 

```
npm run scully
```

expect you to have **ts** file.

**Comment by SanderElias** [comment]
@stevermeister For now, rename the config.js to config.ts.
@jorgeucano we need to update the schematic

**Comment by SanderElias** [comment]
CLosed by #553
