### ISSUE TITLE
Default <code> block in Markdown to have "hljs" class

### ISSUE THREAD

**Issue by nartc** [scullyio/scully#555]
## 🧩 Feature request
Default `<code>` block in Markdown to have `hljs` class name

### Description
#446 PR includes a better way to handle syntax highlighting for Markdown which uses `highlight.js` under the hood. 

Even though it's not officially in the documentations but I've given this new approach a try and I have to say it's working great. The only hiccup (very small) that I ran into was since `highlight.js` is utilized, the `code` in markdown has different class names than `prismjs` and without the class name `hljs` added to the `<code>` element, it requires some fiddling with the hljs's CSS themes.

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
Default `<code>` block in Markdown to have `hljs` class name

 If you have a solution in mind, please describe it.

**Comment by jorgeucano** [comment]
We don't support as default, because a 99% of the devs don't need that, so We add the option to add the `hljs` support directly.
