### ISSUE TITLE
move auto generated config.js out of the 'root' folder.

### ISSUE THREAD

**Issue by SanderElias** [scullyio/scully#557]
### Description
Rigth now, the config.ts is compiled to the config.js file that is visible in the same folder.
This causes confugsion.
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by puku0x** [comment]
I added the config.js file to `.gitignore`, as a temporal solution😅

**Comment by SanderElias** [comment]
Looked into this. The fact that imports are done relative to the position of the TS file (and this also the JS file) makes it very impractical to move the config file.
@GuzmanPI Can you make a note that we need to document this?
