### ISSUE TITLE
TS error on ng add

### ISSUE THREAD

**Issue by Vandivier** [scullyio/scully#561]
### Description

received a ts error in the cli-generated scully config.`

I believe it's easily solved by adding `defaultPostRenderers: [],` to the default config

#### 🔬 Minimal Reproduction
1. have vs code with typescript support
2. `ng add @scullyio/init`
3. visit generated scully config
4. get error

#### 💻Your Environment

**Angular Version:**

<pre>9.1.0<code>
</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "0.0.28",
    "@scullyio/ng-lib": "0.0.22",
    "@scullyio/scully": "0.0.91",
</code></pre>

## 🔥 Exception or Error

```
Property 'defaultPostRenderers' is missing in type '{ projectRoot: string; projectName: string; outDir: string; routes: {}; }' but required in type 'ScullyConfig'.
```

**Comment by Vandivier** [comment]
there's also a typo on `npm run scully`:

```
going to load
config loaed
before build
```

loaded is spelled incorrectly

**Comment by SanderElias** [comment]
@Vandivier Actually, all those issues are already solved. I will push out a new version later to day that holds those changes.
