### ISSUE TITLE
broken json plugin hyperlink

### ISSUE THREAD

**Issue by Vandivier** [scullyio/scully#563]
Visit: https://scully.io/docs/plugins#router-plugin

grep:
`It uses the JSON Plugin which is part of Scully.`

The hyperlink substring broken.

**Comment by Vandivier** [comment]
I also tried to reproduce the `userIdPlugin` described [here](https://scully.io/docs/plugins), but typescript complained:

```
Type 'Promise<{ route: string; }[]>' is not assignable to type 'Promise<HandledRoute[]>'.
Type '{ route: string; }[]' is not assignable to type 'HandledRoute[]'.
Property 'type' is missing in type '{ route: string; }' but required in type 'HandledRoute'.
```

**Comment by ankita-singhal12** [comment]
The broken link issue should be fixed in this PR [https://github.com/scullyio/scully/pull/607]

For the plugin, I returned <any> in the meantime

@SanderElias : Should I go ahead and fix this in the documentation? Any suggestions.

**Comment by AnkitaSinghal** [comment]
The broken link issue should be fixed in this PR [https://github.com/pull/607]

For the plugin, I returned in the meantime

@SanderElias : Should I go ahead and fix this in the documentation? Any suggestions.

**Comment by SanderElias** [comment]
@Vandivier Last week we released an updated documentation site, and the location has changed.
We are going to close this issue because we think its no longer relevant.
When you think we are mistaken, please respond, and clarify, and we will gladly reopen this.
