### ISSUE TITLE
Local Markdown images

### ISSUE THREAD

**Issue by stevermeister** [scullyio/scully#565]
### Description

I suddenly found that current markdown parser tries to parse all the files in the folder, not only **.md** (could be also taken as a **bug**)
I want to keep **images** together with **.md** files like: 
![Screenshot 2020-05-20 at 17 35 57](https://user-images.githubusercontent.com/1526680/82466195-62310700-9ac0-11ea-95d5-13a314369225.png)

### Describe the solution you'd like

Ideally, it will get the image and put it to the assets folder in a build stage(keeping the correct link). 

I would love to help with PR, just give me a hint where it is.

**Comment by stevermeister** [comment]
I found there is an option to create my own **fileHandler** plugins, so at least I can skip the error:

```
const {registerPlugin} = require('@scullyio/scully');

function imageFilePlugin(raw) {
  return Promise.resolve('file');
}
// DO NOT FORGET TO REGISTER THE PLUGIN
registerPlugin('fileHandler', 'png', imageFilePlugin);
registerPlugin('fileHandler', 'jpg', imageFilePlugin);
module.exports.imageFilePlugin = imageFilePlugin;
```

but still, I'm getting the only **rawContent**, without a file path. and it will be stored as **HTML file**. Can I keep the **extension** somehow?

**Comment by SanderElias** [comment]
@stevermeister I like that idea, but have currently no bandwidth to work on this. Currently the assumption is that all handed things are HTML. 
IIRC currently files that have no extension configured should be skipped by default. Will double-check this.

**Comment by stevermeister** [comment]
I found that there is a second parameter for fileHandler provided - **route**, that's great! So at least I can do such workaround: 

```
const { registerPlugin } = require("@scullyio/scully");
const fs = require("fs");

function imageFilePlugin(raw, route) {
  console.log(route);
  return new Promise((resolve) => {
    const src = route.templateFile;
    const dest = "./dist/static" + route.route + '.' + route.templateFile.split(".").pop();
    fs.copyFile(src, dest, (err) => {
        if (err) console.log(err);
        console.log(`${route.templateFile} was copied to ${dest}`);
        resolve('text');
      }
    );
  });
}
registerPlugin("fileHandler", "png", imageFilePlugin);
registerPlugin("fileHandler", "jpg", imageFilePlugin);
module.exports.imageFilePlugin = imageFilePlugin;
```

but still, in this case, I need to sync the image path with generated HTML, so ideally to have it out of the box.

**Comment by SanderElias** [comment]
@stevermeister What you need is some form of assets management. This is also on our radar.
There are many ways to sync with the HTML.
With your plugin you keep it in the same folder structure as the HTML (markdown).
You can then reference them using the `./imageName.png` in your markdown. 
I don't think that is a bad solution and will take this idea with me until I _do_ have some bandwidth

**Comment by stevermeister** [comment]
> You can then reference them using the ./imageName.png in your markdown.

Yes, true. But ideally, I would like to have valid md-file in editor mode (where all the images are shown)

now, I'm thinking that in addition to my `imageFilePlugin ` I can create one more portRender plugin that will update the links in HTML. (writing this line and praying that you would have time to fix it in core :) )

**Comment by SanderElias** [comment]
@stevermeister relative links are permitted in MD, and if the file is in the same folder, it should show in the editor you are using. VScode preview does this perfectly.

**Comment by stevermeister** [comment]
@SanderElias I was also thinking about relative links, but the challenge here is the Scully puts compiled md-file into own folder, so new structure is now: 

![Screenshot 2020-05-28 at 11 57 12](https://user-images.githubusercontent.com/1526680/83127871-f4e22f00-a0da-11ea-9dec-2494fe0a470f.png)

so now I need to do 
`../images/...` 
instead of 
`./images/...`

or copy files to that folder, but it's not yet there at the moment of imagePlugin execution. Keep trying...

**Comment by stevermeister** [comment]
for now, I decided to copy all the image in one root folder that will unblock me before "local images" are supported by Scully:

```
const { registerPlugin } = require("@scullyio/scully");
const fs = require("fs");

function imageFilePlugin(raw, route) {
  return new Promise((resolve) => {
    const src = route.templateFile;
    const dest = "./dist/static/images/" + route.data.sourceFile;
    fs.copyFile(src, dest, (err) => {
        if (err) console.log(err);
        console.log(`${route.templateFile} was copied to ${dest}`);
        resolve('');
      }
    );
  });
}

registerPlugin("fileHandler", "png", imageFilePlugin);
registerPlugin("fileHandler", "jpg", imageFilePlugin);
module.exports.imageFilePlugin = imageFilePlugin;
```

**Comment by stevermeister** [comment]
we definitely need a core solution here, just found that Scully put this images converted into MD-files to **this.scully.available$**

a bit more hardcode: 

```
  getArticles(): Observable<Article[]> {
    return this.scully.available$
      .pipe(map((articles: Article[]) => articles.filter((article: Article) =>
        article.sourceFile?.split('.').pop() === 'md'
      )));
  }
```

**Comment by SanderElias** [comment]
I will make sure non-recognized files will not get processed.
