### ISSUE TITLE
Unable to Change Blog Route

### ISSUE THREAD

**Issue by jtcrowson** [scullyio/scully#566]
### Description

Cannot generate a blog using any route other than `blog`.  

`ng generate @scullyio/init:markdown` works fine when the path is `blog`, but doesn't when path is anything else, like `docs` for example.

#### 🔬 Minimal Reproduction

1. `ng new scully-test`
2. `ng add @scullyio/init`
3. `ng generate @scullyio/init:markdown`
`? What name do you want to use for the module? docs`
`? What slug do you want for the markdown file? slug`
`? Where do you want to store your markdown files? docs`
`? Under which route do you want your files to be requested? docs`
4. `ng generate @scullyio/init:post --name="This is my post"`
`? What's the target folder for this post? docs`
5. Edit the new post to be published `true`:
```md
---
title: This is my post
description: blog description
published: true
---

# This is my post
```
6. Remove all the content in the `app.component.html` file, and add only the router outlet tag `<router-outlet></router-outlet>`
7. Generate a route entry point module:
`ng generate module home --route=home --module=app-routing`
8. Set the empty path attribute for the home route in `app-routing.module.ts`
```
const routes: Routes = [
  {
    path: 'docs',
    loadChildren: () => import('./docs/docs.module').then(m => m.DocsModule)
  },
  {
    path: '',
    loadChildren: () => import('./home/home.module').then(m => m.HomeModule)
  }
];
```
9. Inject the route service in the app component `ts` and `html` files:
```ts
import { Component, OnInit } from '@angular/core';
import { ScullyRoutesService } from '@scullyio/ng-lib';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  links$: Observable<any> = this.scully.available$;

  constructor(private scully: ScullyRoutesService) {}

  ngOnInit() {
    // debug current pages
    this.links$.subscribe(links => {
      console.log(links);
    });
  }
}
```
```html
<p>home works!</p>

<ul>
  <li *ngFor="let page of links$ | async">{{ page.route }}</li>
</ul>
```
10. Build, run, and serve:
`ng build && npm run scully && npm run scully serve`

<hr>

![image](https://user-images.githubusercontent.com/3779096/82481013-aad9c780-9aa2-11ea-91c7-e682c72a25af.png)

<hr>

![image](https://user-images.githubusercontent.com/3779096/82481039-b62cf300-9aa2-11ea-9621-be7e68e3a913.png)

<hr>

#### 💻Your Environment

**Angular Version:**

<pre><code>
9.1.7
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "0.0.28",
"@scullyio/ng-lib": "latest",
"@scullyio/scully": "latest",
</code></pre>

**Comment by jtcrowson** [comment]
Also, if this is a bug/feature, I'd be happy to work on it if a core team member points me in the right direction.

**Comment by jtcrowson** [comment]
Fixed by running `npm run scully -- --scanRoutes` before step 10.  Might be worth adding to the markdown documentation.  Would you like me to add it?

**Comment by SanderElias** [comment]
I'm going to close this, as there is no further action needed.
@jtcrowson You did change the routes in your angular app. Do you feel this message in the console isn't sufficient enough? 
![image](https://user-images.githubusercontent.com/1249083/83378460-0b3d0300-a3d9-11ea-8e3d-e03d79bfb775.png)
But feel free to add something to our documentation, we still need to improve/extend!
