### ISSUE TITLE
clear dist/static before building

### ISSUE THREAD

**Issue by hauner** [scullyio/scully#568]
### Description

It would be nice if scully would clear the `dist/static` folder before building. It is collecting obsolete files. :-)

<img width="306" alt="dist-static" src="https://user-images.githubusercontent.com/321864/82537863-0e1f3480-9b4b-11ea-9c15-08219dfa8cd0.png">

**Comment by SanderElias** [comment]
Use the command-line option `--removeStaticDist` to clear the dist folder before building.
Closing because this is an existing feature

**Comment by hauner** [comment]
Oh, sorry for the noise.  Looked for it but didn't find it the first time... ;-)

**Comment by SanderElias** [comment]
No problem!
