### ISSUE TITLE
Divide output files by application

### ISSUE THREAD

**Issue by kylecordes** [scullyio/scully#570]
## 🧩 Feature request

I added Scully to a Nx workspace. NX (and actually just based CLI) correctly configure the output in various subdirectories underneath dist so that things are divided up her project. It appears that Scully currently always uses dist/static, which does not support mult-iproject workspaces very well. 

Instead, it should use something like this:

`dist/scully/appname`

or similar.

**Comment by SanderElias** [comment]
You can set the `outDir` option in the config.ts, and have a different one for each project.
