### ISSUE TITLE
Access environment.ts from scully config file.

### ISSUE THREAD

**Issue by etavener** [scullyio/scully#571]
Hi,

Firstly I would like to say great work with Scully, it's fantastic! I've given up on complicated SSR for this easy peasy generator.

In my Scully config (I can see you recently changed it to be a ts file). I would like to be able to access values in the environment.ts file. This is where I keep my base URL's and I would like to be able to define my routes using the values in the environment.ts (I have some param information here used when calling the API's).

I understand that the config is a build script and the environment.ts is part of the app, but I would like to re-use this information in a nice way. I've currently got a '.env' file and pre-building an environment.ts file, it's not elegant and some of these values don't belong in environment variables.

Alternatively, if you know a way in which I can elegantly re-use the environment.ts in both the config and in the app, that would be nice.

Thanks again and keep up the excellent work!

**Comment by SanderElias** [comment]
You can import the environment file from your angular app in your config file directly. Make sure you import the correct one. Probably that is the `.prod` version
