### ISSUE TITLE
I can see the transferState escaped at the bottom of my html.

### ISSUE THREAD

**Issue by etavener** [scullyio/scully#572]
### Description
I've just implemented the `transferState` with my `http.get` requests.

However, I can now see all the escaped responses at the very bottom of the page. I think there is something wrong with the escaping. My data is coming from the Wordpress API.

#### 🔬 Minimal Reproduction
<pre>
<code>
function getData( URL: string, httpOptions?: any){
   let key = url;
   return this.state.getState( key ).pipe(
            switchMap( state => {
                if( state ) {
                    return of( state );
                }
                return this.http.get( url, httpOptions ).pipe(
                    map( response => this.state.setState( key, response ) )
                )
            })
   )
}
function getList(){
   return this.getData( `${WORDPRESS_API}/wp/v2/${type}`);
}
</code>
</pre>
#### 💻Your Environment

**Angular Version:**

<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Scully Version:**
<pre><code>

latest
@scullyio/init@0.0.26
@scullyio/ng-lib@0.0.22
@scullyio/scully@0.0.92

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by etavener** [comment]
I fixed it in the end. There was a script tag in a response (a big no no I know) coming from a WP endpoint. I had to do my own stringify / parse and escape and unescape. but you might want to make sure this is done properly from the service side.

In the end, I did the following:

return this.state.getState( key ).pipe(
            switchMap( (state: string) => {
                if( state && cache ) {
                    return of(  JSON.parse( unescape(state) ) );
                }
                return this.http.get( url, httpOptions ).pipe(
                    tap( (r: any) => {
                        if( cache ) {
                            this.state.setState(key, escape( JSON.stringify(r) ) );
                        }
                    } )
                )
            })
        )

**Comment by SanderElias** [comment]
The content in there is JSON data, and it should contain the least amount of state possible.
So, my question is this, you had HTML inside your JSON and that was causing issues? 
I would like to see a reproduction of that, so I can do some testing.

**Comment by etavener** [comment]
To explain a bit further. I am calling a list of posts from a WordPress API. 

On Wordpress I have a common plugin called 'Yoast SEO' installed. When I call the posts API it returns SEO data for each post as well as other properties.

Unfortunately, the Yoast property with a bunch of meta-information as HTML in a string. 

The issue is that this string also contains a  '..<script>....</script>'. The '</script>' closes your script tag.

Therefore, it's possible that the following alert would be executed on a site if this is stored as a value '</script><script>alert('something malicious here.');</script>'

I hope this all makes sense. And yep agree that I shouldn't be storing large amounts and definitely not script.

I would love to see an example of how to use the TransferState elegantly.

BTW. I'm loving Scully. Thanks!

**Comment by SanderElias** [comment]
Ok, I get the issue now. I'm not going to put in encoding right away, but next week I will do a small performance update, that might fix your issue too.
I'm going to close this now. If some has HTML content in their state, they should encode that before putting it into the state.
