### ISSUE TITLE
CI stage "npm run cypress:e2e:server" fails

### ISSUE THREAD

**Issue by evolkmann** [scullyio/scully#576]
### Description

In the GitHub Actions CI pipeline, the Cypress E2E Test fails because of missing browser:

#### 🔬 Minimal Reproduction

See example at https://github.com/scullyio/scully/pull/575/checks?check_run_id=701664156

## 🔥 Exception or Error

<pre><code>
Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system.

Available browsers found are: firefox, electron
</code></pre>

**Comment by SanderElias** [comment]
@evolkmann No clue what happened, I'll restart the tests. Will keep an eye on it.

**Comment by SanderElias** [comment]
That fixed it. Some fluke in GA. Closing for now, will keep an eye on this. if it happens a lot, we need to take some extra care there
