### ISSUE TITLE
Watchmode issue with MacOS mojave

### ISSUE THREAD

**Issue by jorgeucano** [scullyio/scully#583]
### Description

Kill the process with "ctrl+c" after press "r+intro"

#### 💻Your Environment

**Angular Version:**

<pre><code>

</code></pre>

**Scully Version:**

<pre><code>

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by SanderElias** [comment]
Closing as we found no way to reproduce this issue.
