### ISSUE TITLE
Improve scully.io pagespeed score?

### ISSUE THREAD

**Issue by hisham** [scullyio/scully#590]
### Description

Scully claims to be "wicked fast", but when I run your own scully.io site in pagespeed insights, the score is only 54/100. I would expect a "wicked fast" claim to be matched with a score of 90 or above. 

Perhaps improve the scully.io site or explain why only a 54 pagespeed score is achieved? 

## 📷Screenshot

<img width="724" alt="PageSpeed Insights 2020-05-28 17-16-20" src="https://user-images.githubusercontent.com/81853/83203573-f9244180-a106-11ea-8be6-d2e98a6581a7.png">

**Comment by hisham** [comment]
To be fair, Gastby's site is not a 90+ either, but is still better than Scully's: 

<img width="736" alt="PageSpeed Insights 2020-05-28 17-21-38" src="https://user-images.githubusercontent.com/81853/83203931-c7f84100-a107-11ea-9c20-5e6e44c2352d.png">

And here is Netlify: 

<img width="732" alt="PageSpeed Insights 2020-05-28 17-22-48" src="https://user-images.githubusercontent.com/81853/83203987-e8280000-a107-11ea-80e3-7817cbe426f2.png">

**Comment by msacket** [comment]
While I think PageSpeed is a useful metric, I'm not totally sold on its precision.  Multiple runs of any site yield wide-ranging results.  My runs of scully.io yield 69 for mobile and 92 for desktop.  In either case, for me, a cleared-cache run on both desktop and mobile yields nearly instantaneous renderings of the home page. Seems wicked fast to me.  I'm not sure why the number and timings within PageSpeed don't appear to match up my real world observations.

**Comment by SanderElias** [comment]
WIP #594.

**Comment by SanderElias** [comment]
![image](https://user-images.githubusercontent.com/1249083/83632500-ada6e300-a59f-11ea-979e-efd0c7525b26.png)
https://developers.google.com/speed/pagespeed/insights/?hl=nl&url=https%3A%2F%2Fscully.io%2F&tab=desktop

Fixed.
