### ISSUE TITLE
Log format - Errors summary

### ISSUE THREAD

**Issue by stevermeister** [scullyio/scully#591]
## 🧩 Feature request

I'm converting my old WP blog to Scully now, it's about 300+ MD-files. Scully shows errors for some of them, but when it's too much output in the console it's really hard to find all the errors (Even you highlight it orange, thank you). IT would be really convenient to have a summary of all the errors after.

**Comment by SanderElias** [comment]
@stevermeister This is on our radar, and the system is already geared up to do this.

**Comment by SanderElias** [comment]
this is closed by #597. 
By default, Scully now logs warnings to the file `scully.log` in the root folder.
