### ISSUE TITLE
Document why postRenders is overwriting defaultPostRenderers

### ISSUE THREAD

**Issue by samvloeberghs** [scullyio/scully#595]
### Description

Currently we can specifiy the post renderers via 2 options:

1. The `defaultPostRenderers` at the root level of the config
2. The `postRenderers` at the route level of the config.

For example

```js
const { RouteTypes, setPluginConfig } = require('@scullyio/scully');
const { MinifyHtml, MinifyHtmlOptions } = require('scully-plugin-minify-html');

const postRenderers = [MinifyHtml];

exports.config = {
  projectRoot: './src/app',
  defaultPostRenderers: postRenderers,
  routes: {
    '/blog/:slug': {
      type: RouteTypes.contentFolder,
      slug: {
        folder: "./blog"
      },
      postRenderers: postRenderers
    },
  }
};
```

This is the relevant code:
https://github.com/scullyio/scully/blob/23c8fcf740b15c8cb420c5dc1bc2ac7339edea83/libs/scully/src/lib/renderPlugins/executePlugins.ts#L10-L13

Would it be good to just implement this as :

```js
const handlers = [
    route.type,
    ...(scullyConfig.defaultPostRenderers ?? []),
    ...(route.postRenderers ?? [])
  ].filter(Boolean);
```

Where we just extend hierarchically? First the `defaultPostRenderers`, then the `postRenderers` of the related route.

#### 🔬 Minimal Reproduction

You can play around with these setup:
https://github.com/samvloeberghs/scully-universal

#### 💻Your Environment

**Angular Version:**

Latest

**Scully Version:**

Latest

**Comment by SanderElias** [comment]
@samvloeberghs We designed it this way. If you have a route that needs to be really different, you need to be able to dispose of the renderers that are set by default. 
Its going to be really complicated to serve all use-cases with automated behavior:
```typescript
const defaultPostRenderers = ['seoHrefOptimise'];
const sampleConf: ScullyConfig = {
  defaultPostRenderers,
  routes: {
     /** gets the default postrenderes */
    normalRoute: {
      type: 'default'
    }
    /** adds to the default postrenderes */
    someRoute: {
      type: 'default',
      postRenderers: [...defaultPostRenderers, 'myAddition']
    },
    /** removes the default postrenderes */
    someOtherRoute: {
      type: 'default',
      postRenderers: ['unique']
    }
  }
};
```
Yes, there is a risk that you will forget to add the `defaultPostRenderers`  (:raised_hand_with_fingers_splayed:  guilty!) but in my opinion,  the current way is more versatile., and already capable to do _all_ permutations possible.
Adding logic solves the forgetting part, but makes it harder to opt-out.

@aaronfrost and @jorgeucano can you chime in with your opinions

**Comment by samvloeberghs** [comment]
Sounds reasonable to me. Can we transform this ticket and keep it for adding documentation about this?

**Comment by SanderElias** [comment]
@GuzmanPI

**Comment by GuzmanPI** [comment]
> @GuzmanPI 

I'll work on it! 👍🏾

**Comment by SanderElias** [comment]
@GuzmanPI Assuming you took care of this in #605, I'm going to close this issue

**Comment by GuzmanPI** [comment]
I added this info to the docs.
