### ISSUE TITLE
Tooling to automate a scully run.

### ISSUE THREAD

**Issue by SanderElias** [scullyio/scully#614]
### Description

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
We need a tool/schematic that builds everything a scully-run needs, and then runs scully.
Bonus: auto-deploy hook.

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

Goal Deliverable: EOD 2020-07-02

**Comment by koshyviv** [comment]
Is there a way to currently automate those builds, or generate the static files alone?
