### ISSUE TITLE
Ability Update a specific route and not all routes

### ISSUE THREAD

**Issue by etavener** [scullyio/scully#618]
### Description
I'm implementing Scully for a very large application. It currently has 1200+ pages and the API's take a while. In fact it takes 1 hour and 5 mins to generate a static version of the site. However, sometimes only one page has been updated due to a content change.

### Describe the solution you'd like

- provide scully with a single route param via cli. This would trigger an update just for that route. Also if a high level route it could trigger updates for child routes as well (maybe another param).

- Also, you currently store the `data.json` per page. I have api's that are shared across the site and it would be nice to have them more shared.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by SanderElias** [comment]
@etavener Have you seen the `--baseFilter` option?
It enables you to limit Scully to only generate to a single unhandled route.
In the planning is an option to do the same for handledRoutes. That will allow for even more granularity.

**Comment by SanderElias** [comment]
closed by #623
