### ISSUE TITLE
Add outDir to default scully.config.js

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#62]
# 🧩 Feature request
When I run the schematic to add scully, and it generates a `scully.config.js`, we need to add the outDir to the scully.config.js when it is generated. 

Also, we need to warn them if the provide a config that doesn't have an outDir and the warning needs to tell them where we will put the output.

**Comment by Splaktar** [comment]
The error message seems to indicate that the option should be `outFolder`?

> The option outFolder isn't configures, we are using "/Users/splaktar/Git/.../dist/static/ by default now"
Cleaned up /Users/splaktar/Git/.../dist/static folder.

Adding that to my config, seems to have stopped the message:
```js
exports.config = {
  projectRoot: "./src/app",
  outFolder: "./dist/static",
  routes: {}
}
```

> Cleaned up /Users/splaktar/Git/.../dist/static folder.

**Comment by SanderElias** [comment]
@Splaktar I will update the wording to be a bit more descriptive. 
Im not sure what happened, but this issue is dealt with, so I'm going to close it now
