### ISSUE TITLE
Scully Generated NavList component + accidental Docs redesign

### ISSUE THREAD

**Issue by donmckenna** [scullyio/scully#630]
## 🗄️ Docs report

Hello everyone.
I started building a component which was supposed to snap into the current Scully docs, and would generate a hierarchical nested navigation list of all `ScullyRoutesService.available$` pages, and various levels of customizability to the links and nested parent/child structure.

However, one thing led to another and I ended up reworking the Scully docs themselves.

I've laid my idea out as thoroughly and clear as I can at the moment in this repo:
https://github.com/donmckenna/scully-docs-navlist-redesign
..and you can see a live version of what I'm talking about here:
https://boring-benz-f40cbd.netlify.app/

I didn't intend to make this into a giant project, but trying to rethink the navigation system for my component idea ended up going down the slippery slope of "if this, then may as well this", and "well if **this**, may as well **that**".

Regardless though, I hope it can be a constructive addition / suggestion for the Scully docs and help others learn the library and contribute to the docs as smoothly as possible.
Thoughts?

**Comment by SanderElias** [comment]
@donmckenna, We love your redesign. 
I might need to rework it so it can work without JS, as we love to push out the documentation as HTML/CSS only (perhaps a few Kb of js, but certainly not the entire app)
A side-note, we have done quite some work on text, and moved around some content in the markdown files, could you pull those changes in. (preferably after #634 is pulled in)

**Comment by donmckenna** [comment]
That's great, thanks Sander :)

Yes, HTML/CSS only is an appropriate goal.
However then, what would be the best way for the navigation component to function?
It uses JS to be aware of the current route and open the corresponding nested `ul`s, which currently use Angular animations with `*ngIf`s.

Everything else is pretty static already so that component is my only concern, figuring out how it can remain "aware" of the current route and offer visual feedback on user interactions, without JS.
Or if it actually does need minimal JS, how would that be implemented in a compiled Scully app?

Yes for sure, I'll monitor the status of #634 and comb through the updated markdown files to include any changes since my version.

Once I have a better idea on how to proceed with the "dynamic" navigation with only/minimal HTML/CSS, I'll work it all into an actual PR.

**Comment by SanderElias** [comment]
I worked with @donmckenna on some techniques to make the NavList CSS only. 
That will be incorporated, so we can keep the docs free of JS
