### ISSUE TITLE
Question: about Schematic tests not launched during ci / build

### ISSUE THREAD

**Issue by atao60** [scullyio/scully#633]
tests defined under libs/scully-schematics are not launched during ci / build (see .github/workflows/nodejs.yml).
Is it intentional?

**Comment by jorgeucano** [comment]
Yes, because the schematics are not part of the flow... 
When any change the schematics, we use the test for approval or not.

**Comment by atao-web** [comment]
I'm not sure to understand what is the "flow" but OK.

**Comment by atao-web** [comment]
Sorry for this afterwit, my question'd have been: why the schematics are not part of the workflow?

**Comment by atao60** [comment]
Sorry for this afterwit, my question'd have been: why the schematics are not part of the workflow?
