### ISSUE TITLE
Replace Event with Custom Event 

### ISSUE THREAD

**Issue by montella1507** [scullyio/scully#635]
## 🐞 Bug report
Scully doesnt work in IE11 in serve time- it is not good, because you usuallly need to "code" your static page in IE11 compatiblity mode. And it is not possible. 

Scully uses (maybe only in IdleMonitorService so you can just put it out from build in SERVE time and include only in Build time?)  `new Event` which is not supported and is not possible to polyfill in IE11.

Solution #1- replace with CutomEvent + CustomEvent polyfill for IE11:

```
  private initApp = new Event('AngularInitialized', {
    bubbles: true,
    cancelable: false
  });
```

-> 

```
private initApp = document.createEvent('CustomEvent');
initApp.initCustomEvent('AngularInitialized', true, false);
```

Solutin #2 - if new Event is used only in  IdleMonitor - maby it should not be part of "serve" time build, because it is only needed to determine if site is stable and can be rendered?

**Comment by SanderElias** [comment]
This is a known issue with IE, you need to load the polyfills for the events. 
Its is explained in detail in one of the other closed issues

**Comment by montella1507** [comment]
> This is a known issue with IE, you need to load the polyfills for the events.
> Its is explained in detail in one of the other closed issues

i am pretty sure you HAVE NOT solved that issue..

You suggested to use CustomEvent polyfiil - however - it works if u use  document.createEvent('CustomEvent') but you didnt use this - you are doing new Event() = it is not solved by CustomEvent polyfill.. just try to use your Polyfill you have pasted and try to call "new Event() in IE" .. PLEASE.
