### ISSUE TITLE
Scully fails to render route from component with no styles/styleUrls defined

### ISSUE THREAD

**Issue by brandonroberts** [scullyio/scully#637]
### Description

Running Scully with a component that doesn't include a `styles` or `styleUrls` property in the component decorator metadata fails to render the content.
I came across this issue while making single-file components, and removing unused properties from the component decorator metadata.

#### 🔬 Minimal Reproduction

https://github.com/brandonroberts/scully-styles-bug

1. Clone repo
2. Install dependencies with yarn
3. Note that `src/app/blog/blog.component.ts` is missing a `styles` or `styleUrls` property in the component metadata
4. Run `ng build`
5. Run `npm run scully`
6. Note that scully fails to render the `blog` page because it can't find `<scully-content>`
7. Open `src/app/blog/blog.component.ts` and add `styles: ['']` to component metadata
8. Run `ng build`
9. Run `npm run scully`
10. Note that Scully completes successfully

It also fails if `styles` is defined as an empty array.

#### 💻Your Environment

**Angular Version:**

<pre><code>

    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.9
Node: 12.18.0
OS: linux x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cli                      9.1.9
@ngtools/webpack                  9.1.9
@schematics/angular               9.1.9
@schematics/update                0.901.9
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Scully Version:**

<pre><code>

{
  "name": "scully-styles-bug",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.11",
    "@angular/common": "~9.1.11",
    "@angular/compiler": "~9.1.11",
    "@angular/core": "~9.1.11",
    "@angular/forms": "~9.1.11",
    "@angular/platform-browser": "~9.1.11",
    "@angular/platform-browser-dynamic": "~9.1.11",
    "@angular/router": "~9.1.11",
    "@scullyio/init": "0.0.28",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.9",
    "@angular/cli": "~9.1.9",
    "@angular/compiler-cli": "~9.1.11",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
</code></pre>

## 🔥 Exception or Error

<pre><code>

 ☺   new Angular build imported
Background servers already running.
Finding all routes in application.

----------------------------------
Using stored unhandled routes!.
   To discover new routes in the angular app use "npm run scully -- --scanRoutes"
----------------------------------
Pull in data to create additional routes.
Finding files in folder "./blog"
Route list created in files:
  "./dist/static/assets/scully-routes.json",
  "/home/robertsbt/projects/scully-styles-bug/dist/scully-styles-bug/assets/scully-routes.json",
  "/home/robertsbt/projects/scully-styles-bug/src/assets/scully-routes.json"

Route "" rendered into file: "./dist/static/index.html"
Route "/home" rendered into file: "./dist/static/home/index.html"

        ----------------
        Error, missing "<scully-content>" in route "/blog/___UNPUBLISHED___kbk617eb_MdeHUgI6aHEdhvLWRXpT6lE7p3NOJTSI"
        without <scully-content> we can not render this route.
        Make sure it is in there, and not inside any conditionals (*ngIf)
        You can check this by opening "http://localhost:4200//blog/___UNPUBLISHED___kbk617eb_MdeHUgI6aHEdhvLWRXpT6lE7p3NOJTSI"
        when you serve your app with ng serve and then in the browsers console run:
        document.querySelector('scully-content')
        ----------------
        
DOMException {}
Route "/blog/___UNPUBLISHED___kbk617eb_MdeHUgI6aHEdhvLWRXpT6lE7p3NOJTSI" rendered into file: "./dist/static/blog/___UNPUBLISHED___kbk617eb_MdeHUgI6aHEdhvLWRXpT6lE7p3NOJTSI/index.html"
send reload

Generating took 2.8 seconds for 3 pages:
  That is 1.07 pages per second,
  or 936 milliseconds for each page.
  
  Finding routes in the angular app took 1 milliseconds
  Pulling in route-data took 16 milliseconds
  Rendering the pages took 2.06 seconds

</code></pre>

**Comment by SanderElias** [comment]
I pushed a new version to npm that has this fixed
