### ISSUE TITLE
Scully Build : unable to get html page contents. Only pre rendering the new routes.

### ISSUE THREAD

**Issue by phoEnix-511** [scullyio/scully#643]
![Screenshot_20200622-193805](https://user-images.githubusercontent.com/50960590/85297205-1955df00-b4c0-11ea-928c-fa66df155ae2.jpg)
Getting the same error for all the old routes. The html pages doesnt contain the content of the components on the route. 

> @angular/cdk": "^9.2.0",
    "@angular/common": "^9.0.1",
    "@angular/compiler": "^9.0.1",
    "@angular/core": "^9.0.1",
    "@angular/forms": "^9.0.1",
    "@angular/material": "9.2.0",
    "@angular/platform-browser": "^9.0.1",
    "@angular/platform-browser-dynamic": "^9.0.1",
    "@angular/platform-server": "^9.0.1",
    "@angular/router": "^9.0.1",
    "@angular/service-worker": "^9.0.1",
    "@nguniversal/express-engine": "^9.0.0",
    "@scullyio/init": "latest",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
    "@syncfusion/ej2-angular-richtexteditor": "^18.1.52",
    "@types/express": "^4.0.36",
    "@types/lodash": "^4.14.70",

**Comment by SanderElias** [comment]
You might be depending on old behavior from the way routes where rendered.
This might be solved by using the `handle404` `baseOnly` option that is introduced in #644
this will be merged soon, and I will push out a new version when that is done.
Let me know if that helps

**Comment by phoEnix-511** [comment]
Done. Thanks @SanderElias

**Comment by etavener** [comment]
@SanderElias just to make you aware I think the publish you did for v0.0.65 was corrupt. It only serves the home page and looking inside the node package publish a load of your code (that you added for my fix) is commented out.

**Comment by SanderElias** [comment]
@etavener Yeah, I don't know what happened, I need to fix the failing test in #644  (it only fails on GA, not locally)  When that's done I'll emerge it an put out a new version.
