### ISSUE TITLE
0.0.97 'npm run scully:serve' not serving any page other than home.

### ISSUE THREAD

**Issue by etavener** [scullyio/scully#646]
## 🐞 Bug report
Really sorry for being a pain. but the latest release 0.0.97 only serves the homepage on the Angular app when doing `npm run scully:serve`.

It looks like a 404 option has been added, but by default (without setting this 404 to index) a basic Angular route (with no params) in the app is not served and therefore an error is created in the static page.

#### 💻Your Environment

**Angular Version:**
<pre><code>
9
</code></pre>
**Scully Version:**
<pre><code>
0.0.97 
</code></pre>

## 🔥 Exception or Error
<pre><code>
Route "/faq" not provided by angular app
</code></pre>

**Comment by jtcrowson** [comment]
@etavener This should be fixed in the latest released version, `0.0.98`.

**Comment by etavener** [comment]
Yep, just tried it. I will close this issue.
