### ISSUE TITLE
routes.json get all the images

### ISSUE THREAD

**Issue by stevermeister** [scullyio/scully#653]
## 🐞 Bug report

Scully already knows how to ignore all files except *.md, but it still adds all these exceptions to compiled routes.json file.

**Comment by SanderElias** [comment]
I looked at this, and when I add more images to the scully-blog test suite, those are just ignored

**Comment by SanderElias** [comment]
Closing this, as I can't reproduce. When you can a file-plugin that handles image types, this will make Scully try to process them
