### ISSUE TITLE
Route parameters by a list

### ISSUE THREAD

**Issue by miloshavlicek** [scullyio/scully#659]
### Description

Hi, I am not able to find in documentation how to configure parameters in route directly by a list, something like this:
```typescript
export const config: ScullyConfig = {
  routes: {
    "/:lang": {
      lang: ['en', 'de', 'fr', 'cz'],
    },
};
```

Or, is it not possible?

**Comment by kylecordes** [comment]
I don’t think there is such a feature yet, but this would be a great thing to add. In an experiment (which unfortunately I have misplaced rather than published) I had some snippet that did a plug-in which just had a hardcoded list of values rather than fetching them from somewhere.

**Comment by SanderElias** [comment]
@miloshavlicek You can install the [`from-data`](https://github.com/scullyio/scully/tree/main/libs/plugins/from-data) plugin, which does almost this. You can take a look on how its done, and adapt and publish a new plugin that does exactly what you want

**Comment by amycdurbin** [comment]
Close due to inactivity.
