### ISSUE TITLE
Add a way for router plugins to modify the postrender array for a single route

### ISSUE THREAD

**Issue by jorgeucano** [scullyio/scully#664]
### Description

Add a way for router plugins to modify the postrender array for a single route (possibly add postRenderers to the handledRoute)

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by amycdurbin** [comment]
This is done and already worked. You can modify post renderers for any HandledRoute
