### ISSUE TITLE
Support for non-html routes (for example images)

### ISSUE THREAD

**Issue by jorgeucano** [scullyio/scully#670]
### Description

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by aaronfrost** [comment]
This is for things like image optimization, assets management. Things we don't need now, but will need in the future. Possibly make this a postRenderer.

**Comment by aaronfrost** [comment]
Consider image optimization as it's own ticket. Look it the Gatsby image optimization plugins and see how we can make that work with Scully.

**Comment by jorgeucano** [comment]
Create a way to have a different flow... If we have an Image route don't use the normal render (puppeteer ) to use the image render.

- https://www.gatsbyjs.com/plugins/gatsby-image/
- https://www.gatsbyjs.com/docs/preoptimizing-images/
