### ISSUE TITLE
Dynamic metatags

### ISSUE THREAD

**Issue by bart-haasbroek** [scullyio/scully#676]
Hey,
First of all, nice job for creating this generator! As an angular developer i am really excited!
I am wondering if it is possible to generate/add meta tags (description, keywords etc) and the page title dynamically. I want to change it based on the data i fetched from an api.
For example, i use `this.title.setTitle('my test title')` to change the page title but i don't see the change in the generated pages.

i'm aware that you can add a render plugin for changing html but as far as I know you can't use the data fetched from the api.

**Comment by SanderElias** [comment]
@bart-haasbroek You can use the Angular title and meta service. Those are picked up by Scully and do render into the HTML files. 

However, you need to have this done before your app hits "idle". In the default settings, Scully will take the snapshot of the HTML 2 event cycles after the last HTTP call is done. 

In your plugins you can do everything node can do, so fetching data is possible. We even provide a `httpGetJson` utility function that can do simple requests.

I'm closing this now, as there seems no actionable Scully context, but feel free to comment in here, and we will reopen if needed.
