### ISSUE TITLE
Routing is being forced to follow a strict structure

### ISSUE THREAD

**Issue by geometricpanda** [scullyio/scully#679]
### Description
When trying to render a blog, routing must be past in as an array of objects, not an array with a pointer to an object. This seems a bit prescriptive.

#### 🔬 Minimal Reproduction

in `app-routing` change

```ts
const routes: Routes = [
  {
    path: 'blog',
    loadChildren: () => import('./blog/blog.module').then(m => m.BlogModule),
  }
];
```

to 

```ts
const blog: Route = {
  path: 'blog',
  loadChildren: () => import('./blog/blog.module').then(m => m.BlogModule),
};

const routes: Routes = [
  blog,
];
```

and the following error happens upon rebuild:

```sh
No configuration for route "/:slug" found. Skipping
```

#### 💻Your Environment

**Angular Version:**

<pre><code>     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 14.2.0
OS: darwin x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0</code></pre>

**Scully Version:**

<pre><code>"@scullyio/init": "0.0.28",
"@scullyio/ng-lib": "latest",
"@scullyio/scully": "latest",</code></pre>

## 🔥 Exception or Error

<pre><code>No configuration for route "/:slug" found. Skipping</code></pre>

**Comment by SanderElias** [comment]
This is a restriction of Guess-Parser.  Without a static structure, it's near impossible to statically analyze the routes.
You might want to discuss this in the guess-parser repo.

I'm going to close this, as there is no Scully related actionable context in here. Feel free to engage the conversation in the closed issue. If needed we can always reopen the issue.
