### ISSUE TITLE
make particular routes scully static not complete app.

### ISSUE THREAD

**Issue by awais2080** [scullyio/scully#692]
### Description

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by SanderElias** [comment]
I'm going to close this because I think this is answered in our FAQ page: [Ignore routes without config?](https://scully.io/docs/faq/).

If that doesn't answer your question, respond in here, and we can reopen.
