### ISSUE TITLE
assets/scully-routes.json not found when using baseHref option

### ISSUE THREAD

**Issue by rpd10** [scullyio/scully#694]
### Description
When deploying to GitHub Pages, I need to pass `--base-href /my-project-name/` in order to set the `<base>` tag used for loading static assets in Angular.  I cannot find a way to configure Scully with the same base.  When loading the published page, Scully makes a request to https://<user>.github.io/assets/scully-routes.json - instead it needs to request https://<user>.github.io/<project-name>/assets/scully-routes.json

I would be willing to submit a PR for this.  My initial thought is that `ScullyRoutesService` should optionally inject APP_BASE_HREF and if provided, use that value when fetching the scully-routes.json

#### 🔬 Minimal Reproduction
https://github.com/rpd10/diehl-with-software/tree/live

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 9.1.0
Node: 12.18.1
OS: darwin x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "0.0.28",
    "@scullyio/ng-lib": "0.0.24",
    "@scullyio/scully": "0.0.98",
</code></pre>

**Comment by SanderElias** [comment]
@rpd10 Have you tried using the [Scully base-href-rewrite plugin](https://github.com/scullyio/scully/tree/main/libs/plugins/base-href-rewrite)?

**Comment by SanderElias** [comment]
@rpd10 Sorry, it seems there was a regression. I removed the starting `/` (in the above PR) to the Scully lib again.
That means it will use the `base-href` to find the file, solving this issue.

**Comment by rpd10** [comment]
Thanks, I noted the leading `/` yesterday when reading through the Angular docs.  I'll look forward to the next release.
