### ISSUE TITLE
Missing <scully-content> in route when building with baseHref

### ISSUE THREAD

**Issue by rpd10** [scullyio/scully#699]
### Description
I'm trying to deploy to GitHub pages, one of the prereqs is that you must specify the baseHref: https://angular.io/guide/deployment#deploy-to-github-pages

When I run `npm run build && npm run scully` locally, everything works correctly.  
When I run `npm run build -- --prod && npm run scully`, I receive the scully-content warning for my blog page, and the blog rendering fails.

If I modify angular.json and remove the baseHref option from the production deploy, the warning goes away, and rendering works.

#### 🔬 Minimal Reproduction
https://github.com/rpd10/diehl-with-software/tree/live

#### 💻Your Environment

**Angular Version:**

<pre><code>
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cdk                      9.2.4
@angular/cli                      9.1.0
@angular/material                 9.2.4
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.9
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "0.0.28",
    "@scullyio/ng-lib": "0.0.27",
    "@scullyio/scully": "0.0.99",
</code></pre>

## 🔥 Exception or Error

<pre><code>
  "./dist/static/assets/scully-routes.json",
  "/home/runner/work/diehl-with-software/diehl-with-software/dist/apps/web/assets/scully-routes.json",
  "/home/runner/work/diehl-with-software/diehl-with-software/apps/web/src/assets/scully-routes.json"

        ----------------
        Error, missing "<scully-content>" in route "/blog/angular-dynamic-environment-configuration"
        without <scully-content> we can not render this route.
        Make sure it is in there, and not inside any conditionals (*ngIf)
        You can check this by opening "http://localhost:4200//blog/angular-dynamic-environment-configuration"
        when you serve your app with ng serve and then in the browsers console run:
        document.querySelector('scully-content')
        ----------------
        
Route "/blog/angular-dynamic-environment-configuration" rendered into file: "./dist/static/blog/angular-dynamic-environment-configuration/index.html"
Route "" rendered into file: "./dist/static/index.html"
</code></pre>

**Comment by SanderElias** [comment]
@rpd10, We are going to discuss if adapting our internal server is what we need for this, this is actually just a matter of settings.
You should _not set this in the `angular.json`, but instead use out [base-href-rewrite plugin](https://github.com/scullyio/scully/tree/main/libs/plugins/base-href-rewrite) to modify the base-href, after we are done processing the app.
