### ISSUE TITLE
Compatibility with ngx-translate-router

### ISSUE THREAD

**Issue by miloshavlicek** [scullyio/scully#700]
### Description

At this time, when I run:
```
npm run scully -- --scanRoutes
```
with [ngx-translate-router](https://github.com/gilsdav/ngx-translate-router) installed and two languages configured (cz, en), output to scully-routes.json is:
`[{"route":"/"},{"route":"/for-dealers"},{"route":"/sign-in"}]`

Expected output is:
`[{"route":"/cz"},{"route":"/cz/pro-obchodniky"},{"route":"/cz/prihlaseni"},{"route":"/en"},{"route":"/en/for-dealers"},{"route":"/en/sign-in"}]`

### Describe the solution you'd like

Ability to implement ngx-translate-router router interceptor.

### Describe alternatives you've considered

I don't know any workaround for this issue.

**Comment by SanderElias** [comment]
This can be handled as outlined in [our FAQ](https://scully.io/docs/faq/).

**Comment by miloshavlicek** [comment]
> This can be handled as outlined in [our FAQ](https://scully.io/docs/faq/).

It doesn't solve my problem, because .config.ts is static, so I am not able to inject LocalizeRouterService from @gilsdav/ngx-translate-router to translate all routes.

**Comment by SanderElias** [comment]
There is a limited amount of languages (2 in your case). You can iterate over this in your config like I showed in the FAQ. Perhaps I'm not understanding your issue right, so can you provide a repo where I can inspect the issue?

**Comment by SanderElias** [comment]
@miloshavlicek We just discussed this issue in our team, and I now understand what you were trying to ask.
Sorry for closing after misunderstanding the question. 
The main issue here is that the guess-parser we use doesn't see/understand  ngx-translate-router. So we will never get the routes out of the application fully automatic.
Probably we need to have an extra type of plugin for this, so you we can expand the found routes with some custom logic.  I will be looking into this in the coming week.

**Comment by miloshavlicek** [comment]
@SanderElias Thank you so much for your time! I am open to create an plugin, however I don't have any idea how to solve the think with config file (static context),
My implementation is here (as an example your requested from me): https://github.com/cothema/sales-website/tree/dev-ngx

**Comment by gilsdav** [comment]
@SanderElias
1) Is it possible to intercept every routes in a router plugin ?
 ```
routes: {
     "**": {
         type: NgxTranslateRouter
     }
 }
```
2) Is it possible to apply priority on routes management ? (to be sure mine is the latest called and have result of every previous router plugins)
```
routes: {
    "/blog/:slug": {
        type: "json"
        priority: 1
     }
     "**": {
         type: NgxTranslateRouter
         priority: 2
     }
 }
```

**Comment by aaronfrost** [comment]
I think we are talking about doing a separate type of plugin. A `post-route-discovery` but `pre-rendering` plugin. A plugin that would be passed all of the discovered routes + the extraRoutes. 

We need some time to solve the i18n story here, though. We can do it.

**Comment by gilsdav** [comment]
Yes exactly, a little like the post-route-discovery but where we can **manipulate** the given routes (routes + extraRoutes).
This new plugin type need to be executed **before** the existing post-route-discovery.
And to be fully usable we need to be able to choose an execution priority if we use multiple plugins of this type.

**Comment by aaronfrost** [comment]
Execution priority would be left to right, same as the rest.

**Comment by gilsdav** [comment]
@SanderElias It doesn't seems to work correctly: https://github.com/gilsdav/ngx-translate-router/issues/71#issuecomment-657606064
