### ISSUE TITLE
Add express router to handle different base-href's

### ISSUE THREAD

**Issue by SanderElias** [scullyio/scully#701]
To prevent issues like #699, and make handling of multi-language sites easier

**Comment by atao60** [comment]
Why this issue has been closed?

**Comment by SanderElias** [comment]
@atao60 because its solved?

**Comment by atao60** [comment]
I'm still struggling to deploy a scully blog on gh-pages, using @scullyio/scully-plugin-base-href-rewrite. It seems related to the way I organized the angular components. 
As #1088 is also closed, as soon as I'll have narrowed the case, i'll probablbly open a new issue.

**Comment by SanderElias** [comment]
@atao60 Please do. If you have something we can reproduce, it helps also understanding the issue!
