### ISSUE TITLE
base-href-rewrite-plugin error - Plugin "baseHrefRewrite" of type "undefined" is not found, can not store config

### ISSUE THREAD

**Issue by rpd10** [scullyio/scully#706]
### Description
Following the guide here: https://github.com/scullyio/scully/tree/main/libs/plugins/base-href-rewrite I'm trying to add the base-href-rewrite-plugin for all routes.  Running `npm run scully` fails with `Plugin "baseHrefRewrite" of type "undefined" is not found, can not store config`.

#### 🔬 Minimal Reproduction
<pre><code>
import { ScullyConfig, setPluginConfig } from '@scullyio/scully';
import { baseHrefRewrite } from '@scullyio/scully-plugin-base-href-rewrite';

const defaultPostRenderers = ['seoHrefOptimise', baseHrefRewrite];
setPluginConfig(baseHrefRewrite, { href: '/diehl-with-software/' });
export const config: ScullyConfig = {
  projectRoot: './apps/web/src',
  projectName: 'web',
  outDir: './dist/static',
  defaultPostRenderers,
  routes: {
    '/blog/:slug': {
      type: 'contentFolder',
      slug: {
        folder: './blog',
      },
    },
  },
};

</code></pre>

#### 💻Your Environment

**Angular Version:**

<pre><code>
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.1.9
@angular/cdk                      9.2.4
@angular/cli                      9.1.0
@angular/material                 9.2.4
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.9
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "0.0.28",
    "@scullyio/ng-lib": "0.0.27",
    "@scullyio/scully": "0.0.99",
</code></pre>

## 🔥 Exception or Error

<pre><code>
npm run scully

> @rpd10/diehl-with-software@0.0.0 scully /Users/rpd10/Projects/github.com/diehl-with-software
> scully

/Users/rpd10/Projects/github.com/diehl-with-software /Users/rpd10/Projects/github.com/diehl-with-software
0.0.93
Plugin "baseHrefRewrite" of type "undefined" is not found, can not store config
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! @rpd10/diehl-with-software@0.0.0 scully: `scully`
npm ERR! Exit status 15
</code></pre>

**Comment by SanderElias** [comment]
I puhsed a new version of the plugin to pm. @rpd10 can you give that a try?

**Comment by rpd10** [comment]
Thanks, that worked perfectly for me!
