### ISSUE TITLE
Landing page broken links

### ISSUE THREAD

**Issue by GuzmanPI** [scullyio/scully#710]
## 🗄️ Docs report

Landing page books links are broken

### Description

When clicking on the Book links nothing happens.

## 🔬 Minimal Reproduction

N/A

### What's the affected URL?\*\*

https://scully.io/

### Reproduction Steps\*\*

N/A

### Expected vs Actual Behavior\*\*

The links should redirect to a proper route

## 📷Screenshot

![scully-docs-bug](https://user-images.githubusercontent.com/4933011/86933024-b55a2a00-c0ff-11ea-9ad5-e5c3e68e25c8.png)

## 🔥 Exception or Error

N/A

</code></pre>

## 🌍 Your Environment

N/A

### Browser info

N/A

### Anything else relevant?

N/A

**Comment by geromegrignon** [comment]
@GuzmanPI By checking the links on the landing page, i noticed there is no existing route for the 'Contribute' button

**Comment by aaronfrost** [comment]
@GuzmanPI make sure we get another ticket for what Gerome is saying.

**Comment by geromegrignon** [comment]
@aaronfrost @GuzmanPI i opened #719 for the Contribute link.

**Comment by SanderElias** [comment]
@GuzmanPI Is this done?
