### ISSUE TITLE
Landing page features cards in small screens

### ISSUE THREAD

**Issue by GuzmanPI** [scullyio/scully#711]
### Description

The landing page cards in the "Features"section loos the bottom margin in small devices.

## 🔬 Minimal Reproduction

N/A

### What's the affected URL?\*\*

https://scully.io/

### Reproduction Steps\*\*

N/A

### Expected vs Actual Behavior\*\*

The cards should have a bottom margin despite the screen size

## 📷Screenshot

![cards-bug](https://user-images.githubusercontent.com/4933011/86934027-d5d6b400-c100-11ea-95a0-d15848f40711.png)

## 🔥 Exception or Error

N/A

</code></pre>

## 🌍 Your Environment

N/A

### Browser info

N/A

### Anything else relevant?

N/A

**Comment by jorgeucano** [comment]
@GuzmanPI Can you check the PR from @geromegrignon #709 ... He did fix that
