### ISSUE TITLE
Docs site navigation menu not responsive

### ISSUE THREAD

**Issue by GuzmanPI** [scullyio/scully#712]
### Description

The docs website's navigation menu is not responsive.

## 🔬 Minimal Reproduction

N/A

### What's the affected URL?\*\*

Docs website

### Reproduction Steps\*\*

N/A

### Expected vs Actual Behavior\*\*

The navigation menu should be responsive

## 📷Screenshot

![nav-bug](https://user-images.githubusercontent.com/4933011/86934872-da4f9c80-c101-11ea-8b56-7a7039a90c42.png)

## 🔥 Exception or Error

N/A

## 🌍 Your Environment

N/A

### Browser info

N/A

### Anything else relevant?

N/A

**Comment by jorgeucano** [comment]
@GuzmanPI Can you check the PR from @geromegrignon #709 ... He did fix that
