### ISSUE TITLE
Side-menu not responsive

### ISSUE THREAD

**Issue by GuzmanPI** [scullyio/scully#713]
### Description

The docs website's side-menu is not responsive

## 🔬 Minimal Reproduction

N/A

### What's the affected URL?\*\*

All but landing page

### Reproduction Steps\*\*

N/A

### Expected vs Actual Behavior\*\*

The side-menu should be responsive and it should provide the means to be closed/open in large screens

## 📷Screenshot

![side-menu-bug](https://user-images.githubusercontent.com/4933011/86935617-a4f77e80-c102-11ea-8210-da4306a58e3f.png)

## 🔥 Exception or Error

N/A

</code></pre>

## 🌍 Your Environment

N/A

### Browser info

N/A

### Anything else relevant?

N/A

**Comment by amycdurbin** [comment]
Goal Deliverable: 2020-07-13

**Comment by jorgeucano** [comment]
@GuzmanPI Can you check the PR from @geromegrignon https://github.com/scullyio/scully/pull/709 ... He did fix that
