### ISSUE TITLE
Is scully --help a joke ?

### ISSUE THREAD

**Issue by gilsdav** [scullyio/scully#716]
### Description

By using the command `scully --help` it explain how to use `scully --help` command itself and nothing others

![image](https://user-images.githubusercontent.com/21348530/86966409-6e088380-c169-11ea-873a-726c838788f8.png)

### Expected behavior

Having the liste commands available here https://scully.io/docs/scully-cmd-line/ with details.

## 🌍 Your Environment

Scully 0.0.99
Node 12

**Comment by aaronfrost** [comment]
This is a great call out. We should fix this.

**Comment by jorgeucano** [comment]
It is a yargs error really ... There are all the descriptions added to explain each of the commands, I am going to check what happened and why yargs is showing that ..

**Comment by SanderElias** [comment]
closed by #728
