### ISSUE TITLE
Docs: unexpected dash visible

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#718]
### Description

The AppCode component contains the language of the code snippet as a title.
The format is : language-**language name**

As it doesn't make sense to display 'language-', it's hidden.
But the dash is still partially visible.

## 🔬 Minimal Reproduction

Navigate on any page of https://scully.io which contains a code snippet.

### What's the affected URL?\*\*

Navigate on any page of https://scully.io which contains a code snippet.

### Expected vs Actual Behavior\*\*

Actual : 
![image](https://user-images.githubusercontent.com/32737308/87025348-8fee1e80-c1da-11ea-929d-a4e88c92631c.png)

Expected :
![image](https://user-images.githubusercontent.com/32737308/87026272-cd9f7700-c1db-11ea-8eab-4539ad030d03.png)

## 📷Screenshot

![image](https://user-images.githubusercontent.com/32737308/87025348-8fee1e80-c1da-11ea-929d-a4e88c92631c.png)

### Browser info

Reproduced on Chrome, Firefox and Safari

**Comment by geromegrignon** [comment]
fixed by #709

**Comment by SanderElias** [comment]
Done by #740
