### ISSUE TITLE
Missing content for the Contribute link

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#719]
### Description

There is no content for the *Contribute* link in the footer of the docs

### What's the affected URL?\*\*

https://scully.io/docs/CONTRIBUTING

### Reproduction Steps\*\*

Click on 'Contribute' in the footer of any page on https://scully.io
The landing page is loaded.

### Expected vs Actual Behavior\*\*

Actual : the landing page is loaded
Expected : a 'contribute' page is loaded

**Comment by msacket** [comment]
@GuzmanPI Have you started on this?  I'd be happy to work on it if you aren't in the middle of it.
