### ISSUE TITLE
Missing logos

### ISSUE THREAD

**Issue by GuzmanPI** [scullyio/scully#726]
### Description

Missing logos in the showcase page

## 🔬 Minimal Reproduction

N/A

### What's the affected URL?\*\*

https://scully.io/docs/showcase/

### Reproduction Steps\*\*

N/A

### Expected vs Actual Behavior\*\*

Showlogos

## 📷Screenshot

<img width="1600" alt="Screen Shot 2020-07-09 at 10 27 43" src="https://user-images.githubusercontent.com/4933011/87059408-e48b9c80-c1ce-11ea-8380-bbf37bfdd748.png">

## 🔥 Exception or Error

N/A

## 🌍 Your Environment

N/A

### Browser info

N/A

### Anything else relevant?

N/A

**Comment by jorgeucano** [comment]
duplicate #719
