### ISSUE TITLE
TypeErrors for @scullyio/scully-plugin-base-href-rewrite

### ISSUE THREAD

**Issue by kkweon** [scullyio/scully#731]
### Description

Thank you for the amazing project.

- Get type errors following the example
   - https://github.com/scullyio/scully/blame/main/libs/plugins/base-href-rewrite/README.md#L20-L32

Given my scully.my-project.config.ts,

```ts
import { ScullyConfig, setPluginConfig } from '@scullyio/scully'
import { baseHrefRewrite } from '@scullyio/scully-plugin-base-href-rewrite'

const defaultPostRenderers = ['seoHrefOptimise', baseHrefRewrite]
setPluginConfig(baseHrefRewrite, {
  href: '/json-to-protobuf',
})

export const config: ScullyConfig = {
  defaultPostRenderers,
  projectRoot: './src',
  projectName: 'json-to-protobuf',
  outDir: './dist/static',
  routes: {},
}
```

```shell
scully.json-to-protobuf.config.ts:5:17 - error TS2345: Argument of type 'unique symbol' is not assignable to parameter of type 'string'.

5 setPluginConfig(baseHrefRewrite, {
                  ~~~~~~~~~~~~~~~

scully.json-to-protobuf.config.ts:10:3 - error TS2322: Type '(string | symbol)[]' is not assignable to type 'string[]'.
  Type 'string | symbol' is not assignable to type 'string'.
    Type 'symbol' is not assignable to type 'string'.

10   defaultPostRenderers,
     ~~~~~~~~~~~~~~~~~~~~

  node_modules/@scullyio/scully/lib/utils/interfacesandenums.d.ts:18:5
    18     defaultPostRenderers?: string[];
           ~~~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'defaultPostRenderers' which is declared here on type 'ScullyConfig'
```

#### 🔬 Minimal Reproduction

```shell
cd $(mktemp -d)
git clone git@github.com:kkweon/json-to-protobuf.git
cd json-to-protobuf
git checkout feat-scully-bug-report-plugin-base-href-rewrite
yarn
tsc scully.json-to-protobuf.config.ts --noEmit
```

#### 💻Your Environment

**Angular Version:**

<pre><code>
❯ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.0.2
Node: 12.18.0
OS: darwin x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              10.0.2
@angular-devkit/schematics        10.0.2
@angular/cli                      10.0.2
@ngtools/webpack                  10.0.2
@schematics/angular               10.0.2
@schematics/update                0.1000.2
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "^0.0.29",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
    "@scullyio/scully-plugin-base-href-rewrite": "^0.0.2",
</code></pre>

## 🔥 Exception or Error

See above

**Comment by SanderElias** [comment]
Thanks for reporting. The PR is in the pipeline.
I pushed out Scully `.100` to pm, if you install that, the but is fixed.
