### ISSUE TITLE
cli: edge case where <!doctype html> is removed from dist/static/index.html

### ISSUE THREAD

**Issue by Splaktar** [scullyio/scully#74]
# 🐞 Bug report

### Description
In some edge cases, the `<!doctype html>` in `src/index.html` and `dist/web/index.html` is removed in the generated `dist/static/index.html`.

## 🔬 Minimal Reproduction
TBD. I reproduced this in one app, but not in a new CLI app. Investigating...

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 12.13.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@angular/cdk                      9.0.0-rc.6
@angular/fire                     5.2.3
@angular/material                 9.0.0-rc.6
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Scully Version:**
<pre><code>
    "@scullyio/init": "0.0.9",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
</code></pre>

## 🔥 Exception or Error
<pre><code>
Current document does not have a doctype. This may cause some Angular Material components not to behave as expected.
_checkDoctypeIsDefined @ vendor-es2015.js:84784
</code></pre>

**Comment by Splaktar** [comment]
I'm trying to debug this, but I am not sure exactly where to look. What code is actually used for processing the `src/index.html` file?

**Comment by SanderElias** [comment]
that is done by puppeteer. look in the pupeteerrenderer

**Comment by SanderElias** [comment]
@Splaktar can you reproduce this? If you can build a scenario that reproduces this, I will do the debugging and fix it.

**Comment by Splaktar** [comment]
It's reproducible, every time, in my project. I haven't been able to reproduce it in a brand new Angular CLI project (after some considerable time spent). I'll try to dig into the `PupeteerRenderer` on Thursday.

**Comment by SanderElias** [comment]
@Splaktar If you need some help setting up some debugging in there, I can help. 
DM me and we can schedule something.

**Comment by Splaktar** [comment]
@SanderElias will do, but I need to focus on billable work for the rest of this decade 😁
