### ISSUE TITLE
[Schematics] remove unnecessary boilerplate

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#746]
### Description

 A clear and concise description of the problem or missing capability...

When using the blog support with `ng generate @scullyio/init:blog` there is unnecessary boilerplate inside the *BlogComponent* : 
* a var ng
* the route and the router are injected but aren't used (and aren't required later on as a standard)
* preserveWhitespaces setted as true is redondant with default behaviour
* ViewEncapsulation setted as Emulated is redondant with default behaviour

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

Remove this boilerplate

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by SanderElias** [comment]
Thanks @geromegrignon!  closed with the PR
