### ISSUE TITLE
Cannot GET / 

### ISSUE THREAD

**Issue by montella1507** [scullyio/scully#777]
REPO:
https://gitlab.com/operator-ict/golemio/code/pragozor/pragozor-frontend/-/tree/development/portal

STEPS:
1) npm i / or yarn
2) npm run-script build-dev   / or yarn start
3) npm run-script scully-allroutes   / or yarn start

= clean install, no DIST folders yet..

Results in:

`<!DOCTYPE html><html lang="en"><head><meta name="generator" content="Scully 0.0.96">
<meta charset="utf-8">
<title>Error</title>
<script>window['ScullyIO']='generated';</script></head>
<body scully-version="0.0.96">
<pre>Cannot GET /housing</pre>

</body></html>`

in every lazy loaded routes...

Sometimes it works - it is like random  - but even if it works, it is rendered as Home (and not /transport) etc..  But this is second problem - we havent realized why we getting Cannot GET / error. 

Routes are correctly listed in  scully-routes.json  however it looks like "render server" is not correctly serving urls (maybe problem with HTML5 routing / base path?) 
Thank you for your time.

**Comment by geromegrignon** [comment]
The provided link doesn't work.

![image](https://user-images.githubusercontent.com/32737308/88284567-ea64a000-cced-11ea-80ea-445accdc1ab1.png)

**Comment by montella1507** [comment]
Hmm, have to talk with customer about source codes (they may be OSS soon, so it may be not problem to upload here)

**Comment by SanderElias** [comment]
@montella1507 If you are setting a base-href in your app, you need some additional settings in the Scully config.
It is much easier to set a base-href as the last step, using our base-href-plugin, instead of setting it with the CLI.

**Comment by SanderElias** [comment]
I'm closing this as there seems no additional action needed.
If there is feel free to response and we will reopen the issue
