### ISSUE TITLE
ScullyRoutesService getCurrent()

### ISSUE THREAD

**Issue by pegaltier** [scullyio/scully#786]
### Description

ScullyRoutesService getCurrent() return undefined when the plugin seoHrefOptimise is enabled

#### 🔬 Minimal Reproduction

- enable seoHrefOptimise and use getCurrent() (KO)
- disable seoHrefOptimise  and use getCurrent() (OK)

#### 💻Your Environment

**Angular Version:**

<pre><code>

@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cli                      9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "^1.0.0-beta.0",
    "@scullyio/ng-lib": "^1.0.0-beta.0",
    "@scullyio/scully": "^1.0.0-beta.0",
</code></pre>

**Comment by pegaltier** [comment]
Update: not sure about the origin of the issue, i will investigate on my side first

**Comment by yuyueh** [comment]
Hi, did you already solved this problem? 
After adding base-href, I faced similar issue: "ScullyRoutesService.getCurrentRoute will return undefined".

According to the below link and code: `curLocation === basePathOnly(r.route.trim())`   
https://github.com/scullyio/scully/blob/main/libs/ng-lib/src/lib/route-service/scully-routes.service.ts#L103
My tests shown these two variables would not be equalled in this case, so current route can't be found.

Could you give me some advice? Thanks.
