### ISSUE TITLE
npm run scully hangs forever, but kind of works on Netlify

### ISSUE THREAD

**Issue by barbados-clemens** [scullyio/scully#787]
## 🐞 Bug report
when running a scully build, `npm run scully`. The build hangs, I killed after an hour of waiting.

### Description
I was updating my personal site from v0.0.88 to v1.0.0-beta.0 when I noticed this behavior. I also updated to ng v10.0.4 at the same time. 

I figured it was something I did wrong. so created a new scully app according to the documentation and then moved over my components. same issue. Making a blank scully app with blog support doesn't have this issue. I couldn't figure out at what point my application is "breaking" scully. 

When pushing this issue netlify, picked up the branch to build and actually was able to build it with globalThis errors (see errors down below), though none of the static content is being rendered, only the frontmatter. Which leads me to think maybe it's a personal machine issue? but v.0.0.88 works just fine, so not too sure.

I believe the error could be related to issue #703 as Netlify is using node v10

<img width="518" alt="image" src="https://user-images.githubusercontent.com/23272162/88465998-7f51cf80-ce8d-11ea-92e3-7e1b0f5c0d0b.png">

Also as a maybe related issue, I can only run `scully serve` once before I start getting issues with the port already being taken up by another process. even though I'm not running it anywhere else. Looks like it's not successfully being killed.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/23272162/88466019-c6d85b80-ce8d-11ea-8671-ca9349c187e8.png">

I tried killing with 

`npx scully killServer` with no luck. 

#### 🔬 Minimal Reproduction
[My personal repo](https://gitlab.com/caleb-ukle/portfolio/-/tree/hung-builds) where the issues are being presented. the branch is _hung-builds_

[Site that build without content because globalThis issues](https://5f1c95004989cd0008a08212--caleb-portfolio.netlify.app/blog/blur-up-fade-in-images-without-gatsby-a-scully-plugin)

#### 💻Your Environment

**Angular Version:**
<img width="648" alt="image" src="https://user-images.githubusercontent.com/23272162/88465909-875d3f80-ce8c-11ea-8408-67e7904c522d.png">

**Scully Version:**
v1.0.0-beta.0

<pre><code>

"dependencies": {
    "@angular/animations": "~10.0.4",
    "@angular/cdk": "^10.1.0",
    "@angular/common": "~10.0.4",
    "@angular/compiler": "~10.0.4",
    "@angular/core": "~10.0.4",
    "@angular/fire": "^6.0.2",
    "@angular/forms": "~10.0.4",
    "@angular/platform-browser": "~10.0.4",
    "@angular/platform-browser-dynamic": "~10.0.4",
    "@angular/router": "~10.0.4",
    "@angular/service-worker": "^10.0.5",
    "@scullyio/init": "^1.0.0-beta.0",
    "@scullyio/ng-lib": "^1.0.0-beta.0",
    "@scullyio/scully": "^1.0.0-beta.0",
    "@sentry/browser": "^5.20.1",
    "algoliasearch": "^4.3.1",
    "firebase": "^7.13.1",
    "netlify-cms": "^2.10.54",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/architect": ">= 0.900 < 0.1100",
    "@angular-devkit/build-angular": "~0.1000.3",
    "@angular/cli": "~10.0.3",
    "@angular/compiler-cli": "~10.0.4",
    "@angular/language-service": "^10.0.5",
    "@cloudflare/wrangler": "^1.10.3",
    "@sentry/cli": "^1.55.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@types/sharp": "^0.25.1",
    "axios": "^0.19.2",
    "codelyzer": "^6.0.0",
    "dotenv": "^8.2.0",
    "firebase-admin": "^9.0.0",
    "firebase-tools": "^8.0.0",
    "fuzzy": "^0.1.3",
    "husky": "^4.2.5",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jsdom": "^16.3.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "open": "^7.0.3",
    "protractor": "~7.0.0",
    "sharp": "^0.25.4",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }

</code></pre>

## 🔥 Exception or Error

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/23272162/88465965-05b9e180-ce8d-11ea-9999-3b94a734297d.png">

Please let me know if there's any more information or things to try/test 😃

**Comment by barbados-clemens** [comment]
Use node v12, not v14. 

Not sure exactly _why_ v14 breaks it, but when using v12 it just worked like it normally did.

**Comment by SanderElias** [comment]
@barbados-clemens some of our depedencies are not (yet) compatible with node v14.
