### ISSUE TITLE
Put node version limit in package.json

### ISSUE THREAD

**Issue by SanderElias** [scullyio/scully#788]

**Comment by geromegrignon** [comment]
Consider adding it as a Shield.io badge in the Readme file too.

**Comment by amycdurbin** [comment]
Related to #703 
@aaronfrost should we go from node 12-13?

**Comment by aaronfrost** [comment]
I think we should stay on whatever the version the Angular CLI supports. If they went to 13, then let's do it.

**Comment by amycdurbin** [comment]
> I think we should stay on whatever the version the Angular CLI supports. If they went to 13, then let's do it.

@SanderElias^^

**Comment by SanderElias** [comment]
@aaronfrost the cli demands a version like this:
```json
{  
  "engines": {
    "node": ">=10.13.0 <13.0.0",
  }
}
```
However, we have some dependencies in Scully (jsDom at least) that don't work properly anymore with version 10.
The polyfill proposed in #703 has serious TS issues, that might take at least a couple of hours to resolve
I would propose to go to:
```json
{  
  "engines": {
    "node": ">=12.0.0 <13.0.0",
  }
}
```
I'm not sure why the CLI doesn't include 13, as it seems to work fine.

**Comment by SanderElias** [comment]
Tested support for node 12 13 and 14, Scully works with all 3.
Node 10 isn't supported. Some of our dependencies demand globalThis, which is not in V10, and TS is making it really hard to polyfill.
Then we use fromEntries all over the place, and that is part of the es2019 library but does not get polyfilled by TS when we compile down to ES2018 anymore. (this worked with previous TS versions
Then we need this TS version for proper symbol support, so its not easy to go to an older TS version.

Supporting V10 would take at least 2 full day's of work
