### ISSUE TITLE
Emit blog post data as output of <scully-content>

### ISSUE THREAD

**Issue by d-koppenhagen** [scullyio/scully#80]
# 🧩 Feature request

### Description
Within the current implementation the component `scully-content` will be used to display the content of a blog post.
I think it would be great if the `scully-content` component will emit an output event containing the parsed data for the content. This feature would give you the ability to process some meta data additionally and display for example a related thumbnail image or tags.

### Describe the solution you'd like

Imaging a markdown file like this:

```markdown
---
title: 'Foo Bar Baz'
publish: true
author: John Doe
mail: mail@example.com
keywords:
  - Scully
  - Angular
thumbnail: assets/images/blog/pwaheader.jpg
---

# Foo
bar...
```

Scully will currently process this data and display the text below the meta data information but it already parses the meta data.
When it will emit an event with the data, a user can process this data and can handle this meta data information:

```html
<img [src]="thumbnail" />
<scully-content (data)="thumbnail = $event"></scully-content>
```

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by SanderElias** [comment]
@d-koppenhagen the ScullyRouteService already has all this knowledge. I'm already building a method in there that will return the information for the current page only. This will give you exactly the same information, but without you having to resort to template trickery to get it out.

```typescript
class MyBlogComponent {
  myMetaData = this.srs.getCurrentPageData() // <-- NOT YET THERE, Name not confirmed
  constructor(private srs: ScullyRouteService){}
}
```

This will be in early next year. If you can't wait, the complete route-data is already there, and you can extract the current page manually. 
I expect to have this ready somewhere week 1/2

**Comment by d-koppenhagen** [comment]
Hey, sounds great.
I‘ve already implemented a workaround for my needs fetching all data and reducing the result to that what I need.
But great to hear that’s on the roadmap - then I can replace my solution soon. But no hurry.

I wish you a great Christmas time 🎄
