### ISSUE TITLE
New Web Page for Docs

### ISSUE THREAD

**Issue by cenguidanos** [scullyio/scully#803]
### Description

The official docs web is ugly and its difficult to read content

### Describe the solution you'd like

Can i create a new one?

**Comment by geromegrignon** [comment]
There is a ongoing PR about it #753

**Comment by cenguidanos** [comment]
Sorry for my ignorance, it's a tradition in dev create the docs web in the same repo of the entire core project with other stuff? Thanks

**Comment by geromegrignon** [comment]
it mostly depends on how the project will be used.

As this project uses a monorepo structure and only exposes its core as a library, side projects can live inside : docs web and a demo project.

Here are the benefits : 
- you don't have to maintain 2 repositories regarding contributing guidelines
- you can use the 'Projects' feature to manage both the side projects and the core project at once
- it's easier to manage versioning as you can make a unique PR to update both the library and the docs
