### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by sizer** [scullyio/scully#805]
## 🐞 Bug report

I'm trying to add scullyio to empty Angular(9.1.7) project. And found an error as title.

#### 🔬 Minimal Reproduction

```bash
ng new hello_scully --create-application=false
ng add @scullyio/init
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
    error into import SculyLib
Cannot read property 'toString' of null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### 💻Your Environment

**Angular Version:**

<pre><code>

Angular CLI: 9.1.12
Node: 14.5.0
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.12
@angular-devkit/core         9.1.12
@angular-devkit/schematics   9.1.12
@schematics/angular          9.1.12
@schematics/update           0.901.12
rxjs                         6.5.5
typescript                   3.8.3
    
Done in 0.47s.

</code></pre>

**Scully Version:**

<pre><code>

"@scullyio/init": "^1.0.0-beta.0",

</code></pre>

## 🔥 Exception or Error

<pre><code>

    error into import SculyLib
Cannot read property 'toString' of null
</code></pre>

**Comment by sizer** [comment]
... and I resolved it after create Angular application.
it may be better that scully logs some message instead of "Cannot read property 'toString' of null" :)

```bash
ng g application app --routing=false --style=scss
ng add @scullyio/init
# => success
```

**Comment by jorgeucano** [comment]
I will add a new error message, Scully only work with an Angular app using the route module!
