### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by desongyu** [scullyio/scully#807]
## 🐞 Bug report
I am trying to add scully to my existing Angular 7 application and got this error in console without additional message when serving. 

#### 🔬 Minimal Reproduction
ng build
npm run skully
npm run scully:serve
http://localhost:1668/

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 7.3.9
Node: 10.14.1
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.6
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.6
@angular/pwa                      0.12.4
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Scully Version:**
<pre><code>
 "@scullyio/init": "^1.0.0-beta.0"
</code></pre>

## 🔥 Exception or Error

<pre><code>
Uncaught TypeError: Object(...) is not a function
    at scullyio-ng-lib.js:607
    at Module../node_modules/@scullyio/ng-lib/fesm5/scullyio-ng-lib.js (scullyio-ng-lib.js:609)
    at __webpack_require__ (bootstrap:78)
    at Module../src/app/app.module.ts (app.component.ts:12)
    at __webpack_require__ (bootstrap:78)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:78)
    at Object.0 (main.ts:19)
    at __webpack_require__ (bootstrap:78)
    at checkDeferredModules (bootstrap:45)
(anonymous) @ scullyio-ng-lib.js:607
./node_modules/@scullyio/ng-lib/fesm5/scullyio-ng-lib.js @ scullyio-ng-lib.js:609
__webpack_require__ @ bootstrap:78
./src/app/app.module.ts @ app.component.ts:12
__webpack_require__ @ bootstrap:78
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:78
0 @ main.ts:19
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
</code></pre>

**Comment by geromegrignon** [comment]
As stated in the [docs](https://scully.io/docs/pre-requisites/), Scully doesn't support Angular 7.

**Comment by desongyu** [comment]
Thank you! I will try to upgrade. Do you have suggestion should I upgrade to 8 or 9 to better use Scully?

**Comment by desongyu** [comment]
Also, if I have jQuery in Angular ts file or in JS library, would Scully work with that? Thank you.

**Comment by geromegrignon** [comment]
I would always recommend to use latest angular version in order to be up to date with latest features (and it's always easier to update on each new version rather than having to deal with several versions updates at once).
You can use the guidelines of the official site to update your project : https://update.angular.io/#7.0:9.1

Scully parses your project to find routes then use Pupeteer to explore it : JQuery won't affect it.

**Comment by desongyu** [comment]
Thank you so much for your inputs. Scully doc mentioned supports Angular 8 and 9, would it work with Angular 10 work as well?

**Comment by SanderElias** [comment]
@desongyu Yes, Scully works with version 10 as well.
Going to close this issue now as there is no actionable content for us. Feel free to keep discussing things here.

**Comment by desongyu** [comment]
Sounds good. Thank you everyone's help and advice.

**Comment by desongyu** [comment]
Another question. We are thinking of migrating from 7 to 8 to use Scully. But we use JIT compiler from angular/core to compile HTML(containing angular code) from CMS database at runtime. After running Scully, would this function still be there? Or does Scully uses the AOT. What would then happen to our use of the JIT compiler and its behavior? Thank you for your help!

**Comment by SanderElias** [comment]
@desongyu Scully does work with the JIT compiler too. It does parse the end-result, and doesn't care how yo build it.

**Comment by desongyu** [comment]
@SanderElias  Thank you so much for that information. So if I understand correctly, the angular code in the CMS HTML would be compiled into static HTML and Javascript(AOT or JIT on running Scully). No configuration needed in Scully to know if using AOT or JIT in angular.json. With each CMS HTML change, I would just need to rebuild Scully and upload the new static HTML and Javascript for that page. Please let me know if this correct. Thank you!

**Comment by SanderElias** [comment]
@desongyu Yes, the static HTML will start your SPA like it normally does. So uploading the file for that page will work as you expect.

**Comment by desongyu** [comment]
Thank you so much! I look forward to upgrading to 8 then use Scully. Have a great day!

**Comment by desongyu** [comment]
BTW, this just came to me, if Scully doesn't need AOT, why doesn't it support Angular 7?

**Comment by SanderElias** [comment]
Because that would limit the version of typescript we can use. Also, we would need to manually build the library or version 7, add extra testing, and so on. We do only support the Active angular -and the previous version. So currently, we do support V9 and V10.
If you are upgrading your app, you might as well move directly to V10. If you follow the steps on the [update site](https://update.angular.io/#7.0:10.0l2) going from 8 to 9 to 10 is a breeze. (at least it was for me, during the 6 apps I updated in the last few weeks)

**Comment by desongyu** [comment]
@SanderElias Thank you for your inputs. I appreciate your help!
