### ISSUE TITLE
How to create any `/path` root `index.html` ?

### ISSUE THREAD

**Issue by uruha** [scullyio/scully#811]
## 🐞 Bug report
⚠️ This is question issue ⚠️

### Description
How to create any `/path` root `index.html` and routes setting ?

Because, I tried to touch `/blog/index.md` that to create `/blog` root index.html.
But, as excecuted `npm run scully -- --sr` result, `/blog/index/index.html` is output.
So, this output is routes detected `/blog/index` path...

If there is any officially available method, please enjoy it.

#### 🔬 Minimal Reproduction
⚠️ I don't think it's a bug, but I'll post an issue with this template,
so I'm sorry if it's an already asked question 🙇‍♀️

#### 💻Your Environment
👉 [Branch in progress](https://github.com/uruha/PoC_scully/pull/1/files)

**Angular Version:**
```
"@angular/core": "~9.1.11"
```

**Scully Version:**
```
"@scullyio/init": "0.0.28"
"@scullyio/ng-lib": "latest"
"@scullyio/scully": "latest"
```

**Comment by SanderElias** [comment]
@uruha Can you explain your motivation? 
We are building the path's this way because most hosting services/HTML servers demand a structure like that.
if you want to create a 'blog/index.html' you should have a route in your app that handles '/blog' without any addition. We do have something like that in our sample app.

**Comment by uruha** [comment]
@SanderElias 
Thank you for your reply 🙂

>Can you explain your motivation?

Currently, I am working on a FrontEnd guideline in Angular at my company,
This time, we are considering whether it is possible to move to Scully for convenience of operation.

The current guideline URI structure is as follows.
```
URI root
├ /intro
├ /html
├ /css
├ /js
│ ├ /linter-formatter
│ ├ /naming-convention
│ ├ /asynchronous
│ ├ /pre-commit
│ └ /typescript
├ /testing
├ /a11y
├ /security
└ /tips
　 ├ /sesign-pattern
　 └ /scaffolding
```

My motivation is to use Scully to achieve a similar URI with the following markdown configuration.

```
Scully project root
├ /intro
│ └ index.md => example.com/intro
├ /html
│ └ index.md => example.com/html
├ /css
│ └ index.md => example.com/css
├ /js
│ ├ index.md => example.com/js
│ ├ linter-formatter.md => example.com/js/linter-formatter
│ ├ naming-convention.md => ... as a same
│ ├ asynchronous.md
│ ├ pre-commit.md
│ └ typescript.md
├ /testing
│
as a same
 ```

The root of each URI path has a description and general description of that section, so I thought that it would be happy to create a document at index as much as possible, so I discussed this time 🙋‍♀️.

>We do have something like that in our sample app.

Is this in the Scully repository? If you have source code, please let me know! 🤩 (I will refer to it!)

**Comment by SanderElias** [comment]
Oh, yes, that structure is fully possible. 
@GuzmanPI is working on a plugin that takes a single file, and puts it manually into a route. (He is building on top of [this plugin](https://github.com/scullyio/scully/issues/773#issuecomment-662851518)
Is that what you are looking for?

**Comment by GuzmanPI** [comment]
Yes @uruha, as @SanderElias  mentioned I am currently working on a plugin for this. It is actually finished, and I'll have a PR for it tomorrow.

**Comment by uruha** [comment]
Thank you very much.
It seems to be solved by using this plugin !

**Comment by SanderElias** [comment]
@uruha As you redeem this as solved, I'll close the issue.

**Comment by diminutivesloop** [comment]
@GuzmanPI @SanderElias What happened to the mdReplaceRoutePlugin plugin? I found [the PR](https://github.com/scullyio/scully/pull/829) but it was closed without merging.

**Comment by SanderElias** [comment]
IIRC  there were some merge conflicts,  and @GuzmanPI would ix something that needed to be changed and would file a new PR.
@GuzmanPI Is this still on your radar?
