### ISSUE TITLE
Option to Not Include Future Blog Posts

### ISSUE THREAD

**Issue by pjlamb12** [scullyio/scully#812]
### Description

There should be an option to leave out blog posts that have a date in the future. If these posts are not included in the build, you could "schedule" blog posts. 

### Describe the solution you'd like

The Scully config file can have a flag for "includeFuturePosts" or something like that. It can default to true so that it doesn't break anything already deployed using Scully. Setting it to false would set the new behavior.

**Comment by aaronfrost** [comment]
If you used `published: false` in the frontmatter on your .md file, generates the blog with a random slug. And that non-published blog doesn't appear in certain pieces of the scully routes service. 

You can give it a look. Let us know what you think.

**Comment by pjlamb12** [comment]
Yeah, so I've used that and it works, but then you have to manually change it when you're ready to publish it. It seems like a natural setting to not publish a post with a future date. Then you can trigger a Netlify build each day, for example, and eventually that post will be picked up and published. Does that make sense? It's more about automating it and "scheduling" posts than just having a post not be published.

**Comment by pjlamb12** [comment]
@aaronfrost @SanderElias @jorgeucano If one of you can point me in the right direction for where to add the check I would be happy to do it. I was looking around and [think it may be here](https://github.com/scullyio/scully/blob/2861cd8aea9e990b0bc9e56e5d9d9c1ed8a478e7/libs/scully/src/lib/renderPlugins/content-render-utils/readFileAndCheckPrePublishSlug.ts#L17), at least potentially. It looks like there is a check there for the published flag being false, and these should essentially be treated as though they have the published flag set to false.

**Comment by SanderElias** [comment]
@pjlamb12 You need to set the published to false, as that is the main trigger. After the published is false, the publishDate will override "override" this setting. This is done so there will be no accidental 'unpublish'.

**Comment by pjlamb12** [comment]
@SanderElias I can do that, I get it, but the problem I see is then you have a whole bunch of posts that are marked as not published but really are. I see this feature as the post being published, thus the published flag being true, just not until the publishDate. Then you don't have to manually change the published flag or anything like that.

**Comment by SanderElias** [comment]
@pjlamb12 So, a post without a published false, and a future date doesn't get published at all? So no private slug gets generated?

**Comment by pjlamb12** [comment]
My thought was that the publishDate had to be today or earlier, and the published flag had to be true for the page to be generated. If I was "scheduling" a post, I'd set it to published true, but put the publishDate for this Friday for example. Each night I have Netlify kick off a rebuild of my site and pick up any new posts. Once Friday comes and the site is rebuilt it would pick up the scheduled post. But if the published flag is false, I can't schedule the post because I'd have to manually change the published flag before it was actually published. Does that make sense?

What I'm explaining is how my site currently works with Jekyll.

**Comment by amycdurbin** [comment]
@pjlamb12 We talked about this in stand up and we agree. We will work on this.

**Comment by pjlamb12** [comment]
Perfect, thanks so much!

**Comment by pjlamb12** [comment]
Another thing I was thinking as I work with Jekyll is that they have a CLI flag or environment flag to force future posts to be provided. I know that complicates things some more, but it's useful for previews (like for reviews by certain people). So if the build flag is not passed, the publish date is the source of truth. If the build flag is set to true, it overrides the publish date.

**Comment by amycdurbin** [comment]
If @Brocco doesn't finish by 9/17, @jorgeucano take this issue.
