### ISSUE TITLE
ng add @scullyio/init command not working

### ISSUE THREAD

**Issue by ashokthrymr** [scullyio/scully#820]
## 🐞 Bug report
ng add @scullyio/init command not working
### Description
When I try to run this command, I got the following error
**Unable to fetch package metadata: 404 Not Found - GET https://registry.npmjs.org/@scullyio%2finit - Not found**

**Angular Version:**
Angular - 9
[https://www.npmjs.com/package/@scullyio/init](
https://www.npmjs.com/package/@scullyio/init) 
may be library seems to be down.

**Comment by geromegrignon** [comment]
The problem comes from npm directly : https://twitter.com/npmstatus/status/1291296875572629504.

**Comment by jorgeucano** [comment]
I will close because npm have some problems :)
