### ISSUE TITLE
npm run scully hangs on Ubuntu WSL

### ISSUE THREAD

**Issue by TheEnterpriseProgrammer** [scullyio/scully#844]
### Description
When executing npm run scully on Ubuntu wsl it will start the scully and angular servers but will not finish. This then prevents the routes from being injected. I have taken the same repository and executed the npm run scully command on Windows 10 pro and scully completes creation of the sites and routes.

#### 🔬 Minimal Reproduction
1. new angular project
2. Add scullyio
3. execute ng build
4. execute npm run scully

#### 💻Your Environment
Ubuntu v. 20.04 wsl

**Angular Version:**
<pre><code>

Angular CLI: 10.0.5
Node: 10.19.0
OS: linux x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.5
@angular-devkit/core         10.0.5
@angular-devkit/schematics   10.0.5
@schematics/angular          10.0.5
@schematics/update           0.1000.5
rxjs                         6.5.5
</code></pre>

**Scully Version:**
<pre><code>

"@scullyio/init": "^1.0.0-beta.0"

</code></pre>

## 🔥 Exception or Error
No Error
<pre><code>

</code></pre>
![scullyError](https://user-images.githubusercontent.com/31627901/90080938-f5ea2c00-dcd9-11ea-94e1-c5ec33c9df18.JPG)

**Comment by SanderElias** [comment]
You started the server, and it's happily serving results until you stop it.
This is how it is intended to work.
Can you explain to me what you would expect to happen when you start the Scully server part?

**Comment by TheEnterpriseProgrammer** [comment]
Sander thanks for reaching out.

I apologize wrong screen shot.

This is what happens when running npm run scully in Ubuntu 20.04 in wsl:
![runScullyError](https://user-images.githubusercontent.com/31627901/90121887-8bada780-dd2a-11ea-8ff5-29fd067780a6.JPG)

However, when executing against the native windows environment it is successful as seen here:
![runScullySuccess](https://user-images.githubusercontent.com/31627901/90121949-9ec07780-dd2a-11ea-97cb-85e14fc89cde.JPG)

I would expect them to be the same

**Comment by SanderElias** [comment]
Me too.
@jorgeucano can you take a look?

**Comment by jorgeucano** [comment]
In scully@latest we fix the issue, and we add some documentation of "Pre-requisites" to use Scully and WSL 
[here](https://scully.io/docs/learn/getting-started/installation/)

![Capture](https://user-images.githubusercontent.com/5982204/92932910-ed415e80-f41b-11ea-9235-83d3cb417c09.PNG)
