### ISSUE TITLE
Scully doesn't work on nodev10

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#848]
### Description
@jorgeucano and I are doing a workshop, and the users in the workshop can't run Scully cause they get errors. Not Cool!!!

#### 🔬 Minimal Reproduction

Install nodev10, and run npm run scully. You get an error about Object.fromEntries not existing. We need to support node v10. 

#### 💻Your Environment

**Angular Version:**

<pre><code>

</code></pre>

**Scully Version:**

<pre><code>

</code></pre>

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by stevermeister** [comment]
@aaronfrost do you really need v10? 
I think all first adopters of Scully either use v12+ or it's easy for them to switch

**Comment by s0l0c0ding** [comment]
one month ago or earlier had issues with node 10 specifically with jsdom dependency. i think node 10 is outdated

**Comment by SanderElias** [comment]
As by pr #852 this is now closed
