### ISSUE TITLE
Cannot ready property 'toString' of null

### ISSUE THREAD

**Issue by navneetsharmaui** [scullyio/scully#856]
## 🐞 Bug report

Getting error **toString** of null while running command `nx generate @scullyio/init:markdown --project=scully-hour`

### Description

I've created a `nx-workspace` base angular application with `**nx**` **cli** and `**workspace.json**`, and was adding the blog to the application, but while executing the command `nx generate @scullyio/init:markdown --project=scully-hour` it gives error toString of null.

#### 🔬 Minimal Reproduction

1. Create an nx workplace with empty preset `yarn create nx-workspace nx-office-hour`. Select empty workspace and NX as default cli.
2. Install angular plugin `yarn add -D @nrwl/angular`.
3. Create Angular application with router module `nx generate @nrwl/angular:application --name=scully-hour --style=scss --linter=eslint --prefix=scull-hour --routing`.
4. Create a Home module and component add a route to the RouterModule in the app module.
5. Install Scully `yarn add @scullyio/init `.
6. `nx g @scullyio/init:install -- --project=scully-hour`.
7. Run blog command ` nx generate @scullyio/init:blog`

#### 💻Your Environment

**Angular Version:**
<pre><code>
10.0.0
</code></pre>

**Nx Version:**
<pre><code>
10.0.12
</code></pre>

**Scully Version:**

<pre><code>
    "@scullyio/init": "^1.0.0-beta.0",
    "@scullyio/ng-lib": "^1.0.0-beta.0",
    "@scullyio/scully": "^1.0.0-beta.0",

</code></pre>

## 🔥 Exception or Error

<pre><code>
$ nx generate @scullyio/init:markdown --project=scully-hour
? What name do you want to use for the module? blog
? What slug do you want for the markdown file? id
? Where do you want to store your markdown files? blog
? Under which route do you want your files to be requested? blog
    ✅️ Update scully.scully-hour.config.ts
Cannot read property 'toString' of null
</code></pre>
![image](https://user-images.githubusercontent.com/11630812/90507437-8362cb80-e173-11ea-9b33-56ca890e7397.png)

**Comment by jorgeucano** [comment]
@navneetsharmaui Can you update your schematics to `"@scullyio/init": "^1.0.0-beta.1",`

![Capture](https://user-images.githubusercontent.com/5982204/90515248-bc317f00-e138-11ea-923e-7d05ec0657f1.PNG)

**Comment by navneetsharmaui** [comment]
@jorgeucano that resolved the issue but now it's not updating the routes array.
![image](https://user-images.githubusercontent.com/11630812/90525065-73a3b100-e18c-11ea-8313-e72ae271196f.png)
