### ISSUE TITLE
Double encoding for non-latin slugs 

### ISSUE THREAD

**Issue by stevermeister** [scullyio/scully#861]
### Description

When you have non-Latin characters they will be encoded 2 times.

#### 🔬 Minimal Reproduction

minimal set to reproduce - https://github.com/stevermeister/scully-slug-bug
deployed - https://scully-slug-bug.netlify.app/

**Comment by stevermeister** [comment]
@amycdurbin was it published?

**Comment by amycdurbin** [comment]
@SanderElias ^^

**Comment by SanderElias** [comment]
@stevermeister I'll put out a new version tomorrow. IIRC it should be released already, but not 100% sure
