### ISSUE TITLE
provide --host flag for alternative hosts (otherwise scully not works)

### ISSUE THREAD

**Issue by willi84** [scullyio/scully#87]
# 🧩 Feature request

### Description
For some working environments, where localhost is by default not available to use (e.g. strict company VMs). 
When I start ``` npm run scully ``` the mechanism tries to connecto to ```http://localhost:1864/_pong```. But this is not possible in my enviroment, because it redirects to ```http://myhost:1864/_pong```

### Describe the solution you'd like
Angular provides for ng serve a ```--host``` flag, this could be also a solution for you.
The first line it crashed for me was here:
https://github.com/scullyio/scully/blob/8ce6c13c06e07f0082a2d75936f232e03efb3a98/scully/utils/waitForServerToBeAvailable.ts#L13

But there are maybe also other points.

### Describe alternatives you've considered
I tried to edit it directly in the source code. It worked until the next issue (no chromium available for my OS)

**Comment by aaronfrost** [comment]
@jorgeucano is this replaced with the feature you are adding around `hostUrl`?

**Comment by jorgeucano** [comment]
@aaronfrost Yes, WIP
