### ISSUE TITLE
reduce npm footprint 🌱

### ISSUE THREAD

**Issue by willi84** [scullyio/scully#88]
# 🧩 Feature request

### Description
priority: nice to have

When adding your awesome library the usage of disk space increase 3x. 

```
# 353 MB basic angular setup with router
ng new --routing=true <project> 

# 919 MB with scully => @scullyio package ist just 85 MB
ng add @scullyio/init => 919 MB (@scullyio just 85 MB)
```

Angular has already a big footprint, when you try to install it on a small machine or in a wifi with restrictions (e.g. German ICE high speed train wifi: 200 MB high-speed data).

And it will also reduce the 🌱 CO2 footprint ;-)

### Describe the solution you'd like
Try to remove or replace to big dependencies

### Describe alternatives you've considered
no alternative possible when you are restricted in disk space or wifi speed ;-)

**Comment by jorgeucano** [comment]
@beeman @SanderElias The pr `fix: make sure devDependencies are marked as such #110` fix this issue?

**Comment by beeman** [comment]
> @beeman @SanderElias The pr `fix: make sure devDependencies are marked as such #110` fix this issue?

We should check again once a new version of `@scullyio/init` is pushed to master.

**Comment by SanderElias** [comment]
This is indeed a nice to have, but as we have to be dependant on puppeteer, and a few other large resources (None of those end up in the end application!) there is currently no way we can change this.
@willi84 sorry, but I'm going to close this issue, as I see no way we will ever to be able to fix this.
Please note, that all of those resources are only needed to develop/deploy, and that is the price we have to pay for ease of use.
