### ISSUE TITLE
Error: Your distribution files are in "dist". Please change that to include a subfolder

### ISSUE THREAD

**Issue by alcfeoh** [scullyio/scully#893]
### Description

When trying to run `npm run scully`, I get the following error:
![image](https://user-images.githubusercontent.com/4699771/91501871-70d74900-e87b-11ea-999f-2dd58a8f89ae.png)

#### 🔬 Minimal Reproduction
- Clone https://github.com/alcfeoh/ng2-training/tree/scully-test
- Run `npm install`
- Run `ng build`
- Run `npm run scully` 

#### 💻Your Environment

**Angular Version:**

<pre><code>
10.0.6
</code></pre>

**Scully Version:**

<pre><code>
1.0.0-beta.2
</code></pre>

## 🔥 Exception or Error

<pre><code>
Your distribution files are in "dist". Please change that to include a subfolder
</code></pre>

**Comment by SanderElias** [comment]
Make sure the output of your angular build is in a subfolder of dist. Most Operating Systems get confused if you try to recursively copy files into a subfolder. This error prevents your OS from generating an infinitive depth folder.
You can change that in your `angular.json`

**Comment by alcfeoh** [comment]
That works. This info should be in the set-up instructions though as not all projects are configured that way by default. Or perhaps have the Scully schematics change `angular.json` to include that subdirectory config.
