### ISSUE TITLE
Is it possible to suppress the anonymous collection input during 'npm run scully'

### ISSUE THREAD

**Issue by koshyviv** [scullyio/scully#894]
### Description

 A clear and concise description of the problem or missing capability...
```
While running npm run scully
> offset-portal@0.0.0 scully /xxxx/scully
> scully

 ☺   new Angular build imported
⠙ Background servers already running.
Would you allow Scully to collect anonymous errors to improve our services? (Y/n)n
```

We are asked to choose if we want to allow anonymous error collection. Is there a way to disable that option, since im running in an automated fashion.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.
Is it possible to pass arguments to scully, to suppress the message. Eg, `scully --disable-error-collection`

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by SanderElias** [comment]
@koshyviv You can use the `--noPrompt` flag, and there will be no user-prompt and no error collection being done.
I'll double-check the docs if this is listed there.
