### ISSUE TITLE
ng g @scullyio/init:blog does not create blog module

### ISSUE THREAD

**Issue by beeman** [scullyio/scully#90]
# 🐞 Bug report

### Description

Running `ng g @scullyio/init:blog` does not create a blog module/route in my app, only a `blog` folder in my root project and a adds new object to `scully.config.js`.

## 🔬 Minimal Reproduction

```
ng g @scullyio/init:blog
    ✅ 12-24-2019-blog file created
    ✅️ Update scully.config.js
CREATE blog/12-24-2019-blog.md (98 bytes)
UPDATE scully.config.js (168 bytes)
```

## 💻Your Environment 
**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.7
Node: 12.12.0
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@angular/cdk                      8.2.3
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2</code></pre>

**Scully Version:**
<pre><code>
    "@scullyio/init": "0.0.9",
    "@scullyio/ng-lib": "0.0.7",
    "@scullyio/scully": "0.0.46",</code></pre>
## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by Splaktar** [comment]
I ran into this as well. I had to copy over the output from a new Angular CLI project.

**Comment by SanderElias** [comment]
Is this still the case with the latest version? it seems to work for my machines.

**Comment by beeman** [comment]
@SanderElias I tried it on a clean project and it seems to work there. However, on  [this project/branch](https://github.com/beeman/scully-starter/tree/beeman/remove-scully-blog) it does not seem to work:

```bash
ng g @scullyio/init:blog
ng g @scullyio/init:blog\n
    ✅ 12-31-2019-blog file created
    ✅️ Update scully.config.js
CREATE blog/12-31-2019-blog.md (98 bytes)
UPDATE scully.config.js (168 bytes)
```

Not sure if there's anything in that project blocking it?

**Comment by SanderElias** [comment]
@jorgeucano can you take a look at this?

**Comment by jorgeucano** [comment]
i will check now

**Comment by jorgeucano** [comment]
fixed in the new publish :)
