### ISSUE TITLE
Typescript error while compiling plugins. scully/**/*.ts' not found scully/*.ts' not found

### ISSUE THREAD

**Issue by hubbertj** [scullyio/scully#907]
Just updated my project from angular 5 to angular 10 so I can implement scully io. 

After doing the following on a angular 10.1.0 project 

``` 
ng add @scullyio/init 
ng build
npm run scully
```

I get the following error: 

Typescript error while compiling plugins. the error is:
error TS6053: File 'C:/cmder/development/<project_name>/scully/**/*.ts' not found.
error TS6053: File 'C:/cmder/development/<project_name>/scully/*.ts' not found.

Looking at the tsconfig.sjon in the ./scully folder looks like its configured to look for the following:

![Annotation 2020-09-04 181255](https://user-images.githubusercontent.com/1585928/92293690-49672880-eeda-11ea-98b0-9269f2d4f3a0.png)

I have tried commenting out the files property but it just thrown other error. Any ideal?

After further looking into this it seems I can reproduce this with a fresh generation of a angular project.

Here is my versions

Angular CLI: 10.1.0                                    
Node: 12.13.1                                          
OS: win32 x64                                          
                                                       
Angular:                                               
...                                                    
Ivy Workspace:                                         
                                                       
Package                      Version                   
------------------------------------------------------ 
@angular-devkit/architect    0.1001.0                  
@angular-devkit/core         10.1.0                    
@angular-devkit/schematics   10.1.0                    
@schematics/angular          10.1.0                    
@schematics/update           0.1001.0                  
rxjs                                        6.6.2                      

The process for reproduce are:

``` 
ng new my-app
cd my-app\
ng build
 npm run scully

```

The following error happens:

using plugins from folder "./scully"
Typescript error while compiling plugins. the error is:
error TS6053: File 'C:/cmder/development/my-app/scully/**/*.ts' not found.
error TS6053: File 'C:/cmder/development/my-app/scully/*.ts' not found.

⠹ undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! my-app@0.0.0 scully: `scully`
npm ERR! Exit status 15
npm ERR!
npm ERR! Failed at the my-app@0.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hubbe\AppData\Roaming\npm-cache\_logs\2020-09-05T15_01_39_356Z-debug.log

**Comment by SanderElias** [comment]
@hubbertj We are investigating this already. The problem here is that version 10.1 is using TS4, and there is a breaking change in there. We need to fix this in such a way that both the old and the new can work.

**Comment by santiruffino** [comment]
Hey! Same issue here. But I'm using Angular 9.1.12. I created a new Angular app, and fails when I run `npm run scully`.

**Comment by SanderElias** [comment]
Oh, just did a careful rereading. This is not the TS4 issue I thought it was.
@jorgeucano We seem to have missed something in the setup for the 'compile plugins'
@santiruffino Thanks for the update. we are going to fix this today, expect an update tomorrow.

**Comment by hubbertj** [comment]
> Oh, just did a careful rereading. This is not the TS4 issue I thought it was.
> @jorgeucano We seem to have missed something in the setup for the 'compile plugins'
> @santiruffino Thanks for the update. we are going to fix this today, expect an update tomorrow.

Thanks @SanderElias

**Comment by SanderElias** [comment]
For the ones that currently have this issue, and want to move forward, remove the `./scully` (or rename) folder. This will allow you to use Scully normally. 
We are working on a fix, and I still expect this to land today.

**Comment by SanderElias** [comment]
If you have this error, please replace the `/scully/tsconfig.json` with the following:
```json

{
  "compileOnSave": false,
  "compilerOptions": {
    "esModuleInterop": true,
    "importHelpers": false,
    "lib": ["ES2019", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es2018",
    "types": ["node"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "typeRoots": ["../node_modules/@types"],
    "allowSyntheticDefaultImports": true
  },
  "exclude": ["./**/*spec.ts"]
}
```
And all will start to work

**Comment by santiruffino** [comment]
Great! Thanks, @SanderElias and @jorgeucano :+1:

**Comment by hubbertj** [comment]
@SanderElias @jorgeucano Thanks guys, I am really a fan of this project. You guys are doing some good work here.

**Comment by Niaro** [comment]
@SanderElias Hi there! First of all tons of thanks for the tool! 
Is it okay that the Scully command run compiles into js the scully.config.ts and the plugins folder? I kinda don't want js files nearby ts files....

**Comment by SanderElias** [comment]
@Niaro Yes, in this situation there is no way around without doing really funky rewrites of the import/requirements that are done in the user-provided modules.
After Scully is done you can remove the JS files if you really want. 
The temporary config.js file is auto removed by Scully. We leave the stuff in the `./scully/` subfolder because it is allowed to write those things in JS too.
