### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by nhaancs** [scullyio/scully#920]
I dont know why this error below sometimes happens when I navigate between posts. When this happens, the url change, but not the post content. Anybody knows the reason?
`ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

**Comment by SanderElias** [comment]
@nhaancs No, I didn't hear of this issue yet.
If you can provide a reproduction, we will fix it.

**Comment by nhaancs** [comment]
Yeah, 
You can clone this repo: [https://github.com/nhaancs/ngx-scully-blog](https://github.com/nhaancs/ngx-scully-blog)
Check out branch **nhannguyendacoder**
I use this command to build: `ng build --prod --stats-json && npm run scully && npm run scully:serve`

**First issue**
1. After build, goto route `http://localhost:1668/blog`
2. Click on the first post
3. Click on "Home" on the top navigation
4. Click on the first post again
=> This error happens: `ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node`

**Second issue**
1. After build, goto route `http://localhost:1668/blog` 
2. Click on the first post
3. Then on the Categories widget on the right, hover on the third category name (`HTML CSS`), you will see the link is `http://localhost:1668/blog?c=self-learning`
4. Click on the category
=> Error: It first navigate to route `http://localhost:1668/blog?c=self-learning`, but then the url automatically updated to `http://localhost:1668/blog` and clear all the query params.

As I run the Angular version, both errors above will not happen.

Btw, this error below sometimes happens on production with the code I setup Facebook pixel on my site. Do you know any possible reasons. 
`VM30 1637124039759653:30 Uncaught TypeError: fbq.registerPlugin is not a function`


Thank you.

**Comment by SanderElias** [comment]
I checked out your sample.
when you upgrade to the current release of Scully, there is _no_ error.
just run ` npm i @scullyio/ng-lib @scullyio/scully`

**Comment by nhaancs** [comment]
I upgraded follow your instructions but the errors still happen
