### ISSUE TITLE
Spanish documentation

### ISSUE THREAD

**Issue by jorgeucano** [scullyio/scully#922]
### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by damiansire** [comment]
Can you assign me this?

**Comment by AlexScigalszky** [comment]
I made this test https://github.com/scullyio/scully/pull/1099 and I discover that the english file \docs\learn\introduction_es.md is not there but there is a spanish translation. Need I remove the spanish file?

**Comment by SanderElias** [comment]
Its mostly the same as the overview.md
I did split it out a bit. if you have translated the other files, this one can go. Unless you think there are portions of that not accounted in other parts
