### ISSUE TITLE
Scully stucks at step "Creating Route List: 3/3" inside Docker

### ISSUE THREAD

**Issue by moritz31** [scullyio/scully#924]
### Description

Running scully on my local mac works as expected. When running scully inside a docker container it get's stuck during the the Creating Route List 3/3.
Tried it with a combination of the following flags
<code>
 --showGuessError --np --prod --host=0.0.0.0 --scanRoutes --serverTimeout=30000
</code>
#### 🔬 Minimal Reproduction

I've used different node images but buildkite/puppeteer should work to reproduce the issue.
<code>
docker run -it --entrypoint '/bin/bash'  --workdir=/develop -v $(pwd):/develop:rw buildkite/puppeteer -c "npm install && ng build && npm run scully"
</code>

#### 💻Your Environment

**Angular Version: **

<pre><code>
Angular CLI: 10.1.1
Node: 12.18.3
OS: darwin x64

Angular: 10.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.1
@angular-devkit/build-angular     0.1001.1
@angular-devkit/build-optimizer   0.1001.1
@angular-devkit/build-webpack     0.1001.1
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      10.2.1
@ngtools/webpack                  10.1.1
@schematics/angular               9.1.12
@schematics/update                0.803.29
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.44.1

</code></pre>

**Scully Version:**

<pre><code>
"@scullyio/init": "1.0.0",
"@scullyio/ng-lib": "latest",
"@scullyio/scully": "1.0.0-beta.6",
</code></pre>

## 🔥 Exception or Error

<pre><code>
Stuck at Creating Route List: 3/3 without any further output
</code></pre>

**Comment by SanderElias** [comment]
This will happen if chrome isn't preinstalled in your docker container. We are looking at how to generate a more proper error for this.
for now, make sure you do something like this:

```Dockerfile
FROM node:12-alpine

RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
```
As a base docker config, and then make sure to set the environment correctly in the container that runs Scully:
In order to use this I create my projects' Docker file like this:

```Dockerfile
FROM aboveConfig
ENV SCULLY_PUPPETEER_EXECUTABLE_PATH '/usr/bin/chromium-browser'
... more docker stuff here
... in the end:
RUN npm run scully
```

I hope this helps you. I will close this issue as we have another ticket where we track the error-msg,  
If you have further questions, you can still ask them here, and we will answer them. If needed, we will reopen the issue.

**Comment by moritz31** [comment]
@SanderElias thanks! This really fixed the issue for me. 
I used node:12-slim and it seems like debian in combination with chrome didn't worked.

I've slightly modified your approach and added a non root user which is running that build:

`FROM node:12-alpine

RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      freetype-dev \
      harfbuzz \
      ca-certificates \
      ttf-freefont

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV SCULLY_PUPPETEER_EXECUTABLE_PATH '/usr/bin/chromium-browser'

RUN npm install -g @angular/cli

RUN addgroup -S pptruser && adduser -u 8003 -S -g pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser

# Run user as non privileged.
USER pptruser
`

maybe you can reuse this for https://github.com/scullyio/scully/issues/926.

As for documentation i used the following options:
`    puppeteerLaunchOptions: {
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    },`

**Comment by asotog** [comment]
Same for me on Vercel :(

**Comment by magbeat** [comment]
Beside installing the mentioned packages I also had to add the following option to the `scully.config` file
` puppeteerLaunchOptions: { args: ['--no-sandbox', '--disable-setuid-sandbox'] },`

Thanks @moritz31 !
