### ISSUE TITLE
[Doc] Getting started section order

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#928]
### Description

When clicking on the 'Getting started' button on https://scully.io/, it navigate to the 'Minimal setup required' page (https://scully.io/docs/learn/getting-started/requirements/).

But at this page is placed as the fourth position of the 'Getting started' section, the next step based on the buttons on the bottom of the page is 'tips for testing', which might be misleading as the next step should be 'installation'.

![image](https://user-images.githubusercontent.com/32737308/93432079-52d29680-f8c5-11ea-87ff-774a1d84f536.png)

### What's the affected URL?\*\*

https://scully.io/docs/learn/getting-started/requirements/

### Reproduction Steps\*\*

Navigate to https://scully.io/
Click on one of the two 'getting started' buttons
Scroll to the end of the 'Minimal setup required' page => the next step is 'tips for testing'

### Expected vs Actual Behavior\*\*

The 'Minimal steup required' page should be placed on first position of the 'Getting started' section.

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by geromegrignon** [comment]
If you are fine with moving the 'minima setup required' step as the first position of the 'Getting started' section, i can make a PR.

**Comment by SanderElias** [comment]
This is now automated in #930 nd will be solved when that PR is merged
