### ISSUE TITLE
Adding Scully breaks the default Angular app

### ISSUE THREAD

**Issue by owlypixel** [scullyio/scully#93]
# 🐞 Bug report
Hello, I was checking out Scully, but got an error after adding it to the default scaffolded Angular app.
## 🔬 Minimal Reproduction
on Windows 10
Create a default Angular project
`ng new awesome-angular-blog`
(answer Yes, SCSS)
`cd awesome-angular-blog`
`ng serve --open`
The default app opens ok and works. Let's add Scully.
`ng add @scullyio/init`
`ng serve --open`
it opens up a blank screen with the error listed below. So, the app no longer works.
Simply adding Scully breaks `ng serve`.

![issue](https://user-images.githubusercontent.com/23126215/71453421-cfe83980-2793-11ea-8ee7-567df8d1a68d.png)

## 💻Your Environment 
**Angular Version:**
<pre><code>
Angular CLI: 8.3.21
Node: 10.16.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cdk                      8.2.3
@angular/cli                      8.3.21
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Scully Version:**
<pre><code>
{
  "name": "awesome-angular-blog",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@scullyio/init": "0.0.9",
    "@scullyio/ng-lib": "latest",
    "@scullyio/scully": "latest",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.21",
    "@angular/cli": "~8.3.21",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

</code></pre>
## 🔥 Exception or Error
<pre><code>
ERROR NullInjectorError: StaticInjectorError(AppModule)[AppComponent -> IdleMonitorService]: 
  StaticInjectorError(Platform: core)[AppComponent -> IdleMonitorService]: 
    NullInjectorError: No provider for IdleMonitorService!
    at NullInjector.get (http://localhost:4200/vendor.js:39072:27)
    at resolveToken (http://localhost:4200/vendor.js:53990:24)
    at tryResolveToken (http://localhost:4200/vendor.js:53916:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:53766:20)
    at resolveToken (http://localhost:4200/vendor.js:53990:24)
    at tryResolveToken (http://localhost:4200/vendor.js:53916:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:53766:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:64953:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:66019:16)
    at resolveDep (http://localhost:4200/vendor.js:66550:45)
</code></pre>

**Comment by Villanuevand** [comment]
@owlypixel you need to use **Angular 9**.
I recommend start reading  the [Getting Started](https://github.com/scullyio/scully/blob/master/docs/getting-started.md), section [Pre-requisites](https://github.com/scullyio/scully/blob/master/docs/getting-started.md#prerequisites)

To update your project you can check [The angular CLI docs - ng update](https://angular.io/cli/update)

**Comment by YanZzz** [comment]
I ihade same issue but fixed after update cli.
