### ISSUE TITLE
Add a 'focusedRoute' config to scully.config so that I can just have the build focus on ONE route

### ISSUE THREAD

**Issue by aaronfrost** [scullyio/scully#942]
### Description

 Similar to how I can do testing and tell the testing framework to only focus on a single test by using `it.only` or `fit`, I want to be able to have Scully only rebuild a single route so that I can focus on rapid-iteration development around a certain route/feature. 

This would allow the users to run `ng build --watch` as well as `npm run scully:serve -- --watch`. If they had a `focusedRoute` defined, it would only build that one route instead of the entire list of handled routes. This would allow a developer to build/debug Scully plugins easier. Additionally, it allows developers to experience the pre-rendered app, which is what the users are seeing. 

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by SanderElias** [comment]
This feature is already implemented by using the `--routeFilter` option where you can give one or more (comma separated) routes you want to restrict building to
