### ISSUE TITLE
Schematic input does not validate against the schema NX Schematics

### ISSUE THREAD

**Issue by ruslanguns** [scullyio/scully#949]
### Description

Getting issues from the CLI using NX monorepo, also is getting the wrong project instead the projected.

As you can see in the console output you will notice that I asking to scully cli to use the project ui-scully-app but instead is using ui-ng-hola-mundo (the default project)

#### 🔬 Minimal Reproduction

1. Install NX Monorepo and setup a basic project of Angular.
2. Install the DevDependency @scullyio/init 
3. `nx g @scullyio/init:install -- --project=ui-scully-app

#### 💻Your Environment

**Angular Version:**

<pre><code>

➜  ruslan-project git:(offline/project-scully) ✗ nx --version                                          
10.2.1

but angular is using 10.0.0 please checkout the package.json bellow.

</code></pre>

**Scully Version:**

<pre><code>

{
  "name": "ruslan-project",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
    "scully": "scully",
    "scully:serve": "scully serve"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.0.0",
    "@angular/common": "^10.0.0",
    "@angular/compiler": "^10.0.0",
    "@angular/core": "^10.0.0",
    "@angular/forms": "^10.0.0",
    "@angular/platform-browser": "^10.0.0",
    "@angular/platform-browser-dynamic": "^10.0.0",
    "@angular/router": "^10.0.0",
    "@scullyio/ng-lib": "^1.0.0",
    "@scullyio/scully": "^1.0.0",
    "rxjs": "~6.5.5",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/compiler-cli": "^10.0.0",
    "@angular/language-service": "^10.0.0",
    "@nrwl/angular": "^10.2.1",
    "@nrwl/jest": "10.2.1",
    "@nrwl/nest": "^10.2.1",
    "@nrwl/nx-cloud": "latest",
    "@nrwl/workspace": "10.2.1",
    "@scullyio/init": "^1.0.1",
    "@types/jest": "26.0.8",
    "@types/node": "~8.9.4",
    "codelyzer": "~5.0.1",
    "dotenv": "6.2.0",
    "eslint": "6.8.0",
    "jest": "26.2.2",
    "jest-preset-angular": "8.3.1",
    "prettier": "2.0.4",
    "ts-jest": "26.1.4",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "~3.9.3"
  }
}

</code></pre>

## 🔥 Exception or Error

<pre><code>

```bash
➜  ruslan-project git:(offline/project-scully) ✗ nx g @scullyio/init:install -- --project=ui-scully-app
    Install ng-lib for Angular v9 - v10
    ✅️ Added dependency
✔ Packages installed successfully.
    ✅️ Update package.json
    ✅️ Created scully configuration file in scully.ui-ng-hola-mundo.config.ts
Schematic input does not validate against the Schema: "ui-ng-hola-mundo"
Errors:

  Data path "" should be object.
➜  ruslan-project git:(offline/project-scully) ✗ 
```

</code></pre>

**Comment by ruslanguns** [comment]
Just in case you guys would like to see the command output, here's my project bug branch.

https://github.com/ruslanguns/ruslan-project/tree/bugs/scully/installation

**Comment by jorgeucano** [comment]
With vanilla and angular (started) nx workspace, work perfectly... I will check what happened in your workspace

**Comment by jorgeucano** [comment]
@ruslanguns You have an error in your workspace, I clone the project, but the angular app not work! You need to fix that first and after you can install scully.... Is something in your config! 

![Capture](https://user-images.githubusercontent.com/5982204/94056513-c5a3ac00-fdb4-11ea-90c3-a008c7854355.PNG)

**Comment by jorgeucano** [comment]
Sorry, re-open fix one change! and now i can check the issue

**Comment by jorgeucano** [comment]
I put the name of the project and work for me! Can you check that?

![Capture](https://user-images.githubusercontent.com/5982204/94057938-b887bc80-fdb6-11ea-9ca4-da97b7504462.PNG)

**Comment by ruslanguns** [comment]
@jorgeucano thanks for doing it by yourserlf, it kinda weird, I tried twice but i did it not with the hola-mundo project instead a separated clean project called scully-app and the schematic did not point correctly.

**Comment by jorgeucano** [comment]
I recommend checking this office hour with the NX team https://www.youtube.com/watch?v=DkU_xQMAdE8
